### ISSUE TITLE
Adding Realm.framework into a custom framework

### ISSUE THREAD

**Issue by phongleq** [realm/realm-cocoa#1067]
So I am trying to add the iOS framework into my own custom framework that will be used by the app and the extensions it has. 

I am running into a issue where my framework cannot find RLMObject, RLMArray and RLMResults for armv7. Is the pre built framework not meant to be added into a custom iOS framework?

I also tried just using the project and it builds, but when it tries to validate for the app store it gives me that any app with a framework or extensions need to support 64 bit error.

**Comment by ryujik** [comment]
Hi. I want use Realm into a custom framework. When clean and build in target to custom Framework not problem, but when I add custom Framework rebuild in project show this error "framework not found Realm for architecture armv7". what could I do?

**Comment by ryujik** [comment]
I also had this problem but was solved for the moment, but I'm not sure if it's ok. I did so:
I have my custom framework, and I need to add the Realm framework. So that from a single framework can manage database and other.

1) Add the Realm framework to Custom Framework, making the necessary settings Realm (https://realm.io/docs/swift/latest/).
2) Then compile and generate the binary Custom Framework.
3) Then add the Custom Framework with a test project.
4) Compile the test project and fails. The framework of Realm says missing
5) Add the Realm Framework to the project and I made all the settings Realm. Compile it and ran.

In this way it works, but what worries me is that both sides are the framework of Realm.
|--------------------- Custom Framework ---------------------|
Realm Framework --- Add ---> Custom Framework
|--------------------- Project Test ------------------------------|
Custom Framework --- Add ---> Test Project
Realm Framework --- Add ---> Test Project

**Comment by iphonerosie** [comment]
@jpsim Can you explain in more detail the steps to link the realm framework? It mentions in the realm installatin instructions to add the realm framework to your custom framework... in their list of instructions for adding the realm framework, it mentions to drag the realm.framework and the realmSwift.framework files into the embedded binary section of an xcode project but in a .framework project that section is not there. Can it only be done with cocoapods if adding realm to a framework project?

**Comment by jpsim** [comment]
I'm sorry I can't take the time to do that for you right now. But there's nothing unique to Realm in this process. If you find detailed steps to link another framework, those should work with Realm too.
