### ISSUE TITLE
Skip sorting when calling count on an RLMResults that hasn't been constructed yet

### ISSUE THREAD

**Issue by kunalsood** [realm/realm-cocoa#1160]
Continuing the discussion from [this thread] (https://groups.google.com/forum/#!topic/realm-cocoa/3zWhXrCcIic) on the mailing list, I was made aware of how the count property on RLMResults works.

From doing a little more benchmarking, it seems to me that sorting my large query by a single NSDate property is the most expensive operation being done by Realm. Further, it also looks like, Realm is doing the sorting even for count-only queries. I came to this conclusion by testing the following 2 queries.

    [[[Article allObjectsInRealm:realm] sortedResultsUsingProperty:@"date" ascending:YES] count];
    [[Article allObjectsInRealm:realm] count];

The difference was significant. So, if this is indeed the case, do you guys think, not doing sorting on count-only queries is something Realm should handle internally?

**Comment by segiddins** [comment]
It appears that this is already done? (see a03f0c0b8f97)

**Comment by alazier** [comment]
@segiddins that optimization was made before this issue was opened. Calling ```sortedResultsUsingProperty``` requires a tableView to exist which is expensive. Only calling ```count``` doesn't require tableView construction and is usually much faster. It seems that @kunalsood understands this based on his original post (that calling count alone on RLMResults is much faster than calling count on a sorted RLMResults).

I think what is being asking for here is to do tableView creation lazily when calling ```sortedResultsUsingProperty```. This is possible but would require a bit refactoring and storing the sort state both in the binding and in core which is something that would be good to avoid.

**Comment by jpsim** [comment]
The last time we spoke about this, we decided to add two methods to improve transparency and performance: `-[RLMResults evaluate]` and `-[RLMResults isEvaluated]`. With these methods, calling `-[RLMResults count]` would never create the tableView and users would have more control over when table views are actually constructed.

Should we create a GitHub issue to implement this, @alazier @tgoyne?

**Comment by tgoyne** [comment]
`count` already never creates the tableview. Adding `evaluate` is unrelated to this.

**Comment by alazier** [comment]
But sorting does create the tableView. Don't think it makes too much sense to change the current behavior.

**Comment by kunalsood** [comment]
Slightly related question: When a sorted RLMResults which is being used to populate the user interface posts a change notification, does that cause the already constructed tableView in the core to be re-constructed if the UI tries to access some new/changed properties in it?

PS: If my two cents are worth anything, I would vote for this optimization being a lower priority than some kind of API that would allow for async main-thread queries.

**Comment by alazier** [comment]
Whenever data has changed which can effect the contents of an RLMResults the tableView will be reconstructed and sorting reapplied on next access. This has the benefit of ensuring your data is always up to date but also has some unwanted performance implications.

We have plans to add the ability to `freeze` an RLMResults to change this behavior so that we can prevent tableView reconstruction in certain situations (currently not possible). This turns out to be closely related to the async queries issue and is actually a prerequisite for many of the design that have been discussed.

**Comment by kunalsood** [comment]
Awesome! Thanks for addressing this.
