### ISSUE TITLE
Podspec with framework

### ISSUE THREAD

**Issue by fnxpt** [realm/realm-cocoa#1290]
Hi guys,

I think it should be better to have the framework on podspec file instead of the source code.

Best Regards,
fnxpt

**Comment by segiddins** [comment]
Since the Realm cocoa binding is open source, I see no reason why the podspec shouldn't refer to the source files -- it allows developers to have transparent access to the code they're including in their applications.

This is a discussion that has come up in broader terms a few times, and the CocoaPods core team has concluded that we want to encourage developers to ship source rather than binaries in their podspecs whenever possible.

**Comment by fnxpt** [comment]
You are right but we should be able to have a precompiled version to avoid building realm source everytime we make a build or archive. Maybe a second podspec that points to the framework instead

**Comment by tgoyne** [comment]
If you want to use prebuilt binaries, don't use a dependency management tool designed to make it easy to build all of your dependencies from source. [Carthage](https://github.com/Carthage/Carthage) may be more of what you're looking for, or just do it manually since including a framework in a project isn't something that even really needs a helper tool.

**Comment by nikolaykasyanov** [comment]
@tgoyne a single framework substantially increasing build times doesn't seem like a good reason to switch the whole project to Carthage, though.
