### ISSUE TITLE
Realm Browser sometimes shifts column titles

### ISSUE THREAD

**Issue by WesleyAC** [realm/realm-cocoa#1294]
Realm Browser will sometimes shift the column names.  Test database is here: https://dl.dropboxusercontent.com/u/63662632/realm.realm

When going to "Match" via the panel on the left, everything is displayed as expected.

When going to Competition -> Click on "Match (200)" the columns appear to be shifted.  Under the heading "match" there is "Team (3)", and under the heading "blueTeams" there is the officalRedScore.

I assume that this is an issue with Realm Browser, because it works when viewing the matches directly from the panel on the left.

Thanks,
Wesley.

**Comment by GreatApe** [comment]
Hello Wesley, sorry about this. This is what I think happened: you dragged the calculatedData column to the left, and then Cocoa autosaves the column order (even though it shouldn't, I have probably re-enabled that by accident in interface builder). Since the Browser currently doesn't handle column reordering, when you go back to the array later it will display the data in the normal order, but it will remember that the headers should be reordered.

If you move the column back to its correct position and leave the Match view and come back, the problem should be fixed!
