### ISSUE TITLE
In Realm browser copy and paste only works with the right-click context menu.

### ISSUE THREAD

**Issue by webmagnets** [realm/realm-cocoa#1295]
In the Realm browser I am unable to copy with &#8984;-c or paste with &#8984;-p. It works if I right click and then choose one of those options from the context menu.

Thanks for all your hard work guys (and girls?)!

p.s. - Just in case someone is searching for this issue, var &#8984; = "command" // :smile:

**Comment by GreatApe** [comment]
Hello, this is because the copy functionality you describe comes from OSX, not the Browser. And I presume they didn't bind the keys because the underlying apps will want to do that. In any case, the Browser itself does not currently have copy-pasting, and when it is introduced there will at least two different kinds: 

1. Copying text (and possibly other media) inside individual cells/properties.
2. Copying entire objects or sets of objects.

Since 2 is probably more important, the key bindings might reflect that, or it might be that CMD-C should do different things depending on what is selected. Unless that is too confusing.

The short answer is that what you observed is expected behaviour!

**Comment by webmagnets** [comment]
IMHO: I think text copying should be cmd-c and object copying should be some other combo.

**Comment by mrh-is** [comment]
+1 for this feature.

IMHO: Copy whatever is selected, Excel-style. If the row is selected, copy the object; if the text in a cell is selected (by double clicking), copy the text. (Same for paste.)

**Comment by TimOliver** [comment]
This issue was moved to realm/realm-browser#12
