### ISSUE TITLE
Use default value for NSInteger property for NSNull values in value NSDictionary

### ISSUE THREAD

**Issue by mfclarke** [realm/realm-cocoa#1339]
Hi,

Currently, Realm throws an exception when an object is being created from an NSDictionary with an NSNull value for an NSInteger property. Rather than throw an exception, would it be possible for Realm to use the default value as defined in the +[RLMObject defaultPropertyValues] method?

**Goals**
Parse an NSDictionary returned from the Foundation NSJSONSerialization class, where the json fed to it has <null> for properties with "number" type (rather than string type, which are surrounded by quotes). In the case of strings that are NSNull, I can use an NSValueTransformer. But in the case of an NSInteger, there is no object class to transform to, so this method is not possible.
 
**Expected results**
In these cases, Realm uses the default value returned by the object's +[RLMObject defaultPropertyValues] method

**Actual results**
Realm throws an exception, stating that NSNull isn't a valid value for the property.

**Steps to reproduce**
Create a Realm object with an NSInteger property
Attempt to create this Realm object using an NSDictionary with NSNull set as the value for the key of the NSInteger property

**Version of Realm/Xcode/OSX**
Xcode 6.1.1, Realm 0.89.2, iOS 8.1.2

Thanks

Max

**Comment by alazier** [comment]
Unfortunately we need to leave the behavior as it currently is, the reason being that NSNull indicates a null value for a property rather than a missing value. At the moment the only properties which are NULLable are RLMObject properties, so for those properties we need to treat NSNull as null even if a default property value is specified. This behavior will be consistent across all types once they all support NULL values (currently in the works). We could explore interpreting NSNull as null only for properties which are optional, while ignoring it for required properties, although I worry this would be confusing and potentially error prone.

Other users who have run into this have used value transformers to automatically strip NSNull from their objects before importing them into Realm. I know AFNetworking has such a feature somewhere, and we will support this feature/option when we release our JSON/object mapping and transformation apis.
