### ISSUE TITLE
defaultRealm returns nil

### ISSUE THREAD

**Issue by brandonroth** [realm/realm-cocoa#1435]
Playing around with the Backtrace example provided there are times when I run the app and get a crash on the line which calls RLMRealm.defaultRealm().  on Subsequent runs nothing works (no crashes, just no output) and any calls to defaultRealm returns nil.  I have to delete the app to get things working again.  I'm not sure what triggers this but I would assume a call to defaultRealm would create one if it doesn't already exist.

**Comment by jpsim** [comment]
Hi @brandonroth, we don't have an example named "Backtrace", so I'll assume you're referring to the [Backlink example](https://github.com/realm/realm-cocoa/tree/master/examples#backlink-1). I'll also assume you're using Swift based on the fact that you refer to `RLMRealm.defaultRealm()`.

Creating an `RLMRealm` can fail at any time due to a number of factors ([low available memory, low available storage, file permissions, etc.](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm.mm#L277-L304)). Is it possible that an exception is being thrown? If so, which one?

If `RLMRealm.defaultRealm()` returns `nil` without throwing an exception, that is a bug and we'd appreciate if you could share the steps to reproduce it so we can fix it.

If you're accessing Realm in a situation that could potentially fail, we recommend that you use a Realm constructor which accepts an `NSError` parameter (e.g. [`RLMRealm.realmWithPath(_:readOnly:error:)`](http://realm.io/docs/cocoa/0.90.4/api/Classes/RLMRealm.html#//api/name/realmWithPath:readOnly:error:)) so you can handle error cases.
