### ISSUE TITLE
Automatic writing/exception debugging

### ISSUE THREAD

**Issue by nmock** [realm/realm-cocoa#1470]
I have an integer declared in an interface extension, when I modify this property, it is automatically being written to disk (I know because I am getting an exception: `Attempting to modify object outside of a write transaction - call beginWriteTransaction on an RLMRealm instance first.` I am not even surrounding it in the begin/commit transaction sequence and it is automatically being included in a write transaction. Is it true that changes are automatically written when calling a setter? If not, how can I track down what is being written to disk? Currently I am searching for instances of `commitWriteTransaction`, and it seems they are all balanced by `beingWriteTransaction`...is this the wrong approach/assumption to make? Do all changes to an object need to be surrounded by `beginWriteTransaction`?

This leads me to my second issue, is it really required to list all properties that are to be ignored from being persisted and if so, is there a type-safe way to do this (strings seem kind of clunky and refactoring seems like it could be a pain)? It seems that properties I define in my interface extension should automatically be excluded, no? It only makes sense to me that properties in the public header would be included. Also, I got warnings regarding some types such as NSArray, etc..shouldn't it be possible to just automatically exclude these or is there a design reason that I must explicitly exclude these types that aren't able to be persisted?

Particularly in the development of a new project, I am making a lot of changes/additions to the model. For every change, I am warned about the migration...is there a way to bypass when working on the initial version where I wouldn't necessarily want to have the migration support and I am making a bunch of changes to the model? The only way I've found so far is to delete the app from my device and re-build.

Lastly, is there a way to use the Realm browser to inspect/modify the realm DB on a device?

**Comment by segiddins** [comment]
Writing to a property outside of a write transaction will indeed cause an exception to be thrown, which is exactly what you are seeing -- that is intentional. All changes to the database occur inside write transactions, which is what makes Realm a transactional database. In short, yes, all changes to an object need to happen inside a write transaction, either via `beginWriteTransaction` and `commitWriteTransaction` or `transactionWithBlock`.

As to your second question, yes, you must explicitly list all ignored properties as an array of strings. Since an interface extension gets folded into your class definition at compile time, there would be no way to know it came from an extension. The reason you need to explicitly ignore types that are currently unpersistable in Realm is for forwards-compatibility reasons: they might be supported in the future, and we wouldn't want your model schema to change without you making explicit changes to it.

When in development, your best bet will probably be to delete the realm file when you make changes to your schema.

Finally, you can certainly copy the Realm file from your device to your Mac to use the Realm Browser, but there's a cool alternative called [NBNRealmBrowser](https://github.com/nerdishbynature/NBNRealmBrowser) that acts as an on-device browser.

I hope this was helpful!

**Comment by yoshyosh** [comment]
Here is a snippet of code that works nicely when wanting to delete the file automatically

````obj-c
[[NSFileManager defaultManager] removeItemAtPath:[RLMRealm defaultRealmPath] error:nil];
````
