### ISSUE TITLE
Pass the realm to the block in transactionWithBlock:

### ISSUE THREAD

**Issue by CraigSiemens** [realm/realm-cocoa#1498]
Currently when calling `transactionWithBlock:`, it requires you to create a realm variable that you can use in the block.

```objc
RLMRealm *realm = [RLMRealm defaultRealm];
[realm transactionWithBlock:^{
    [realm addObject:foo];
}];
```

It would be nice if the realm was passed into the block for you instead of requiring the user to create a variable every time they need it. The ideal solution would look like this.

```objc
[[RLMRealm defaultRealm] transactionWithBlock:^(RLMRealm *realm){
    [realm addObject:foo];
}];
```

**Comment by segiddins** [comment]
We've actually been discussing this change this week, thanks for the suggestion!

**Comment by astigsen** [comment]
We should probably consider a class method:

```obj-c
[RLMRealm transactionInDefaultRealmWithBlock:^(RLMRealm *realm){
    [realm addObject:foo];
}];
```

**Comment by yoshyosh** [comment]
I like that @astigsen, with the autocomplete it will be easy for users to recall

**Comment by alazier** [comment]
It also makes autocomplete less useful in general as we continue to add more and more methods. Is it worth it? I'm not sure. In any case I see no reason not to pass the Realm to the transaction block other than breaking current code, so we would probably have to have two variants...

**Comment by yoshyosh** [comment]
Agreed, but I think this is the most used function out of all. 3 lines of code to add an object to your DB is very impressive

**Comment by anlaital** [comment]
I like @astigsen's idea. I'm a huge fan of autocomplete and this would not cause me any issues since autocomplete remembers the methods you've used most recently. :+1:

**Comment by segiddins** [comment]
We need to (eventually) decide if this is something we want to do, as it's a major breaking change with no real way to deprecate.

**Comment by jpsim** [comment]
The extra class method is a step backwards since it only works with the default realm, but I could see us implementing the original suggestion:

```objc
[[RLMRealm defaultRealm] transactionWithBlock:^(RLMRealm *realm){
    [realm addObject:foo];
}];
```

But it's not worth it when saving a single-line assignment, only in *some* scenarios. Especially in Swift, where usage would look more like this:

```swift
Realm().write { realm in
  realm.add(foo)
}
// or
let realm = Realm()
realm.write { _ in
  realm.add(foo)
}
```

The current approach also has the added advantage of encouraging users to keep strong references to realms, which leads to better usage patterns as described in https://github.com/realm/realm-cocoa/issues/2424#issuecomment-133464754.

For these reasons, I'm closing this ticket.
