### ISSUE TITLE
Support specifying objectSchema/classes to be stored in a Realm

### ISSUE THREAD

**Issue by yasirmturk** [realm/realm-cocoa#1506]
i have created multiple realm DBs but it creates all classes in every realm..? how to specify a model class for a specific realm?

**Comment by segiddins** [comment]
Right now, there is no way to only have certain classes in certain Realms (there will be database tables created for all of your RLMObject subclasses), but the overhead from those empty tables is negligible. I hope that helps!

**Comment by yasirmturk** [comment]
this could be simpler than it looks ..may be something like .. `[[RLMRealm defaultRealm] registerClasses:...];`

**Comment by segiddins** [comment]
@yasirmturk the issue with require a call like that is that it's counter-intuitive and makes the API harder to use and more confusing to read code that uses Realm. We've never really seen anyone report an issue with the tables that are created, even if they are not used. Do you have a particular reason why you think the ability to register classes would be necessary?

**Comment by yoshyosh** [comment]
I think there is an issue that describes hiding any empty tables so it will end up doing this automatically

**Comment by astigsen** [comment]
The correct solution will probably be to add the tables lazily, so that
they are not created in the realm until the first time you add an object of
that type to it.

**Comment by alazier** [comment]
@yasirmturk you will be able to do what you are asking once we open up support for our dynamic interface. With the dynamic interface you can open a Realm providing a custom schema, which is basically just a list of the objects/properties stored in the Realm - so eventually you will be able to specify what objects each Realm should support each time it is opened. Not sure yet when we will get around to making this functionality public though.

**Comment by yasirmturk** [comment]
@segiddins an overload for advanced users never hurts the beginners using intuitive solution.. another suggestion is to use the method which is specifying migration rules.. 
`    [RLMRealm setSchemaVersion:1
                forRealmAtPath:realmPATH
                 registerClasses:@[[Employee class], [Department class], ...]
            withMigrationBlock:^(RLMMigration *migration, NSUInteger oldSchemaVersion) {                
            }];`
i think that is simpler than the other solutions @alazier @yoshyosh .. @astigsen gave a good idea too..
@segiddins it is a real mess even if you have 3 realms each having 10 tables and you end up looking at 2 DBs with 30 tables each

**Comment by jpsim** [comment]
I'd be in favor of allowing users define per-realm models. I think this functionality would be different (simpler) than providing an entire schema in the dynamic interface case.

Not having superfluous tables in a db means not having to migrate one realm because the model class for another has changed.

How about something similar to `+[RLMRealm setEncryptionKey:forRealmsAtPath:]` like `+[RLMRealm registerModelClasses:forRealmsAtPath:]` which needs to be called prior to accessing a realm at that path. Then we'd be able to filter the schema before assigning it to the realm [here](https://github.com/realm/realm-cocoa/blob/9e9679b2aeba6e1362977418128d0c4442834957/Realm/RLMRealm.mm#L451-L485).

Changing which classes are registered for a path would require a migration. This will make it easy for us to support existing users who want to clean up their realm files.

**Comment by yasirmturk** [comment]
+100

**Comment by alazier** [comment]
We will likely add this once we add support for RealmConfiguration for Realm initialization

**Comment by yasirmturk** [comment]
Great..and i assume it would handle the cleanup of existing Realm DBs in production too

**Comment by yasirmturk** [comment]
there is another backdraw ..it requires to migrate all models even if i have added a property in one of my 3 realm models

**Comment by timanglade** [comment]
This will be implemented as part of #1584

**Comment by yasirmturk** [comment]
What about the cleanup? of older schema versions?
