### ISSUE TITLE
Pod integration with the tests target

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#1538]
Related issue: https://github.com/realm/realm-cocoa/issues/1517

1) The goal is to correctly setup the tests target with `Realm`
2) Expected result is a successful build
3) When building the test target I get the following (image and text representation, for copy-paste ease, paths sanitized):
![screenshot 2015-02-23 16 09 17](https://cloud.githubusercontent.com/assets/457094/6329213/11b6a7ae-bb77-11e4-8479-ab027f64a802.png)
```
ld: warning: directory not found for option '-L/Users/username/Projects/name/Pods/build/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/username/Projects/name/testTarget/Frameworks'
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_RLMObject", referenced from:
      _OBJC_CLASS_$_Product in Product.o
  "_OBJC_METACLASS_$_RLMObject", referenced from:
      _OBJC_METACLASS_$_Product in Product.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

To clarify: the `Product` class target membership is both main and testing targets.
The error occurs when I try to build the tests target.

4) I followed the steps from http://realm.io/docs/cocoa/0.90.6/#testing : 
```
target :mainTarget do
    pod 'Realm'
    [other pods]
end
target :testTarget, exclusive: true do
    pod 'Cedar'
    pod 'Realm/Headers'
end
```
5)XCode 6.1.1, pods version 0.35.0 . I might assume that the problem might be on the pods side, but other pods work fine :) It would be great if we are sure that the problem is definitely not on the `Realm` side :)

I hope I didn't miss anything.
Hope this helps! 

PS I fixed the problem by just setting this (no `/headers` part):
```
target :testTarget, exclusive: true do
    pod 'Cedar'
    pod 'Realm'
end
```

**Comment by mrackwitz** [comment]
I think the guide is at this part a bit misleading. Thanks for pointing that out. :+1:
Here a bit more extensive explanation for when to use what:

* If you have a unit / logic test target, like in your case, where you share the implementation files and make them members of both, your application and the test target, you also need to link the framework, which happens by using `pod 'Realm'`.
* If you have an integration / application test target, and your implementation files only belong to the application target, then you should not link Realm to the test target. But if you need to interface Realm from your tests, e.g. to setup test conditions, then you can make the headers available by using `pod 'Realm/Headers'`.

**Note:** This last point only applies as long as you're using the static framework, we're currently distributing over CocoaPods 0.35. That's the case, because the application test target builds a dynamic library for your test target, which will be injected into your running app executable. If you use CocoaPods 0.36, once it is released or with the RC and use the option `use_frameworks!`, there will be no need to make a difference anymore.

**Comment by jasich** [comment]
:+1:

**Comment by ryanchou1991** [comment]
I thought that you may forgot to add `pod 'realm'` into your ProjectTests Target.
