### ISSUE TITLE
Add undo manager feature as in CoreData

### ISSUE THREAD

**Issue by anbarasu0504** [realm/realm-cocoa#1572]
Add undoManager feature as in CoreData

**Comment by jpsim** [comment]
Thanks for the feature request, @anbarasu0504. We have a number of high priority features we'd like to build before diving into something like this, but it would certainly be nice to have at some point.

If you, or anyone, feels like contributing to this, please start with a design proposal in this issue demonstrating how the feature should work, which API it should expose and how to deal with potential pitfalls:

1. What kind of operations and/or models can be undone?
2. Should undos be grouped by transaction? Or by some other mechanism? Or not grouped at all?
3. What happens in a multithreaded or multiprocess scenario?
4. How can we efficiently compact the transaction log to only preserve history which can be undone while discarding the irrelevant aspects?

**Comment by bkerensa** [comment]
@jpsim any chance you might escalate this?

**Comment by jpsim** [comment]
No, we still have a number of high priority features we want to tackle before dedicating resources to this. But my comment above does provide some guidance as to how an external contributor could get started with this.

**Comment by andrewebling** [comment]
Any further thoughts or update on this? It's the last thing that is holding up my adoption of Realm on a few projects.

**Comment by jpsim** [comment]
@andrewebling it's fairly difficult to build undo in a general-purpose API, but relatively easy to build it in a domain-specific setting, so I'd encourage you to build undo functionality on top of Realm yourself for your specific app's needs.

For example, instead of storing values, store operations (insert string, remove string, etc.). You can then compute the final value by applying all these operations. You could also trim the history as you see fit on a recurring basis. You could then more easily track what things you want to "roll back", what points in time make sense as discrete "checkpoints", etc.

**Comment by joninsky** [comment]
I built a drawing app using Realm (Similar to Realm demo app but on a map). I needed an undo queue because, well, users expect it when drawing. I was dreading the implementation because it's kind of complicated. But... It turned out to be easy with Realm! Especially if you have primary keys.

I have an object:
```swift
class Line: Object {
    @objc dynamic public var lineID: String?
    @objc dynamic public var strokeStyleRaw: String?
    @objc dynamic public var strokeHexColor: String?
    @objc dynamic public var lineTypeRaw: String?
    public let points = List<MyPointObject>()

    override static public func primaryKey() -> String? {
        return "lineID"
    }
}
```

Right before you do anything that could need an updo, create an unmanaged copy of the object using realm convenience initializer.

```swift
//myManagedLine is the `Line` object you are working on that is part of a Realm.
let copy = Line(myManagedLine)
``` 

Then append the new unmanaged object to an array

```swift
//Array is probably declared at the top of your `UIViewController`
let myUndoArray = [Line]()
//"Push" copy on to the array
myUndoArray.append(copy)
//Change the managed line object
Realm().beginWrite()
myManagedLine.points.append(NewPoint)
try! Realm().commitWrite()
```

Now, when the user presses the undo button you just pop off the last object in the undo array and save it using the add with update function.

```swift
let revertedLine = myUndoArray.removeLast()
Realm().beginWrite()
Realm().add(revertedLine, update: true)
try! Realm().commitWrite()
```

Magic!! The `myManagedLine` object is now reverted. So, bottom line. Just push an unmanned copy of the object you want to "Undo"  onto a queue. On undo, just save it again! All assuming you are using the primary keys.

**Comment by ksatao** [comment]
Any updates on this?

**Comment by bmunkholm** [comment]
Closing this as it's not expected to happen in any foreseeable future.

**Comment by bdkjones** [comment]
It's been two more years. I hope the team will revisit this decision because a first-class undo manager is table stakes for many apps and it's a definite reason someone would choose Core Data over Realm.

**Comment by jsflax** [comment]
@bdkjones coincidentally, we have begun to reconsider this feature very recently. I cannot promise what it will look like or when it will arrive, but we have begun talking about it.

**Comment by phranck** [comment]
Hey there. What's the current status to this topic? We (our company) are in very need to such a feature. Currently we did our own solution, which is a real pita! So, it would be awesome to have Undo/Redo right in the core of Realm.

I also opened feature request in your [feedback system](https://feedback.mongodb.com/forums/923521-realm/suggestions/47660246-general-undo-redo-system).
