### ISSUE TITLE
Modify schema from Realm Browser

### ISSUE THREAD

**Issue by vittoriom** [realm/realm-cocoa#1597]
Any plans to improve the Realm browser by adding the possibility to change the schema of a <code>.realm</code> file for example adding columns or whole tables?

Our use case is the following:

We're using Realm in our current app, and we have a suite of integration tests setup. What we do there, since the database is populated and updated through REST calls, is we save a snapshot of the database at a given time and we bundle one or more copies (depending on some characteristics, like "empty realm", "populated realm", and so on) in the test target, so that we can rely on a static data source when running the tests.

You know already what happens when in the development cycle we change the database schema. All the tests fail because the Realm cannot be initialized. What this means is that we have to replace the database snapshots with a newly populated database from the app, AND we have to replace all the constants for data identifiers we use in the tests to simulate fetching and so on (since the data the app generated through REST calls now is different from the data we had at the time of the last snapshot). This is a huge amount of time for every change to the schema we do, and it would be nice if I could just open the snapshot and add the column I need, either through interface or through some kind of query language which I think is more complex for you anyway :) )

P.s. this of course only applies for the first development cycle since in some way we'll handle migrations after the first version goes live. But since we still have a long time before the first version comes out, I think it's also not really helpful to create mini-migrations for changes we do during the development cycle

Any ideas?

**Comment by yoshyosh** [comment]
Hi @vittoriom we do have plans to add that down the line. I'm helping with the new browser and would very much like that ability as well :). There is no timeline on when such a thing would be added.

I think your best bet for right now will be to do the mini migrations

**Comment by vittoriom** [comment]
great, looking forward to try the new browser :)

**Comment by yoshyosh** [comment]
:+1: me too :)

**Comment by compojoom** [comment]
This has been closed, but it doesn't seem to be implemented yet? 
as @vittoriom pointed out during development when you might change the schema several times it is really annoying to have to write a migration or drop the whole database in order to work with the damn thing. If I drop the db, then I have to populate it with dummy data. If I make a migration, then I spent time making a migration for something that won't be needed in production...

**Comment by yoshyosh** [comment]
cc @TimOliver

**Comment by TimOliver** [comment]
I think we closed this because we moved all discussions about the Realm Browser over to [the Realm Browser repo](https://github.com/realm/realm-browser-osx).

Thanks for the comment @compojoom. I appreciate your passion on the topic. :)

Yeah, I've been pushing for this functionality for a while. I've got several use cases where it would be great to pre-build a Realm file so it can be bundled with an app. I was assuming it would actually just be a matter of performing an internal migration and then resetting the schema version value of the Realm file back to 0. 

Apparently the mechanisms for this are already in Realm Core; they just need to be exposed to the Object Store and then the Objective-C/Swift wrappers.

It's just a matter of time and resources. We're really busy on improving all of the features and stability for the Realm Mobile Platform at the moment and since you can 'sort of' work around this at the moment, it's not an absolute showstopper. Sorry about that.

We should have an issue in Realm Cocoa here talking about modifying the Realm schema (separately from the Browser). If there isn't, I'll create one.
