### ISSUE TITLE
[Doc] RLMObject.init(forPrimaryKey:String) is not in the documentation

### ISSUE THREAD

**Issue by voidref** [realm/realm-cocoa#1635]
The init method on RLMObject that takes the primary key is not documented anywhere except in some release notes.

http://realm.io/docs/cocoa/0.81.0/api/Classes/RLMObject.html  <-- offending page

This wouldn't be so bad, except you can't browse the class definitions in Swift. It just comes up as a blank page (Xcode bug?)

**Comment by jpsim** [comment]
Hi @voidref, you can't find `+[RLMObject objectForPrimaryKey:]` because you're looking at outdated documentation from ~8 months ago. Here are the [`objectForPrimaryKey:`](http://realm.io/docs/cocoa/0.91.1/api/Classes/RLMObject.html#//api/name/objectForPrimaryKey:) and [`objectInRealm:forPrimaryKey:`](http://realm.io/docs/cocoa/0.91.1/api/Classes/RLMObject.html#//api/name/objectInRealm:forPrimaryKey:) docs from the latest release (0.91.0).

We'll soon be removing old docs from search engine indexing and displaying a banner on older documentation so this should be less confusing in the near future.

**Comment by voidref** [comment]
Thanks, I could have sworn I had gotten to that doc page via realm.io, but I was clearly mistaken. Sorry about that!
