### ISSUE TITLE
Allow filter when pushing a dictionary into createOrUpdateInRealm

### ISSUE THREAD

**Issue by davejlong** [realm/realm-cocoa#1641]
I was recently working with some API data to push into Realm data store formatted like the following:

```javascript
[
  {
    "id": 1234,
    "confirmation": 483,
    locations: [
      {
        "id": 5678,
        "address": "54 Main Street",
        ...
        "arrive_at": "2015-03-12T17:37Z"
      },
      {
        "id": 5679",
        "address": "72 Center Street",
        ...
        "arrive_at": null
      }
    ],
    ...
  },
  ...
]
```

The JSON is an array of trips for a hired driver. I have models setup in Swift as follows:

```swift
class Trip: RLMObject {
  dynamic var id = 0
  dynamic var confirmation = 0
  dynamic var locations = RLMArray(objectClassName: Location.className())
  ...
}

class Location: RLMObject {
  dynamic var id = 0
  dynamic var address: String = ""
  ...
  dynamic var arriveAt: NSDate = NSDate()
  ...
}
```

I originally had Swift code like the following to save each block from the API:

```swift
func parseTrips (trips: JSON) {
  let realm = RLMRealm.defaultRealm()
  realm.begineWriteTransaction()
  for tripJson in trips.arrayValue {
    Trip.createOrUpdateInRealm(realm, withObject: tripJson.dictionaryObject)
  }
  realm.commitWriteTransaction()
}
```

The code failed because of the arriveAt property on the Location class. I'd like to see a configurator option somewhere, either in RLMObject when it's passed on object or in createOrUpdateInRealm as an argument to cast variables.

Something like:

```swift
class Location: RLMObject {
  dynamic var id = 0
  dynamic var address: String = ""
  dynamic var arriveAt: NSDate = NSDate()

  func castInputObject (data: Dictionary) -> Dictionary {
    data["arriveAt"] = NSDate.fromISO8601String(data["arrive_at"])
  }
}
```

**Comment by segiddins** [comment]
Hi @davejlong, we already have a couple of issues tracking this feature request, namely https://github.com/realm/realm-cocoa/issues/694, https://github.com/realm/realm-cocoa/pull/1272, & https://github.com/realm/realm-cocoa/issues/1063. In the meantime, you'll either have to pre-process your dictionaries before passing them into `createOrUpdateInRealm`, or otherwise look into using something like [Realm-JSON](https://github.com/matthewcheok/Realm-JSON) or [RestKit](https://github.com/RestKit/RestKit).
