### ISSUE TITLE
Dealing with exceptions in Realm

### ISSUE THREAD

**Issue by rbaulin** [realm/realm-cocoa#1697]
How to recover from Realm exceptions? 

**Imagine the case:** you have found a great playlist and listening to track #31. As a user you have performed some subsequent actions which formes the current state of the app. Сoincidentally somewhere else a small object was added to Realm with a duplicate key.. Boom. Crash. Start over. Moderate alert error would be so much better.

Provided realm docs and examples give no clue on how to handle exceptions in production environment. How do I know which methods can throw an exception? Should I wrap each realm call in `@try-catch` block? Examining the source code shows that there are **plenty of vulnerable exceptions, which might not be discovered when an application is being created can pop up in release builds**. Even `-realmWithPath:error` can throw an exception `Realm at path already opened`.

An example of the API *would be nice* to have:

    [realm beginWriteTransaction];
    BOOL added = [realm addObject:object error:&error]; // does NOT trigger an exception under no circumstances
    if (!added) {
      // e.g. error = duplicate content, no default value etc
      // report error to some remote service
    }
    [realm commitWriteTransaction];

#### Background

Please read [Apple's Exception Programming Topics](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Exceptions/Exceptions.html#//apple_ref/doc/uid/10000012i) **IMPORTANT** block, it makes total sence: **most of the current RLMExceptions should be catched at the top level of the library and translated them into an appropriate return code or state.**

> Instead of exceptions, error objects (NSError) and the Cocoa error-delivery mechanism are the recommended way to communicate expected errors in Cocoa applications.

More references below:

[Programming with Objective-C • Dealing With Errors](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/ErrorHandling/ErrorHandling.html#//apple_ref/doc/uid/TP40011210-CH9-SW1)

> When you’re writing code with Objective-C, exceptions are used solely for programmer errors, like out-of-bounds array access or invalid method arguments. These are the problems that you should find and fix during testing before you ship your app ... All other errors are represented by instances of the NSError class".

[Apple's Error Handling Programming Guide](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/ErrorHandling/ErrorHandling.html#//apple_ref/doc/uid/TP40001806)

[StackOverflow NSError vs NSException](http://stackoverflow.com/questions/11100951/nsexception-and-nserror-custom-exception-error) [StackOverflow Errors vs Exceptions](http://stackoverflow.com/questions/5009597/objective-c-assertion-vs-exception-vs-error)

#### How others handle it:

[FMBD](https://github.com/ccgus/fmdb): any method execution returns bool + static last database error

[CoreData](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/CoreDataFramework/Classes/NSManagedObjectContext_Class/index.html#//apple_ref/occ/instm/NSManagedObjectContext/save:) [(reference)](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/NSMigrationManager_class/index.html#//apple_ref/occ/cl/NSMigrationManager): errors pop up on
- initialization phase: `-addPersistentStoreWithType::error:`
- migration: `-migrateStoreFromURL::error:`
- save and fetch: `-save:error` `-executeFetchRequest:error`

* * *

I am suprised nobody addressed the problem yet. Realm is such a great framework, but it is just being fragile sometimes. Remember that UITableView's `NSInternalInconsistencyException`?

> Invalid update: invalid number of rows in section 0. The number of rows...

Doesn't it feel insane that the some minor animation stops user experience and crashes the app?

Realm maintainers, please consider the concept above. At least we should also make up basic guidelines on exception handling.

**Comment by tgoyne** [comment]
We do strive to follow Apple's guidelines that you quoted: exceptions are used only to indicate misuse of the API, and NSError is used for runtime errors. We strongly discourage trying to catch and handle any exceptions thrown by Realm, and if you find a scenario where it is not possible to avoid having Realm thrown an exception then that is a bug. The two exceptions to this are the convenience overloads of the RLMRealm factory methods which do not take an error out parameter, and a few methods which could potentially fail due to a memory allocation failure but do not have a good way to supply an error parameter (such as the generated property setters for persisted objects).

If you want to add an object without it throwing an exception if an object with that primary key already exists, either use `addOrUpdate:` if you simply want to replace the existing object, or use `objectForPrimaryKey:` to check for the object existing first. There's no risk of a race condition where another thread creates the object between the check and when you call `addObject:` because only one thread can be in a write transaction at a time.
