### ISSUE TITLE
RealmSwift doesn't use the nested Realm framework

### ISSUE THREAD

**Issue by lewo** [realm/realm-cocoa#1771]
Hi Guys,

Still having issues with RealmSwift and Xcode 6.3, I've created a new single view swift project.

Changed to the MR-SWIFT-1.2 branch of realm-cocoa
Added the RealmSwift.xcodeproj to  my project
Under build phases:
 added RealmSwift.framework under "Link with Libraries"
 created a new copy files phase and changed to framework and added RealmSwift.framkwork.

added the import RealmSwift to the ViewController. 

And when I compile I have the following error: 

Swift Compiler Error
Missing required modules: "Realm.private', 'Realm'

I've performed a build.sh iso-dynamic in the realm-cocoa clone just in case but same issue.  I can resolve it by manually adding the realm framework to my project.

Sample project available if needed.

Thanks
Leigh

**Comment by rlimberger** [comment]
I am running into this behavior as well. Can someone from the realm team please post a quick guide on how to use the framework from the mr-swift-1.2 branch in a swift project? Thanks so much in advance.

**Comment by segiddins** [comment]
We don't yet have a guide on using RealmSwift yet since it is unreleased. We're still working out all the kinks (such as figuring out how to make the install process as smooth as possible), but definitely do appreciate you trying to use it. As soon as it's released, we'll let you know!

**Comment by rlimberger** [comment]
Noted about it being unreleased, we aprechate you are making the branch available. I was more curious how those of you working on this branch get realm swift to work while developing. Thanks, realm is awesome.

**Comment by depl0y** [comment]
Today I started a new branch of my project to integrate RealmSwift instead of Realm, but I am indeed encountering the same thing. Bulding the example projects from the `swift-next` folder works as expected, but when I drag the RealmSwift.xcodeproj in my own project it fails building because of the missing `Realm.private`.

**Comment by jpsim** [comment]
We're working on this now. There's a problem with how we're building RealmSwift right now where it needs the dynamic `Realm.framework` to be next to `RealmSwift.framework` in the same parent directory.

Since this is still unreleased, I can't say with any certainty when this will be fixed, but will keep you posted.

**Comment by jpsim** [comment]
I just opened #1809, which will resolve some issues with installing Realm Swift. The two ways you can use that branch to install Realm Swift are:

1. Run `./build.sh ios-swift` and grab `RealmSwift.framework` from the `build/ios/` folder.
or
2. Use Carthage with `github "realm/realm-cocoa" "jp-single-xcode-project"` in your Cartfile.

You'll have to add this prebuilt framework (no matter which option you use to build it) to your app's "Embedded Frameworks" so they're properly copied into the `Frameworks` directory and linked. You'll also have to add `path/to/RealmSwift.framework/Frameworks` to your app's framework search paths.

#1774 should be merged soon too, which will add support for CocoaPods.

Keep in mind that since Realm Swift is unreleased, any of this could change at any time.

**Comment by jpsim** [comment]
This is fixed as of #1826.
