### ISSUE TITLE
Multiple deleteObject calls within a transaction remove only half of the objects (0.92.0 and earlier)

### ISSUE THREAD

**Issue by maciejtrybilo** [realm/realm-cocoa#1846]
I have 290 objects in a realm and I run the code below to remove them. (In reality I don't want to remove all objects, I'm just simplifying here, so deleteAllObjects is not the solution.) The first time I run the code I get:

```
before delete: 290
after delete: 145
```

When I run the app again I get:
```
before delete: 145
after delete: 72
```
...and so on. Not sure why is that happening.

```Swift
realm.beginWriteTransaction()

let objects = MyObject.allObjectsInRealm(realm)
println("before delete: \(objects.count)")

for object in objects {
    realm.deleteObject(object)
}

realm.commitWriteTransaction()

let objects1 = MyObject.allObjectsInRealm(realm)
println("after delete: \(objects1.count)")
```

**Comment by tgoyne** [comment]
Query results are live-updating after every modification, so each time you delete an object all of the remaining objects in the results are shifted by one. If you want to delete all objects matching the query, use `realm.deleteObjects(objects)`. If you need to loop over the query and decide which ones to delete, you have to manually iterate by index and either iterate backwards (so that the shifted results are the ones you've already looked at), or adjust the index each time you delete an object.

We're planning to add a way to freeze the results during iteration, but there's some surprisingly complex parts.

**Comment by maciejtrybilo** [comment]
Ok, I take it's akin to modifying a collection while iterating through it. I'm going to build an array and use deleteObjects. Cheers.

**Comment by jpsim** [comment]
There's no need to copy the items into an array, you should just pass in the `RLMResults` into `deleteObjects(_:)`:

```swift
realm.beginWriteTransaction()

let objects = MyObject.allObjectsInRealm(realm)
println("before delete: \(objects.count)")
realm.deleteObjects(objects)

realm.commitWriteTransaction()
```
