### ISSUE TITLE
http://realm.io/docs/swift/latest/ the manual setup is missing Copy Files phase

### ISSUE THREAD

**Issue by marcvanolmen** [realm/realm-cocoa#1848]
hi, 

i just switched over to RealmSwift.framework and the documentation for the manual install has a Copy Files phase missing to copy the RealmSwift.framework into the Framework folder.

marc

**Comment by jpsim** [comment]
Actually, the installation instructions specify to drag `RealmSwift.framework` into the "Embedded Binaries" section of your main target, which would automatically add an appropriate "Copy Files" phase.

But since that's easily overlooked, we'll add a note in there to make sure the framework is being copied.
