### ISSUE TITLE
Different return for min, max, sum, average in RealmSwift

### ISSUE THREAD

**Issue by duemunk** [realm/realm-cocoa#1902]
Big kudos on the Swift release! It's really impressive and feels much more native now.

I don't understand why `min` and `max` on `Results` return optionals while `sum` and `average` returns non-optionals?

```swift
    public func max<U: MinMaxType>(property: String) -> U? {
        return rlmResults.maxOfProperty(property) as! U?
    }
    public func sum<U: AddableType>(property: String) -> U {
        return rlmResults.sumOfProperty(property) as AnyObject as! U
    }
```

The documentation for `max` states:
```swift
// The maximum value for the property amongst objects in the Results, or `nil` if the Results is empty.
```
Shouldn't this also be true for `sum` and `average`?

**Comment by dbworku** [comment]
I am not on the Realm team but my view is that they should not be optionals because their value is always "known". Just like the `count`, `sum` and `average` are 0 when there are no values returned.

However, you question brings up a bug:
- `averageOfProperty` currently returns nil... Calling `.average` would crash when `average` implicitly unwraps the value. I'll look at it's usage and make a PR.

See [RLMResults.mm](https://github.com/realm/realm-cocoa/blob/5a50d23d02bf0689a7d95274fb6fa1db23d05446/Realm/RLMResults.mm) for the underlying methods that the Swift code is calling.

**Comment by duemunk** [comment]
But how is a value "known" if it doesn't count anything. What is the max value of nothing, it's nothing. The same goes for sum, even though sum usually start on 0. The whole idea about optionals in Swift is to not have fake NULL/nil values.

**Comment by tgoyne** [comment]
We went with matching the behavior of the KVC collection operators on empty sets.

The sum of zero elements is generally considered a well-defined value (i.e. zero), but the average is 0/0 and the min/max are meaningless.

**Comment by segiddins** [comment]
We intend to match Foundation's KVC collection operator behavior, so `average` of the empty set should return `nil`, but `sum` will continue to return the additive identity, `0`.

**Comment by duemunk** [comment]
But if you agree that 0/0 doesn't make any sense to be 0, then why is `average` then a non-optinal re https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Results.swift#L259.

Also, even though this might match KVC collections, is annoying to remember to type `as Double` vs. `as Double?`. Xcode/Swift really doesn't give meaningful errors if you choose the wrong one.

**Comment by segiddins** [comment]
@duemunk I'm pulling together a pull request to make `average` return an optional.
