### ISSUE TITLE
Public source dynamic API

### ISSUE THREAD

**Issue by rbaulin** [realm/realm-cocoa#1950]
@jpsim @tgoyne @segiddins mapping between transient NSObjects and RLMObjects would be so much easier with dynamic schema.

I have found a great example in [tests](https://github.com/realm/realm-cocoa/blob/master/Realm/Tests/DynamicTests.m), but unfortunately it seems to be using private headers for now. Do you have plans to public source the API in the near future?

Please see this [gist with the usage example.](https://gist.github.com/rbaulin/29eb1da6eeb52233ecd1)

**Comment by tgoyne** [comment]
We plan to expose the dynamic API at some point, but there's two main reasons that we haven't done it yet:

1. It's incomplete. We've pretty much only implemented what was needed for migrations and the browser, and there's a good chance that the things implemented but not used by those don't actually work correctly, since we don't have extensive test coverage for the parts not in use.
2. It exposes some things that are currently implementation details. While we're willing to break backwards compatibility when needed pre-1.0, we still don't want to do it willy-nilly. This means that we need to first make sure that our internal APIs are in a state that we're happy with, which isn't entirely the case at the moment.

If you use the private dynamic API now you don't have to worry about us removing the functionality entirely and we will fix bugs that you report, but do expect bugs and breaking changes without warning.

Closing this issue in favor of the existing one tracking this (https://github.com/realm/realm-cocoa/issues/1291).
