### ISSUE TITLE
RealmSwift reset relationship list

### ISSUE THREAD

**Issue by krzyzanowskim** [realm/realm-cocoa#1999]
Hi.

I have a relationship that I want to reset with new list, and I can't make is happen. What is the proper way to reset relationship ?

this is what I tried
```swift
class MyModel: Object {
    var childs =  List<Child>()

    func change() {
       realm?.write {
            // I want to replace childs relationship list. Nothing I tries is working
            // self.realm?.delete(self.childs)
            // self.chats.removeAll()
            self.childs = List<Child>()
            self.childs.extend(newChildrens)
       }
    }
}

```

**Comment by jpsim** [comment]
I should preface this answer with a bit of context. The state of dynamic dispatch in Swift is quite limited and ripe with sharp corners. To make things work in Realm, we've had to make some compromises in this area, especially when it comes to `List` properties.

Since generic class properties cannot be represented in the Objective-C runtime, you shouldn't declare your `List` properties as `dynamic`. You're already doing this, so this part is ok. :+1: 

However, since non-dynamic properties don't have setters which can be overridden at runtime, Realm can't catch when you're trying to set that property and perform the equivalent operation in the underlying database.

So when you do `self.childs = List<Child>()` in your code above, Realm is never notified of what you did. Swift :cry:.

So this is why our documentation only ever shows `List` properties declared as `let`. Because setters wouldn't work :disappointed:.

So the recommended way to update a `List` property is to call [`List.removeAll()`](https://realm.io/docs/swift/latest/api/Classes/List.html#/s:FC10RealmSwift4List9removeAllU__FGS0_Q__FT_T_), followed by [`List.extend(_:)`](https://realm.io/docs/swift/latest/api/Classes/List.html#/s:FC10RealmSwift4List6extendU__FGS0_Q__USs12SequenceType_USs13GeneratorType__FQ_T_).

We'd really love to see Swift improve its dynamic capabilities and have filed numerous radars to help nudge future language developments in this direction and we hope you'll do the same if you're unsatisfied with the status quo.

**Comment by krzyzanowskim** [comment]
there is issue with this sequence:

```swift
list.removeAll()
list.extend(newList)
```

let's say I already have record in db. by calling `extended()` realm engine will try to insert it again to the table, and if I have setup with primary key... it wont be possible. So I tried something like this

```swift
realm.write {
    realm.delete(list)
    list.removeAll()
    list.extend(newList)
}
```
Can't set primary key property 'mykey' to existing value '35;75'.

however I still get error that record is already inserted and can't be inserted again (due to primary key)

**Comment by jpsim** [comment]
As you can see from `List.extend(_:)`'s [source](https://github.com/realm/realm-cocoa/blob/v0.92.3/RealmSwift/List.swift#L241-L245), it simply calls down to `-[RLMArray addObject:]` ([source](https://github.com/realm/realm-cocoa/blob/v0.92.3/Realm/RLMArrayLinkView.mm#L140-L148)) which will only add the objects if they're not already persisted to that Realm.

So it really depends what's contained in your `list` variable you've referenced above. If you're assigning a *standalone* list of unpersisted objects, then they'll be added to the Realm, and if those objects have primary keys and interfere with other objects already stored, you'll get an exception because you'll be trying to add objects with existing primary keys to the Realm, which isn't allowed.

I'm wondering at the moment why we call `-[RLMRealm addObject:]` rather than `-[RLMRealm addOrUpdateObject:]` and can't think of a good reason, although it may be escaping me. I'll bring it up with the team so we can reconsider which approach we should be taking here.

**Comment by krzyzanowskim** [comment]
regarding removeAll() how about:

```swift
    func removeAll() {
        realm?.delete(self)
        _rlmArray.removeAllObjects()
    }
```

**Comment by jpsim** [comment]
That's not quite what `removeAll()` is intended to do. Sometimes you simply want to remove those objects from a `List` without deleting it from the Realm.

**Comment by krzyzanowskim** [comment]
I understand and agree. removeAll() just "disconnect" relationship without deleting related items. If you name it `deleteAll()` it would be a bit more connected to the realm. I mean... 2 functions to reset relationship is not something that came first to my mind ;-)

**Comment by jpsim** [comment]
I do wonder how often you really want to completely reset a to-many relationship. What's a use case in which you wouldn't be better off completely throwing away the existing relationship items rather than inserting/removing?

**Comment by krzyzanowskim** [comment]
Since realm don't have "cascade delete" feature, this seems to me quite useful to keep db consistent.

**Comment by jpsim** [comment]
I've created #2005 to improve our documentation around `List` properties to make them a bit easier to understand. We won't be changing how `List.append(_:)` or `List.extend(_:)` work, however. If you're adding unpersisted objects to Realm with conflicting primary keys, you'll get an exception and that's up to you the user to manage.

**Comment by AndrewBarba** [comment]
Are there any updates to this since KVO support? You guys must be able to do something better than what I'm doing...
```
    // Lists
    public var items: List<BookingItem> = List() {
        willSet(newValue) { items.removeAll() }
        didSet { items.forEach(oldValue.append) }
    }
    
    public var fees: List<BookingFee> = List() {
        willSet(newValue) { fees.removeAll() }
        didSet { fees.forEach(oldValue.append) }
    }
    
    public var users: List<BookingUser> = List() {
        willSet(newValue) { users.removeAll() }
        didSet { users.forEach(oldValue.append) }
    }
```

**Comment by jpsim** [comment]
This is tricky. The short answer is that I don't think you'll get to a much more elegant solution than what you already have.

We can't override List property setters because that type can't be represented by the Objective-C runtime. We can't automatically do what you're doing because `willSet` and `didSet` have to be implemented at the property level, not the type level.

We might be able to simplify your code a tiny bit, however. Would this work?

```swift
public var items: List<BookingItem> = List() {
    willSet { items.removeAll(); items.extend(newValue) }
}
```

**Comment by AndrewBarba** [comment]
Yeah this is what I settled on but now I am running into a really strange issue where the list is being reset to an empty list if `map["xyz"] == nil`. I am only losing values on the `List` types so I cannot for the life of me figure out why that is happening.

**Comment by AndrewBarba** [comment]
Definitely an ObjectMapper issue, opened an issue here: https://github.com/Hearst-DD/ObjectMapper/issues/252

**Comment by AndrewBarba** [comment]
Okay I figured it out... ObjectMapper will set the property to itself. So instead I made an extension:
```
// MARK: - List

extension List {
    
    public func replace(list: List, delete: Bool = false) {
        if list === self { return }
        removeAll()
        appendContentsOf(list)
    }
}
```
And then I can just use:
```
public var images: List<Image> = List() {
    willSet { images.replace(newValue) }
}
```
