### ISSUE TITLE
Why do In-Memory Realms create files in Documents?

### ISSUE THREAD

**Issue by rsahara** [realm/realm-cocoa#2029]
I'm using 0.91.3.
I tried to create an in-memory realm obj with the following code.

```objective-c
_cacheDb = [RLMRealm inMemoryRealmWithIdentifier:@"cacheDb"];
```

This created the following files in the app's Documents:
cacheDb, cacheDb.lock, cacheDb.log, cacheDb.log_a, cacheDb.log_b

Why does it create files on storage?
Even the document says
> Normally Realms are persisted to disk, but you can also create ones which are **purely in memory** by using the [RLMRealm inMemoryRealmWithIdentifier:] initializer

These files are persistent, and they (at least "cacheDb") get bigger when I add data.

**Comment by jpsim** [comment]
Our documentation is clearly wrong here. In-memory realms aren't *purely* in memory, as you've noticed. In-memory Realms still use mmapped files for all their operations, including storing data, but have next to no guarantees of consistency across launches, which does speed certain things up.

We call them "in-memory" because they're volatile and aren't persisted across launches.

We'll update that documentation as soon as possible to reflect this behavior.

**Comment by jpsim** [comment]
I've created #2031 for us to track updating our docs.

**Comment by astigsen** [comment]
> In-memory Realms still use mmapped files for all their operations,
including storing data, but have next to no guarantees of consistency
across launches, which does speed certain things up.

They also never explicitly sync to disk. So unless so much memory is used
that it has to spill to disk, it is likely to operate entirely in memory
(note that a consequence of this is that 'in-memory' mode actually can
handle data bigger than what fits in memory, but then it will have to use
the disk backing for swap, even if it is not persisting it across launches).
