### ISSUE TITLE
Clarify that in-memory realms still may write to disk

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2031]

**Comment by astigsen** [comment]
It is actually working in-memory. It may write to disk, but only in the sense that any other write to memory can cause a the virtual memory to swap to disk (at least on OSX, iOS does not swap).

When in in-memory mode, it will never do an explicit write to disk (apart from occasionally resizing the backing file).

**Comment by segiddins** [comment]
But since the backing file is in a user-visible location, it appears to the user that they're "written to disk", which is what might be confusing.

**Comment by rsahara** [comment]
By the way, the file I saw first was only 383KB (became 800KB after adding some data) and appeared just after the app started (I'm not sure but maybe after a commitWriteTransaction during initialization.)
From my point of view, I didn't see much difference between in-memory and saved to disk.

Maybe some explanations/hints on the usage (when to choose in-memory) would be nice.
Because in my case, I was trying to implement a mode for my app that doesn't use cache storage (including cached models, images etc) at all, so users with low storage don't crash (around 10 users were crashing because of low storage last 10 days, at DAU 20K.) For realm models, I was thinking that maybe just switching Realm in-memory would work, which was a bad approach.
