### ISSUE TITLE
Why my realm test is far slow than coredata?

### ISSUE THREAD

**Issue by ufosky** [realm/realm-cocoa#2046]
I use https://github.com/samus/iOSStorageShootOut test performace, the result is realm is far slow than coredata.

**Comment by segiddins** [comment]
@ufosky I'm surprised to hear that! Taking a look at the Realm code in that repo, there are a few places where performance could probably be optimized a bit: 

1) https://github.com/samus/iOSStorageShootOut/blob/9758896f64835046f67e37264d4cb085de1cdf33/RealmShootOut/RealmPostDataController.m#L22-L38 -- importing posts could do a write transaction outside of a loop, so there's only one write transaction for all the posts imported at once

2) https://github.com/samus/iOSStorageShootOut/blob/9758896f64835046f67e37264d4cb085de1cdf33/RealmShootOut/RealmPostDataController.m#L40-L45 -- if `postId` where made a primary key, you could use `+[RLMObject objectForPrimaryKey]`.

3) https://github.com/samus/iOSStorageShootOut/blob/9758896f64835046f67e37264d4cb085de1cdf33/RealmShootOut/RealmPostDataController.m#L70-L76 -- `RLMResults` is optimized to be lazy, so converting it to an `NSArray` is often unnecessary overhead, since `RLMResults` also conforms to `NSFastEnumeration`.

**Comment by jpsim** [comment]
Also, I'd encourage you to make sure you're running these benchmarks in the "Release" configuration, since Realm's debugging builds are considerably slower.

**Comment by jpsim** [comment]
@ufosky those benchmarks aren't representative of Realm's performance in production.

For one, you're measuring the CSV parsing as part of the benchmarks, which takes over 90% of the benchmark time. Also, all the schemes are set to run in Debug mode (which doesn't reflect the behavior or performance of Release builds). Applying Sam's recommendations makes Realm significantly faster than Core Data (and other solutions in those tests).

We've published benchmarks before (see our [launch blog post](https://realm.io/news/introducing-realm/) and corresponding [benchmark source code](https://realm.io/assets/Bench.zip)). I encourage you to look through those for more information, although they are a bit outdated.
