### ISSUE TITLE
When setting a `defaultPropertyValues` and there is no property, Realm should warn/crash

### ISSUE THREAD

**Issue by natanrolnik** [realm/realm-cocoa#2048]
In one of my RLMObject subclasses, I implemented defaultPropertyValues. Then, I removed one of the properties from the object declaration, and forgot to remove the default value from `defaultPropertyValues`. 

The app stopped [here](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMObjectBase.mm#L46) and simply became unresponsive, without crashing or explaining the reason.

Wouldn't it be better if Realm would let the developer know the problem, or crash to show that there is something wrong?

**Comment by segiddins** [comment]
@natanrolnik can you share the entire backtrace at the point the app is hanging? Having extra keys in that dictionary shouldn't be causing any issues.

**Comment by jpsim** [comment]
I'm not sure why the exception message wasn't being printed to the console, since when I try:

```objc
@interface Model : RLMObject
@end
@implementation Model
+ (NSArray *)defaultPropertyValues {
  return @{@"undefined": @YES};
}
@end
```

I get the following exception:

```
'[<Model 0x7fbe1ae723e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key undefined.'
```

I've seen reports of [Xcode not logging exception messages](http://stackoverflow.com/questions/19377018/xcode-5-not-printing-exception-detail), but those cases should be marked as Xcode bugs, not Realm.
