### ISSUE TITLE
Cannot have property names that start with "init"

### ISSUE THREAD

**Issue by edgarjcfn** [realm/realm-cocoa#2076]
This kept me "entertained" for the last 2 hours or so, and it's easily reproduceable:

If a class is defined as such
```swift
class MyThing :RLMObject {
   dynamic var initValue :Int = 0;
   dynamic var finalValue :Int = 0;

   func save() {
        let realm = RLMRealm.defaultRealm();
        realm.beginWriteTransaction();
        realm.addObject(self);
        realm.commitWriteTransaction();
   }
}
```

And then the save method is called
```swift
let thing = MyThing();
thing.save();
```

A runtime error is thrown:
```
malloc: *** error for object 0x7f9e664c1f80: pointer being freed was not allocated
```

And that can easily be solved by simply removing or renaming the property `initValue` so that it doesn't start with "init".

I'm using obj-c framework v. 0.93.1, running on Simulator. (We chose to go with the obj-c framework, even though we use Swift, because we need to support iOS 7).

**Comment by tgoyne** [comment]
[ARC requires that names starting with `init` and then a non-lowercase character be initializer methods](http://clang.llvm.org/docs/AutomaticReferenceCounting.html#method-families). A property named `initValue` violates this, resulting in an extra release due to ARC expecting the method to return a +1 value when it actually returns a +0 value. This also causes a crash in the following non-Realm code:

```swift
class MyThing :NSObject {
    dynamic var initValue :Int = 0;
    dynamic var finalValue :Int = 0;

    func save() {
        self.valueForKey("initValue");
    }
}

let thing = MyThing();
thing.save();
```

**Comment by edgarjcfn** [comment]
That's nice to know. Thank you!
