### ISSUE TITLE
Output messed up when using "long long" type

### ISSUE THREAD

**Issue by tebica** [realm/realm-cocoa#2083]
This is reproducible on simulator and device both 

Please check [sample code](https://github.com/TheFinestArtist/Realm-Long-Long-Test-Objective-C/blob/master/Simple/AppDelegate.m) here

* Expected result (see the README.md on [Android project](https://github.com/TheFinestArtist/Realm-Long-Test-Android)): 
* [iOS Project](https://github.com/TheFinestArtist/Realm-Long-Long-Test-Objective-C)
  * first query : working fine (243 result)
  * 2nd query : returning big range number results even it queries "key <= 9". (maybe it seems like big numbers are overflowed or something)

**Comment by tgoyne** [comment]
In the simulator this is hitting a bug in the SSE2 variant of the code. I can repro on a 32-bit device but not a 64-bit device which is a bit odd, as we don't have any ARM SIMD code for that so it's using the same (seemingly correct) code for both of those.

**Comment by tgoyne** [comment]
Okay, so there's several problems here. The SSE4.2 code path for < and <= on a 64-bit value is actually doing != due to a typo, but the problem you're running into when running on device is that `[NSPredicate predicateWithFormat:@"key <= %llu", 9]` is invalid. `%llu` is expecting a 64-bit value, but `9` only gives a 32-bit value and it's reading another four bytes of garbage off the stack, possibly resulting in a very large number. The first query works because the values are too large for a 32-bit int, so the int literal is giving a 64-bit int. The simplest fix for this is to either do `[NSPredicate predicateWithFormat:@"key <= %llu", 9ULL]` so that the int literal matches the format string or change the format string to `%d`.

**Comment by jpsim** [comment]
This should be resolved once we cut cocoa releases with an updated version of Realm (SSE fix included in https://github.com/realm/realm-core/pull/883).

**Comment by bmunkholm** [comment]
@jpsim: Hasn't this been released by now?

**Comment by segiddins** [comment]
Yes, this was fixed in https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md#0940-release-notes-2015-07-29.
