### ISSUE TITLE
Realm file using primary keys written by Android, crashes on iOS due to migration required

### ISSUE THREAD

**Issue by yaming116** [realm/realm-cocoa#2160]
i have a realm file , it create by android .when i query the data, i got a crash

*** Terminating app due to uncaught exception 'RLMException', reason: 'Migration is required for object type 'ZtyHomeWorkContent' due to the following errors:
- Property 'ho_id' has been made a primary key.'
*** First throw call stack:

**Comment by ldramire** [comment]
I ran into the same issue. I forget where I found the solution, but adding an empty migration block in my app delegate resolved the problem. Not sure why this is necessary since it does nothing and importing a Realm db in Android that was created with Objective C works fine with no such workaround, but here you go:

````ObjectiveC
[RLMRealm setDefaultRealmSchemaVersion:1
withMigrationBlock:^(RLMMigration* migration, uint64_t oldSchemaVersion) {
	}];
````

**Comment by yaming116** [comment]
thanks.
I have an almost 60Mb file, IOS also need these data, in Object-C program, I rushed directly on the server to download the file

**Comment by kishikawakatsumi** [comment]
@yaming116  I'm sure there are some differences in schema definitions among Android and iPhone.

`Property 'ho_id' has been made a primary key.'`

This message shows the `ho_id` is not primary key on Android. However it is defined as a primary key on iPhone. So please check the schema definition of Android whether `ho_id` is primary key or not. If not, you should remove specifying `ho_id` as primary key.

**Comment by ldramire** [comment]
@kishikawakatsumi I don't know if that is the issue with the OP, but when I ran into this issue, there was no difference in schema. A simple model with the same primary key defined in both Android and iOS would throw this error when opening the Realm on iOS that had been generated on Android. However, creating a Realm DB in iOS and opening it in Android worked just fine.

**Comment by tgoyne** [comment]
Are you using a version of Realm Java older than 0.80.3? Until then it wrote the primary key metadata in a way incompatible with Realm Cocoa (newer versions of Realm Java will automatically migrate files to the correct format).

**Comment by ldramire** [comment]
@tgoyne I am using Java 0.80.3 and iOS 0.93.2.

**Comment by jpsim** [comment]
@ldramire are you still having this issue? It would be helpful if you shared your realm file with us so we could investigate what is wrong with it.

Since Realm Java 0.80.3 introduced an automatic migration from the old, java-only, primary key format to the new, cross-platform compatible primary key format, please make sure to run this java migration before using the file from Realm Objective-C.

**Comment by ldramire** [comment]
@jpsim Haven't looked into it further since adding the workaround, but I can try it again and post back when I get a chance.

**Comment by jpsim** [comment]
Please do! We'll reopen if you can share more if it's still a problem.
