### ISSUE TITLE
Option for closing a realm

### ISSUE THREAD

**Issue by lbanders** [realm/realm-cocoa#2203]
In some cases it would be nice to be able to close the realm instance by calling a close() or closeRealm() method on the RLMRealm instance.

E.g.: We are handling migration manually and sometimes we would have to close the DB for setting a new schema version. For now I have simply nilled the instance, but as the amount of data grows it seems it takes longer to close the db this way.

**Comment by segiddins** [comment]
@lbanders relinquishing all strong references to the Realm will cause it to become "closed", but in general we don't recommend using the same path for multiple different realm files.

**Comment by jpsim** [comment]
I'm closing this issue as it's a fundamental design decision driving how Realm works: `RLMRealm` instance lifecycles map directly to database connection lifecycles. This means that as much as possible, it's safe to access data in a Realm if you have an `RLMRealm` instance available.

Offering a `close()` method would then invalidate all other realms, and there may be some active transactions at that time in other threads, so behavior would then be very surprising since those realms could invalidate at any time, without warning.

**Comment by lbanders** [comment]
That sounds fair :) 
I have found a different way of dealing with this issues as the way I was dealing with upgrades at that time was kinda buggy.
