### ISSUE TITLE
Document how to do "paging" in Realm

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2264]
See #2247.

**Comment by kunalsood** [comment]
This may not be a good place for this comment, but I couldn't think if any better place.

Have you guys considered, writing a high-level Technology Overview of Realm?
Kind of like: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CoreData/Articles/cdTechnologyOverview.html

It could talk a little about memory mapping, and it's advantages in the context of Ream. It could highlight the fact that because it is memory mapped, the need for batching/faulting, caching, and paging is pretty much eliminated in Realm. It could also explain that lightweight object accessors are only created when accessed in arrays/results, and how properties are literally read from a memory mapped file (as per my understanding) when they are accessed instead of being copied into memory.

I think this might reduce the number of issues that get opened (on a fairly regular basis) about issues batching/faulting/caching/paging.

Hopefully, this comment is at least a little helpful. :)

**Comment by jpsim** [comment]
> Hopefully, this comment is at least a little helpful. :)

Definitely! This is something we'd love to do, and it's only a matter of taking the time. There are many [docs issues](https://github.com/realm/realm-cocoa/labels/docs) that we need to tackle first though...

**Comment by jpsim** [comment]
@TimOliver you assigned yourself to this a while back. Are you still working on it? If so, what's blocking you? If not, please unassign yourself.

**Comment by TimOliver** [comment]
Sorry JP! I was aiming to do this one this week (Which was why I hadn't removed myself).
I've filed a PR for adding this to the docs now.

**Comment by jpsim** [comment]
Done: https://realm.io/docs/objc/latest/#limiting-results
