### ISSUE TITLE
Initialising an in-memory Realm with the contents of an on-disk Realm?

### ISSUE THREAD

**Issue by tonyarnold** [realm/realm-cocoa#2328]
It'd be nice to be able to initialise an in-memory Realm with the contents of an on-disk Realm.

**Comment by segiddins** [comment]
@tonyarnold if I'm remembering correctly, this has been brought up before. What advantages do you see this bringing you?

**Comment by tonyarnold** [comment]
Yeah, possibly — it's been a while since I've had a chance to do anything Realm-related. My main use case here is for my NSDocument subclass that I've been working on — a document can move from an on-disk representation to one that only exists in memory until the users chooses to save. 

It sounds like it might be useful for things like bundling pre-populated DBs with apps, and testing as well.

**Comment by segiddins** [comment]
At the end of the day, in-memory realms are basically just normal realms that are never `fsync`ed, and are unlinked after they're no longer referenced. To start, you could `writeCopyToPath:` to a tmpdir, and manage cleaning that up yourself?

**Comment by tonyarnold** [comment]
That's exactly what I am doing :wink: Thanks!

**Comment by tonyarnold** [comment]
Did you mean to close this? I'd still love to be able to seed an in memory realm on creation with the contents of another using realm API rather than having to maintain this myself. This could be useful for on disk realms too.

**Comment by jpsim** [comment]
Yes, we meant to close this, but not without comment. Sorry about that! The current mechanism for copying an entire Realm is by using [`writeCopyToPath:`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/writeCopyToPath:error:).

I believe the proper approach here is actually to deprecate in memory realms as a concept altogether and instead have a "durability" setting when configuring a realm. This would be a more honest reflection of what we currently call "in-memory" vs "persisted" realms.

Again, sorry for closing this without comment, it's something we generally try to avoid because it leaves everyone confused. But I hope this explanation helps.
