### ISSUE TITLE
Indexed property support for all types including Float and Double

### ISSUE THREAD

**Issue by florianreinhart** [realm/realm-cocoa#2333]
Realm should provide indexed property support for all types. The documentation states that only String and Int properties are supported: https://realm.io/docs/swift/latest/api/Classes/Object.html#/s:ZFC10RealmSwift6Object17indexedPropertiesFMS0_FT_GSaSS_

**Comment by jpsim** [comment]
Thanks for the feature request @florianreinhart! We're already tracking this issue as #2188, so I'll be closing this one as a duplicate. Let's continue the conversation there.

Until we add support for this, can you share the use case that prompted you to look for Float and Double indexing? Indexing only really helps speed up certain types of queries relying on the indexed column, but otherwise doesn't expose any additional functionality. Everything you can do with an indexed property you can do without indexing. If you found a particular query to be slower than you needed, please post it here and we may be able to optimize it by other means.

Thanks!
