### ISSUE TITLE
sad not support ios7.0

### ISSUE THREAD

**Issue by longxianlin** [realm/realm-cocoa#2339]
I have to use sqlite3 instead of realm

**Comment by longxianlin** [comment]
swift

**Comment by kishikawakatsumi** [comment]
@longxianlin Realm can work on iOS 7, unlike RealmSwift. Could you please try to use Realm Objective-C with Swift bridge? Realm Objective-C is also made to be easy to use from Swift according to Nullability and Generics support.

And please make sure to use `RLMSupport.swift` file when you use Realm Objective-C from Swift. It gives refinements for the Objective-C API for Swift.

**Comment by segiddins** [comment]
@longxianlin what @kishikawakatsumi said is the best advice we have for supporting iOS 7 -- Realm Swift simply can't support it, since iOS 7 doesn't support third party dynamic frameworks and there's no way to make static libraries that contain Swift. I'm going to close this issue for now, but feel free to reopen it if you have further questions!
