### ISSUE TITLE
Safe deletion of Realm files

### ISSUE THREAD

**Issue by segiddins** [realm/realm-cocoa#2422]
Should we add a method that takes a configuration and, ensuring there are no realms open at the given path, deletes the realm file?

**Comment by jplazcano87** [comment]
yes, i handle multiple realm files, one per user logged into the app, this will be a awesome feature

**Comment by bcapps** [comment]
This would be nice. We currently manually delete the realm file and lock file when Realm() initialization throws a migration error, and simply re-initialize a new one after. A method for this would simplify that process.

**Comment by segiddins** [comment]
@bcapps a configuration option to delete when migration needed is actually a separate issue already.

**Comment by kunalsood** [comment]
+1
This would be pretty useful.
Another method that would be useful: There is already a compact method in RLMRealm, but, is kept out out the public header because (if I understand correctly) it may only be used when there are no realms open at the given path. So, a method that takes a configuration and, ensuring there are no realms open at the given path, compacts the realm file.

**Comment by segiddins** [comment]
@jpsim @tgoyne thoughts on this one?

**Comment by jpsim** [comment]
We definitely do need to provide a safe way to delete a realm file and all its associated files since NSFileManager's removeItemAtPath won't warn/throw if there are any open realms, which has lead to users being surprised by the behavior in the past.

I can't think of any reason that the entire configuration object would be useful, however, so simply a `+[RLMRealm deleteRealmAtPath:error:]` should be sufficient.

**Comment by jplazcano87** [comment]
if this solve the problem with open realms, then is excellent !

**Comment by jpsim** [comment]
> if this solve the problem with open realms, then is excellent !

You'll still need to nil out realm references before deleting realm files, even with a new deletion method. If we didn't require this, it'd be possible to delete a file while an open transaction is taking place, causing data to be read from a deleted file at runtime, which would be very dangerous.

**Comment by jasper-ch-chan** [comment]
So for safety sake, I imagine this method should throw an error should the user try to delete the Realm files while there is a realm reference to it?

**Comment by jpsim** [comment]
> So for safety sake, I imagine this method should throw an error should the user try to delete the Realm files while there is a realm reference to it?

Yes, which would give it an advantage over `NSFileManager` or other lower level file operations with no knowledge of Realm.

**Comment by DominicFrei** [comment]
This is covered by https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm.h#L273 already but hasn't been closed yet. 👍
