### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#2424]
Hi!
This is a curious case for me, and I would be glad to analyse it with you, guys.
I have some time profiling tools reports.
**While I will describe our logic, it is possible that some of our choices are not very good for optimisation, but lets ignore that for a while and focus on Realm behaviour.**

First of all we use 0.94.1 version.
We are an e-commerce app, therefore we have products, and Wishlists.
Consider the fact that Wishlist already exists in the database, and it's always only one Wishlist.
Products that are considered in Wishlist - are added to a RLMArray<Product> in Wishlist object.
In our case it doesn't matter if there are already some products in the Wishlist.

We have a product list screen - a collection view, with 2 products per row, 4 per view. So At first there are 4 shown, and at scroll plus 2 cells are being loaded.
Each tile has a Favourite button (read as Wishlist), which has two states: in Wishlist or not, and it can be toggled right from the list.

Now each time when we scroll and new cells are allocated, it want to know the state of the favourite-button. For this, it wants to know whether this product is in Wishlist. 

**The problem:**
Very obvious UI lags on scroll.

Because there is only one wishlist, we have a pseudo-singleton implementation:
```
+ (Wishlist *)defaultWishlist {
    NSArray *wishlists = [<wrapper_class>:[Wishlist objectsWhere:@"name = %@", NameConstant]];
    Wishlist *defaultWishlist = wishlists.count > 0 ? wishlists[0] : [self createPersistedWishlistWithName: NameConstant];

    return defaultWishlist;
}
```
So at our point `else` is never called. In our tests there is always a wishlist already initialized.
And we have this:
```
+ (BOOL)isProductInDefaultWishlist:(Product *)product {

    return [[self defaultWishlist] isProductInWishlist:product];
}
```

First, I used the NSDate-check arround the `NSArray *wishlists = [<wrapper_class>:[Wishlist objectsWhere:@"name = %@", NameConstant]];` line.

```
 0.610766 RLMAccessor_v0_Wishlist
 0.000085 RLMAccessor_v0_Wishlist
 0.000070 RLMAccessor_v0_Wishlist
 0.000066 RLMAccessor_v0_Wishlist
 0.411311 RLMAccessor_v0_Wishlist
 0.000088 RLMAccessor_v0_Wishlist
 0.342239 RLMAccessor_v0_Wishlist
 0.000080 RLMAccessor_v0_Wishlist
```

We can see the pattern: 4+2+2, and every first call is a long one.
Now I think you have enough information to analyse this: 
![screenshot 2015-08-21 16 14 51](https://cloud.githubusercontent.com/assets/457094/9411456/b5c2ad7c-482e-11e5-8aa9-d1347807974c.png)
This stack shows the trace.
Please notice the methods that are being called: 
`Repo.isProductInDefaultWishlist -> Repo.defaultWishlist -> RLMObject methods`

Now, the interesting part!
When I will toggle any product (which will either remove it from the wishlist, or add it to wishlist),
This happens:
```
0.000116
0.000101
0.000102
0.000070
0.000178
0.000068
0.000104
0.000087
0.000135
0.000066
```
And the new stacktrace:
![screenshot 2015-08-21 17 52 31](https://cloud.githubusercontent.com/assets/457094/9411580/79c3f8e8-482f-11e5-99ee-7c01aa92d1b7.png)
Also is funny the methods that are being called:
`Repo.isProductInDefaultWishlist -> Wishlist.isProductInWishlist -> RLMArray methods`

So what is the difference? Why it was needed to toggle a wishlist state in database to make it cached and speed up the process?

**Comment by tgoyne** [comment]
When you fetch the Wishlist the first time, Realm has to first open the database file (`SharedGroup::open()`), which takes some time. After opening the file, Realm adds the `RLMRealm` instance to a cache, and reuses it for the next three calls. However, the `RLMRealm` instance only stays in the cache as long as you're holding a reference to an object from that Realm somewhere, as otherwise it'd be a memory leak. This means that if you aren't holding any references (and once the autorelease pool is drained), Realm has to re-open the file the next time a new cell comes into view.

The solution is to store a reference to the Realm somewhere for the duration of the lifetime of the view controller. The quick-and-dirty thing would be to just have an `RLMRealm *` property that's initialized to `[RLMRealm defaultRealm]` in `viewDidLoad`. My inclination for a nicer solution would be to have the VC store an instance of `NMSWishlistRepository` which would be responsible for that sort of thing.

**Comment by jpsim** [comment]
@OlegAnghelov let us know if the response posted above helped explain what's happening here, and please open an issue if you have any further questions!

**Comment by OlegAnghelov** [comment]
The cleanest solution we thought about was declaring `Wishlist *defaultWishlist`  as static, so it maintained the reference to the object, and it did solve the problem.

Thanks for great hints, sorry for not replying sooner :)
