### ISSUE TITLE
Non-optional Link properties throw error

### ISSUE THREAD

**Issue by rpless** [realm/realm-cocoa#2434]
In Swift 2 on Xcode 7 beta 6, any link property that is not marked with optional throws an error as of d2bf93c27785df9046d31907b9d704437d9cbf1d. Are there any plans to bring back non-optional link properties?

**Comment by segiddins** [comment]
This is actually an intentional change, which is called out in the CHANGELOG. Realm actually never supported non-optional link properties, and could make no guarantees that a non-optional link property would _never_ be nil, and Xcode 7 Beta 6 was a reminder of the danger of returning `nil` from a non-optional properties (NULL dereferences in the Swift runtime), so we thought it would be better to make that an error upfront. If you'd like, you _should_ be able to declare the property as an implicitly unwrapped optional, though we haven't tested that yet.

**Comment by rpless** [comment]
Hey @segiddins. Thanks for the quick response. Implicitly unwrapping the optional seems to be working for us.
