### ISSUE TITLE
Build warnings in Realm 0.95

### ISSUE THREAD

**Issue by lionpants** [realm/realm-cocoa#2448]
Just updated to Realm 0.95 and am receiving the following build warnings...

`../RealmSwift/RealmConfiguration.swift:135:45: Forced cast from 'Object.Type' to 'AnyClass' always succeeds; did you mean to use 'as'?`

`../RealmSwift/Migration.swift:73:58: 'defaultPath' was deprecated in * version 1: Use Configuration.defaultConfiguration`

`../RealmSwift/Realm.swift:636:93: 'defaultPath' was deprecated in * version 1: Use Configuration.defaultConfiguration`

A bit ironic. :P

Thanks for fixing the analyzer warning in 0.64. :)

**Comment by jpsim** [comment]
Thanks for reporting this issue, @lionpants! The first warning is fixed in master (see https://github.com/realm/realm-cocoa/blob/35575f1dc3713a2f86f5399953cf645ebc850777/RealmSwift-swift1.2/RealmConfiguration.swift#L135). As for the deprecation warnings, those will be addressed once Realm entirely moves from the old path methods to the new configuration methods, which we intend to do for our next major release.
