### ISSUE TITLE
Fast object count  : countForFetchRequest equivalent?

### ISSUE THREAD

**Issue by phin** [realm/realm-cocoa#2472]
I currently need (for tracking purposes) to count the number of objects currently in the Realm database of a specific Model.
I use at the moment `RealmModel.allObjects().count` to keep track of the count through my whole flow.

Back in the CoreData days (a.k.a until 2 weeks ago), I used countForFetchRequest , which from what I understood would not load the data, just do a "faster" basic count http://stackoverflow.com/questions/1134289/cocoa-core-data-efficient-way-to-count-entities

Is there/Should there be an equivalent for Realm?

**Comment by jpsim** [comment]
Since Realm's queries are *lazy*, it's unnecessary to use a different API to optimize getting the number of objects matching a query. So please continue to use `RealmModel.allObjects().count`.

See our implementation for `-[RLMResults count]` to get an idea of how this works: https://github.com/realm/realm-cocoa/blob/v0.95.0/Realm/RLMResults.mm#L224-L233. E.g. if the view has already been created, get its size. If the query hasn't run yet, just get its count.

This pattern is generally applicable for most tasks you'd want to do in Realm. We've worked hard to optimize the natural way to do things as much as possible.

**Comment by tgoyne** [comment]
In the specific case of `allObjects()` it doesn't even have to run a query and get the count, as that returns a different RLMResults subclass [that just reads the size of the backing table directly](https://github.com/realm/realm-cocoa/blob/v0.95.0/Realm/RLMResults.mm#L565).

**Comment by jpsim** [comment]
Ah, yes sorry I missed that.
