### ISSUE TITLE
Equality & Hashing

### ISSUE THREAD

**Issue by dimazen** [realm/realm-cocoa#2490]
While you have `-[RLMObject isEqualToObject:]` and `RLMObjectBaseAreEqual` common Foundation equality `-[NSObject isEqual:]` & hashing `-[NSObject hash]` are not implemented . Any plans for it?

**Comment by dimazen** [comment]
p.s. not important at all, just was curious about this :)

**Comment by jpsim** [comment]
`-[RLMObject isEqual:]` and `-[RLMObject hash]` *are* implemented in `RLMObject`'s superclass, `RLMObjectBase`: https://github.com/realm/realm-cocoa/blob/v0.95.0/Realm/RLMObjectBase.mm#L227-L246

We don't have interfaces for these in `RLMObject` or `RLMObjectBase` because they're provided in their superclass `NSObject`.

**Comment by dimazen** [comment]
Thanks for clarification! Haven't seen!
