### ISSUE TITLE
JSON to realm object mapping issue iOS Swift

### ISSUE THREAD

**Issue by mustafa-almulla** [realm/realm-cocoa#2509]
I have asked this question in stockoverflow, see link below, and I got the answer from one of Realm Team member. but I had following up comment which is "why wouldn't realm try to cast/convert the string to int when the data type is int, and only throw an error when value cannot be cast? "

could you please elaborate more on it. 

http://stackoverflow.com/questions/32412108/json-to-realm-object-mapping-issue-ios-swift/32441004#32441004

**Comment by segiddins** [comment]
This indeed is intentional -- Realm won't attempt to perform any sort of value transformation because it doesn't have the context into your app that you, as the developer, do. For instance, what would we do if the string _couldnt_ be converted to an integer? You might not have planned for that in development if all you tested against were well-formed responses, and thus throwing an exception there would be _incredibly_ surprising. Instead, we found it to be better to 'fail fast' and fail consistently when presented with data incompatible with your object model.

**Comment by TimOliver** [comment]
@mustafa-almulla Thanks for following this up on the Realm GitHub like I suggested Mustafa! I hope that cleared up the reason why JSON-mapping was implemented as it was in Realm.
