### ISSUE TITLE
Missing documentation on how to uninstall Realm

### ISSUE THREAD

**Issue by conradwt** [realm/realm-cocoa#2517]
I was able to install things per the instructions in the docs but there's no documentation to uninstall.

**Comment by TimOliver** [comment]
@conradwt Hi Conrad! I'm just going through the issues here and touching base on some of the ones that haven't been followed up properly yet.

In what context would you want to uninstall Realm? Are you wanting to switch away from Realm to another library? And if so, how come?

In any case, at this point, I'm not sure if there's much to actually write in regards to 'uninstalling' Realm. Most often than not, it's simply a matter of removing the frameworks references from your app project.

**Comment by conradwt** [comment]
@TimOliver  In short, I need to be able to remove the templates that were installed via the zip file on Mac OS X.  

Why I'm switching away?  I prefer to stick with the Apple frameworks at this time for persistence.

**Comment by jpsim** [comment]
To remove the components installed by the Realm Xcode plugin, you'll need to undo the steps performed in https://github.com/realm/realm-cocoa/tree/master/plugin. We don't offer an uninstaller for this, if only because we haven't written one yet, and this is actually the first time anyone's requested it.

**Comment by conradwt** [comment]
@jpsim Thanks for the information because this has resolved my issue.
