### ISSUE TITLE
realm.close() and realm.rekey(newkey:NSData?)

### ISSUE THREAD

**Issue by angerman** [realm/realm-cocoa#2541]
Hi, two questions:

First, are there any plans to add the option to forcefully close a realm?
Second, are there plans to support changing the encryption key on the fly?

**Comment by angerman** [comment]
The JAVA version does have a `close`:
see `https://github.com/realm/realm-java/blob/master/realm/src/main/java/io/realm/Realm.java#L239`

Would be nice to have that in iOS as well.

**Comment by jpsim** [comment]
> First, are there any plans to add the option to forcefully close a realm?

This was brought up before in #2203 where I explained why this isn't really an option without losing our language-level object lifetime guarantees.

> Second, are there plans to support changing the encryption key on the fly?

This is supported today through [`-[RLMRealm writeCopyToPath:encryptionKey:error:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#//api/name/writeCopyToPath:encryptionKey:error:). We can't do it "in-place" because that could be catastrophic if the operation failed partway through.
