### ISSUE TITLE
Support for NSArray, which doesn't contain Realm objects, but a base class of object

### ISSUE THREAD

**Issue by peterpaulis** [realm/realm-cocoa#2542]
It should be possible to parse into standard NSArray where the objects inside this array wouldn't be Realm objects

- like i have a class, which has .references (see bellow), but i don't want to have a realm object for that a NSDictionary is just fine... moreover the references don't have a primary key and i want to just replace the whole array when using createOrUpdate

<pre>
    {
        "name": "1 2 2 6 6 Pentamethyl 4 piperidyl methacrylate",
        "htmlName": "1,2,2,6,6-Pentamethyl-4-piperidyl methacrylate",
        "compoundID": 2659,
        "referenceNumber": 2637,
        "synonymns": [
                      "1,2,2,6,6-Pentamethyl-4-piperidinyl methacrylate",
                      "2-Propenoic acid, 2-methyl-, 1,2,2,6,6-pentamethyl-4-piperidinyl ester"
         ],
        
        "references": [
                       {
                           "SiteCaption": "PubChem",
                           "SiteUrl": "http://pubchem.ncbi.nlm.nih.gov/",
                           "referenceCaption": "10933588",
                           "referenceUrl": "http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?cid=10933588"
                       },
                       
                       {
                           "SiteCaption": "ChemSpider",
                           "SiteUrl": "http://www.chemspider.com/",
                           "referenceCaption": "9108824",
                           "referenceUrl": "http://www.chemspider.com/Chemical-Structure.9108824.html"
                       }
                       
          ]
        
    }
</pre>

**Comment by jpsim** [comment]
These are features we'd also like to add!

We're tracking support for arrays of primitives (non-Realm objects) in #1120, "typeless" dictionaries in #1486, which we would implement as "inline" objects like you're asking (replace the whole property when setting).

So since these are all features we're already tracking, I'll be closing this as a duplicate. Feel free to subscribe to the aforementioned tickets to be notified of any progress we make on these fronts.
