### ISSUE TITLE
Any way to migrate from Core Data/Magical Record?

### ISSUE THREAD

**Issue by dslysenko** [realm/realm-cocoa#2550]
Title. I would consider switching to Realm, but will stick with Core Data if it would mean all my users having to re-log-in.

**Comment by bmunkholm** [comment]
Hi @dslysenko 
Not sure what you mean with "re-log-in"? Realm is a pure local embedded database. We don't handle anything related to login. For some ideas about how to migrate from CoreData you can checkout this blogpost: https://realm.io/news/migrating-from-core-data-to-realm/

**Comment by dslysenko** [comment]
Right, sorry, left out some context. The assumption is that if we move to
Realm without being able to migrate existing device data, our users will
have to log in again in order to re-sync all the user's data from the
server.

**Comment by jpsim** [comment]
That's totally up to you, but if you want, you can absolutely copy the data from your users' old Core Data stores to Realms.

**Comment by TimOliver** [comment]
@dslysenko Hi Dennis!

I've migrated one of my apps from Core Data to Realm before (And I'm also the one who wrote that blog post above). 

That being said, in my case, I was using Core Data to cache metadata information from files inside my app, so it wasn't necessary to perform any proper migrations; the data was simply regenerated the next time the user opened the app. 

Since Core Data (from what I've been told) lets you read data directly from `NSManagedObject` (Without need to subclass), it should be a relatively trivial matter of moving all of your model objects over to Realm, and then adding a small helper class to query for any data in Core Data and manually move that over when the user opens the app for the first time.

Let me know what you plan to do!

**Comment by jpsim** [comment]
Closing since we've provided some recommended approaches and haven't heard back from @dslysenko.

**Comment by dslysenko** [comment]
@jpsim: Fair! Sorry I forgot to do that myself.

@TimOliver: Thanks for the advice. I have to say we are a little overloaded with other work right now but I will reference your comment when I next consider the topic!
