### ISSUE TITLE
Xcode Crash on debugging

### ISSUE THREAD

**Issue by andr3a88** [realm/realm-cocoa#2561]
Hi, when i try do debug RLMOjbect on Xcode the loading wheel appears and after a minute Xcode crashes.

Debugger output during "loading" before xcode crash:

![realm](https://cloud.githubusercontent.com/assets/6755254/10048001/3e8fc6ac-6211-11e5-9536-24c5b7f56a01.png)

**Comment by jpsim** [comment]
Looks like you're hitting issues with our LLDB plugin. As a short term "solution", I'd recommend disabling the plugin if it's causing issues for you.

If you'd like to help us identify why it's not working in your case, more information would definitely be useful (version of Realm, Xcode, RLMObject subclass declarations, etc.). Thanks!

**Comment by andr3a88** [comment]
Realm 0.95.0
Xcode 7.0

How can I disable the plugin?

**Comment by jpsim** [comment]
Remove the `rlm_lldb.py` line from your `~/.lldbinit` file.

**Comment by andr3a88** [comment]
Other information that may be helpful:

-This problem appears when i have *RLMResults* where every results is composed by RLMObject with relationship. It seems that the script take much time to get the relationship, maybe this cause an infinitive loading and Xcode crashes.

-A RMLResults with few objects it takes less times to load, and xcode not crash.

**Comment by jpsim** [comment]
Thanks for that additional info, @andr3a88. Unfortunately the LLDB plugin hasn't seen much active development since its initial release, and we currently lack the resources to optimize its performance in cases where there are potentially a large amount of data to load in memory.

We'd certainly welcome any contributions that could improve this situation, however. If you feel up for it!

For now, I'll be closing this issue, but don't hesitate to reach out again if you have any further questions.

**Comment by jeeftor** [comment]
I had the same crash here - can you just comment out this line???

**Comment by jeeftor** [comment]
:+1:
