### ISSUE TITLE
No such module 'RealmSwift'

### ISSUE THREAD

**Issue by nootfly** [realm/realm-cocoa#2584]
cocoapod 36.2

platform :ios, '9.0'
use_frameworks!
pod 'RealmSwift'

**Comment by jpsim** [comment]
Please update CocoaPods to the latest version. Realm requires CocoaPods 0.37.1 or later.

**Comment by nootfly** [comment]
I used cocoapod 0.38.2 version. You can have a test to verify it. Thanks. Please repoen it.

**Comment by jpsim** [comment]
We maintain installation examples for all our supported installation methods and platforms in the [examples/installation](/realm/realm-cocoa/tree/master/examples/installation) directory of this repo. We run unit tests on those projects every time new code is pushed to the `master` branch of this repo, which gives us confidence that Realm continues to be installable on a continuous basis.

If you're still having issues installing Realm in your project, please share steps that we could take in order to reproduce the issues you're having. Thanks.

**Comment by nootfly** [comment]
1. Create a new project using Xcode 7
2. Create Podfile using cocoapod 0.38.2, and add " pod 'RealmSwift' " to Podfile
3. Create a simple class using "import RealmSwift"
4. This issue will occur.

I tried twice on different mac books. I run into the same issue.

**Comment by jpsim** [comment]
The steps you've shared work for me (and for our CI server that verifies this on a continuous basis).

It sounds to me like it may be an issue specific to the one device where this is failing.
