### ISSUE TITLE
Value of type 'RLMRealm' has no member 'isEmpty'

### ISSUE THREAD

**Issue by XBeg9** [realm/realm-cocoa#2587]
After latest changes in swift-2.0 branch, I can't compile.

**Comment by mrackwitz** [comment]
I guess that your build of the underlying used Realm.framework is cached. Can you clean your build folder? (⌥⇧⌘K)
Beside that: How do you integrate Realm Swift in your project? Because since the release of Xcode 7, Swift 2.0 is the default version on the `master` branch and there is no need to use the `swift-2.0` branch.

**Comment by ainopara** [comment]
I met the same issue and it is fixed by changing
```
pod 'Realm',      :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
```
to
```
pod 'RealmSwift'
```

**Comment by mrackwitz** [comment]
Thanks for letting us know. That's actually the recommended way now to integrate RealmSwift when using Swift 2.0.
