### ISSUE TITLE
NSURL-compatible Realm.Configuration APIs

### ISSUE THREAD

**Issue by Mazyod** [realm/realm-cocoa#2593]
Hello,

After updating to Swift 2.0, all my string path manipulation code didn't compile anymore, and requires the use of `NSURL` instead. (E.g. `stringByAppendingPathComponent`)

With RealmSwift mostly supporting string paths (which I originally thought was a great approach), it doesn't work so well with the new `NSURL` oriented approach Apple is pushing for.

Now, the realm Swift API is absolutely great to work with, and for me to raise an issue like this just means how a minor issue quickly stands out amidst the clean API.

Thanks,
Maz

**Comment by jpsim** [comment]
Thanks for the feature request, and the kind words!

This issue is mostly cosmetic, which matters, but the merits of moving to NSURLs rather than Strings are debatable at the very least. Both approaches make compromises.

Overall, I think I agree with you that `Realm.Configuration.path` and `Realm.path` would be better served by taking/returning NSURLs rather than Strings because getting a String out of *that* is a non-fallable operation, but the inverse (what we have now) *is* fallable.

Until we make a decision on this, you can of course add NSURL methods in your own extensions:

```swift
extension Realm {
  var pathURL: NSURL? { return NSURL(string: path) }
}
extension Realm.Configuration {
  var pathURL: NSURL? {
    set { path = newValue?.path }
    get { return NSURL(string: path)
  }
}
```

**Comment by jpsim** [comment]
Given the string path changes to Foundation that arrived with Swift 2, we should do this sooner rather than later in `Realm.Configuration`.
