### ISSUE TITLE
value of type 'RLMRealm' has no member 'isEmpty'

### ISSUE THREAD

**Issue by vishaltelangre** [realm/realm-cocoa#2609]
I just updated to latest version.

```
Installing RealmSwift 0.95.2 (was 0.95.0)
```

And now I am getting `value of type RLMRealm has no member isEmpty` error at `Realm.swift:62` in `RealmSwift` pod. Everything was working in `v0.95.0`

![screen shot 2015-09-30 at 7 21 06 pm](https://cloud.githubusercontent.com/assets/876195/10194837/765676de-67a8-11e5-8ac8-435f68f326ac.png)

I tried _Clean_ and _Clean Build Folder_, still can't compile.

This issue seems same as of #2587.

FYI, I am using Xcode Version 7.0 (7A220).

**Comment by jpsim** [comment]
Can you please share the entire contents of your `Podfile`? As you can see [here](https://github.com/realm/realm-cocoa/blob/v0.95.2/RealmSwift-swift2.0/Realm.swift), `Realm` doesn't have an `isEmpty` property in v0.95.2, that feature wasn't included in that release.

**Comment by vishaltelangre** [comment]
@jpsim Thanks for quick attention.

Here is partial contents of my `Podfile`, omitted irrelevant lines for brevity.

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!
target 'MyApp' do
    # [...] content omitted above this line
    pod 'Alamofire', '~> 2.0'
    pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
    pod 'JSONHelper', :git => 'https://github.com/isair/JSONHelper.git', :branch => 'swift-2.0'
    pod 'Kingfisher',  :git => 'https://github.com/onevcat/Kingfisher.git', :branch => 'swift-2.0'
    pod 'iCarousel', '~> 1.8.1'
    # [...] content omitted below this line
end
```

I tried altering RealmSwift entry with following, and still having same issue:
```
pod 'RealmSwift', '~> 0.95.2'
```

**Comment by jpsim** [comment]
So this line:

```ruby
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
```

should just be

```ruby
pod 'RealmSwift', '~> 0.95.2'
```

And then re-install your Pods:

```
rm -rf Pods
pod install
```

The `swift-2.0` branch is just a mirror of `master` at the moment and will be discontinued very soon. Since your `RealmSwift` pod was pointing to `master` (essentially), but your `Realm` pod was pointing to the latest official release (0.95.2), these were incompatible, giving you the error you first described.

**Comment by vishaltelangre** [comment]
Well, I actually tried the way you described it, and was having the same issue. And because I had to work on other things, I reverted my `Podfile.lock` which fallen back to earlier working `RealmSwift v0.95.0`.

But I will give it another try tomorrow. For now marking this issue as closed, as I suspect that I might be having older copy of `Realm` whereas `RealmSwift` might have updated to newer version only as you said.

Thanks

**Comment by jpsim** [comment]
If you continue to have issues, I'd encourage you to file a GitHub issue on <https://github.com/CocoaPods/CocoaPods>, since I suspect that pod updates using stale cached data is more relevant to them than us. Or perhaps filing a radar on <http://bugreport.apple.com>, if it relates to stale derived data.

**Comment by vishaltelangre** [comment]
:+1:
