### ISSUE TITLE
Update docs & website to reflect that Realm initialization can throw in Swift 2

### ISSUE THREAD

**Issue by jpsim** [realm/realm-cocoa#2613]
As pointed out by https://twitter.com/kylebshr/status/649342598511919104

**Comment by kylebshr** [comment]
Some examples would be nice too! Like, how to handle it when it fails.

**Comment by hermanolsson** [comment]
@jpsim we are right in the middle of migrating to Swift 2, and the fact that Realm() throws is really putting us on the edge, since we use that a lot to be sure that we access the correct realm on each thread.

Do you have any suggestions for handling this frequently, or do you think we should rethink our approach to handle the impact of all do/catch (or try! 🙈) ?

We haven't shipped a version with RealmSwift yet (and we will migrate to Swift 2 before we do), but we did not use the old error handling model more than at the start of the app before, so this comes as a quite big change for us.

It would be greatly appreciated if you could point us in the right direction.

**Comment by tgoyne** [comment]
Using `try!` everywhere is the equivalent of using the non-failable `Realm()` in Swift 1.2, and is actually what I'd personally consider appropriate for most scenarios -- if you've previously opened a Realm file and aren't doing anything weird, the only reason for it to fail is resource exhaustion, which you probably aren't prepared to handle gracefully.

Ideally it'd be nice to find some way to express in the type system whether or not a given call to `Realm()` can fail, but I suspect it requires some deeper changes.

**Comment by jpsim** [comment]
This was done a while back, and we now have a script that validates that all our Swift code samples on the website compile with the latest stable versions of Swift and Realm Swift.
