### ISSUE TITLE
Exclude from being updated

### ISSUE THREAD

**Issue by Fredehagelund92** [realm/realm-cocoa#2618]
I've connected class to a rest api, which add all news updates and update based on the primary key. However i've also created a favorite bool, which is only stored locally, so when it updates an object it also update the favorite bool to default. Is there a way to exclude the favorite bool from being update to default when the rest is updated?

    class Pet: Object{
        dynamic var id: Int = 1
        dynamic var title: String = ""
        dynamic var type: String = ""
        dynamic var favorite: Bool = false

        override class func primaryKey() -> String {
            return "id"
        }
    }

**Comment by jpsim** [comment]
If you want to prevent `favorite` from being overridden when using `Realm.create(_:value:update:)`, just remove the `favorite` key and the Object's existing value will remain untouched.

**Comment by Fredehagelund92** [comment]
remove the key?

this is what i'm doing. this will update the object with the id 2 and then update the favorite to default? why does it do that?

    let pet = Pet()
    pet.id = 2
    pet.name = "Dog"
    pet.type = "German Shephard"


    try! realm.write {
        realm.add(pdg, update: true)
    }

**Comment by jpsim** [comment]
What's happening here is that when you create a `Pet` instance, it's initialized with its default property values, which you then mutate (`pet.id = 2`, etc...). Guess what the default property value for `favorite` is? `false`.

So when you call `realm.add(pdg, update: true)`, all of `pdg`'s property values are copied over into the existing objects.

There's a few different ways you can avoid this.

1. Use a dictionary with `Realm.create(_:value:update:)`

```swift
try! realm.write {
    realm.create(Pet.self, ["id": 2, "name": "Dog", "type": "German Shephard"], update: true)
}
```

This is what I meant by "remove the key", I was assuming you were passing in a dictionary to Realm.create(). The `favorite` property isn't touched here because it's absent from the value passed in.

2. Fetch and mutate

Approach no. 1 loses the type safety of your object model. To regain that, you can fetch the existing object (if you know it exists for sure) and mutate just the values you want to change.

```swift
try! realm.write {
  let pet = realm.objectForPrimaryKey(Pet.self, 2)
  pet?.name = "Dog"
  pet?.type = "German Shephard"
  print(pet?.favorite) // => prints existing value of favorite for Pet with id 2.
}
```
