### ISSUE TITLE
Constructing using init(value:) should throw in Swift 2

### ISSUE THREAD

**Issue by kylebshr** [realm/realm-cocoa#2619]
When passing a dictionary of values, shouldn't the initializer throw so that we can catch it? Or perhaps make it an optional initializer? I'd like to be able to pass a dictionary, and get an object if possible but silently fail if not.

**Comment by jpsim** [comment]
At the moment, you're expected to do your own validation of values passed to `Object.init(value:)`. It's considered a programmer error to pass in a value that won't map to the model's properties.

Longer term, I would agree with you that it would be worth building in user-recoverable error throwing (ideally in an opt-in way), so I'll mark this as an enhancement and we'll keep this issue open. Thanks for the suggestion!

**Comment by kylebshr** [comment]
Thanks for looking at it. In the meantime, is there anyway at all to catch the exception `Terminating app due to uncaught exception 'RLMException', reason: 'Invalid value 'value' for property 'property''`? Then I could make my own initializer, maybe something like

    convenience init?(dict: AnyObject) {
        do {
            self.init(value: dict)
        } catch _ {
            return nil
        }
    }

**Comment by jpsim** [comment]
@kylebshr the point of that exception (and all other Objective-C runtime exceptions that Realm throws) is to indicate programmer error. As in, using Realm in a way that is not supported. So those exceptions aren't meant to be caught at runtime, but rather to make you change how you use Realm.

In this case, an exception is thrown when passing a value to `Object.init(value:)` that doesn't match the property layout of the object. The solution is to not do that. If you don't control the layout of the dictionary you're passing in to the Object initializer, you should sanitize the dictionary to make it conform to what `Object.init(value:)` expects.

**Comment by kylebshr** [comment]
I see exactly what you mean now — thank you very much for explaining why it does what it does.

**Comment by jpsim** [comment]
Happy to help!

**Comment by aurimasengagecraft** [comment]
Just my 3 cents.  init(value:)  _is_ one of the best things in Realm, when You get a  json data (with objects tree) from the server and want o cash it localy - one line of code and You're done - all objects and relations are stored. Thank You for that! 
The only caveat here is when You get the huge data structure with a hundred of objects with sophisticated relations, You cannot use the beloved init(value:) for that. Because You usually do not control the backend, so it's enough to  get one tiny  "StringsProperty" : 0  instead of "StringProperty: "0" and Your app crashes. 
And Yes, You may be right, saying it's not Realms problem, but initialising database with init(value:) You already are doing data validation while traversing through object tree. So "the only thing" You need to do is to fall back gracefully - trow an exception so we can catch it, instead of crashing the app. I know, it's  a huge task to ask for. 
But the option for everyone  to write data validation routines each time when it's already been done and do it each time before init(value:) is a waist of  resources on mobile devices and it makes on of the best Realm's features impossible to use for production. 
I've been numerous times rejected from AppStore review just because of this, so I really know the pain. And performance really suffers when executing  validation on large structures. 
Anyway, Realm is really great product and I really appreciate it very much. Thats why I know it can be enhanced so much!

**Comment by austinzheng** [comment]
Nothing further actionable on this ticket.
