### ISSUE TITLE
createOrUpdateInDefaultRealmWithValue not finding associations with primaryKey

### ISSUE THREAD

**Issue by MikeSilvis** [realm/realm-cocoa#2648]
per https://realm.io/docs/objc/latest/api/Classes/RLMObject.html#//api/name/createOrUpdateInDefaultRealmWithValue:

When using the `createOrUpdateInDefaultRealmWithValue` it is supposed to also work for nested associations: 

`If nested objects are included in the argument, createOrUpdateInDefaultRealmWithValue: will be called on them if have a primary key (createInDefaultRealmWithValue: otherwise).`

However when trying this i am still getting a crash on a duplicate primary key. 
See the following test project
https://github.com/MikeSilvis/realm-create-or-update

with https://github.com/MikeSilvis/realm-create-or-update/blob/master/Realm%20Create%20Or%20Update/ViewController.m#L45 throwing an error

**Comment by tgoyne** [comment]
Line 38 is throwing an exception because `ticket.objectID` is `nil`, not because of a duplicate primary key. If I run it multiple times then line 29 throws a duplicate primary key exception due to it using `addObject:` rather than `addOrUpdateObject:`.

**Comment by MikeSilvis** [comment]
@tgoyne sorry you are correct. I updated the project to properly showcase the error

**Comment by tgoyne** [comment]
With the updated version, `ticket2.contact = contact2` is throwing a duplicate PK exception because when you assign a standalone object to a property of an object persisted in a Realm, that object is implicitly added to the Realm using `addObject:` semantics (since it'd be dangerously error-prone to have it implicitly overwrite the values from an existing object).

**Comment by MikeSilvis** [comment]
but the documentation clearly states: `If nested objects are included in the argument, createOrUpdateInRealm:withValue: will be called on them if have a primary key (createInRealm:withValue: otherwise).`

**Comment by tgoyne** [comment]
`ticket2.contact = contact2` is what's throwing an exception, so it's never even getting to the call to `createOrUpdateInDefaultRealmWithValue:`.

**Comment by MikeSilvis** [comment]
@tgoyne Okay so do you guys recommend I do a find there to look for a contact with an ID and then set it?

**Comment by MikeSilvis** [comment]
Also is there anyway for me to know if the `RLMObject` i am dealing with is a persisted object or not?

**Comment by bmunkholm** [comment]
Just FYI: Some tool automation is closing issues in my name... Maybe waffle?

**Comment by bdash** [comment]
There are a couple of ways to do this. Which to use depends on the control you want over the behavior.

* You can look up the existing object using `-objectForPrimaryKey:`. This will return `nil` if the object does not exist. You can handle this case however you see fit (perhaps by creating a new instance with the appropriate primary key).
* You can pass a dictionary rather than an instance of `RLMObject` to `-createOrUpdateInDefaultRealmWithValue:`. This moves the setting of the properties to within  `-createOrUpdateInDefaultRealmWithValue:`, making its documented behavior applicable.

To address your later question: you can use `-[RLMObject realm]` to determine if an object is persisted or not. It will return `nil` when the object is standalone.
