### ISSUE TITLE
Call can throw, but it is not marked with'try' and error is not  handled. in swift 2.0

### ISSUE THREAD

**Issue by alexliubj** [realm/realm-cocoa#2657]
How can I fix this compile error? Thanks advanced. 
 ` func addToList(item:ChatListItem)
    {
        let realm = try! Realm()
        realm.beginWrite()
        realm.add(item)
        realm.commitWrite() //Call can throw, but it is not marked with'try' and error is not  handled.
    }
`

**Comment by alexliubj** [comment]
I don't think this is a good solution if I do like this 
        try! realm.commitWrite()

**Comment by crhuber** [comment]
+1 same issue

**Comment by kishikawakatsumi** [comment]
Using `try!` is not a bad idea, it would be the original behavior. Previously, an app was just crashed when an error occurs on a committing write transaction. Making the app crash is the only correct way because it happened a serious unrecoverable error in most cases.

However, the exceptional case, it can be recoverable by deleting the Realm file. If there is no problem even the data is lost, for example, if you are using just as a cache.

So if you'd like to recover from the write error, you can handle the error in the following manner:
If not (cannot allow losing any data), just crash is a better way in most cases.

```
do {
    try realm.commitWrite()
} catch let error {
    // Handling write error,
    // e.g. Delete the Realm file, etc.
}
```

**Comment by 14lox** [comment]
@kishikawakatsumi Can you expand upon "Delete the Realm file, etc." and how to best handle recreating the realm file and trying to commit write again. 

Also, are you also advising ```try! realm.commitWrite()``` as being the correct way to handle a commit error which can't be fixed?

**Comment by jpsim** [comment]
> Also, are you also advising `try! realm.commitWrite()` as being the correct way to handle a commit error which can't be fixed?

The only Swift error that can be thrown in this case is if the disk is out of free space, so you should probably be handling that error using `do {... try} catch {...}` unless you're sure the disk will have sufficient space for the commit.

**Comment by jpsim** [comment]
> Can you expand upon "Delete the Realm file, etc." and how to best handle recreating the realm file and trying to commit write again.

I don't recommend that you delete realm files as you're accessing them.

**Comment by 14lox** [comment]
Thanks @jpsim - it would be great to get authoritative guidelines on how best to deal with these situations.

**Comment by jpsim** [comment]
What would you like to know?

You shouldn't delete Realm files as they're being accessed, as that will cause your app to crash.

The only safe time to delete a Realm file is at app startup, before any `Realm`/`RLMRealm` instances are created. It's also possible to ensure there are no instances of `Realm`/`RLMRealm` in memory at a later point in the app's lifecycle through careful usage of autoreleasepools, but in practice that can be unfeasible.
