### ISSUE TITLE
Any idea when new documentation will be released?

### ISSUE THREAD

**Issue by BlackTablet** [realm/realm-cocoa#2660]
I'm just writing my  first project with Swift and with Realm on iOS and I'm getting there but it's hard work ...

The problem is that I'm using Swift 2 in Xcode 7 and almost all the Realm API docs, the example docs on the web and the example code supplied with Realm 0.95.3 do not work as is. Just the simple line:

let realm = Realm()

causes an error as it can now throw. Given that this was my first line of code things hadn't started well. All the code examples on other web sites linked to from the Realm web site seem to be from 2014 and both Realm and Swift have changed a fair bit in that time.

It would be really helpful to have:

1) Up-to-date General Swift-based documentation on Realm's site
2) Up-to-date Swift API documentation on Realm's site
3) Example code/project that compiles with Xcode 7 and Swift 2
4) Simple and complex example application code showing what can be done with Realm - a Dog and Person and a few bits more are handy as a starting point but left me with a whole load of questions that did not appear to be answered by the documentation when I wanted to move on.

I'm trying to build a multi class/table app and it's now writing the data as far as it goes but I feel I may miss out on a lot of Realm's features and shortcuts simply through a lack of understanding. I love the essential simplicity of Realm and it's clear that there's a lot of power under the bonnet - I just want to make sure that I know how to make the best of it.

Thanks a lot.

**Comment by istx25** [comment]
:+1: - I'm sure a lot of us would appreciate this. :smiley:

**Comment by mrackwitz** [comment]
Thanks for complaining. We all here can empathize and it's among our top priorities. We will keep trying harder to keep investing enough time into documenting and explaining our thoughts and ideas behind the API design and not only in moving forward with fixing bugs, implementing new features etc. 

It's not always easy to keep up in a fast moving environment like ours with Swift, especially with things like documentation, which are likely the most important as it's the first part of our database you come in touch with. But you have to see that some of our users are still stuck with Swift 1.2. Understandably! If you have a larger codebase, the changes required [are immense and it's not a trivial effort](https://twitter.com/andy_matuschak/status/648671170695335936).
We invested massive efforts in trying to keep up with the pace of Apple and are still supporting two Swift versions at the same time, with our [own tooling around documentation](https://github.com/realm/jazzy), we've build to make that possible for us [and others](http://blog.cocoapods.org/CocoaDocs-Colo/). We seemed to have missed the best point in time to fully go Swift 2.0 with our docs.
It's not quite true though, that we didn't take care for our website since 2014. You'd wonder if you'd see what massive changes we did to that since then. I will note though that this was seemingly still not enough. :memo: 

Gladly, I can report that we made some good progress on that. @jpsim just made sure that we automatically verify our code snippets in our documentation and discovered some typos and outdated snippets, we didn't quite caught when going through manually for every release. That's just a tiny piece in the puzzle, but one which will help us also in future to provide up-to-date code snippets. :tada:

1) That will be addressed soon - we're working on that, right now.
2) The API docs should be up-to-date as they are re-generated by CI on release. What are you missing / what is wrong specifically?
3) The examples in the repo are also built by CI to ensure that they always work with the latest release. I can also confirm that the examples especially in the here relevant [swift-2.0 directory](https://github.com/realm/realm-cocoa/tree/master/examples/ios/swift-2.0) work for me locally. Do you want to describe what kind of issues you're experiencing specifically?
4) So Simple examples are there. :relieved: I'd agree that there is a need for even more advanced examples. You're really welcome to describe for what kind of use-cases, you would expect further examples and more help from us.

**Comment by jpsim** [comment]
We've just updated our Swift docs' inline code samples to Swift 2.0 and Realm Swift 0.95.3: https://realm.io/docs/swift/latest/

I've also written some tooling to ensure that our Swift code samples compile on the latest version of Realm Swift on a continuous basis, so this should be simpler to keep up in the future.

**Comment by istx25** [comment]
We appreciate your effort! :heart: Thank you for updating the code samples.

**Comment by istx25** [comment]
:100:

**Comment by BlackTablet** [comment]
Thanks so much for a very speedy reply Marius and JP too. :-)

Thanks very much for the updates to the main docs and the API docs are now correct - or maybe they were anyway but as the content section is quite narrow on the web page the “throws” I may have lost that on the far right of the func spec.

The tooling to ensure that all examples are compiled with the latest Realm/Swift sounds great and just the sort of things that computers are very useful for …

Some of the errors in examples were to do with missing launch image screens which were standard stuff but there is an off one for me with the example code for Swift 2 where Backlink builds and runs fine, but then when I return to the source code I get 6 errors! Build and they go away, but then add a blank line to the AppDelegate.swift file and they return! Xcode complains it can’t find Object, Realm and so on yet the code imports RealmSwift. Even odder is that TableView > AppDelegate.swift doesn’t exhibit this even though both source files include RealmSwift. This almost looks like an Apple bug but I really don’t know.

I’ve had to write documentation many times myself and it is no easy matter especially when, as you say, Realm and Swift are changing frequently. I think that there is such a wealth of documentation about Core Data and SQL that that for Realm looks quite sparse and I would love more use cases with detail of one-to-one and one-to-many, when and how to best use primary keys in Realm. Examples like the Xcode examples you include but that show off some of the broader features of Realm and approach to writing apps with it. It’s the concern that I will either think Realm can’t do what I want when it can, or I wouldn’t even have considered that it might do it! I’ve used a number of databases over the years which often have unusual and original takes on data access but without documentation you’d never know - I started on Informix years back and then moved to Unify and the latter was radically different.

Finally, my issue about the website was not that the Realm website was out of date as such, just that there were a lot of links to examples code and discussion on other websites but they were mostly from 2014 and referred to RLMObjects and such like.

Anyway, my code builds now, data is written and it looks OK in the browser so all seems good for the moment.

Thanks again guys. 😊

**Comment by jpsim** [comment]
> This almost looks like an Apple bug but I really don’t know.

You got it! Please file a radar and let Apple know their Swift tools are broken. Add your voice to the choir.

> Finally, my issue about the website was not that the Realm website was out of date as such, just that there were a lot of links to examples code and discussion on other websites but they were mostly from 2014 and referred to RLMObjects and such like.

We knew it would be challenging to maintain both Objective-C and Swift variants of our cocoa API but felt that it was the best way to provide native experiences in both languages. I'm afraid that's a tradeoff that comes with the decision. We do strive to keep both APIs as close to one another as possible to make it easier for users, however.
