### ISSUE TITLE
Does Realm Support custom RLMObject initializers ?

### ISSUE THREAD

**Issue by Kimmins** [realm/realm-cocoa#2673]
i want to initialize some ignored properties when query RLMObjec, i don't know how to achieve it .

NSArray* joinedTopis = [[Topic objectsWhere:@"joined == 1"] toNSArray];
 i don't know which initializers should be override.

**Comment by kishikawakatsumi** [comment]
You can not override the initializer that is called by queries since it is private.

But the behavior you expected is possible by overriding the getter of properties. Because ignored properties just behave as normal properties. So you can override getter methods to return the default value if the property has no value. 

```
@interface Topic : RLMObject
@property NSString *title;
...
@end

@implementation Topic

- (NSString *)title {
    if (!_title) {
        _title = @"DefaultTitle";
    }
    return _title;
}

+ (NSArray *)ignoredProperties {
    return @[@"title"];
}

@end
```
