### ISSUE TITLE
Cannot compile Realm using latest Cocoapods

### ISSUE THREAD

**Issue by rexmas** [realm/realm-cocoa#2703]
using `cocoapods-0.39.0` I get the following error when I compile
![screen shot 2015-10-17 at 5 24 21 pm](https://cloud.githubusercontent.com/assets/4276518/10561885/14837e9e-74f4-11e5-9140-689151dcdc46.png)

using `cocoapods-0.38.2` works however.

**Comment by kishikawakatsumi** [comment]
@rexmas I believe the problem due to a case-sensitive file system. Do you use a case-sensitive file system? The workaround is executing `pod install` in the case-insensitive file system. Create temporary disk image with Disk Utility then mount it. Copy your project into it and execute `pod install` there.

We are working on to fix the issue: https://github.com/realm/realm-cocoa/pull/2675

**Comment by rexmas** [comment]
Yup, you got it. I don't know why so many years ago I decided that would be a good idea, but too much of a hassle to go back now.
