### ISSUE TITLE
Migration Required Due to Properties Made Optional After Update?

### ISSUE THREAD

**Issue by mamaral** [realm/realm-cocoa#2706]
I just upgraded all of my pods, the relevant one being upgrading Realm from 0.95.0 to 0.96.0, and have run into an issue I've not encountered before.

```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Migration is required for object type 'MyClass' due to the following errors:
- Property 'myPropertyName' has been made optional.
- Lots more of the same...
```

I haven't changed anything on my end after this update, but I assume I need to *do something* to make these properties either non-optional or optional? I've already implemented `defaultPropertyValues` for all of the properties.

**Comment by jpsim** [comment]
Hi @mamaral, first I encourage you to read our [0.96.0 release blog post](https://realm.io/news/realm-objc-swift-0.96.0/) if you haven't done so already, which explains much of the new behavior introduced in that version, specifically support for nullable properties.

Specifically, unless you mark the properties on your models that are of a now nullable type (NSString, NSData & NSDate) as required by implementing `+requiredProperties`, you'll need to perform a migration so Realm can copy those older non-nullable values to the new nullable format.

**Comment by mamaral** [comment]
Excellent, good to know! Thank you!

**Comment by jpsim** [comment]
No problem!

**Comment by mamaral** [comment]
Upping my schema version and letting the migration do it's thing fixed this for me, thanks again.

**Comment by samiq** [comment]
Hi guys, I wished next time a change as impactful as this is introduced, you guys implement a transition in way that doesn't break any previous functionality, if we all have been doing things in a way, and now you guys provide a change this big, at least provide a smarter transition on wether everything is marked optional or not, if default values are present then it means everything could be made required until otherwise defined in the code. I understand that development is on going, but at lot of our automated build processes update pods as part of build processes and features like this where we don't expect a crash to happen, happens.

**Comment by highwinddq** [comment]
Hi guys, sorry for reopening this thread but I'm facing the errors mentionned in the original question at the moment and though I understand the thread and have read the blog post, I am not sure what the best way to fix the problem is.

Do I have to perform a migration on all the properties one by one if no property has actually changed ? Or would an empty migration block be enough ?

**Comment by jpsim** [comment]
@highwinddq an empty migration block is sufficient to migrate required properties to optional.
