### ISSUE TITLE
APPLICATION_EXTENSION_API_ONLY in Realm 0.96

### ISSUE THREAD

**Issue by justadreamer** [realm/realm-cocoa#2719]
I've recently updated via cocoapods to Realm 0.96.1 - and discovered that my target now has: APPLICATION_EXTENSION_API_ONLY = YES due to Realm podspec.    I am not developing an app extension and using the APIs in question - therefore my target now does not build.  I can change the setting manually, but why should I do this every time I do 'pod update'?   Can you remove this from the realm podspec please?

**Comment by mrackwitz** [comment]
This build setting was added, because it wasn't building in some scenarios, because CocoaPods didn't covered those all. See CocoaPods/CocoaPods#4321.
The build setting doesn't harm as long as it is only added to framework target and not the user target.
Due to a bug in CocoaPods 0.38.2, which we fixed in 0.39, this wasn't the case when integrating with static libraries, what is causing here trouble for you.
So please update your CocoaPods version.
