### ISSUE TITLE
'default' could not be opened. It may be encrypted, or it isn't in a compatible file format.

### ISSUE THREAD

**Issue by RodrigezJson** [realm/realm-cocoa#2735]
Error showing during open default.realm using realm browser.
please help me to figure out.
thanks

**Comment by kishikawakatsumi** [comment]
If you are using Realm Browser 0.95.2 (AppStore's latest), that version of Browser cannot read the Realm file created by Realm 0.96.x. Because the new file format was introduced from 0.96, Realm Browser has not supported the format yet. 

If so, you can use pre-release version of Realm Browser downloaded from https://github.com/realm/realm-browser-osx/releases/tag/0.96-prerelease

**Comment by RodrigezJson** [comment]
ok thank you very much. problem solved

**Comment by kishikawakatsumi** [comment]
Glad we could help!
