### ISSUE TITLE
*** Terminating app due to uncaught exception 'RLMException', reason: 'Migration is required for object type

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#2744]
realm version: the latest version,0.96.1

Simulator: Normal
Iphone6 Plus,IOS9.1: Crash

![1](https://cloud.githubusercontent.com/assets/3182964/10714020/409a3568-7b11-11e5-9dc1-f6530f686b5c.jpg)

**Comment by kishikawakatsumi** [comment]
@hengchengfei Because 0.96 has breaking changes. With this release, fields of the types String, Date, and NSData are now nullable by default. It needs a migration step or marked these properties to nonnull in `+requiredProperties`. You can specify that a field cannot be null by overriding `+requiredProperties` class method.

see also:
https://realm.io/news/realm-objc-swift-0.96.0/

**Comment by hengchengfei** [comment]
I really appreciate

**Comment by kishikawakatsumi** [comment]
My pleasure :smile:
