### ISSUE TITLE
Object saved in one thread can’t be read on the main thread

### ISSUE THREAD

**Issue by meap** [realm/realm-cocoa#2764]
In one thread I create the object in the standard way `[YMMBox createInRealm:realm withValue:mapping];` after finishing the transaction I’m trying to load it again in the main thread using the primary key. Unfortunately the success rate is about 50%, once it finds it, once it doesn’t.

```objc
      RLMRealm *realm = [RLMRealm defaultRealm];
      [realm beginWriteTransaction];
      
      [YMMBox newBoxWithId:box.boxId
                    userId:box.userId
                     appId:box.applicationId
                categoryId:box.categoryId
       secondaryCategoryId:box.secondaryCategoryId
           coverIdentifier:box.coverIdentifier
           templateVersion:box.templateVersion
              visibleSince:box.visibleSince
              visibleUntil:box.visibleUntil
                attributes:box.attributes
                     realm:realm];
      
      [realm commitWriteTransaction];

      dispatch_async(dispatch_get_main_queue(), ^{
        YMMBox *createdBox = [YMMBox objectInRealm:[RLMRealm defaultRealm]
                                     forPrimaryKey:box.boxId];

        self.box = createdBox;
        [self initializeContentView];
      });
```

What am I doing wrong? Thanks!

>Realm version 0.96.2

**Comment by tgoyne** [comment]
To avoid having data change beneath your feet in the middle of a function, we only update which version of the data an RLMRealm uses between each iteration of the runloop. Unfortunately, because GCD blocks are the highest-priority events, `dispatch_async(dispatch_get_main_queue(), ^{ ... }) immediately after a commit can result in the block being run on the main thread before our autorefresh signal, resulting in the block seeing the version of the Realm from before the commit.

You can work around this by explicitly calling `[realm refresh]` at the beginning of your block that needs to see the latest data. The more proper way would be to instead do the work in a Realm notification block rather than a dispatched block, but with the current limited notifications that'd be difficult to do.

**Comment by IsHass** [comment]
Exactelly the same happening to me using RealmSwift.  It was working fine for months untill today ( I updated to Xcode 7.1).

**Comment by jpsim** [comment]
As @tgoyne mentioned, to force a Realm to refresh before it receives the autorefresh signal, call `-[RLMRealm refresh]`. See our docs on [Seeing Changes From Other Threads](https://realm.io/docs/objc/latest/#seeing-changes-from-other-threads) for more information.
