### ISSUE TITLE
Sometimes a objectsWhere query returns empty RLMResults even when the DB is showing 300 objects respecting that query

### ISSUE THREAD

**Issue by crsantos** [realm/realm-cocoa#2795]
I have 2 RLMObjects on my DB, ``Contact`` and ``MSISDN``. 
``Contact`` has a list of ``MSISDN`` called ``listOfMSISDN``

I cannot reproduce this every time, but for some reason, when querying Realm (on main thread), with this query:

    [MSISDN objectsWhere:@"%K == YES", NSStringFromSelector(@selector(valid))];
    // (where valid is just a BOOL field that is set on object creation)

As you can see, the is a screenshot from my DB using _Realm Browser_ , showing the list of MSISDNs on my DB (300) on that exact moment that this issue arose.
![screenshot 2015-11-04 10 01 38](https://cloud.githubusercontent.com/assets/25558/10935441/25b2b71e-82de-11e5-8083-3e609e2dbfbe.png)

Using the debugger with a  breakpoint, open the exact moment that this happened, a query to ``[MSISDN allObjects]`` still returns ``0`` objects, and a query to ``[Contact allObjects]`` shows each contact (of 267 available) with its list of MSISDNs empty..

    (lldb) po [[Contact allObjects] lastObject]
    Contact {
        contactId = 3280;
        name = Caaaa;
        listOfMSISDN = RLMArray <0x15f8e77a0> (
    
        );
    }
I checked and all of the ``contactID`` of ``MSISDN`` matches the ``contactID`` of all ``Contact``.

This object is an MSISDN usually inserted in a RLMArray inside a Contact object (keeping a ref to its parent via contactID).

This is happening to me in a daily basis and I still don't know if I'm creating some kind of "DB lock" on Realm of if this is a real bug on Realm.

Any ideas?

**Comment by TimOliver** [comment]
Hi @crsantos!

Sorry to hear that this is happening! Hmm, I'm not too sure if I can diagnose what's going on here off just this information. Are you sure you can't see any pattern to when this error appears, such as straight after a write transaction, or any activity on a background thread?

A couple things I might recommend to test out.
* Just to be sure, try calling `refresh` on the default Realm before you make that query.
* Unless there's a reason for that, try and simplify the query as well (You should be able to make it simply `valid == YES`)

If all else fails, would you be willing to send us that app so we can analyse what's going on ourselves?

Thanks a lot!

**Comment by crsantos** [comment]
Thanks for the quick response!

> Just to be sure, try calling refresh on the default Realm before you make that query.

I've set a breakpoint on a debug IF for when that case happens again and will try to catch it, but made sure that inside that debug IF I call ``[[RLMRealm defaultRealm] refresh]`` and repeat the query again, just to test.

> Unless there's a reason for that, try and simplify the query as well (You should be able to make it simply valid == YES)

That's the way I'm used to define selectors as keys (``%K``), to avoid missing that one when refactoring. Been using this technique on all predicates. Any reason I shouldn't? Any advices?

One thing that I suspect that might cause that is a bulk delete of old MSISDNs that I have when importing new objects (due to Realm doesn't supporting delete cascade - so I have to delete the old MSISDNs before adding the new ones).

But I'm pretty sure that the persistence of new MSISDNs is synchronous in my code, and I'm waiting till it ends before I call the validMSISDN troubling query.

**Note** That query is being called on main thread.

**Comment by crsantos** [comment]
Made a refactor on my code, and right now, never replicated that issue again.
I guess that I was doing that bulk delete of old MSISDNs and after that inserting the new ones.
I think my main issue was not waiting for a completionBlock when creating the new ones.
So I think we can close this issue for now, as this was a mis-use of Realm. If I ever replicate this again we can reopen it.

Thanks for everything and apologies.

**Comment by crsantos** [comment]
I'm going to re-open this one as I've successfully reproduced it with a 100% success rate on this conditions:

* I'm using [RBQFetchedResultsController](https://github.com/Roobiq/RBQFetchedResultsController) on a `UICollectionView`
* Scheduled a query for retrieving all my objects (on Main Thread)
* On the exact moment before the query is triggered, I start scrolling my `UICollectionView` (it spawns fetch requests to realm on the same (Main) thread I suppose)
* The scheduled query was hang on a breakpoint with zero results.

**Quick fix**: performing the query on background fixed it. Is this supposed to happen?

@bigfish24, a little help here, have you ever replicated a scenario like this?

**Comment by TiagoVeloso** [comment]
I am experiencing something similar to @crsantos.

I am implementing a chat view backed by an `UICollectionView`. I am having a crash whenever users send a message and scroll on the collectionview. I am also using @bigfish24's FRC.

The crash is due to the FRC not returning objects, and is instead returning nil. But I am positive that it can't return nil for those index paths.

**Comment by bigfish24** [comment]
@crsantos and @TiagoVeloso any chance you can share your source code privately to help figure out the issue?

**Comment by crsantos** [comment]
I guess the simplest way is to setup a clean project with an example of our stack and show you.
In the process, we can even figure out that is a bad usage or config from our side. 
I'll reach you again when it's done. 
Thanks

**Comment by bigfish24** [comment]
@crsantos I had a bit more time to think about this, but don't really have any good ideas. I wanted though to clarify your comment:

> Scheduled a query for retrieving all my objects (on Main Thread)

What do you mean by this? When you perform a query with Realm, the results object will not have evaluated the query until you request an object at an index in the result collection or the count of the collection. Is that what you mean, in that you create the result object, but you haven't yet acted on the object? If not, I am confused because Realm doesn't yet offer async queries.

> On the exact moment before the query is triggered, I start (quickly) scrolling my UICollectionView (it spawns fetch requests to realm on the same (Main) thread I suppose)

Second, when you scroll a `UICollectionView` that is backed by RBQFRC, it should not spawn any fetch requests, instead the RBQFRC will simply retrieve the objects for the various indexPaths needed to retrieve the data for the cells displayed.

RBQFRC only updates when you manually call `performFetch` or if you post a notification using the manual or helper notification methods on `RBQRealmNotificationManager`. Also, whatever `RBQFetchRequest` you initialized RBQFRC with doesn't change until you call `updateFetchRequest:`.

So my best guess based on this confusion is that you might be using RBQFRC incorrectly, but honestly that's just a shot in the dark until I can see more of the code...

**Comment by bigfish24** [comment]
@crsantos and @TiagoVeloso I would suggest you look at the implementation for [ABFRealmGridController](https://github.com/bigfish24/ABFRealmGridController) because this is a `UICollectionViewController` subclass that is using RBQFRC as its backing data source. It automatically updates based on results from the New York Times API and animates the changes... I have never encountered the scenario you describe.

**Comment by crsantos** [comment]
@bigfish24 I've managed to replicate the issue on [ABFRealmGridController](https://github.com/bigfish24/ABFRealmGridController) project example.
Just after clicking the **Reload** button, I started scrolling (vigorously) the collectionView and with a breakpoint on your `- (id)objectAtIndexPath:(NSIndexPath *)indexPath` to know when the object is `nil`.

Please, check the screenshot
![screenshot 2015-12-10 17 36 59](https://cloud.githubusercontent.com/assets/25558/11723229/2937da2e-9f65-11e5-83ba-603d3b6f8772.png)

I don't know if this is a Realm main thread query problem, that's why I kept the thread on this repo

**Comment by bigfish24** [comment]
@crsantos thanks for digging into this! I will attempt to reproduce and see if I can figure out what is going on.

**Comment by bigfish24** [comment]
The issue was related to how Realm notifies other Realm instances to update. When you commit a write transaction on a background thread, a notification is then sent to other Realm instances on other threads (this works through a [named pipe](https://realm.io/news/thomas-goyne-fast-inter-process-communication/)) to refresh to the latest version of the DB that includes the recently committed transaction. The problem though is that notification is processed on the receiving thread only during the [default run loop mode](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/Multithreading/RunLoopManagement/RunLoopManagement.html#//apple_ref/doc/uid/10000057i-CH16-SW12). When you are scrolling, the main thread will run in `NSEventTrackingRunLoopMode` for that pass of the run loop. This means that Realm's notification will not be processed until the thread is back in default mode.

The result of this means that `RBQFetchedResultsController` should simply manually call `refresh` on the Realm that contains the objects backed by the FRC before attempting to retrieve it. This alleviates the assumption that the notification to trigger the refresh has been processed before `object/safeObjectAtIndexPath:` is called.

I can confirm this commit fixes the problem: https://github.com/Roobiq/RBQFetchedResultsController/commit/03de5b623e4451dede175c356826a2960d966664

**Comment by crsantos** [comment]
First of all Adam: thank you so much  for fixing this in such a quick timeframe.

Thumbs up to your wonderful and detailed explanation of the issue. 
Now I can totally understand that the "myth" that UI animations rules (NSEventTrackingRunLoopMode) over other resources is true. 

And thanks again for pointing that excelent reading about IPC on @realm. Excelent piece of engineering!

I hope this fix will also help many more users as it helps us.

Cheers,

Carlos

**Comment by bigfish24** [comment]
@crsantos happy I could help! Definitely enjoy working along side @tgoyne and others on the team that deserve the credit for teaching me about IPC and other topics.
