### ISSUE TITLE
"property must be marked as being optional" in unit test

### ISSUE THREAD

**Issue by owenzhao** [realm/realm-cocoa#2814]
My code is 

````swift
class CFRealmBaseURL: Object {
    dynamic var path = ""
    
    override class func primaryKey() -> String? {
        return "path"
    }
}

class CFRealmCard: Object {
    dynamic var baseURL = CFRealmBaseURL()
    dynamic var projectType = ""
    dynamic var company = ""
    dynamic var projectNumber = ""
    dynamic var projectProcess = ""
    var relativeURL:NSURL {
        get {
            let path = [self.projectProcess, self.company, self.projectNumber, self.projectProcess].joinWithSeparator("/")
            return NSURL(fileURLWithPath: path, isDirectory: true, relativeToURL: NSURL(fileURLWithPath: self.baseURL.path, isDirectory: true))
        }
        
        set(newURL) {
            let paths = newURL.pathComponents!
            
            if let baseURLCount = newURL.baseURL?.pathComponents?.count {
                self.baseURL.path = newURL.baseURL!.absoluteString
                self.projectType = paths[baseURLCount]
                self.company = paths[baseURLCount + 1]
                self.projectNumber = paths[baseURLCount + 2]
                self.projectProcess = paths[Range(start: baseURLCount + 3, end: paths.endIndex)].joinWithSeparator("/")
            }
        }
    }
    
    dynamic var projectStatus = CFRealmProjectStatus()
    dynamic var projectSummary = ""
    let contactPersonList = List<CFRealmProjectContactPerson>()
    
    dynamic var createdDate = NSDate(timeIntervalSince1970: 0)
    
    func setCard(baseURLs:[NSURL], url:NSURL) {
        let fullPath = url.absoluteString
        for aBaseURL in baseURLs { //baseURLs is order by levels from deep to low
            let aBasePath = aBaseURL.absoluteString
            if fullPath.hasPrefix(aBasePath) {
                var path = fullPath
                path.removeRange(Range(start: aBasePath.startIndex, end: aBasePath.endIndex))
                self.relativeURL = NSURL(fileURLWithPath: path, isDirectory: true, relativeToURL: aBaseURL)
            }
        }
    }
    
    override class func ignoredProperties() -> [String] {
        return ["relativeURL"]
    }
}
````

The failed alert is : 

> failed: caught "RLMException", "The `CFRealmCard.baseURL` property must be marked as being optional."

However, I don't see the need to mark it as optional. Any idea?

**Comment by jpsim** [comment]
To-one relationships (links) in Realm cannot enforce that a link is *always* present. So they always have to be marked as optional because there's no way to prevent `nil` from being stored for a link in the file format.

Therefore, we require that Realm models defined in Swift explicitly mark to-one relationships as Optional.

You'll have to do this for both `baseURL` and `projectStatus` properties:

```swift
class CFRealmCard: Object {
    dynamic var baseURL: CFRealmBaseURL? = nil
    dynamic var projectStatus: CFRealmProjectStatus? = nil
}
```

**Comment by kharmabum** [comment]
@jpsim the to-one relation example in the latest swift docs states `// Can be optional`, which is quite confusing. It would be worth updating the docs to express that optionals are required (and implicitly unwrapped optionals are not tolerated).

**Comment by i-schuetz** [comment]
This is a bit inconvenient, it was was better in previous versions with the default value...

Now I will probably use "getters" like this, which should be the equivalent for the previous default values:
```swift
    dynamic var myField_: MyField? = nil
    var myField: MyField {
        myField_ ?? MyField()
    }
```
Would that be the recommended approach?

**Comment by kharmabum** [comment]
@i-schuetz did you add `myField` as an ignored property?

**Comment by i-schuetz** [comment]
@kharmabum oh right, adding it as an ignored property would solve the first problem, thanks. About the implicitly unwrapped optional I just tend to avoid them, it shouldn't make a difference concerning the last issue...

**Comment by jpsim** [comment]
@kharmabum you're right that the "can be optional" comment was unclear because it was next to a to-one relationship. We've since changed that to say "Properties can be optional". In the ["Model->Relationships"](https://realm.io/docs/swift/latest/#to-one-relationships) section of the docs, we now stated that "to-one relationships must be optional", so hopefully this makes it clear to users what does and does not have flexible optionality.

> This is a bit inconvenient, it was was better in previous versions with the default value...

I'm sorry for the inconvenience, although that situation was inconvenient for others who did want that relationship to be optional.

If you're certain that you'll always have a value for that relationship, you can represent it as an implicitly unwrapped optional, as @kharmabum suggested. Although if you ever use a Realm file that matches your model but was created in a different environment, this could crash if there's a `nil` relationship.

---

I'm closing this issue now because I think we've sufficiently covered this particular topic here, but if you'd like to continue the conversation, feel free to reopen.

**Comment by mohammdsss1** [comment]
I am having the issue of "property must be marked as being optional", my class has a property:
`@objc dynamic var sale: Sale!`

where `sale` is another Object type that should not be nil, how I can achieve that without putting it as optional?, as doing it as optional will require a major update in each area using that property. 

Also be noted that it was working fine before that latest update of Xcode 10!
