### ISSUE TITLE
Is there a way to compress encrypted realm file?

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#2835]
hi, i am using "realm.writeCopyToPath(  path, encryptionKey: getKey())" to create a encryption file, but if i zip it, the size didnot become smaller: 94.9M-->94.2M;  the realm without encryption can zip to:  94.9M-->30M. is there a way i can resize the encryption file? thanks.

**Comment by mrackwitz** [comment]
Your only option is to compress before encrypting.
Encryption turns your data into high-entropy data, usually indistinguishable from a random stream. Compression relies on patterns in order to gain any size reduction. Since encryption destroys such patterns, the compression algorithm is unable to give you much reduction in size if you apply it to encrypted data.

**Comment by github2016a** [comment]
thanks，@mrackwitz。
I,have already compressed the file before encrypting. i think the only way is,to encrypt on the app's first run, fetching realm file without encryption from a zip with password. when finish,delete the zip file and the temp realm file. but there is still some risk before deleting the temp realm file. the data is not safe until the encryption finished.
is there some tip to solve this issue? thanks

**Comment by mrackwitz** [comment]
What's your whole use case for that? What do you want to achieve?

**Comment by github2016a** [comment]
i want to release an app with some initialized data in realm, the data is about 100M, with realm in zip it is 30M, with  encryption  realm it is more than 90M, too big.
I want to keep realm file on iphone encrypted, so i have to pack an realm unencrypted, and encrypt it when user run the app(use "writeCopyToPath",to create a new realm), and i have to keep the data safe In the process( encryption will take 2 minute)。
so in this 2 minute, i haven't found a way to keep data safe.

**Comment by github2016a** [comment]
and I thought about pack the app with json data, but the migration to realm will take much more time.

**Comment by mrackwitz** [comment]
As you would bundle static encrypted(?) data into your app, the two minutes, where the data is accessible in plain text on disk seem negotiable from my perspective, as the weakest link in the chain is that you need access to the symmetric encryption key locally which is _inherently unsafe_. So a potential attacker could instead of trying to get access to the plain data on disk at a specific moment in time, extract the key - which you can harden by obfuscation, but not prevent - and use it to decrypt the bundled zip. Both scenarios are subject to matter only on jailbroken devices, where FairPlay won't protect you.
