### ISSUE TITLE
Infinite loop crash on moving from Realm 0.96.1 to 0.96.2

### ISSUE THREAD

**Issue by alexanderjarvis** [realm/realm-cocoa#2851]
Version 0.96.2 RealmSwift

Affecting only 3 users, suspected upgrading from previous version but no model migrations in this version change. Previous app version used Realm version 0.96.1

```
Thread : Crashed: com.apple.main-thread
0   Realm                          4324865704 realm::StringIndex::leaf_insert(unsigned long, int, unsigned long, realm::StringData, bool) + 40
1   Realm                          4324862168 realm::StringIndex::do_insert(unsigned long, int, unsigned long, realm::StringData) + 436
2   Realm                          4324860604 realm::StringIndex::TreeInsert(unsigned long, int, unsigned long, realm::StringData) + 32
...
```

See full crash report here:
http://crashes.to/s/5ca1f6ca098

**Comment by bdash** [comment]
@alexanderjarvis, I'm sorry you're hitting this. I've filed an issue to have our core engine team look at this crash. We'd appreciate any further information you're able to provide to help us investigate. Particularly useful would be a copy of the Realm file from any user that's seeing this crash.

**Comment by TimOliver** [comment]
Hi @alexanderjarvis! 

I'm just going through and doing an appraisal of some of the older outstanding issues here to see if we can help resolve them before our next set of releases.

Have you seen this issue happen anymore since you reported it? If it has, we would absolutely love it if you could capture the Realm file from one of the affected users.

Thanks a lot!

**Comment by alexanderjarvis** [comment]
Hi @TimOliver I've not seen this for a while so guess it was fixed.
