### ISSUE TITLE
 is the getKey() will always return the same keyData if the "keychainIdentifier" is the same?

### ISSUE THREAD

**Issue by github2016a** [realm/realm-cocoa#2861]
hi,guys,i want to know is the getKey will always return the same keyData if the "keychainIdentifier" keep the same? this will be different by device right? if on the same iphone, will this change if user update ios version ?
getKey()  from the sample project :
func getKey() -> NSData {
    let keychainIdentifier = "1111111111"
    let keychainIdentifierData = keychainIdentifier.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!
...............................

**Comment by github2016a** [comment]
or on what condition ,if keychainIdentifier keep same, getKey() will return different value?

**Comment by bdash** [comment]
`keychainIdentifier` is a unique identifier for an item within the user's keychain. `getKey` works by looking for an item with that identifier in the keychain. If one exists, it returns the item's data. If it doesn't exist, it generates a random key, stores it in the keychain with that identifier, and returns the generated data. 

Items in the keychain will not be removed by updating to a newer version of iOS. They may appear to have been removed if the user backs up their device to iCloud, then restores from the iCloud backup. The same is true of a user backing up to iTunes but opting not to encrypt their backup with a password. This is because iCloud Backup, and unencrypted iTunes backups, does not include keychain items, but does include application data such as Realms.

For more information about keychains on iOS, please see Apple's documentation on [Keychain Services Concepts](https://developer.apple.com/library/mac/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html) and [iOS Keychain Services Tasks](https://developer.apple.com/library/mac/documentation/Security/Conceptual/keychainServConcepts/iPhoneTasks/iPhoneTasks.html).

**Comment by kishikawakatsumi** [comment]
@github2016a Closing due to no response and question seems to be answered. Please reopen if there is any new information.
