### ISSUE TITLE
Bug - Relationship object wiped

### ISSUE THREAD

**Issue by modLX4** [realm/realm-cocoa#2880]
Relationship object are wiped when createOrUpdate called from top level object, even if relationship has primary key set

Similar issue : https://github.com/realm/realm-cocoa/issues/1401

Here is a sample project which reproduce the  bug
https://dl.dropboxusercontent.com/u/64096245/241523154jkjdqwfqwe/RealmTest%202.zip

**Comment by modLX4** [comment]
<img width="595" alt="screen shot 2015-11-19 at 2 21 19 pm" src="https://cloud.githubusercontent.com/assets/12533332/11272694/d532158c-8ef4-11e5-825a-70b93b02027b.png">

**Comment by modLX4** [comment]
Is someone from Realm working on this ???

**Comment by bdash** [comment]
The code in question is as follows:

```objc
[[RLMRealm defaultRealm]beginWriteTransaction];
[Book createOrUpdateInDefaultRealmWithValue:@{
                                              @"bookID" : @K_DEF_PRIMARY_ID,
                                              @"bookTitle" : @"Updated Book Title",
                                              @"bookDescription" : @"This is an updated value",
                                              @"authors" :@[@{ @"authorID" : @50,
                                                              @"authorName" : @"Updated AuthorName",
                                                              @"aboutAuthor" : @"Updated About About" }]
                                              
                                              
                                              }];

[[RLMRealm defaultRealm]commitWriteTransaction];
```
If I understand correctly, your issue is that after this call the `authors` property of the `Book` object has only a single `Author` in it. This is expected: the `authors` key in the dictionary you've passed has only a single object in it, so we update the `authors` property to contain only the single object that you requested.

If your intention is to update the properties of the `Author` with `authorID` equal to 50 and not modify which objects are present in the `Book`'s `authors` array, you can do so by passing the inner dictionary to `+[Author createOrUpdateInDefaultRealmWithValue:]`.

**Comment by jpsim** [comment]
@bdash's answer appears correct to me, so I'm closing this issue. @modLX4 please reopen if you need some clarifications or if you have any further questions.
