### ISSUE TITLE
Preloaded realm file (xcode 7 - swift 2.0)

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [realm/realm-cocoa#2896]
Hi All,

Any help regarding the preloaded realm file using the latest version of xcode and swift, I have to include a preloaded realm file in my project.

Any suggestion or sample link?

Thanks.

**Comment by kishikawakatsumi** [comment]
@rjjohnpatrickcruz There are some explanations for preloaded realm file in our documentation: [Other Realms](https://realm.io/docs/swift/latest/#other-realms) and [Bundling a Realm with an App](https://realm.io/docs/swift/latest/#bundling-a-realm-with-an-app) I hope these help.

It's quite easy to bundle preloaded Realm files in your app. 

1. Create data using iOS simulator or Mac app.
2. Copy data files to your app bundle.
3. Read data from files in app bundle **Note:** Realm should be read only, because app bundle does not allow writing.

```swift
let config = Realm.Configuration(
    // Get the path to the bundled file
    path: NSBundle.mainBundle().pathForResource("MyBundledData", ofType:"realm"),
    // Open the file in read-only mode as application bundles are not writeable
    readOnly: true)

// Open the Realm with the configuration
let realm = try! Realm(configuration: config)

// Read some data from the bundled Realm
let results = realm.objects(Dog).filter("age > 5")
```

**Comment by rjjohnpatrickcruz** [comment]
Thanks! @kishikawakatsumi I try this.

**Comment by rjjohnpatrickcruz** [comment]
its working @kishikawakatsumi! Thanks. cheers!

**Comment by kishikawakatsumi** [comment]
@rjjohnpatrickcruz My pleasure!

**Comment by Isuru-Nanayakkara** [comment]
@kishikawakatsumi Thanks for the example. By the way, the Realm docs needs updating. `Realm.Configuration` doesn't seem to have that particular initializer anymore.

**Comment by jpsim** [comment]
Which docs? We use `fileURL` in all our docs as far as I know.
