### ISSUE TITLE
what's the type of Encryption? AES or others?

### ISSUE THREAD

**Issue by liuxuan30** [realm/realm-cocoa#2916]
what's the type of Encryption? AES or others? I searched the code, but don't see where it is declared.

**Comment by bdash** [comment]
The [Encryption section of the documentation](https://realm.io/docs/objc/latest/#encryption) states:
> Realm supports encrypting the database file on disk with AES-256+SHA2 by supplying a 64-byte encryption key when creating a Realm.

**Comment by liuxuan30** [comment]
Thanks, one more question: if I use Realm encryption, as you may know, submitting apps to AppStore will ask you if the app includes encryption, shall I say YES to this option?
I am not in USA and never had encryption feature in my app. Thanks!

**Comment by bdash** [comment]
You do need to say "yes" to that question. The [iTunes Connect documentation on Trade Compliance](https://itunespartner.apple.com/en/apps/faq/Managing%20Your%20Apps_Trade%20Compliance#24867840) is the authoritative source for information on this topic.

**Comment by liuxuan30** [comment]
OK, thanks so much!

**Comment by slackernrrd** [comment]
Sorry if this is a stupid question, but after reading the linked iTunes Connect documentation, my conclusion is that you need to say "yes" to the App Store question about encryption even if you *don't* use encrypted realms, since Realm provides it's own encryption code. Is this correct? I am basing this on the following from the iTunes Connect Documentation: 

> If your application does use, access, implement or incorporate encryption, it may be necessary to submit confirmation of approval [...]

My app doesn't "use" or "access" encryption, but I guess by including Realm it "implements" or at least "incorporates" it?

So if my conclusion is correct, is there a way to not include the encryption code in my build? Seems like a lot of work to get the necessary approvals for apps that don't use the encryption functionality.

**Comment by tgoyne** [comment]
On iOS we use CommonCrypto and don't actually have any export-controlled crypto code in the core library itself, so it's basically the same scenario as if you had an app which used NSURLSession for HTTP only.

**Comment by slackernrrd** [comment]
Oh, OK. After trying to read up I was under the impression that Realm had it's own implementation, but I'm happy I was wrong :)

Thanks for the help, @tgoyne!

**Comment by bubbltrubl** [comment]
Hi,

I am using Realm with encryption enabled.
Can I answer the following Export Compliance question with **No**?

**Does your app implement any standard encryption algorithms instead of, or in addition to, using or accessing the encryption in Apple’s iOS or macOS?**
