### ISSUE TITLE
RealmMapView requires a mechanism to filter results

### ISSUE THREAD

**Issue by xcodewarrier** [realm/realm-cocoa#2921]
RealmMapView would be even more awesome if it was possible to provide a predicate to filter the results.

E.g. I might only want to show those pins on a map for a specified object.type

**Comment by aperechnev** [comment]
Isn't it?

```
RLMResults *r = [Dog objectsWhere:@"age > 8"];
r = [r objectsWhere:@"name contains 'rex'"];
```

**Comment by xcodewarrier** [comment]
That works for Realm, but the request is for RealmMapView as [described in this tutorial](https://realm.io/news/building-an-ios-clustered-map-view-in-swift/). 

Currently there is no mechanism to filter the query that is used to populate the map.

**Comment by bigfish24** [comment]
@xcodewarrier thanks for bringing this up, and it definitely should have this feature. I just added it via a property on `ABFRealmMapView`/`RealmMapView` called `basePredicate`. If you set an `NSPredicate` for the property in which it filters the objects the map is searching on, it will combine the predicate with generated bounding box location predicate, so that the map only displays results that match your filter in the map area.
