### ISSUE TITLE
Feature? iCloud backup/sync of active Realm db file?

### ISSUE THREAD

**Issue by kristofer** [realm/realm-cocoa#2932]
Is there already an Add On or somethng that allows me to tell Realm that should be backed up stored in iCloud? I'd like to be able to get the latest Realm db from someplace when I switch devices and am using my app.  I keep all the app's data in CloudKit, and havea realm db as an index to it all. 

I'd like a way to make sure I'm always using the latest realm index, not matter which device most recently changed the index.

anyone got any suggestions? is this a Feature coming soon? :-)

**Comment by jpsim** [comment]
To back up Realm files via iCloud should be as simple as keeping the Realm file in the documents directory of your app which is where the default Realm's path, `RLMRealmConfiguration.path`, is set by default. This will be included in your users' iCloud backups of their phones. So if they restore their backup on a different device, they'll preserve those Realm files.

To *synchronize* Realms across devices via iCloud, I recommend you store the Realm file as an iCloud document. However because iCloud doesn't know about Realm's binary format, it will sync the entire file every time a change is made, no matter how small. We're aware that this experience can be improved and are tracking that in #913.

**Comment by Tom29** [comment]
@jpsim I'm storing data in the app group. because i want both app and extension can access to the data. Will it be sync? If i move the realm file to the iCloud document, does it good and safe as storing in the app group?

**Comment by tariq235** [comment]
@jpsim  Any update on icloud sync ? You have linked this ticket to #913 1.5year ago. I'm excited to know if you guys have made any progress.

**Comment by jpsim** [comment]
With the [Realm Mobile Platform](https://realm.io/products/realm-mobile-platform/), you can now synchronize your Realms across devices seamlessly & efficiently.

iCloud/CloudKit do not provide the granularity needed to do so.

**Comment by wojciech-kulik** [comment]
@jpsim As far as I understand, it is a bit different solution than the requested one. iCloud sync is often used to ensure the privacy of vulnerable data without the need of authentication with 3rd party services nor sending private data to 3rd servers.

Realm Mobile Platform seems to be a different solution where the user must first authenticate to have its own space and all the data are stored in a database where the owner has access, am I right?

Regarding iCloud sync, let's assume I store Realm db file in iCloud Documents and my app is tracking changes. How can I ensure the update of displayed data? I performed some tests by just replacing the file and Realm does not detect updates. Additionally, after replacing the file and changes in db are not preserved.
