### ISSUE TITLE
What error is this?

### ISSUE THREAD

**Issue by betaSavvy** [realm/realm-cocoa#2986]
Hi,

Using RealmSwift -> 0.96
I have this funny error althou I can still compile fine but does this error affects anything?

![screen shot 2015-12-11 at 7 15 40 pm](https://cloud.githubusercontent.com/assets/9004457/11742627/4adad7f8-a03c-11e5-9cfa-ced27bb7bdea.png)

**Comment by SandyChapman** [comment]
It's a potential loss of precision. What this means in general terms is that if this long long variable is too large to reasonably fit into a size_t variable, the number's representation will be incorrect.

Example:

Let's say I have a 16 bit integer and let's say it's holding the value 8. In binary this is:

0000 0000 0000 1000

Now let's say I want to store this in an 8 bit integer:

0000 1000

Great, no problem. It's still 8. However, let's say I'm storing the number 495383.

1100 0001 1000 0010

And then I assign a 8 bit integer to this value:

1000 0010

Uh oh. This is actually the number 130. A very different value. This is why we're getting a warning in this code. Really, the Realm developers should take a look at fixing these sorts of warnings as they can lead to subtle bugs. It's technically not an error because application logic often ensures this conversion is safe, but the compiler is being helpful in telling us to double check.

**Comment by betaSavvy** [comment]
@SandyChapman Thank you very much for the detailed explanation!

**Comment by bdash** [comment]
This was previously reported as #2973, and will be fixed in our next major release.
