### ISSUE TITLE
Two way relationships

### ISSUE THREAD

**Issue by TiagoVeloso** [realm/realm-cocoa#3003]
Is it possible in Realm to have two way relationships?

Something like this:

    @interface Dog : RLMObject
    @property NSString *name;
    @property NSInteger age;
    @property Person owner;
    @end
    RLM_ARRAY_TYPE(Dog)
    @interface Person : RLMObject
    @property NSString             *name;
    @property NSData               *picture;
    @property RLMArray<Dog *><Dog> *dogs;
    @end

I have tried something similar and I get a crash on my app.

**Comment by jpsim** [comment]
Instead of doing the double-bookkeeping necessary to maintain inverse relationships manually, you should use Realm's inverse relationships mechanism, which provides you with all of the objects pointing to another object using a given property:

```swift
class Product: Object {
    dynamic var id : Int = 0
    dynamic var name : String = ""
    var stands: [Stand] {
        // Realm doesn't persist this property because it only has a getter defined
        // Define "stands" as the inverse relationship to Stand.products
        return linkingObjects(Stand.self, forProperty: "products")
    }

    override static func primaryKey() -> String? {
        return "id"
    }
}
```

See Realm's docs on [Inverse Relationships](https://realm.io/docs/swift/latest/#inverse-relationships) for more information.

If you *must* maintain full links on both side for some reason, We'll need more information to help you troubleshoot your crash. Your model objects seem fine to me. Where is your app crashing? Is there an exception or assertion message printed to the console? What steps could we reproduce to trigger such a crash? Please refer to our [CONTRIBUTING.md](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md) file for more details about what information is useful to us when filing an issue.

Thanks!

**Comment by TiagoVeloso** [comment]
I think my crash is due to me having a compound-key on my `Dog` object, which contains a property of the owner.

When adding a dog and a person in the same transaction the app was crashing. And that is what probably was causing the crash.

**Comment by jpsim** [comment]
Realm still shouldn't be crashing you app. I did notice one problem: `@property Person owner;` should be `@property Person *owner;`, although I suspect that's just a typo in your code sample here because your app wouldn't compile otherwise.

I don't see what you mean by compound key on the `Dog` model. We sometimes refer to compound keys as a key representing the concatenation of two other keys, but you don't seem to be doing anything like that in your model.

Finally, did my suggestion help you at all? I really think using Realm's built-in inverse relationship mechanism is the right design here.

**Comment by TiagoVeloso** [comment]
Yes your suggestion did help me. It's probably a better solution by design.

You are right, that code is just sample code I copied from realm.io and edited to present something similar to my scenario.

I will try to implement your idea.
