### ISSUE TITLE
Crash when Results.setValue(_:forKeyPath:) mutates objects to no longer match predicate

### ISSUE THREAD

**Issue by bigluck** [realm/realm-cocoa#3028]
Hi, after upgrading realm to the latest version `v0.97.0` my code crash:

```Swift
let remove = db.objects(VODBrand.self)
    .filter("topBrand = %@", RealmOptional<Bool>(true))
if remove.count > 0 {
    remove.setValue(RealmOptional<Bool>(false), forKeyPath: "topBrand")
}
```

`remove.count` have a value of 1, but `RLMCollectionSetValueForKey()` methods is looping 3 objects:

<img width="896" alt="schermata 2015-12-22 alle 19 30 55" src="https://cloud.githubusercontent.com/assets/1511095/11962751/90f67b80-a8e2-11e5-9b77-0988213238d3.png">

Here the crash:

```
Terminating app due to uncaught exception 'RLMException', reason: 'Index 2 is out of bounds (must be less than 1)'
```

What's up?

**Comment by bdash** [comment]
`RLMCollectionSetValueForKey` is mutating objects so that they no longer match the predicate. This causes the length of the collection to change on each iteration, which makes it unsafe to iterate the collection by index as `RLMCollectionSetValueForKey` is doing.

To work around this you can write the mutation explicitly as:

```swift
for brand in remove {
    brand.topBrand.value = false
}
```

Please also verify that your `topBrand` property is declared using `let` rather than `dynamic var`. `RealmOptional` properties must be mutated by changing their `value` property, not by assigning to the property itself as your snippet shows you doing.
