### ISSUE TITLE
Deleting lots of objects is abysmally slow AND makes the database larger

### ISSUE THREAD

**Issue by JustSid** [realm/realm-cocoa#3045]
I have a realm which contains flight navigational data, waypoints, ATS routes, runways, airports, arrival and departure routines. The whole thing. We are talking a good 500k objects per cycle here, although they are all pretty lightweight.

Now, with that out of the way, when I try to delete a whole cycle, it takes forever. We are talking a solid 5 minutes here, on an i7 Haswell MacBook Pro with SSD no less (importing the data takes less than 30 seconds). I tried batching it up into smaller transactions instead of deleting everything at once, but no matter what, it still takes forever. Worse yet though, with two cycles in the realm it takes up roughly 46mb of disk space. After _deleting_ a cycle I suddenly end up with a 67 mb realm!

I'm at the point where I'm seriously considering using a realm per cycle and just deleting the file on disk instead, but can that really be? I don't think deletion should be a slow operation, at least not multiple orders of magnitude slower than insertion. So maybe I'm doing something wrong here?

I'm afraid I can't post the realm in question, at least not publicly, since it contains proprietary data, but if you have a private email or similar where I can drop off confidential data, let me know and I'll send you the data.

**Comment by tgoyne** [comment]
If the data sets for the cycles are entirely independent and you'll never need to work with multiple simultaneously, then I actually would recommend a separate file per cycle. Deleting just some of the data from a file will always be slower than deleting the entire file.

The file size growing is due to that Realm never overwrites data currently in use. All modifications write a new version of the thing being changed, and then once all of the readers have switched to the new version, the old version is marked as free space and is reused for future writes. Data that isn't modified isn't rewritten, but deleting anything but the most recently inserted object actually modifies two rows in the low-level storage, and deleting exactly the older half of the data could hit a pathological case where every remaining row will need to be rewritten.

Note that this won't result in continued growth in the file size over time as long as the maximum amount of live data doesn't increase -- inserting a third cycle and then deleting the second should leave the size unchanged.

All that said, while deletion isn't speedy, it *definitely* shouldn't be taking ten times as long as insertion (our benchmarks have it taking ~50% longer). Are you using `-[RLMRealm deleteObjects:]`/`Realm.delete()` directly on a `Results`? That will normally be significantly faster than passing in an array of objects to delete (or manually looping over an array). Other than that there aren't any major gotchas, so seeing some of the code involved and a subset of the data could be helpful. You can email us anything that you're willing to share but can't post publicly at `help@realm.io`.

**Comment by JustSid** [comment]
I have indeed been feeding it arrays, feeding it `RLMResults` did decrease the deletion time to about 4 minutes. I have tried multiple variations before though, in terms of how much to delete, at first I was actually collection every single object and then gave it to Realm at once, which took the longest to complete (so long actually that I stopped it and never tried that approach again).

Anyway, I've sent you an email with a database containing two cycles and the data model itself, including the code I use to delete everything. Let me know if you need any more information.

**Comment by tgoyne** [comment]
Profiling the deletion shows nearly all (>95%) of the time spent in updating the string indexes. We have one of the developers of the core library looking into how to make this less awful, but if lookup speed is acceptable without an index you can try removing them as a workaround for now.

**Comment by rrrlasse** [comment]
We have now optimized deletion of rows of an index table. It should now take seconds instead of minutes. Will be included in the next release.

**Comment by jpsim** [comment]
A fix for this was merged in #3015. Thanks all for reporting!
