### ISSUE TITLE
Using Realm in a dynamic framework

### ISSUE THREAD

**Issue by abury** [realm/realm-cocoa#3051]
I'm building a standalone framework for a client was hoping to use Realm as it's caching mechanism, but after ~3 hours of trying various integration methods I've been unable to get it working.

### Goals
Integrate Realm cleanly into an external dependancy

### Expected results
Realm integrates the same as other frameworks (I've successfully integrated SnapKit and SDWebImage)

### Actual results
Whilst the framework target builds successfully, any target that includes my framework (test target and example project) throw the following error:
`ld: framework not found Realm for architecture x86_64`

### Steps to reproduce
Example project at https://www.dropbox.com/s/2xcz3il74pv9k9u/Example-Framework-Project.zip?dl=0

### Version of Realm / Xcode / OSX
- Realm: 0.97.0
- Xcode: 7.2
- OSX: 10.11.1

### Version of involved dependency manager (CocoaPods / Carthage)
I've tried using the dynamic framework at https://static.realm.io/downloads/swift/realm-swift-0.97.0.zip, building from source and building with Carthage(latest version)

Thanks guys and/or gals

**Comment by kishikawakatsumi** [comment]
@abury You should add the parent path of RealmSwift.framework to the “Framework Search Paths” in TidyOrderAheadExample's build settings. Because RealmSwift.framework uses Realm.framework internally, so RealmSwift.framework should be able to find Realm.framework and linked to. 

Like the following:

<img width="902" alt="screen shot 2016-01-04 at 16 18 21" src="https://cloud.githubusercontent.com/assets/40610/12085050/e2ada5fe-b2fe-11e5-9982-cc25244f0993.png">

Meaning of what is written in no. 3 in installation section is it.

> 3 . In your unit test target’s “Build Settings”, add the parent path to RealmSwift.framework in the “Framework Search Paths” section.
https://realm.io/docs/swift/latest/#installation-swift-211

FYI: You embedded some frameworks to TidyOrderAhead.framework though, in development, it works. But AppStore might reject if your app includes such nested frameworks.
To attempt to integrate some of the framework in one will not go well. Because AppStore does not support nested framework.

**Comment by abury** [comment]
@kishikawakatsumi So the parent app would need to update it's search paths because of a frameworks dependancy? I can see that being necessary if the parent app is using it directly, but i'm trying to build a standalone framework that is just 'drop in' and as easy to integrate as possible.

Thanks for the heads up on embedded frameworks having nested dependancies, I wasn't aware that it was an issue. I'm struggling to find an effective way of making this work, but it looks like I'll have to just include the source of those frameworks for now and do without Realm for the Framework, shame :cry: 
Thanks heaps for your help.

**Comment by jpsim** [comment]
Welcome to dynamic linking :disappointed:. This issue isn't unique to Realm, but rather dynamic frameworks in general. You could attempt to statically link Realm Swift into your framework by using the static version of `Realm.framework` and compiling Realm Swift's files with your framework, but that's unsupported and quite a hassle. Unfortunately, Swift doesn't support static linking at the moment, so you can't just statically link `RealmSwift.framework`.

**Comment by kishikawakatsumi** [comment]
> So the parent app would need to update it's search paths because of a frameworks dependancy? 

@abury Yes.

> i'm trying to build a standalone framework that is just 'drop in' and as easy to integrate as possible.

We had tried to do so a several months ago. But we gave up because we cannot resolve AppStore submitting issue. https://github.com/realm/realm-cocoa/pull/1942

**Comment by sassiwalid** [comment]
what do you think about adding realm by the developer outside the framework. I found that this solution is better to avoid the problem of submitting next in the AppStore???

**Comment by jpsim** [comment]
@sassiwalid that's necessary to comply with App Store rules.
