### ISSUE TITLE
Can't remove migration block even after removing all previously made objects

### ISSUE THREAD

**Issue by mrigdon** [realm/realm-cocoa#3095]
I'm using the RealmSwift library for my iOS app, and added a field to one of my models. I performed the migration, but can't remove the migration block of code even after I deleted all instances of that model. Do I really have to leave that migration block in my AppDelegate function forever? Doesn't that slow the app launch down considerably? (I asked Stack Overflow but got no response that's why I'm opening an issue)

**Comment by jpsim** [comment]
Hi @mrigdon, yes you have to keep that migration block in your app, because this new version of your app can be installed over any other previous version of the app. But the migration block will only ever run when applying the migration, which will only happen *at most* once per schema version number.

> I asked Stack Overflow but got no response that's why I'm opening an issue

I assume you're referring to [this](http://stackoverflow.com/questions/34758675/realm-swift-update-all-model-objects-and-remove-migration) StackOverflow question that was posted a few minutes before you filed this GitHub issue? That's [since been answered](http://stackoverflow.com/a/34759403/373262) by @TimOliver:

> Yes. Since you used a migration to bump the `schemaVersion` number of the Realm file, that migration block is required with the assumption that another migration may be required in future.
> 
> If you want to completely reset the migrations and remove the migration block, you'll need to delete your Realm file from disk and recreate it (i.e., simply deleting just the objects isn't enough).

For future reference, there's no need to post questions multiple times in different places. If you follow the guidelines described in the [Getting Help](https://realm.io/docs/objc/latest/#getting-help) or [Reporting Realm Issues](https://realm.io/docs/objc/latest/#reporting-realm-issues) sections of our docs, we'll find it!

**Comment by mrigdon** [comment]
That stack overflow question was the second time I asked. No one answered the first one so I asked a second time and opened an issue to find out in the fastest way possible. The first one was later closed as a duplicate
