### ISSUE TITLE
Adding automaticallyNotifiesObserversOfFoo for each property hurts Realm initialization time

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#3111]
A user emailed help@realm.io about the performance of Realm initialization with Realm 0.97.0. Their application has a very large data model, comprising of over 90 subclasses of `RealmSwift.Object`. They provided an Instruments trace that shows the initialization time being dominated by calls to `class_addMethod` within `RLMAccessorClassForObjectClass`. These calls add implementations of `+automaticallyNotifiesObserversOf<Property>` for each property to prevent the KVO machinery from sending notifications for properties that we manage. Each of the calls to `class_addMethod` flushes the Objective-C runtime cache for the class, which is relatively expensive when done repeatedly. It looks like KVO supports disabling automatic notification using a single `+automaticallyNotifiesObserversForKey:` method. Depending on how performance-sensitive this is we could either implement this directly on `RLMObject`, or add custom implementations on each accessor class.

**Comment by bdash** [comment]
@tgoyne, can you speak to why you chose to add `+automaticallyNotifiesObserversOf<Property>` methods dynamically, and whether you considered implementing `+automaticallyNotifiesObserversForKey:` instead?

**Comment by bdash** [comment]
One thing I noticed while testing this is that `class_addMethod` is significantly faster on iOS 9.3. It looks like flushing the Objective-C runtime cache for a class is much cheaper as it no longer flushes the cache for the metaclass and its subclasses.

**Comment by tgoyne** [comment]
We have a similar number of classes in our test targets, and even on-device the calls to class_addMethod took an inconsequential amount of time when I last benchmarked accessor creation (which would have been iOS 8). Maybe it's just an issue for iOS 7? Also, we incorrectly call `objc_registerClassPair()` immediately after creating the class rather than when the class is ready to go, and fixing that would probably help with this.

Overriding `automaticallyNotifiesObserversForKey:` would be more complex and have worse performance at observer-add time (it can't just return NO because in theory the user could have overridden it for their ignored properties), but it's certainly an option.

**Comment by bdash** [comment]
The user report mentions iOS 9. It's possible that `class_addMethod` performance regressed in iOS 9 and iOS 9.3 restores things to the way they were.

If there's a cheap way to get the object schema for a given `Class` an implementation of `+automaticallyNotifiesObserversForKey:` in `RLMObjectBase` could be relatively cheap. If Foundation caches the results of calls to that method, which it appears to, then there shouldn't be much impact to having a slightly less efficient implementation of `+automaticallyNotifiesObserversForKey:`.

**Comment by bdash** [comment]
> If there's a cheap way to get the object schema for a given `Class`

`+[RLMObjectBase sharedSchema]`
