### ISSUE TITLE
Can't use removeObserver:forKeyPath: during observeValueForKeyPath:

### ISSUE THREAD

**Issue by timothycosta** [realm/realm-cocoa#3116]
Realm crashes with EXC_BAD_ACCESS if you attempt to call removeObserver:forKeyPath: while using observeValueForKeyPath:ofObject:change:context:.  This is in contrast with normal KVO where this is possible.

It seems like this might be avoidable, since the next/prev pointers in RLMObservationInfo are being changed, but not to valid (null) values.  They are always 0xN000000000000000 (where N is not 0) when the crash occurs.  Perhaps that is intentional?

The documentation page states:
>Because properties can change in value when not in a write transaction or even as part of beginning a write transaction, trying to modify persisted Realm objects from within -observeValueForKeyPath:ofObject:change:context: is not recommended.

But it reads to me as though you shouldn't try to update the persisted properties.  If this is intentional behavior, maybe the wording could be updated to make this situation more clear.

**Comment by kishikawakatsumi** [comment]
@timothycosta Thank you for reporting! Could you provide us with more code that leads up to this? Could you share the code around crash and start observing?  If you could send a small reproducible project or the actual project privately to help@realm.io it will help us look into this.

**Comment by tgoyne** [comment]
Removing observers from within the observation handler should work correctly, and in a fairly minimal test of adding observers to a few persisted objects, triggering changes on them, and removing the observer from within the notification seems to work. Are you maybe also deallocating the object from within observeValueForKeyPath:ofObject:change:context?

**Comment by jpsim** [comment]
@timothycosta we weren't able to reproduce the issues you reported. Would you be able to come up with a failing unit test or sample project that can trigger the issue so we can investigate?

**Comment by timothycosta** [comment]
@tgoyne @jpsim @kishikawakatsumi I wasn't able to exactly replicate what was happening in my app in a sample.  It is possible the object was getting deallocated.  I was able to get a crash to occur by *deleting* the object during observerValueForKeyPath: though.  I verified that deallocating a regular NSObject does not cause a crash.  

Here's a gist, and I will email the full project to help@realm.io.  Revision one and revision three show two different ways of generating two different exceptions.
https://gist.github.com/timothycosta/829df1ae35deeb93eaed
You can test a normal NSObject by uncommenting line 35 (observe UILabel), and commenting out line 63/64 (observe a realm object).

**Comment by tgoyne** [comment]
In that code it is the call to `beginWriteTransaction` within `updateProfile` that's throwing, because the Realm is still in the write transaction began in `changeLanguage:` and we do not support nested transactions. Changing `updateProfile` to only begin a write transaction if it is not already in one (and only commit it if it began it) makes that code run without errors for me.

**Comment by timothycosta** [comment]
@tgoyne That makes sense, and I thought about doing something like that as well.  However, wouldn't it make more sense to just delay all KVO updates until after commitTransaction is called, even on the same thread?  Otherwise, theoretically any code that could ever be touched via KVO would need to be peppered with checks for whether you are already in a writeTransaction.  Should I already be doing that?  It would be simple enough to create a category with a block which would do that, but it seems a little dirty to me.

By the way, this section of the documentation is a little bit confusing.  "When you directly assign to it" to me reads like "when you assign outside of a write transaction" (which you shouldn't be doing anyway, unless I'm mistaken).  Something like "as soon as you assign to it during a write transaction on the same thread" might be clearer.

```With persisted objects, there are three times when the value of a property may change: when you directly assign to it; when you call [realm refresh] or the Realm is automatically refreshed after a write transaction is committed on a different thread; and when you call [realm beginWriteTransaction] after changes on a different thread which have not been picked up by a refresh on the current thread.```

**Comment by tgoyne** [comment]
Foundation's implementation of KVO isn't really flexible enough to support delayed notifications. It's fundamentally designed around the idea of synchronous notifications that are delivered before the setter returns.In theory delaying the call to `didChangeValueForKey:`until the transaction is committed could work, but in practice it broke horribly, and would result in observers on RLMObject working weirdly differently from observers on normal objects. One of the goals of KVO support was to support the pre-existing ecosystem of things built on top of KVO rather than requiring Realm-specific code for watching for object updates, so drifting too far from the normal behavior is counter-productive.

I don't think it's possible to write fully-correct code which modifies an RLMObject from code called by a KVO observer on another RLMObject if you're making writes on multiple threads. Checking if you're already in a write transaction before beginning one handles the simple cases (but as you say, is ugly), but in the case of a notification being sent due to starting a write transaction (if there was a write made on another thread, beginning a write transaction will always advance to the most recent version of the data first), the change being observed happens at a point where you aren't yet in a write transaction, but you also can't begin one.

>  reads like "when you assign outside of a write transaction" (which you shouldn't be doing anyway, unless I'm mistaken)

It's not that you shouldn't be doing that; you can't, and if you try it'll throw an exception.

**Comment by timothycosta** [comment]
@tgoyne Thank you very much for the detailed explanation.  It really helps my understanding of realm and KVO.  I'll close this.  I wasn't able to duplicate my original problem in a sample project.  The problem there wasn't (as far as I could determine!) trying to write anything during the notification.  Nevertheless the workaround I found was simple enough anyway.
