### ISSUE TITLE
Any plans to support RxSwift?

### ISSUE THREAD

**Issue by mrahmiao** [realm/realm-cocoa#3117]
Since we have official RxJava support, why not add a RxSwift one?

**Comment by jpsim** [comment]
The Swift community is pretty lucky to have so many reactive extension frameworks to choose from (RxSwift, ReactiveCocoa, ReactKit & Interstellar to name a few of the most popular ones).

Rather than officially endorse one over the other & bundle it with Realm, forcing that choice onto our users, we prefer to support all of them equally as best we can and leave our users to choose which Rx framework (if any) to use with Realm.

If there's anything we can specifically do to better support those other frameworks, please let us know and we'll be sure to consider it.

We have a few Rx examples in this repo that you can browse to see how to do the same for your app: [ReactKit](https://github.com/realm/realm-cocoa/tree/master/examples/ios/swift-1.2/ReactKit) and [ReactiveCocoa](https://github.com/realm/realm-cocoa/tree/master/examples/ios/objc/RACTableView).
