### ISSUE TITLE
It spend about 2 seconds at first time.

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#3128]
start > 2016-01-22 12:34:25.642
end  >  2016-01-22 12:34:27.917

First time, call the method as follows,it spend about 2 seconds,probably, it too slow.

```ruby
print("start")
DataCache.sharedInstance.getJsonString("xxxx")
print("end")
```

```ruby
public class DataCacheModel:RLMObject  {
    dynamic  var key:String = ""
    dynamic  var value:String = ""
    
    override public class func requiredProperties() -> [AnyObject]{
        return ["key","value"]
    }
}

public class var sharedInstance: DataCache {
        struct Static {
            static let instance: DataCache = DataCache()
        }
        return Static.instance
}

public func getJsonString(key:String) -> DataCacheModel?{
        let results:RLMResults = DataCacheModel.objectsWithPredicate(NSPredicate(format: "key = %@",key))
        if results.count > 0 {
            let object:DataCacheModel = results.objectAtIndex(0) as! DataCacheModel
            return object
        }
        return nil
}

**Comment by mrackwitz** [comment]
Is that all code related to Realm, you have in your project? The first initialization of a Realm instance might take some time. On which device and OS are you seeing these times? What is the size of your database and the JSON string you're retrieving? It would help if you would provide some instrumentation data to see where the time is spent.
What might also help is to initialize the first Realm accessor at another place on the same thread and cache it in advance, so that you keep your database open and don't have to allocate memory all over again.

**Comment by jpsim** [comment]
@hengchengfei as @mrackwitz has said, there are many factors that can affect the performance numbers you're seeing, such as running in Release/Debug mode, the size of the database, the size of your JSON string, the device you're running on, the number of Realm models you have linked in this app, etc.

If you find a bug, or performance optimization we could make, please let us know. Until then, I'm closing this issue.
