### ISSUE TITLE
Realm crashes when primary key type is not int or string with confusing error

### ISSUE THREAD

**Issue by gal-orlanczyk** [realm/realm-cocoa#3129]
when i used realm in my unit tests, i received a strange error:
"`Object` classes must not be pre populated with query results from a Realm"
but the real problem was my primary key was of wrong type and only needs to be int or string.
i think you should have an appropriate error message for such case.

**Comment by mrackwitz** [comment]
I'm unable to reproduce that. In general, you hit that exception for a recursive schema initialization call, which might happen implicitly by pre-populating attributes with queried results. Could you share how your model code before you adopted the necessary change?

**Comment by TimOliver** [comment]
Hi @gal-orlanczyk! Just checking in! Are you still having this issue, or were you able to fix it yourself?

We're eager to hear how you went! :)

**Comment by gal-orlanczyk** [comment]
Sorry for the delay... First of all i love your product and i think it has great potential.
Secondly, i was able to fix it at the time by fixing the primary key type i accidently did it of type date instead of string.
I think the thing missing with your product is a real life example with different kinds of scenarios.
When i was search answers in the web and stack overflow i havent found a lot of material.
For my opinion the following ideas should be covered: using primary keys, fetching results on background queue and transfering it to the main queue. Using realm notification and exaplaining them.

**Comment by jpsim** [comment]
> I think the thing missing with your product is a real life example with different kinds of scenarios.

I'm assuming you've read through all of our [examples](https://github.com/realm/realm-cocoa/tree/master/examples) and [recipes](https://realm.io/docs/objc/latest/#realm-recipes)? We want to continue to grow this area of our documentation, so your request is noted!

> When i was search answers in the web and stack overflow i havent found a lot of material.

We answer all questions on SO tagged with `realm`, you can see all of them here: http://stackoverflow.com/questions/tagged/realm

> For my opinion the following ideas should be covered: using primary keys, fetching results on background queue and transfering it to the main queue. Using realm notification and exaplaining them.

Have you read our documentation on [primary keys](https://realm.io/docs/objc/latest/#primary-keys), [threading](https://realm.io/docs/objc/latest/#threading) and [notifications](https://realm.io/docs/objc/latest/#notifications)? If you think of ways we could better explain these concepts, please let us know!

I'll close this issue since you've mentioned you resolved your problem by setting your primary key type to a property type we support.
