### ISSUE TITLE
unable compile 0.97.1 in swift

### ISSUE THREAD

**Issue by frankcjw** [realm/realm-cocoa#3159]
Hi
I found I'm unable compile 0.97.1 in swift..

in index_set.cpp
line 19 
#include "index_set.hpp"

shows error index_set.hpp not found.
<img width="637" alt="screen shot 2016-01-30 at 9 55 59 pm" src="https://cloud.githubusercontent.com/assets/6236022/12696112/59e74150-c79c-11e5-9e5a-8e7a67e645ef.png">

my podfile wrote
pod 'RealmSwift'

**Comment by jpaas** [comment]
I'm having the same problem

**Comment by jpaas** [comment]
0.97.0 works fine though

**Comment by umwelt** [comment]
this worked for me, search for index_set.hpp and in targetMembership found that its was added only to Realm and not also to RealSwift.

So adding  index_set.hpp to RealmSwift in targetMembership did it for me

**Comment by Carpemeid** [comment]
Also had the same problem. Had to downgrade for it to work. When I'll have some more time I'll experience the "umwelt" solution.  But for now I'm afraid to touch the cocoa pods again, as it still doesn't work flawlessly with adding and removing frameworks without some "missing modules" stuff.

**Comment by SergeHaddad** [comment]
@Carpemeid how did you downgrade to Realm 0.97.0 ?

**Comment by jpsim** [comment]
This is likely a cache invalidation issue in either Xcode or CocoaPods. I recommend that you clear your derived data and reinstall your pods:

```shell
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod install
```

Realm Swift does not directly depend on `index_set.hpp`, so adding that to Realm Swift's target membership as @umwelt described above likely won't do anything.

Reverting to a previous version of Realm is completely unnecessary.

**Comment by jpaas** [comment]
@jpsim I'm pretty sure I tried

1. cleaning the project
1. deleting derived data
1. deleting Pods directory, Podfile.lock and even the workspace and regenerating with a pod install

**Comment by jpsim** [comment]
It's possible that performing those steps didn't work for you, but in our integration tests, we're able to install Realm Swift 0.97.1 with CocoaPods on all our supported platforms.

If you can share a project with us that can reproduce this issue, we'll be happy to look into it further.

**Comment by frankcjw** [comment]
@jpsim it work~~ thanks a lot~

**Comment by Carpemeid** [comment]
I understand it may be a "cache" stuff. But I went crazy for 3 hours (just for the fun fact and trust that I can update the lib and use my time for the project) with the deadline ahead of me trying to reclean/reinstall everything. 

And it was not fun at all. 

And why would it be an issue for so many people? Even if pods do something wrong, isn't there a flag or an option which should be set and would make pods work correctly? Because triggering an error for all the developers is for sure not a way to do things. 

@SergeHaddad  In case cleaning doesn't work for some magical reasons to downgrade you need to specify the older version in pods not only for Realm-Swift but also for Realm itself, even if you didn't have Realm specified at all in the pods before. At least this is what I had to do.
