### ISSUE TITLE
Swift - Search for objects using a UITextField

### ISSUE THREAD

**Issue by SergeHaddad** [realm/realm-cocoa#3160]
Hello. I've used the RealmSearchViewController to search for objects, but i also want to do that using a UITextField, where the user starts typing a patient's name into a text field, and a tableview under it shows the patients with the corresponding letters. Can you please add that feature ?

**Comment by TimOliver** [comment]
@SergeHaddad 

Hi Serge! Thanks for your issue!

Hmm, if you want the functionality of `RealmSearchViewController`, but you're implementing a custom UI, it might be appropriate for you to implement the UI code, and perform the search directly against Realm yourself.

This would be really simple to implement. Each time the user types into the `UITextField`, its delegate can pass the search string as an `NSPredicate` to Realm, which can then provide a `Results` object that you can use to populate your `UITableView`.

If you think that this definitely is a feature that `RealmSearchViewController` should implement, then it would be more appropriate to file this issue [on its repo](https://github.com/bigfish24/ABFRealmSearchViewController/issues) instead of this one.

I hope that helped! Let me know how you go! :)

**Comment by SergeHaddad** [comment]
Hello,

Thanks fir replying. I've never used NSPredicates before, and i didn't
understand how that NSPredicate can provide a Results object. Is there any
demo project ? I'm trying to search patients' names. Can you show me how to
create that NSPredicate from the UITextField and then provide a Results
object from it ?

**Comment by SergeHaddad** [comment]
Hey Tim, it worked! Thank you. I did as you said. I used an NSPredicate
with CONTAINS[c] and then used realm.objects(Class).filter(predicate) and
then populated the table with it. Thanks again

**Comment by jpsim** [comment]
We're glad you got this working, @SergeHaddad!
