### ISSUE TITLE
Ambiguous use of 'subscript'

### ISSUE THREAD

**Issue by Conaaando** [realm/realm-cocoa#3164]
Hi,

I'm installing Realm (0.97.0) as a "Dynamic Framework" in my Swift 2.1.1 project. (Drag RealmSwift.framework and Realm.framework from the ios/swift-2.1.1... directory to the “Embedded Binaries” section.)

So far, so good.

But after I create a class that is of type **Object** (say: _class Account: Object {...}_) my project does not compile anymore. The error is:

![subscriptissue](https://cloud.githubusercontent.com/assets/664951/12727175/d6fe8bc8-c902-11e5-91c9-cf09204f8b8a.jpg)

**As soon as I remove that class (_class Account: Object {...}_), my project builds again.**

Do you have any idea what the problem may be?

Thanks.

**Comment by jpsim** [comment]
Realm is only involved very indirectly here, maybe just because it depends on Foundation even.

In any case, subscripting `AnyObject` is ambiguous because `AnyObject` doesn't allow subscripting. You likely either want to pass `JSON: NSArray` as a parameter to `persistUserIDAndToken` or cast `JSON` to a subscriptable type in the function: `let JSON = JSON as! NSArray` or similar.

**Comment by Conaaando** [comment]
Yes, that is probably true. The workaround would be:

```
...(JSON: **NSDictionary**) {
let userId = JSON.objectForKey("id")!
...
}
```

I just wanted to understand why the problem manifests itself only when Realm is added to the project.

(Anyway, the workaround is there, if this is something that wouldn't/shouldn't be fixed in Realm, I think it's safe to close it.)

Thanks.

**Comment by jpsim** [comment]
> I just wanted to understand why the problem manifests itself only when Realm is added to the project.

Probably due to how Swift resolves ambiguous function references, including subscripts.

In any case, I'm closing this as you understand that this isn't a Realm issue.
