### ISSUE TITLE
import a JSON with date field and a specific format

### ISSUE THREAD

**Issue by finddoc** [realm/realm-cocoa#3171]
Hi, I have a JSON object that would like to import to Realm, however, the date format of that JSON is "DD/MM/YYYY", how could I pass this info to realm so that it recognize the format and automatically import it. Thanks

**Comment by tgoyne** [comment]
Realm does not currently support any data transformations when creating or updating objects, including converting from a string to a date. https://github.com/realm/realm-cocoa/issues/1013 is this issue tracking adding that, but it's low priority for us because there are many third-party libraries data mapper libraries which do a perfectly good job of it that work with Realm, and so we just recommend using one of them.
