### ISSUE TITLE
Dont work objectsWithPredicate with operator "NOT IN"

### ISSUE THREAD

**Issue by axenovV** [realm/realm-cocoa#3186]
Hi all, I need to take to get items from the array that are not in the database.I'm trying to make this predicate

`    NSPredicate *predicate = [NSPredicate predicateWithFormat:@"!(id IN %@)", array];
    return[ProductModel objectsWithPredicate:predicate];`
 
But it returns nil, but if you use a predicate without NOT, then everything works.

**Comment by axenovV** [comment]
This is work in coredata.

**Comment by edalford11** [comment]
@axenovV try this syntax.

RLMResults *results = [ProductModel objectsWhere:@"NOT id IN %@", array];

**Comment by TimOliver** [comment]
Hi @axenovV!

I noticed you also asked [this same question on StackOverflow](http://stackoverflow.com/questions/35273890/dont-work-objectswithpredicate-with-operator-not-in).

I'm going to close this issue in favour of keeping the conversation there. This is mainly because these sorts of questions are much better off on StackOverflow as they remain visible, even after resolved.

As @bdash requested on the StackOverflow page, can you please expand your code sample on there to give us some more information on how you're implementing this? By all accounts, this should already work!

Thanks! :)
