### ISSUE TITLE
Realm is left in a state where calling beginWrite crashes.

### ISSUE THREAD

**Issue by anlaital** [realm/realm-cocoa#3199]
Firstly I apologize for not being able to provide a reproducible case for this. This started happening directly after upgrading to v0.98.1, so I'll try and roll back a bit to see if it fixes the issue.

The exception is as follows:

```
*** Terminating app due to uncaught exception 'RLMException', reason: 'Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress)'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105d43e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000107894deb objc_exception_throw + 48
	2   Realm                               0x0000000103ad10e8 -[RLMRealm beginWriteTransaction] + 136
	3   RealmSwift                          0x0000000103f83abd _TFC10RealmSwift5Realm10beginWritefS0_FT_T_ + 45
```

The Realm's inWriteTransaction is ```false```. The source of the exception is ```_realm->begin_transaction();```, so I'm not able to debug this further as I don't have the source for that.

**Comment by anlaital** [comment]
This is reproducible with both ```v0.98.1``` and ```v0.98.0``` releases. Downgrading to release ```v0.97.0``` fixes the issue.

**Comment by tgoyne** [comment]
[Realm::begin_transaction()](https://github.com/realm/realm-cocoa/blob/master/Realm/ObjectStore/shared_realm.cpp#L285) is still in the open-source part of things, but digging into that probably won't yield anything interesting, since the problem is probably going to be that the wrapper's state got out of sync with the actual transaction state sometime before that. I'm looking into how this could happen now.

**Comment by tgoyne** [comment]
I'm able to hit this exception with the following test code:

    RLMRealm *realm = RLMRealm.defaultRealm;
    realm.autorefresh = NO;
    [realm transactionWithBlock:^{ }];

    XCTestExpectation *notificationFired = [self expectationWithDescription:@"notification fired"];
    RLMNotificationToken *token = [realm addNotificationBlock:^(NSString *note, RLMRealm *realm) {
        if (note == RLMRealmDidChangeNotification && !realm.inWriteTransaction) {
            [realm transactionWithBlock:^{ }];
            [notificationFired fulfill];
        }
    }];
    [self dispatchAsync:^{
        [RLMRealm.defaultRealm transactionWithBlock:^{ }];
    }];

    [realm beginWriteTransaction];
    [self waitForExpectationsWithTimeout:2.0 handler:nil];
    [realm cancelWriteTransaction];
    [token stop];

The last `beginWriteTransaction` refreshes the realm as part of beginning the write transaction (in this case because autorefresh is off, but it could still happen with autorefresh on if a commit is made immediately before that on a different thread), and then it sends the DidChange notification between when the write transaction is begun and `m_in_transaction` is set to true.

This specific case should be trivial to fix, but it may not be what you're actually hitting.

**Comment by anlaital** [comment]
I'd be happy to try out the fix from a branch, if you'd like. I can reproduce the crash with our codebase pretty much 100% of the time.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-cocoa/pull/3202 fixes the issues I've been able to locate so far.

**Comment by anlaital** [comment]
Thank you so much for looking into this without a reproducible use case, @tgoyne! I know how painful it can be...

You'll be happy to learn that the fix you made also does in fact fix the crash I'm seeing. I tested this a couple of times by reproducing the crash on ```v0.98.1``` then doing the exact same steps after pulling Realm and RealmSwift code from ```tg/transaction-state-tracking``` and could not reproduce the crash nor see any inconsistencies how the app behaved.

Awesome work! :+1:
