### ISSUE TITLE
Pod update error

### ISSUE THREAD

**Issue by Onetaway** [realm/realm-cocoa#3210]
```
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.96.1
Downloading core failed:
curl: (35) Server aborted the SSL handshake

````

I was use 0.96.1, when I pod update, it shows this error.
It is installing 0.98.1

The above error appear when I use VPN to pod update. Then I closed VPN, run `pod update` again.
It shows another error.
```
[!] /bin/bash -c
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.96.1
Downloading core failed:
curl: (56) SSLRead() return error -9806

```
I have google `sslread() error -9806`, but didn't find anything usefull.

I am in China and I have found #2713 . But I got the different error, not `poor network`

**Comment by mrackwitz** [comment]
Even though your error looks different, it is unfortunately the same root cause. I changed the error handling in our script meanwhile, so that it shows in some cases more helpful output. But the concatenation of circumstances that apply here lead to a slightly less obvious error messaging. See also #3183.
