### ISSUE TITLE
A Plain Old <Insert your language> Objects approach

### ISSUE THREAD

**Issue by trustyfrog** [realm/realm-cocoa#3212]
While I love Realm, it does have the tendency to leak its abstraction through the layers. A feature I would like is to create POSOs (Plain Old Swift Object) but have Realm do the heavy lifting in my data layer.

There are ORM systems out there that deal with persistence in such a manner. (I acknowledge you're not an ORM, but this is the closest set of examples I can arrive at.)

**Comment by jpsim** [comment]
There are a number of reasons why Realm doesn't do this.

One is that Realm is designed to have "live" objects, a concept which is fundamentally incompatible with detached/in-memory "plain old 'x' objects". There are a number of features provided by Realm which are rendered impossible by this detachment: liveness of data, reactiveness of APIs, low memory footprint of data, performance of operations, lazy & cheap access to partial data, lack of data serialization/deserialization, keeping potentially complex object graphs synchronized, etc.

That being said, it is sometimes useful to detach objects from its backing Realm. Unfortunately, this is more often needed to work around temporary limitations in our library rather than as an ideal design decision (such as thread-confinement). This is why we've worked hard to ensure that standalone/detached Realm objects behave exactly like plain old NSObjects. We support making "in-memory copies" of Realm objects by exposing an initializer that creates a standalone object via KVC copying of a persisted object's properties. For example:

```swift
let standaloneModelObject = MyModel(value: persistedModelObject)
```

Finally, we'd love to be able to offer an immutable, non-thread-confined, value-semantics Swift struct interface to Realm Objects. But Swift's current language machinery, as well as some minor cosmetic limitations in our core database engine, prevent us from doing so without sacrificing all of the advantages of Realm's "live" features outlined above. We're working on addressing those internal shortcomings at the moment, and we're hopeful that the property behaviors the Swift core team is currently working on (apple/swift#1297) will provide the machinery necessary for us to fully support Realm-backed Swift structs.

**Comment by trustyfrog** [comment]
That's a great response. I'd love to know (read: understand) more about the underlying architecture, but that's fine for now.

**Comment by AliSoftware** [comment]
@trustyfrog if you're interested in Realm engine internals, architecture and design choices, I found [this talk](https://realm.io/news/jp-simard-realm-core-database-engine/) — by @jpsim himself — really interesting!

**Comment by alickbass** [comment]
So the [apple/swift#1297](https://github.com/apple/swift/pull/1297) was merged into master on February. Any changes on this topic?

**Comment by jpsim** [comment]
Property behaviors still aren't available in Swift by default, you need to enable with with an unofficial compiler flag and will likely go away or change significantly in the future.

**Comment by alickbass** [comment]
@jpsim thanks for clearing out)
