### ISSUE TITLE
Access default.realm file from iTunes

### ISSUE THREAD

**Issue by AlexEdunov** [realm/realm-cocoa#3238]
If I understood correctly, default.realm file is located in Documents folder. I tried to access it from iTunes by enabling UIFileSharingEnabled flag in Info.plist, but it doen't appear yet. Could you give any recommendations how to do that?

**Comment by TimOliver** [comment]
Hi @AlexEdunov!

Yes! That's correct! Realm, by default places `default.realm` in the `Documents` directory of iOS apps. You only need to enable `UIFileSharingEnabled` in the Info.plist file and everything should simply appear in the 'File Sharing' section of your device's configuration in iTunes:

<img width="1084" alt="screen shot 2016-02-19 at 11 49 37 am" src="https://cloud.githubusercontent.com/assets/429119/13166114/01804102-d6ff-11e5-8367-4c079ede4284.png">

If the app itself hasn't appeared in the list yet, it's possible iOS hasn't properly noticed that the key has been set on it yet. If that's the case, you can try either deleting the app from your device and re-installing it, or even just rebooting the device in order to get iOS to refresh it.

Let me know how you go!

**Comment by mrackwitz** [comment]
As we didn't heard back on this, I assume this could be answered by @TimOliver's proposals. If you should be still unable to retrieve your Realm file from your phone, please feel free to comment.
