### ISSUE TITLE
Null table when initializing Realms to the same file location on different threads and deleting the physical files

### ISSUE THREAD

**Issue by Fab1n** [realm/realm-cocoa#3240]
*(Please help me with a shorter, more descriptive title)*

I am running into a `EXC_BAD_ACCESS` when 
...creating a `Realm` instance with a static path and keeping the reference
...then writing to that realm
...then deleting all files at that path (path's parent folder)
...then creating a new `Realm` instance with the same path (thus "static")
...then writing to the new realm

**Important: This only happens when creating the `Realm` instances on different threads**
As far as I have tested it should be fine in the background on the _same_ `NSThread` or on `MainQueue`

When writing to the new realm (adding an object) I end up having the crash at `Table::add_empty_row(size_t num_rows)`, in `table.hpp:1745`, latest Realm (0.98.1) and 0.97.1, too

Here is some complete code you could throw into a demo project (using PathKit):
``` swift
import UIKit
import RealmSwift
import PathKit

class Car: Object {}

class ViewController: UIViewController {
    
    var realms = [Realm]()
    
    var dir: Path {
        let path = Path(try! NSFileManager().URLForDirectory(
            NSSearchPathDirectory.ApplicationSupportDirectory,
            inDomain: NSSearchPathDomainMask.UserDomainMask,
            appropriateForURL: nil,
            create: true
            ).path!) + "MyApp"
        if !path.exists {
            try! path.mkdir()
        }
        print(path)
        return path
    }

    @IBAction func createDBAndWrite(sender: AnyObject) {
        let path = dir + Path("realm") + Path("0")
        
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) {
            print(NSThread.currentThread())
            do {
                try (self.dir + Path("realm")).mkdir()
                let config = Realm.Configuration(path: path.description)
                
                let realm = try Realm(configuration: config)
                self.realms.append(realm)
                
                try realm.write {
                    let car = Car()
                    realm.add(car)
                }
            } catch {
                print(error)
            }
        }
    }

    @IBAction func deleteDBFolder(sender: AnyObject) {
        let fileManager = NSFileManager.defaultManager()
        try! fileManager.removeItemAtPath(dir.description)
    }
}
```

**Comment by jpsim** [comment]
It's likely that the issue here is that Realm files are being deleted while the database is still being accessed. To fully stop Realm from accessing its backing database files, the `Realm` instance has to be deallocated, which can be forced by wrapping all usage of the Realm in an `autoreleasepool`.

I've written more on the subject and provided guidance for avoiding these situations on Stack Overflow recently: http://stackoverflow.com/q/35474907/373262

**Comment by Fab1n** [comment]
OK, the problem is our setup is extremely complex with realm. The smallest, hidden retain cycle can lead to a retained `Realm` somewhere. I am currently hopping through all of our code to make sure all `Realm` instances are released properly when deleting our db files on disk.

But I think this is a nearly unrealistic task... If somebody introduces code that makes a Realm not release itself (stuck in a cycle) then deletion and recreation of the database cannot be done without a crash. For us this is not acceptable. 

Is this a `won't fix` because of how Realms share their schema or so?
Until now I have 2 solutions:
1. Make sure all realms are released always (though this is not possible with `autorelease` for us). 
2. When deleting the database and setting up a new one use `UUIDs` for file names, so the retained `Realms` do not conflict with new `Realms`, because of using the same path

What do you think?

**Comment by jpsim** [comment]
You're right that it is very challenging (if not realistic in most cases) to make changes to Realm files outside of Realm's API between the time a file is first accessed and until that process terminates.

One of Realm's core design decisions is to tie the lifetime of objects with a "connection" to the backing file. This allows Realm objects to be retained across iterations of the run loop, making their access both "live" and very efficient. However, one limitation of this design choice is that all in-memory Realm instances must be completely deallocated, across all threads, in order for file operations (that don't go through Realm's API) to be safe. Given Cocoa's runloop + ARC models, this is a very difficult state to reach. We feel that the tradeoffs here are worth it, but we understand others might disagree.

The two options you provide (deallocating all Realm instances & using different Realms) are the only ways to stop using a Realm file that we support.

There is a private API for invalidating a Realm ([`-[RLMRealm invalidate]`](https://github.com/realm/realm-cocoa/blob/v0.98.3/Realm/RLMRealm.mm#L522-L544)) but this is not officially supported because it would cause errors if other objects that depend on that Realm (such as Results, or Objects) try to access data.

There's another private API for compacting a Realm in-place ([`-[RLMRealm compact]`](https://github.com/realm/realm-cocoa/blob/v0.98.3/Realm/RLMRealm.mm#L546-L581)) which is also not officially supported because this requires that no other Realm instances exist (by use of either `autoreleasepool`s or `-[RLMRealm invalidate]`).

I must stress that these private APIs are not officially supported.

On a related note, we are tracking adding an API to safely delete Realm files in #2422 but this wouldn't help you in your case, because this API will also require that no Realm instances exist for that path.

**Comment by jpsim** [comment]
So assuming I'm understanding you correctly, this issue is in fact a feature request for decoupling the `Realm` object lifecycle from a "connection" to its backing file so that it be possible to invalidate all Realms pointing to a file so that this file may be modified, moved or deleted from disk.

In response, this is something that already exists privately via (`-[RLMRealm invalidate]`) but due to the strict requirements in using this API, and the potentially surprising and destructive impact of its misuse, we are choosing not to expose this API publicly for the time being. This is why I'm considering this ticket as "won't fix". In the future, I hope we can find ways to improve this situation, but for now that's not possible.
