### ISSUE TITLE
API review before 1.0

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-cocoa#3257]
Review API for consistency (also with Java) and update any API naming if needed.

**Comment by cmelchior** [comment]
For quick reference: https://github.com/realm/realm-java/issues/1594

**Comment by jpsim** [comment]
Did a walk through of the Cocoa API with @nhachicha, reviewing from his perspective from a Java binding developer. We found most of the actionable feedback to be done on the Java side. See this comment for his action items following the review: https://github.com/realm/realm-java/issues/1594#issuecomment-197904615

The cocoa team has identified a number of APIs that should be deprecated. See #3442, #2593, #1324, #3396 & #2849. Review of those deprecations will be delegated to those pull requests rather than this overarching ticket.

In a more general review of the Objective-C API, the biggest sore point in my opinion is the concept of a default Realm. `[RLMRealm defaultRealm]` offers no error handling, the shorthand default Realm methods add a heavy layer of duplication to the API, and finally the mutable default configuration has been a source of confusion and bugs for users.

However, so many users rely on the default Realm that it would be unwise to break it at this point in time. Might be worth considering an alternative with Realm 2.0 😉.

The migration & dynamic APIs are also ripe for improvements after a 1.0 release, but not urgent enough to invest before then.

The Swift API isn't burdened by most of the default Realm problems the Objective-C version has thanks to default parameter values, but the mutable default configuration might be worth deprecating post 1.0 too, since it really doesn't save all that much code in the Swift API compared to storing desired configurations in user-defined global variables.

---

All that to say that other than existing work to refine the API as outlined above, I don't think any further API refinements are necessary before a 1.0 release.

**Comment by jpsim** [comment]
Additional API review considerations:

**Encryption duplication**

Some Objective-C APIs have duplicate versions with and without an encryption key parameter.

* `+[RLMRealm schemaVersionAtPath:error:]` & `+[RLMRealm schemaVersionAtPath:encryptionKey:error:]`
* `-[RLMRealm writeCopyToPath:error:]` & `-[RLMRealm writeCopyToPath:encryptionKey:error:]`

The versions without an encryption key are superfluous and the only role they serve is to have a less verbose API for users who don't have encrypted Realms.

I propose we deprecate the shorthand versions given how infrequently these methods are used.

**`schemaVersionAtPath` in Swift still uses an `NSErrorPointer`**

I think this was just missed in the Swift 2 transition when converting `NSErrorPointer` APIs to use `throws`.

I propose we update this function to use `throws` and to return a `UInt64` rather than an `Optional<UInt64>` because the only time it should return `nil` is when the file doesn't exist, which would throw anyway.

**Error handling duplication**

Both `transactionWithBlock:` and `commitWriteTransaction` have variants that support error handling. However, in many situations it's not practical to recover from these errors. Therefore, I propose keeping all these variants for now.

**Comment by mrackwitz** [comment]
>The versions without an encryption key are superfluous and the only role they serve is to have a less verbose API for users who don't have encrypted Realms.

I see potential for misunderstanding through the lack of the convenience short-hand methods. Novice users might feel forced to specify a value for the encryption key argument, even though it's explicitly declared as nullable. But I'm pretty sure we can help here with explaining that in the API doc comment.

**Comment by mrackwitz** [comment]
Beside the minor comment above, I agree with all conclusions drawn here from @jpsim. Well noted! :+1:

**Comment by TimOliver** [comment]
I was thinking the same thing as @mrackwitz. The methods without the `encryptionKey` are good to avoid confusion, but they definitely are superfluous. As long as we highlight clearly in our documentation that `encryptionKey` can be `nil`, that should be sufficient.

Apart from that, all good! :+1:

**Comment by tgoyne** [comment]
Using `nil` to signal "don't encrypt this" is more error-prone, especially in combination with obj-c's behavior of allowing messaging `nil`. It's not hard to imagine a bug where a user forgets to actually initialize their keychain manager object and doesn't notice that they're actually writing unencrypted files because everything appears to just work fine.

`schemaVersionAtPath` doesn't have the same issue, as if they accidentally pass `nil` they'll just fail to open the file.

**Comment by jpsim** [comment]
> Using nil to signal "don't encrypt this" is more error-prone, especially in combination with obj-c's behavior of allowing messaging nil. It's not hard to imagine a bug where a user forgets to actually initialize their keychain manager object and doesn't notice that they're actually writing unencrypted files because everything appears to just work fine.

That's an unlikely scenario I think. If that was the case, they'd get the same bug in `RLMRealmConfiguration` when opening that Realm that was written to with `writeCopyToPath:`, since that property is nullable by default too.

**Comment by bdash** [comment]
Given that the encryption key is already a nullable property `RLMRealmConfiguration`, I think it's fine to allow the encryption key argument to nullable on the two methods in question. I don't feel super strongly either way though.

**Comment by jpsim** [comment]
Thanks for the feedback all, unless you think we missed something big, I'll close this as done.

We can continue discussing the API changes from #3458 in that PR.
