### ISSUE TITLE
Create a SET from Existing Value.

### ISSUE THREAD

**Issue by Dfmarulanda** [realm/realm-cocoa#3269]
## Goals

Hello Everyone. I have some objects in my backend that i'm sending to my iOS App. The idea is just to add the new objects (not updating the existing ones) so, i created a SET with my online data, and i'm trying to compare it with my realm data. 

## Expected Results

I expect to substract the realm data from the online data in order to add the new data.

## Actual Results

Actual Data = 175 Objects.
Substract = 175 Objects
Union = 350 Objects

So, nothing is happening when i'm working with the sets. When i'm priting directly from 
```swift
realm.objects(Incident).toArray()
```
I get the expected print (With all my objects filled)
But when i make a array 

```swift
let x = realm.objects(Incident).toArray()
print(x)
```
I get all values as nil.

## Steps to Reproduce

create a SET from Array
```swift
   let a = Set(config.incidents)
   let b = realm.objects(Incident).toArray()
   let c = a.substract(b)
```

## Code Sample
console output for b
``` swift
  [174] = 0x00000001312a7140 {
    RealmSwift.Object = {...}
    idIncident = 0
    typeName = nil
    state = nil
    desc = nil
    date = nil
    reporter = nil
    incidentType = 0
    location = nil
    photoUrl = nil
    colorSticker = nil
  }
}
```

Note: When i iterate over b, i can access for each value.
```swift
// Incident Model
class Incident: Object, Mappable, Equatable, Hashable {
    
    dynamic var idIncident = 0
    dynamic var typeName: String?
    dynamic var state: String?
    dynamic var desc: String?
    dynamic var date: NSDate?
    dynamic var reporter: Citizen?
    dynamic var incidentType = 0
    dynamic var location: Location?
    dynamic var photoUrl: String?
    dynamic var colorSticker: String?
    
    
    
    override static func indexedProperties() -> [String] {
        return ["state"]
    }
    override static func primaryKey() -> String? {
        return "idIncident"
    }
    // MARK: JSON
    required convenience init?(_ map: Map) {
        self.init()
    }
    
   
    
    func mapping(map: Map) {
        idIncident <- map["id_incident"]
        typeName <- map["type_name"]
        state <- map["state"]
        desc <- map["desc"]
        date <- map["date"]
        reporter <- map["reporter"]
        incidentType <- map["incident_type"]
        location <- map["coord"]
        photoUrl <- map["photo_url"]
        colorSticker <- map["color_sticker"]
    }
    
   override var hashValue : Int {
        get {
            return idIncident.hashValue
        }
    }

}


func ==(lhs: Incident, rhs: Incident) -> Bool {
    return lhs.isEqual(rhs)
}
 
```
## Version of Realm and Tooling

Last version of Realm, iOS and XCode.

**Comment by mrackwitz** [comment]
Where is `toArray()` coming from. How do you convert there the retrieved `Results`?
Note that the LLDB output can be misleading, please make sure that you installed [LLDB plugin](https://github.com/realm/realm-cocoa/blob/master/plugin/rlm_lldb.py). But if you printed the object via `print` in Swift, you should definitively see correct values.

**Comment by jpsim** [comment]
`Set.subtract(_:)` takes a `SequenceType` (see [swiftdoc.org](http://swiftdoc.org/v2.1/type/Set/#func-subtract_)), so there's no need to convert a `Results` to an `Array` just to subtract its items.

I'd suggest that you check if `==` returns `true` for the values you'd expect to be equal. `Object.isEqual(_:)` will return `false` when comparing objects in different Realms or standalone objects with realm-backed objects.

See the following relevant source for Realm object equality:

* `Object.isEqual(_:)`: https://github.com/realm/realm-cocoa/blob/v0.98.4/RealmSwift-swift2.0/Object.swift#L242
* `RLMObjectBaseAreEqual()`: https://github.com/realm/realm-cocoa/blob/v0.98.4/Realm/RLMObjectBase.mm#L409-L433

If you want different equality semantics for your model, you'll need to implement it in `==` instead of forwarding to `Object.isEqual(_:)`.

**Comment by jpsim** [comment]
Closing since we never heard back from @Dfmarulanda. Hopefully my last answer sufficiently addressed the original comment.
