### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by cookeri6** [realm/realm-cocoa#3276]
## Goals

Trying to install Realm via cocoapods
## Actual Results

[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 0.92.4
Downloading core failed. Please try again once you have an Internet connection.

## Version of Realm and Tooling

pod 'Realm', '~> 0.95.0'
Using latest xcode and OSX

**Comment by osochill** [comment]
I'm getting the same thing, anyone?

**Comment by mrackwitz** [comment]
This might appear, if you have restrictions with your internet connection as described in #2713.
@cookeri6: But I see that you're trying to use a version from a while ago. Can you try installing instead the latest version of Realm, because we improved the error handling for the download of core since then, so that this would give us some hints what is really going wrong here.

**Comment by jpsim** [comment]
Closing this issue as this problem is well documented in #2713.
