### ISSUE TITLE
how to save the sorted result to List object?

### ISSUE THREAD

**Issue by hengchengfei** [realm/realm-cocoa#3304]
if save the sorted result to list object,got this error.

```swift
private var groups = List<CSFPortfGroupCache>()
```
<img width="1362" alt="2016-03-09 17 52 01" src="https://cloud.githubusercontent.com/assets/3182964/13631450/aa1c69f6-e61f-11e5-9faa-fd206aee4a3e.png">

```swift
public class CSFPortfGroupCache: Object {
    dynamic public var id:String?
    dynamic public var name:String?
}
```

**Comment by mrackwitz** [comment]
First of all, the list property in your models should be defined as a constant as seen in our docs. Assigning another list to an attached object's list property causes that this isn't attached anymore and so this assignment as any further modifications to the new value wouldn't be persisted anymore.

As the compiler already hints, `Results` can't be assigned to `List` typed variables, because it's from a different type and not a subtype.

You should use [`List.appendContentsOf(_:)`](https://realm.io/docs/swift/latest/api/Classes/List.html#/s:FC10RealmSwift4List16appendContentsOfu__Rdq_CS_6Objectqd__Ss12SequenceTypezq_qqqd__S2_9GeneratorSs13GeneratorType7Element_FGS0_q__Fqd__T_) instead.

**Comment by hengchengfei** [comment]
Thank you for your response.

I defined list variable at UIViewController.

```swift
class CSFPortfListController: UIViewController{
   private var groups = List<CSFPortfGroupCache>()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let realm = try! Realm()

        //this line can get all objects
        groups = realm.objects(CSFPortfGroupCache)

        //Error
        groups = realm.objects(CSFPortfGroupCache).sorted("order")
    }
}
```

**Comment by mrackwitz** [comment]
`List` is reserved for defining properties in your models. For querying the database, you have to use `Results` or alternatively the type-erasing wrapper `AnyRealmCollection`.

**Comment by hengchengfei** [comment]
`Results` don't support `removeAtIndex` or `insert(newElement: Element, atIndex:Int)` method similar to Array?

**Comment by mrackwitz** [comment]
That's right as you can't reorder objects stored in a Realm, you can just sort them temporarily when querying the Realm. If you want to store these query results on an object with a list property, you can achieve that with `appendContentsOf(_:)` as pointed out before. I think it would help, if you could explain what you want to achieve.
