### ISSUE TITLE
Initializing new object inside collectionView's itemForCellAtIndexPath takes too long (up to 100ms)

### ISSUE THREAD

**Issue by Tarpsvo** [realm/realm-cocoa#3312]
## Goals & expected results

Good performance when using RLMResults as datasource for collectionView.

Question is: how do I speed things up so that my UI doesn't hang for 1/10th of a second every time I add a new item into the displayed list?

## Actual Results

Initializing one cell takes up to 100ms when accessing a new instance of a Realm object for the first time.

## Code Sample

Message object has the following properties:
```
    dynamic var id = NSUUID().UUIDString
    dynamic var chatUserId = ""
    dynamic var messageId: String? = nil
    dynamic var directionRaw = "out"
    dynamic var message: String? = nil
    dynamic var mediaId: String? = nil
    let read = RealmOptional<Int64>()
    let received = RealmOptional<Int64>()
    dynamic var created: Int64 = 0
    dynamic var pending = false
```

DataSource for my collectionView is:
```
     let realm = try! Realm()
     self.messages = realm.objects(Message).filter("chatUserId = %@", chatUserId).sorted("created", ascending: false)
```

Place that takes 90ms is:
```
override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
    let cell = collectionView.dequeueReusableCellWithReuseIdentifier("MessageViewCell", forIndexPath: indexPath) as! MessageViewCell
    let message = messages![indexPath.row] // 90ms!!!
    cell.messageTextLabel.text = message.message!
    return cell
}
```

## Version of Realm and Tooling

Realm 0.98.3

**Comment by jpsim** [comment]
It appears you cross-posted this question from StackOverflow. In the future, please just post once: Realm engineers monitor both StackOverflow and GitHub, so we'll find your question no matter where you post it.

I'll repost my answer from StackOverflow so that others who land here have all the context:

---

Your question leaves out a number of important details in order to help you. The following are questions you should ask yourself when profiling Realm performance:

## 1. How many `Message` objects are in your database?

The more objects you have, the more Realm will need to search to perform the initial query. If you have 5 items when it takes 90ms to perform the initial query, that's quite slow and should be reported to the Realm team for more performance analysis. If you have a million items in your database, then 90ms is pretty good! Odds are that your data set lives somewhere in the middle there.

## 2. Is your `Message.chatUserId` property indexed?

Realm (like most databases) has the ability to mark a property type as *indexed*, which will slow down writes but accelerate certain kinds of queries, such as queries for equality. If these kinds of queries are performance-critical in your app, you should consider indexing them. Be sure to profile the impact of this in your app on a real device though to truly assess if it's the right move for you!

You can learn more about indexing in Realm here: https://realm.io/docs/swift/latest/#indexed-properties

## 3. What device & build configuration is this benchmark run on?

Realm's performance can easily be affected by running in debug or release mode. Debug mode has better debugging information while release mode is faster but has fewer checks. Whenever running benchmarks or profiling for performance, you should run your app on a real iOS device with your app built in Release mode.

How much pressure the device is under will also impact performance. For example, disk I/O memory and contention, CPU usage, number of threads access a Realm file, etc.

---

After all this, if you still believe Realm's performance in this situation to be unreasonable, I encourage you to file an issue on Realm's GitHub repository along with a benchmark sample project that reproduces this poor behavior: https://github.com/realm/realm-cocoa/issues/new

Also, Realm has mechanisms in place to efficiently keep queries live and always up to date (see docs on [Auto-Updating Results](https://realm.io/docs/swift/latest/#auto-updating-results)) so subsequent accesses of the results should be faster than the initial one.

**Comment by Tarpsvo** [comment]
Hello jpsim.

Sorry for cross-posting the issue. I hastily posted it on Github and then realized 'wait a second, this is not an issue. I should've put it on StackOverflow.' And then I did both. I'll not do that again, sorry.

About the issue at hand:
#### 1. `Message` object count
The issue happens even when I have even 1 message in the database.

The context is simple: I have a messenger app. It contains a textfield and a button to send messages. When I write a lot of messages continuously, the UI thread is noticeably overloaded and will start queuing input actions (if tap on the screen rapidly for two seconds, the actions runs for more than 3 seconds). I managed to trace the time consumer down to the Realm `Message` object initialization call. If I manage to send 10 messages in 2 seconds, that means the UI thread has already spent 900ms in just initializing the Realm objects.

#### 2. Is `Message.chatUserId` property indexed?
No. I will do it and check the results immediately. I do imagine that will help to some extent. I'm sorry I overlooked something that simple.

#### 3. What device & build configuration is this benchmark run on?
I test the application on an iPod Touch 6 and build the application in debug mode.

Thank you for your thorough answer. I will try all of your suggestions and then reply back. I will probably be able to answer on monday though, as I am currently away from my Mac and unable to test the changes.

Thanks again. Have a nice weekend.

**Comment by Tarpsvo** [comment]
Alright, yesterday managed to fix the UI freezing issue. Apparently, my observe blocks, attached to Message object, were too complicated and caused the lag which I experienced. I found out about it after digging deep into the profiling traces.

I still experience some scenarios where Message object initialization takes more than 100ms, but it doesn't noticeably freeze the UI thread anymore.

Basically, the issue was caused by my stupidity not Realm being slow. Thanks again for your help.
