### ISSUE TITLE
List / Results Empty

### ISSUE THREAD

**Issue by georgepoenaru** [realm/realm-cocoa#3314]
> Please fill out this template when filing an issue.
> All lines marked as quotes (`>`) instruct you with
> what info we expect.
> Remove this opening paragraph.

## Goals

Get a non empty list of objects: List<Messages>

## Expected Results

return a non empty list

## Actual Results

Objects and stored fine in database. I can se them with Realm Browser

my Chat object contain a list of Messages: List<Message>

-- 1. I retrieve chat results: 

`datasource = Realm().objects(Chat.self).sorted("modifiedAt", ascending: false)`

-- 2. Now I get a chat from datasource: 

`chat = datasource["index"]`

Is successfully retrieved and is valid.

-- 3. Now I want all messages in chat:

' datasource = chat.messages.sorted("modifiedAt", ascending: false)'

But datasource.count is Zero
The sorting is fine. chat.messages.count is also Zero

But in Realm Browser I can see related messages objects corect.

## Steps to Reproduce

> Provide steps we can follow to reproduce this issue.

## Version of Realm and Tooling

Xcode 7.2.1
0.98.3

**Comment by jpsim** [comment]
Could you please send us your realm file so we can investigate this? You can email it to us privately to help@realm.io if you'd rather not post it here. Thanks!

**Comment by jpsim** [comment]
Thanks for sending your Realm file. It turns out that you haven't set any `messages` on your one `Chat` object. See the count of zero here:

![gh3314_browser](https://cloud.githubusercontent.com/assets/474794/13795331/6b68a88a-eabd-11e5-939a-fe3580e61e7d.png)

You can add a `Message` to your `Chat` object's `messages` property by calling `chat.messages.append(message)`. See the API reference for [`List.append()`](https://realm.io/docs/swift/latest/api/Classes/List.html#/s:FC10RealmSwift4List6appenduRdq_CS_6Object_FGS0_q__Fq_T_) for more details.

**Comment by georgepoenaru** [comment]
Thank you. 

The problem was that I have async overwriting the entire chat object so the messages property was also overwrited. At the breakpoint moment when I have visualised the realm db, the messages counter was correct, later was overwritten. 

Thank's again
