### ISSUE TITLE
Realm has stopped working

### ISSUE THREAD

**Issue by pjebs** [realm/realm-cocoa#3336]
Realm stopped working today. Perhaps it was after a pod update.

In app delegate:
` RLMRealm *realm = [RLMRealm defaultRealm];`
The app crashes straight after showing the splash screen.
I've deleted the app and tried again.
This was all done whilst device was connected to Xcode.

**Comment by pjebs** [comment]
![screen shot 2016-03-16 at 11 30 00 am](https://cloud.githubusercontent.com/assets/5377970/13798441/8f41cc2a-eb6a-11e5-86bf-30809214f64f.png)
![screen shot 2016-03-16 at 11 29 40 am](https://cloud.githubusercontent.com/assets/5377970/13798444/9279e5ee-eb6a-11e5-9eb8-371dd7d5dc72.png)

**Comment by bdash** [comment]
You're hitting #3321. This was fixed in v0.98.5, released yesterday afternoon. Please update to the latest version and report back.

In the future, please provide the information outlined in the GitHub issue template (also mentioned in the [Filing Issues](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#filing-issues) portion of our documentation on contributing) so that information so that we can tell which versions of Realm, iOS and Xcode you're using.
