### ISSUE TITLE
Getting the default values

### ISSUE THREAD

**Issue by OlegAnghelov** [realm/realm-cocoa#3441]
Environment:
Supported iOS7-9
Realm 0.98.1
Pods 0.39.0
Objective-C only

Hi!
Thanks for the great job you're doing guys :)

I am trying to achieve clean null handling.
As per documentation we implemented the `defaultPropertyValues` method.
But there is a catch.

Lets assume:
```
@implementation Dog
+ (NSDictionary *)defaultPropertyValues {

    return @{@"name" : @"dog1"};
}
@end
```
And lets have these test methods:
```
- (void)notNil {
    Dog *dog = [[Dog alloc] init];
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm addObject:dog];
    }];
    NSLog(@"%@", [Dog allObjects]);
}
```
The output of this code is going to be obvious:
```
RLMResults <0x7f963af65090> (
	[0] Dog {
		name = dog1;
	}
)
```

But then we do this:
```
- (void)isNil {
    Dog *dog = [[Dog alloc] init];
    dog.name = nil;
    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm addObject:dog];
    }];
    NSLog(@"%@", [Dog allObjects]);
}
```

And the output is this:
```
RLMResults <0x7fe5f962b7a0> (
	[0] Dog {
		name = (null);
	}
)
```

**Why does setting a nil value to a property cancels taking the default property value?**

In our previously production realm version, 0.94.x, it caused a lot of crashes just because of 
```
name = variable?: nil;
```
instead of
```
if (variable) {
 name = variable
}
```

**Comment by mrackwitz** [comment]
The properties of Realm objects are initialized to their default values at the time of the object initialization.
If the property `Dog.name` is nullable, `nil` is considered as much a legitimate value as any actual value, otherwise you wouldn't be able to add null values.
Note that `NSString` properties defined from Objective-C are nullable by default. If you don't want them to be nullable, you can enforce that by declaring them in the `requiredProperties`. For more info see also our docs and the [blog post](https://realm.io/news/realm-objc-swift-0.96.0/#objectivec) we did, when null support was introduced.
I hope that my answer helps, but please let me know if there are questions left.

**Comment by OlegAnghelov** [comment]
The question was more in the context of the time when null support wasn't there yet, but your answer did left me with no questions, so thanks for that!
