### ISSUE TITLE
Migration is required due to the following errors

### ISSUE THREAD

**Issue by i-phil** [realm/realm-cocoa#3452]
@interface Dog : RLMObject
@property NSString *name;
@property NSInteger age;
@end

@implementation Dog
// No need for implementation
@end

RLM_ARRAY_TYPE(Dog)

@interface Person : RLMObject<NSObject>
@property NSString      *name;
@property RLMArray<Dog> *dogs;
@end

@implementation Person

+(NSString *)primaryKey
{
    return @"name";
}
@end

[#error]

2016-04-19 16:36:54.290 Simple[42837:5525138] *** Terminating app due to uncaught exception 'RLMException', reason: 'Migration is required due to the following errors: 
- Property 'name' has been made a primary key.'

**Comment by jpsim** [comment]
This is happening because a previous version of your app opened a Realm file before `name` was made a primary key. You'll need to perform a migration to update the existing data in the Realm to reflect this new schema. You can learn more about migrations in the [Migrations section of our docs](https://realm.io/docs/objc/latest/#migrations).

**Comment by i-phil** [comment]
@jpsim  thank you
