### ISSUE TITLE
Running Playground Example with RealmSwift Scheme

### ISSUE THREAD

**Issue by benmorrow** [realm/realm-cocoa#3507]
## Goals

Run the GettingStarted.playground from RealmExamples

## Expected Results

The instructions say: "In the scheme selector choose RealmSwift > iPhone 6s"

## Actual Results

There is no RealmSwift in my scheme selector. Screenshot:

![screen shot 2016-04-30 at 12 19 47 pm](https://cloud.githubusercontent.com/assets/5604/14938080/e2755430-0ecd-11e6-9e7f-a182d7ed3aff.png)

## Steps to Reproduce

1. Open RealmExamples.xcworkspace. 
2. In the Project Navigator, open GettingStarted.playground. 
3. Try to follow the instructions there.

## Code Sample

N/A

## Version of Realm and Tooling

Mac OS X 10.11.4 15E65

Xcode 7.3 7D175

Realm 0.100.0

**Comment by jpsim** [comment]
Hi @benmorrow, the `RealmSwift` scheme should only show up in the source version of the examples (e.g. the contents of this git repository). It won't show up in the zip packages that you'd download from GitHub releases or https://realm.io.

It also shouldn't be necessary to select the scheme from the zip packages either, since the framework will already be built, in which case we should update the playground instructional comments to reflect that. I'm downloading the zip release now to confirm this is indeed the case, but on airport wifi, it might take me a few days... 😭

**Comment by benmorrow** [comment]
Hi @jpsim, that makes sense. You are correct that I downloaded the zip package from https://realm.io.

However, the playground doesn't locate the framework and produces an error. This is a screenshot:

![screen shot 2016-05-02 at 12 43 46 pm](https://cloud.githubusercontent.com/assets/5604/14965709/b3140aa0-1063-11e6-9b92-b4d9ebf21d20.png)

Hope your flight went well!

**Comment by jpsim** [comment]
Yes, I confirmed this is a problem with our packaging, now I have to figure out a way to integrate prebuilt frameworks with Xcode playgrounds...

**Comment by jb80016** [comment]
Still broken

**Comment by jpsim** [comment]
@jb80016 we're happy to help if you file a new issue, taking care to fill out the template.
