### ISSUE TITLE
Predicate on an Embedded RLMObject inside another RLMObject

### ISSUE THREAD

**Issue by Chris59160** [realm/realm-cocoa#3539]
Hello guys,

I have a problem I am not sure how to sort it out.

I have a RLMObject 'A' that has another RLMObject 'B' as property.
```
class A : RLMObject
{
      @property _name:NSString;
      @property _b:B;
}

class B : RLMObject
{
      @property _a_property:int;
}
```
I would like to filter the A objects I get from my Realm file on their embedded B object.

Basically, I would like to do something like:
```
_name = 'Whatever Name' AND (_b != nil or _b._a_property = "5")
```
It is similar to a joint in SQL.

It doesn't work, because obviously _b_a_property isn't the name of a property on A...but I was wondering if any one knows if there's a way to achieve that

I absolutely need a RLMResults, so no need to suggest to work with RLMArray. I tried putting the objects one by one in an RLMArray, do manually my filtering on B, then calling sortedResultsUsingProperty on it, but Realm raise an exception because this RLMArray cannot do 'sortedResultsUsingProperty' on an RLMArray not returned by Realm...

Any help appreciated :-)

I am using Realm 0.96.3

Thank you,

Christophe

**Comment by bdash** [comment]
I'd expect the predicate you wrote to work as-is. What problem are you having with it?

**Comment by Chris59160** [comment]
Realm says that  _b._a_property isn't a property of A object

**Comment by bdash** [comment]
The following is a complete code snippet that works with the predicate you've provided (with one minor tweak: you had an unnecessary set of double quotes around the number 5). It's quite possible there's an error in how your model is declared since what you provided isn't valid code for any of the languages we support. I had to change the model code you provided significantly to make it valid.

```swift
import RealmSwift

class A: Object {
    dynamic var _name: String = ""
    dynamic var _b: B?
}

class B: Object {
    dynamic var _a_property: Int = 0
}

let realm = try! Realm()
let results = realm.objects(A).filter("_name = 'Whatever Name' AND (_b != nil or _b._a_property = 5)")
print(results)
```

If you're still encountering problems, please share the exact model classes you're using and the code you're using to filter the results using a predicate.

**Comment by Chris59160** [comment]
Thanks bdash, no idea what I was doing wrong before, but I adapted to the realm property names and it works fine now...mystery, but it works fine and I was just doing something bad :/

Thanks for the help !!

**Comment by austinzheng** [comment]
Looks like you're good to go. If you run into any other problems please feel free to open a new ticket.
