### ISSUE TITLE
Make deleteRealmIfMigrationNeeded delete the file regardless of schema version changes

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-cocoa#3583]
It might not be obvious that even if `deleteRealmIfMigrationNeeded` is set to true, migrations are still executed if a higher schema version is specified. We should point out in the API docs, that the Realm file is just deleted if there are outstanding migrations beyond those which are specified with the configuration.

/c @kishikawakatsumi @icanzilb

**Comment by icanzilb** [comment]
Are you saying that the migration block will be executed and then the realm file will be deleted @mrackwitz ?

**Comment by mrackwitz** [comment]
No, that can't happen. If there is an outstanding migration, this *must* be sufficient. If the schema version matches, but the runtime schema has changes ahead, then the file will be deleted. If both matches, the file is opened successfully.

**Comment by icanzilb** [comment]
I'm still not 100% what that means ... is `deleteRealmIfMigrationNeeded ` only working if the schema version is same as last time? or something else?

**Comment by sxua** [comment]
Is there a way to get a notification or callback when realm file been recreated to populate all data from scratch?

**Comment by jugyo** [comment]
Do I still need to specify `migrationBlock` for the configuration even if `deleteRealmIfMigrationNeeded` is `true`?

**Comment by mrackwitz** [comment]
@sxua: You can achieve that from the next release by implementing the strategy on your own by handling the error returned/thrown on a schema mismatch. See [my answer here](https://github.com/realm/realm-cocoa/issues/3542#issuecomment-219453073) to a similar question.

**Comment by mrackwitz** [comment]
@icanzilb:

>I'm still not 100% what that means ... is `deleteRealmIfMigrationNeeded` only working if the schema version is same as last time? or something else? 

Yes. If you're bumping the schema version as well, you're indicating that you want to migrate your schema, which takes priority. The `deleteRealmIfMigrationNeeded` is just the last resort if the schema doesn't match. This makes it a nice flag to set for development to avoid writing [a bit of tedious boilerplate setup code](https://github.com/realm/realm-cocoa/issues/3542#issuecomment-219453073), once you understood that schemas are fixed and migrations would be needed once you deployed your app for the first time.

----

@jugyo: No a migration block is not needed. This is only needed if you specify a schema version and bumping the schema version indicates that you want to delete the file.

**Comment by icanzilb** [comment]
ok I see ... for me this is the most understandable way to explain what this setting does will be something along the lines "Deletes the existing Realm file if the schema number didn't change but the schema doesn't match. That setting makes sense mostly in development since the described situation is rarely to happen in production."

**Comment by jugyo** [comment]
@mrackwitz got it. thanks!

**Comment by jugyo** [comment]
@mrackwitz So no need to put `schemaVersion` anymore if delete realm for migration every time?

**Comment by mrackwitz** [comment]
@jugyo: Yes. While you would obviously loose data, so it might be not what you want to do, if you use your Realm database beyond caching and even then it might be worthwhile to migrate depending on your use case.

**Comment by jugyo** [comment]
@mrackwitz ok, thanks!

**Comment by jpsim** [comment]
We have a few options here:

1. Change the logic so that Realms are deleted *regardless* of the file's initial schema version, the configured schema version, or presence of a configured migration block.
2. Make it a programmer error to set either `schemaVersion` or `migrationBlock` to anything but their default values if `deleteRealmIfMigrationNeeded` is also set by throwing an exception.
3. Keep this behavior as-is but improve the documentation.

Thinking about this more, I'd suspect it'd be best to go with option 1.

**Comment by cmelchior** [comment]
Just to note that Java does the following:
`deleteRealmIfMigrationNeeded` takes precedence over a migration block. It is allowed to set both the boolean and a migration block, but `deleteRealmIfMigrationNeeded` will take precedence. We don't throw any exception if you set both a migration block and deleteRealmIfMigrationNeeded, although it would probably make sense as that prevents the ambiguity.

**Comment by icanzilb** [comment]
cons about nr. 2 - if you're working on a newer version of your app, you have comment out the migration block in order to enable `deleteRealmIfMigrationNeeded` - this will probably lead to a bunch of people not enabling again migration when they're finished with their code updates... 

If we get to choose in between the 3 proposed by @jpsim I'm leaning more towards nr. 3.

My personal preference would be to make `deleteRealmIfMigrationNeeded` kick-in ONLY when there's no change in the schema version. The benefit of this behavour would be that this will prevent the situation when anyone releases their app with the property set to true and then their users will loose their stored date because of the `deleteRealmIfMigrationNeeded`. (Assuming people will remember increasing their schema version each time releasing a new app version)

**Comment by cmelchior** [comment]
For what it is worth, we had zero reports on people forgetting to remove it again when going to production on the Java side (and we had that boolean for quite a while now). Anecdotal I know, but still.

**Comment by kishikawakatsumi** [comment]
My preference is 2. Because we cannot determine which is a mistake when both `migrationBlock` and `deleteRealmIfMigrationNeeded` are specified.

But more important thing is to align the behavior of Java, I think. So it should be 1. (I misunderstood the behavior of Java side is same as 3)

**Comment by tgoyne** [comment]
> if you're working on a newer version of your app, you have comment out the migration block in order to enable deleteRealmIfMigrationNeeded - this will probably lead to a bunch of people not enabling again migration when they're finished with their code updates...

You'd want to do something like the following, which makes that a non-problem:

    #if ENV_DEV
    config.deleteRealmIfMigrationNeeded = true;
    #else
    config.schemaVersion = ...;
    #endif

**Comment by mrackwitz** [comment]
I agree with what @tgoyne proposes, but we should document that in the guides and the API docs imho.

**Comment by jpsim** [comment]
After speaking with a few people on this, we determined to go with option 1: unconditionally delete the file if a migration is required. Rationale:

1. Simplest to reason about and document.
2. Closest to behavior to Realm Java.

I'll get started on implementing asap.
