### ISSUE TITLE
Realm.io Primary key property 'serverId' has duplicate values after migration.'

### ISSUE THREAD

**Issue by danpe** [realm/realm-cocoa#3585]
After upgrading to Realm `0.102` from `0.95.3` I added a migration to support the `optional`

        realmConfig.migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {
            [migration enumerateObjects: GKUser.className block:^(RLMObject *oldObject, RLMObject *newObject) {
                if (oldSchemaVersion < 6) {
                    NSLog(@"serverId: %@", oldObject[@"serverId"]);
                    newObject[@"userId"] = [oldObject[@"userId"] length] > 0 ? oldObject[@"userId"] : nil;
                    newObject[@"profilePic"] = [oldObject[@"profilePic"] length] > 0 ? oldObject[@"profilePic"] : nil;
                }
            }];
        };

I'm getting the following error:

    2016-05-12 17:27:16.342 MyApp[37326:2727222] *** Terminating app due to uncaught exception 'RLMException', reason: 'Primary key property 'serverId' has duplicate values after migration.'

As you see I'm also printing the `serverId` and in all those prints nothing is duplicate.

Link to SO: http://stackoverflow.com/questions/37197818/realm-io-primary-key-property-serverid-has-duplicate-values-after-migration

**Comment by austinzheng** [comment]
Hi @danpe,

Thanks for getting in touch. Would you be willing to share the old and new definitions of your `GKUser` model? Any other information you'd be willing to provide to help produce a reproduction case would be greatly appreciated!

**Comment by jpsim** [comment]
Hi @danpe, I'm just following up on @austinzheng's last request for information. Have you fully ruled out that there are no duplicate values from `serverId`? For example, if it's an optional property, keep in mind that `nil` is a valid value and it _must_ be unique since it's set as a primary key. Thanks!

**Comment by stel** [comment]
Closed due to inactivity.

**Comment by TaoistKing** [comment]
Same Problem here.
I just set my primary key as requiredProperties, then rerun my app, realm throws error:
> Primary key property 'RLMProfile.objectID' has duplicate values after migration

I did nothing in the migration block.
And all my primary keys are unique, non-nil.

**Comment by jpsim** [comment]
> I did nothing in the migration block. And all my primary keys are unique, non-nil.

Hmm, the exception message would indicate otherwise. Could you please file a new issue (this one's been closed for months) including all the `RLMProfile`s `objectID` values at the start of your migration block? Ideally with enough information for us to help you, if anything else is relevant? Thanks!
