### ISSUE TITLE
Feature Request: Create of update relationships by list of primary ids

### ISSUE THREAD

**Issue by startupthekid** [realm/realm-cocoa#3594]
In accordance with #2849 and the possibility of renaming primary to object id, I suggest a feature where one can update a relationship `List` object by passing an array of object ids.

Given the following simple schemas:

```swift
class Library: Object {
    dynamic var id = ""
    let books = List<Book>()    

    static func primaryId() -> String? {
        return "id"
    }
}

class Book: Object {
    dynamic var id = ""
    dynamic var name = ""
    dynamic var author = ""

    static func primaryId() -> String? {
        return "id"
    }
}

```

And given instances already persisted in a realm such as:

```
{
    "id": "1234",
    "books: [
         {
             "id": "1",
             "name": "Harry Potter"
             "author": "J.K. Rowling"
         },
         {
             "id": "2",
             "name": "Catch 22"
             "author": "Joseph Heller"
         } 
    ]
```

one should be able to update or create a library object with a list of object ids for books like:

```swift
    realm.create(Library.self, values: ["id": "4321", books: ["1", "2"]], update: true)
```

and realm can intelligently realize that for `Book` objects, it's being passed object ids, do a query for those object ids, and populate them if they exist, otherwise create a `Book` instance with the object id set.

This isn't without precedence either, I believe Mongoose/MongoDB does this, a really awesome feature, something it'd be great to see in Realm in the future.

**Comment by jpsim** [comment]
You can do this today in Realm by slightly modifying your creation/update code:

```swift
let books = ["1", "2"].map { realm.objectForPrimaryKey(Book.self, key: $0) }
realm.create(Library.self, values: ["id": "4321", "books": books], update: true)
```

Is it reasonable for you to use this approach?

I'm inclined to reject this proposal because once Realm supports arrays of primitives (#1120), we'll likely want to reserve the syntax you use for the `books` value to represent an array of strings.

**Comment by startupthekid** [comment]
It's reasonable but not ideal, at least in my situation. Right now at least, I have my persistence and network calls abstracted so that in order to update an object on the network and on disk, all I have to do is `Library.update(object, changes: someDictionaryValue)` so it'd be nice if both processes operated in the same way, not the most important thing ever but convenient. 

In regards to #1120, is there a reason they can't both be supported? I haven't delved into the source for Realm as much as I want to but would there be a way to check if the value being updated is of type `List` and the value provided isn't a json object, then do an intelligent search?

**Comment by jpsim** [comment]
> would there be a way to check if the value being updated is of type `List` and the value provided isn't a json object, then do an intelligent search?

sure, but the more flexibility of this kind we expose, the more overhead we add to object creation.

**Comment by startupthekid** [comment]
Hmm that's true and I do like how fast Realm is...it'd be a nice feature to have but nothing that anyone can't implement themselves. I'll close the issue in that case.

**Comment by movsar** [comment]
Hey there, is there anyone working on this feature? The given answer is not really a solution, to make it sustainable I need to always keep an instance of realm throughout my app just about everywhere, when using repository pattern with models and interfaces you don't want to pass around a realm instance because like in my app, you simply might need to use different databases.... anyways, I would be super happy if you added this, I know the topic is from 2016, yet the issue is the same.

**Comment by bmunkholm** [comment]
@movsar Please create a new issue in realm-dotnet. Thanks!
