### ISSUE TITLE
ld: framework not found RealmSwift for architecture i386 after upgrade CocoaPods 1.0.0

### ISSUE THREAD

**Issue by nixzhu** [realm/realm-cocoa#3609]
Install RealmSwift via CocoaPods 1.0.0, when build for simulator gets this error:

`ld: framework not found RealmSwift for architecture i386`

I have try clear DerivedData &`rm -rf ~/Library/Caches/CocoaPods/; rm -rf Pods/; pod update` to reinstall pods, but not work.

## Version of Realm and Tooling

Realm version: ?
0.102.1

Xcode version: ?
7.3.1

iOS/OSX version: ?
iOS 9.3 Simulator

**Comment by nixzhu** [comment]
In Unit Test Target, I @testable import main target (In main target, of corse, import RealmSwift).
It work in CocoaPods 0.39.0, but not work in CocoaPods 1.0.0, here is my Podile:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def pods
    pod 'Kanna', '1.0.2'
    pod 'Navi'
    pod 'Appsee'
    pod 'Alamofire'
    pod 'DeviceGuru'
    pod '1PasswordExtension'
    pod 'KeyboardMan'
    pod 'Ruler'
    pod 'Proposer'
    pod 'FXBlurView'
    pod 'Kingfisher'
    pod 'TPKeyboardAvoiding'
    pod 'pop'
    pod 'Base64'
    pod 'SocketRocket'
    pod 'RealmSwift'
    pod 'MonkeyKing', '0.0.2'
    pod 'JPush'
    pod 'Fabric'
end

target 'Yep' do
    pods
end
```

You can find whole project at https://github.com/CatchChat/Yep (develop branch).

**Comment by arden** [comment]
the same errors to me.

**Comment by jpsim** [comment]
Because `@testable` will re-expose your imported module's internal declarations, you'll need to link any external module that's referenced in those internal APIs.

This isn't a Realm issue, or CocoaPods one for that matter, but rather `@testable` working as intended.

To make your tests compile again with CocoaPods 1.0, you'll need to link any pod referenced in the `Yep` module's internal APIs to your unit test target. Just add this to your Podfile:

```ruby
target 'YepTests' do
    pods
end
```

It's possible that CocoaPods prior to 1.0 linked app target pods to test targets implicitly, which is why you're only seeing this now with CocoaPods 1.0, but if that's the case, I'd consider this new behavior to be more correct.

**Comment by nixzhu** [comment]
@jpsim After add unit test target in my Podfile, build successful. Thank you!
