### ISSUE TITLE
dyld: Symbol not found: with update from 0.100 to 0.103.2

### ISSUE THREAD

**Issue by KenziTrader** [realm/realm-cocoa#3648]
## Goals

Update RealmSwift with CocaoPods from version 0.100 to 0.103.2

## Expected Results

On a clean simulator I expect my App to run normally as with version 0.100.

## Actual Results

crash on startup

dyld: Symbol not found: __TFC10RealmSwift6Object14linkingObjectsuRxS0_rfTMx11forPropertySS_GSax_

## Steps to Reproduce

- Update to version 0.103.2 with "pod update"
- Xcode menu Product / Clean
- Product / Run

## Code Sample

Crashes at startup before any of my code runs.

## Version of Realm and Tooling

Realm version: 0.103.2

Xcode version: 7.3.1 Build version 7D1014

OSX version: OS X 10.11.5 15F34

iOS version: Version 9.3 SimulatorApp-645.9

Dependency manager + version: CocaoPods 1.0.0

**Comment by jpsim** [comment]
Could you please try deleting derived data and cleaning the build folder in Xcode? You're likely getting this error because Xcode thinks its build cache is valid when in fact it isn't.

To clean the build folder, hold down the ‘Option’ key while opening the ‘Product’ menu, then choose ‘Clean Build Folder…’. You can also type “Clean” into the Xcode help search menu and select the ‘Clean Build Folder…’ menu item when it shows up in the search results.

**Comment by KenziTrader** [comment]
I deleted the DerivedData directory and cleaned the build folder but it didn't help.

Also I tried to remove the RealSwift dependency from my podfile, did "pod update". Then added RealmSwift back in and did "pod install". The problem remains.

Do you have any other suggestion?

**Comment by jpsim** [comment]
Try this:

```
pod cache clean Realm
pod cache clean RealmSwift
pod deintegrate
rm -rf Pods
pod install --verbose
```

**Comment by KenziTrader** [comment]
I found the problem. I still had an old FRAMEWORK_SEARCH_PATHS in Build Settings which pointed to an old Realm version before I switched to CocaoPods. After I deleted this setting I still had to delete the DerivedData directory and clean the build folder before it worked.

Thanks for your help.

**Comment by jpsim** [comment]
Glad to hear you resolved this!
