### ISSUE TITLE
About RLMLinkingObjects

### ISSUE THREAD

**Issue by huogh** [realm/realm-cocoa#3670]
One Blog can has many Comment, and one Comment can only belongs to one Blog. The model definition as:

```objc
@interface Comment : RLMObject
@property (readonly) RLMLinkingObjects *blog;
@property NSString *message;
@end

@implementation Comment
+ (NSDictionary *)linkingObjectsProperties {
    return @{
        @"blog": [RLMPropertyDescriptor descriptorWithClass:Blog.class propertyName:@"comments"],
    };
}
@end
RLM_ARRAY_TYPE(Comment)

@interface Blog : RLMObject
@property RLMArray<Comment> *comments;
@end

@implementation Blog
@end
```

My question is:how can i access via comment? Like comment.blog?

**Comment by mrackwitz** [comment]
What do you want to access exactly in what way? If you want to access the `Blog` object, you can achieve that as proposed by `comment.blog`.

**Comment by smolskyaleksey** [comment]
I have the same question and I can not use properties of Blog class, because comment.blog return RLMLinkingObjects

**Comment by mrackwitz** [comment]
`RLMLinkingObjects` gives access to one or more backlinking objects in a very similar fashion to `RLMResults`. Even if you expect that there is always just a single instance, this can't be expressed. You would need to go over `comment.blog.firstObject` to access the properties of the `Blog`.
I'd furthermore recommend to declare the generic type parameter in the interface:
```objc
@property (readonly) RLMLinkingObjects<Blog *> *blog;
```

**Comment by smolskyaleksey** [comment]
Also i found solution in this issue
https://github.com/realm/realm-cocoa/issues/3533

**Comment by smolskyaleksey** [comment]
if I use @property (readonly) RLMLinkingObjects<Blog *> *blog; 
I get error:
 "Type argument 'Blog *' does not satisfy the bound ('RLMObject *') of type parameter 'RLMObjectType'"

**Comment by kishikawakatsumi** [comment]
@smolskyaleksey 

This is due to limitation for Objective-C compiler. The generic constraints for RLMArray need their elements should be a subclass of RLMObject. But Objective-C compiler cannot recognize it from `@class` forwarded declaration.

To resolve this, I think the only way is to declare both @interface in the same file, then declare their properties using Class Extension. Like the following:

```objc
@interface Blog : RLMObject
@end

@interface Comment : RLMObject
@end

RLM_ARRAY_TYPE(Comment)

@interface Comment()
@property (readonly) RLMLinkingObjects<Blog *> *blog;
@property NSString *message;
@end

@implementation Comment
+ (NSDictionary *)linkingObjectsProperties {
    return @{ @"blog": [RLMPropertyDescriptor descriptorWithClass:Blog.class propertyName:@"comments"] };
}
@end

@interface Blog()
@property RLMArray<Comment> *comments;
@end

@implementation Blog
@end
```

See also http://stackoverflow.com/questions/36966858/rlmlinkingobjects-circular-dependency/36987537#36987537

**Comment by mrackwitz** [comment]
Closing this assuming it was answered. If there are still troubles with that, please let us know.

**Comment by hk** [comment]
@kishikawakatsumi I have the same issue and have multiple models that depend on each other.  Would it be wise to fit all models into 1 file using the method above? I have say 4 different models in different files but need to be able to have many-to-many between a few of them without getting this issue, so should I just fit all of their declarations in one file?

**Comment by jpsim** [comment]
Reopening this since @hk is still having issues with this according to [this tweet](https://twitter.com/henryk/status/744964874594312196).

So to answer your question, yes the classes need to be declared prior to being able to use them as `RLMLinkingObjects` properties to satisfy the Objective-C compiler.

You can do this a number of different ways, as @kishikawakatsumi mentioned above.

You could also have all your models declared in separate files without their linking objects properties, and then in a separate file have class extensions that import the necessary models and expose the linking objects properties from there.

If these solutions don't work for you, please share your models and we'll help you refactor them for all this to work.

**Comment by hk** [comment]
@jpsim you guys are awesome, thanks for following up.  So I decided to go the route of having separate model files and not linking object properties while in a separate file importing the models and then linking relationships, however I get a runtime error of "unrecognized selector sent to instance" when trying to access a relationship.  Below is an example of some of the classes:

So there's a User model (User.h) that looks like this:

```
@interface User : RLMObject
@property NSString *first;
@property NSString *last;
@property NSString *picture;
@property NSNumber<RLMInt> *userId;
@property NSString *phone;
@property NSNumber<RLMInt> *rank;
@property NSString *color;
@property NSNumber<RLMBool> *isUser;

@end
RLM_ARRAY_TYPE(User)
```
A current user model that inherits the User model

```
@interface CurrentUser : User

@end
RLM_ARRAY_TYPE(CurrentUser)
```
And then there is a Relationships.h file that, as I said above, links all the relationships between the above models and the rest of them in the application:

```
#import <Realm/Realm.h>
#import <UIKit/UIKit.h>
#import "Chat.h"
#import "CurrentUser.h"
#import "Invite.h"
#import "List.h"

@interface User()
@property RLMArray<List *><List> *lists;
@end

@interface List()
@property RLMArray<User *><User> *users;
@property RLMArray<User *><User> *admins;
@end

@interface Invite()
@property RLMArray<Chat *><Chat> *chatMessages;
@property RLMArray<User *><User> *usersInvited;
@property RLMArray<User *><User> *usersAttending;
@property User *user;
@end

@interface Chat()
@property User *user;
@end

@interface CurrentUser()
@property RLMArray<Invite *><Invite> *feed;
@property RLMArray<Invite *><Invite> *hiddenInvites;
@property RLMArray<User *><User> *friends;
@end
```

Everything compiles properly when I import the Relationships.h file (without it I get errors that the properties don't exist) however when I run it and call currentUser.feed for example it throws an error saying "unrecognized selector sent to instance".  Is there something else I need to do for the class extensions in Relatioships.h to work?

**Comment by hk** [comment]
So I included Relationships.h in each model's implementation (.m) files, but now I get an error on build with the following: 

"- Property 'users' declared as origin of linking objects property 'lists' does not link to class 'CurrentUser'." UserInfo={NSLocalizedDescription=Schema validation failed due to the following errors:"

It's driving me mental trying to figure this out now

**Comment by jpsim** [comment]
@hk what that last exception message means is that you have code like this:

```objc
+ (NSDictionary *)linkingObjectsProperties {
    return @{
        @"lists": [RLMPropertyDescriptor descriptorWithClass:CurrentUser.class propertyName:@"users"],
    };
}
```

but `CurrentUser.users` either doesn't exist or doesn't point to the object on which you've defined this inverse relationship. Instead of just sharing headers for your objects, can you also share the relevant implementations, notably the class methods that further define your models (e.g. `linkingObjectsProperties`, `ignoredProperties`, `primaryKey`, `indexedProperties`, etc.).

**Comment by jpsim** [comment]
@hk I hope my last comment was helpful. I'll be closing this since we haven't heard back from you in a little while, but let us know if there's anything more we can do to help!
