### ISSUE TITLE
wrong value when accessing property directly

### ISSUE THREAD

**Issue by baydet** [realm/realm-cocoa#3689]
I have model like that 
```
class A: Object {
...
var date: NSDate = NSDate()
...
}
```

In the app I'm creating object A(), setting some value to date property (01-01-2000 for example) and adding this object to Realm. 
When I'm fetching this object from Realm I different values when accessing property date:
- when I call a.valueForKey("date") I'm receiving correct date (01-01-2000)
- when I'm accessing this property through calling a.date, I'm getting NSDate() object (current time at the moment of the call)

Could you explain this behaviour?

```
realm-cocoa version 
v1.0.0

ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A279b

/Applications/Xcode.app/Contents/Developer
Xcode 7.3
Build version 7D175

/usr/local/bin/pod
0.39.0
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.16.2
github "realm/realm-cocoa" "v1.0.0"

/usr/bin/git
git version 2.6.4 (Apple Git-63)

```

**Comment by kishikawakatsumi** [comment]
@baydet Because you did not declare `date` property as `dynamic`. 

The String, Double and Object properties of your Object subclasses need to be declared with the dynamic modifier to allow Realm to override the getter and setter of the property. Without this the Swift compiler will access the object's instance variable directly, which doesn't provide any opportunity for Realm to read or write data from the Realm file. See [Realm's model property cheatsheet](https://realm.io/docs/swift/latest/#cheatsheet) for a quick overview of how to declare properties of each of the supported types.

**Comment by baydet** [comment]
Oh, thank you. That was my problem
