### ISSUE TITLE
Support Swift 2.3 in Xcode 8 beta 1

### ISSUE THREAD

**Issue by svenbacia** [realm/realm-cocoa#3749]
## Goals
Use Realm with Xcode 8 and Swift 2.3

## Actual Results
When using the current version I get the error message that the module was built with an old compiler.

When I try to build a new version of the framework with Xcode 8 I get the following error message:
`error: Swift 2.3 is not supported.`

## Steps to Reproduce
- Clone the repository
- set the selected Xcode version to Xcode 8 (`xcode-select -s <path-to-xcode-8>`)
- set the swift version to legacy in Xcode 8 for the realm project
- run `sh build.sh ios-swift`

## Version of Realm and Tooling
Realm version: 1.0.1
Xcode version: 8.0
iOS/OSX version: iOS 10.0 / MacOS 10.11.5
Dependency manager + version:  Carthage 0.16.2

**Comment by jpsim** [comment]
We're working around a bug in the Xcode 8 beta (https://twitter.com/jckarter/status/742815062377693184) that prevents us from doing this. The workaround mentioned in that tweet is something that you can do in your local check out of Realm, but we can't merge that in here because it would adversely affect everyone else.

**Comment by marchy** [comment]
Any update on Swift 2.3 support?
