### ISSUE TITLE
How to consistently test crashes in Realm migration before release?

### ISSUE THREAD

**Issue by Voley** [realm/realm-cocoa#3777]
## Goals

What do you want to achieve?

App that doesnt crash every time update is rolled out.

## Expected Results

What did you expected to happen?

That app does not crash before/after migration. We had the same issue with 0.97 and now with 0.101

## Actual Results

I can't even cite the crash report because it does not reproduce when I migrate on my devices, it works fine. And Hockeyapp does not even init before Realm crashes the app, so I don't see any crash logs.
But the users say that app crashes right after update.

How do I catch this issue reliably before the app hits the store?

## Steps to Reproduce

What are steps we can follow to reproduce this issue?
Have an app with Realm 0.101.0, update app, migrate database, crash.

## Code Sample

Here is the migration code:

```
- (void)migrateDatabase {
    
    // App Versions and database versions
    // 1.0 -> 0
    // 1.0.1 -> 1
    // 1.0.2 -> 2
    // 1.0.4 -> 3
    
    RLMRealmConfiguration *config = [RLMRealmConfiguration defaultConfiguration];
    config.schemaVersion = 3;
    config.migrationBlock = ^(RLMMigration *migration, uint64_t oldSchemaVersion) {
        if (oldSchemaVersion < 2) {
            
            [migration enumerateObjects:EZHProfile.className
                  block:^(RLMObject *oldObject, RLMObject *newObject) {
                      // Add the 'enhancementNotifications' property only to Realms with a schema version of 2
                      if (oldSchemaVersion < 2) {
                          newObject[@"enhancementNotifications"] = nil;
                      }
                  }];
        }
        
        if (oldSchemaVersion < 3) {
            [migration enumerateObjects:EZHouse.className block:^(RLMObject * _Nullable oldObject, RLMObject * _Nullable newObject) {
                newObject[@"houseProfile"] = nil;
            }];
            [migration enumerateObjects:EZHContract.className block:^(RLMObject * _Nullable oldObject, RLMObject * _Nullable newObject) {
                newObject[@"addons"] = nil;
            }];
        }
    };
    
    // Tell Realm to use this new configuration object for the default Realm
    [RLMRealmConfiguration setDefaultConfiguration:config];
    
    // Now that we've told Realm how to handle the schema change, opening the file
    // will automatically perform the migration
    [RLMRealm defaultRealm];
}
```

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 0.101

Xcode version: 7.3

iOS/OSX version: 9.3

Dependency manager + version: Cocoapods 0.99

**Comment by jpsim** [comment]
Hi @Voley, the reason Realm is throwing an exception in this case is to indicate that you're missing something in your migration block. Much like Foundation and other Cocoa frameworks, Realm only ever throws runtime exceptions when being used in a way that's not supported.

It would greatly help if you could share the exception message being logged, as that message should tell you what to do to avoid this situation. And help us help you avoid this.

To specifically answer your question:

> How do I catch this issue reliably before the app hits the store?

First, make sure you've read and understand our documentation on [Migrations](https://realm.io/docs/objc/latest/#migrations). Following the rules there will help you avoid these situations.

Another important thing to do is to test your migrations. I recommend that you have a test for migrating each schema version you've shipped with your app to the latest version at all times. This will give you the peace of mind of making sure you're covering as many use cases in testing rather than in production.

Let me know if any of this helps, I'm happy to answer any further questions you may have.

**Comment by Voley** [comment]
Ok this helped, after more investigation I found that one field did not migrate, and it was pretty complicated to fill it, which was not done in test cases.
Thanks

**Comment by jpsim** [comment]
Glad to see you worked this out, @Voley! Don't hesitate to file issues again in the future if you bump into any difficulties!
