### ISSUE TITLE
crash when declare RLMArray on rlmobject subclass

### ISSUE THREAD

**Issue by qylibohao** [realm/realm-cocoa#3794]
```objc
@interface FriendRealmItem : RLMObject

@property NSString* name;

@end
// This protocol enables typed collections. i.e.:
// RLMArray< FriendRealmItem >
RLM_ARRAY_TYPE(FriendRealmItem)
```
---
```objc
@interface RoleRealmItem : RLMObject

@property NSString* name;

@property RLMArray< FriendRealmItem > * friendsItemArray;

@end

// This protocol enables typed collections. i.e.:
// RLMArray<RoleRealmItem>
RLM_ARRAY_TYPE(RoleRealmItem)
```

it crash when i declare "@property RLMArray < FriendRealmItem > *  friendsItemArray;"

the log is : 
```
NSScanner: nil string argument
libc++abi.dylib: terminate_handler unexpectedly threw an exception
```

**Comment by JadenGeller** [comment]
The code you've given seems to work, so the problem must be elsewhere. Can you provide more context?

**Comment by JadenGeller** [comment]
If you could provide more context, I'd love to help you, @qylibohao! 🙂

**Comment by JadenGeller** [comment]
Since I haven't heard back, I'm going to assume that @qylibohao resolved this issue. If this isn't the case, feel free to reopen, and I'd love to help!

**Comment by qylibohao** [comment]
this is  the screen shot when i call the "allobjects" method .
![20160706-0](https://cloud.githubusercontent.com/assets/5283516/16609676/7ac4a012-4388-11e6-80e3-e2bfc1cb07ff.png)



![20160706-0](https://cloud.githubusercontent.com/assets/5283516/16609659/600379ce-4388-11e6-9fe6-ca425d349a6f.png)

**Comment by qylibohao** [comment]
@JadenGeller

**Comment by bdash** [comment]
The screenshots indicate an exception is being thrown due to an error in how one of your model classes is declared. If you continue from the exception breakpoint then the exception message will likely be logged to Xcode's console. That will include an informative message that tells you what's wrong with your model class declaration. From the screenshot it appears to be related to a property of type `RLMLinkingObjects`. If you need assistance in interpreting the error message, please share it along with the model classes in question and we'll be happy to help.

**Comment by qylibohao** [comment]
@bdash thank you ,i already solved the problem.it's the wrong way i declare linkingobjects,
