### ISSUE TITLE
Allow write notifications that don't trigger collection notifications

### ISSUE THREAD

**Issue by emuye** [realm/realm-cocoa#3807]
## Feature Request

I'm using realm Collection Notifications to keep a UITableView in sync with a particular query. I've been trying to build out a feature that let's the user delete an item from the table. In this case I'd like to be able to show the delete and updated state of the UI without waiting for the asynchronous collection notification. 

I often see delays between a write and the corresponding collection notification that make waiting on the notification a pretty bad experience. Given that the collection notifications are aggregated, ignoring specific updates is a challenge. As far as I can tell there is no way to modify the tableview directly (and then propagate the change to realm) while using collection notifications.

**Comment by jpsim** [comment]
Hi @emuye, thanks for filing this. We agree that we need to expose a mechanism through which write transactions may be performed without triggering collection change notifications and are tracking that as #3665.

When making changes to data due to user interactions (e.g. main UI thread), you should certainly make those synchronously to keep things flowing at 60fps. Notifications are delivered asynchronously.

I'm closing this ticket as a duplicate and would encourage you to continue this conversation in #3665 so we can keep the discussion in one place. Thanks!
