### ISSUE TITLE
Incorrect Thread

### ISSUE THREAD

**Issue by chashmeetsingh** [realm/realm-cocoa#3810]
## Goals

What do you want to achieve?
Want to load data from db into an array of realm objects

## Expected Results

What did you expected to happen?
It should load fine in an dispatch_queue
## Actual Results

What did happened instead?  
libc++abi.dylib: terminating with uncaught exception of type realm::IncorrectThreadException: Realm accessed from incorrect thread.

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

`
          dispatch_async(dispatch_queue_create("background", nil)) {
              let realm = try! Realm()
             let allShows = realm.objects(Show.self)
            for show in allShows {
                self.shows.append(show)
            }
            self.collectionView.reloadData()
        }
`

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?
1.0.1
Xcode version: ?
7.3.1
iOS/OSX version: ?
iOS 9.3
Dependency manager + version: ?

**Comment by jpsim** [comment]
Realm objects are confined to the thread on which they were created or retrieved.

This constraint is in place to preserve the isolation of your object graph between versions.

In your case, you're likely accessing Realm objects from `self.shows` on your main thread (judging from your call to `collectionView.reloadData()`), even though they were retrieved on a background thread.

If you want Realm objects from a query (in this case `realm.objects(Show.self)` to be retrieved and kept up to date in the background, you can simply use [`Results.addNotificationBlock()`](https://realm.io/docs/swift/latest/api/Classes/Results.html#/s:FC10RealmSwift7Results20addNotificationBlockFFGOS_21RealmCollectionChangeGS0_x__T_CSo20RLMNotificationToken), which will asynchronously load and maintain the Results, as long as you don't access one of its elements until the `.Initial` notification is delivered. You should always prefer using Realm collections like `Results` and `List` rather than copying objects into a standard library container like `Array`.

For more information on Realm and threading, see our docs on [Threading](https://realm.io/docs/swift/latest/#threading).

For more information on asynchronous Results, see our docs on [Auto-Updating Results](https://realm.io/docs/swift/latest/#auto-updating-results).

**Comment by chashmeetsingh** [comment]
hey @jpsim thanks for replying
I changed the code to this 
```
        let realm = try! Realm()

        shows = realm.objects(Show.self)

        self.collectionView.reloadData()
```
shows being Results<Show> but isn't that synchronous? I want to implement asynchronous task here
Please can u help (new here) thanks !

**Comment by jpsim** [comment]
Yes, that's synchronous, but `addNotificationBlock(_:)` will load the results asynchronously. Take a look at our [`TableView`](https://github.com/realm/realm-cocoa/blob/master/examples/ios/swift-2.2/TableView/TableViewController.swift) example to see this in action.

**Comment by chashmeetsingh** [comment]
<img width="1090" alt="screen shot 2016-06-30 at 8 05 11 pm" src="https://cloud.githubusercontent.com/assets/8962264/16492065/010479b6-3efe-11e6-8e3c-34a03b75e756.png">

**Comment by chashmeetsingh** [comment]
also isn't that too synchronous as we are storing the objects in results directly
@jpsim

**Comment by jpsim** [comment]
@chashmeetsingh obviously you'll need to add a `notificationToken` property on your view controller if you're trying to assign to one.

> also isn't that too synchronous as we are storing the objects in results directly

Have you read the documentation links from my previous comment (https://github.com/realm/realm-cocoa/issues/3810#issuecomment-229661795)?

**Comment by chashmeetsingh** [comment]
ahh ok thanks for that missed the docs part 
@jpsim

**Comment by chashmeetsingh** [comment]
@jpsim how do I verify if its asynchronously

**Comment by jpsim** [comment]
Xcode ships with a tool called Instruments which is quite useful to see what threads are up to.

Or crudely:

```swift
print("1")
self.notificationToken = results.addNotificationBlock { _ in
  print("3")
}
print("2")
```

**Comment by chashmeetsingh** [comment]
awesome thanks for the great help 👍
