### ISSUE TITLE
Database size doesn't change after the insert ?!

### ISSUE THREAD

**Issue by Tom29** [realm/realm-cocoa#3824]
I've added some records to the database, i can see all of them in the realm browser. But don't see the db size has changed even a single byte ?!

I need to know the filesize change to synchronize to the iCloud.

**Comment by bdash** [comment]
The file size of a Realm does not correspond directly to the amount of data stored within it. Depending on the amount of data you're adding in a given write transaction the file may grow one or more times, or not at all. I'd suggest using a more direct mechanism for detecting when changes have occurred, such as [Realm notifications](https://realm.io/docs/swift/latest/#realm-notifications).

**Comment by Tom29** [comment]
@bdash Thanks for your reply. But by doing this way, i have to keep persist connection with the database? And it can't tell which one has bigger data number. I need to compare db size from local and iCloud to select the version has more records.

**Comment by bdash** [comment]
If you need to know the number of objects contained within a Realm, then yes, you'll need to open the Realm and query it for that information. It's not something that can be inferred from the file size.

If you can provide more information about what it is you're trying to do we may be able to suggest a different approach that would better suit your needs.

**Comment by TimOliver** [comment]
Hi @Tom29! Just checking to see if this issue is still in progress. :)

Like @bdash was saying, there's no way to accurately determine the number of objects in a remote Realm file. But that being said, it would be entirely appropriate to store that sort of metadata about the Realm file somewhere else in iCloud that's easier to access remotely (for example, [the iCloud key-value store](https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSUbiquitousKeyValueStore_class/#//apple_ref/occ/clm/NSUbiquitousKeyValueStore/defaultStore) as a possible solution)

In any case, please let us know if you have any additional queries about this. :)

**Comment by Tom29** [comment]
@TimOliver Thanks Tim, i've found the way to work around. I have to count and check total record in the db to know which one is the newer version.
