### ISSUE TITLE
The query string numbers such as "205", "105", "10" this type of data, sorting is not accurate. There are a solution it?

### ISSUE THREAD

**Issue by MonkeyRing** [realm/realm-cocoa#3856]

**Comment by TimOliver** [comment]
Hi there @MonkeyRing!

Thanks for your issue, but could you please add some more information about your question? We provide a template when creating new issues to outline the information we need, and it would be great if you check it out and provide us with it. :)

In this case, can you please provide us with your source code for the following:
* Your Realm model object properties, outlining the data types you're actually using to store these values.
* Your source code when actually performing the sort operation.

Please let me know if you can do this. Thanks a lot!

**Comment by MonkeyRing** [comment]
```
   dynamic var name_parent = ""                   
   dynamic var ticker_parent = ""           
   dynamic var srs = ""                    
   dynamic var pts = ""                         
   dynamic var nav_price_ratio_fcst_parent = ""    
   dynamic var nav_fcst_parent = ""              
   dynamic var nav_parent = ""                  
```
```
    dynamic var name_parent = "name"                   
    dynamic var ticker_parent = "000001"           
    dynamic var srs = "0"                    
    dynamic var pts = "1"                         
    dynamic var nav_price_ratio_fcst_parent = "1.05"    
    dynamic var nav_fcst_parent = "-10.25"              
    dynamic var nav_parent = "3.78"
 ```

##### This is a list entity. Each entity corresponding fields have different values.  And  i follow the values of one sort fields, not found in the sort order.
```
memoryRealm.objects(JSVMutualFundEntity).sorted("nav_parent", ascending: false)
```

**Comment by TimOliver** [comment]
Ahh okay. I think I see the problem.

Because these values are all `String` types, they're being sort alphabetically, instead of numerically. This will mean that numerical order isn't guaranteed (e.g., things like "1", "10", "2", "3" can happen). 

I'd recommend that unless you have a very specific reason for not doing so, you should convert those `String` values to `Int` or `Double` before you insert them into Realm. This will let you apply proper numerical sorting.

If you absolutely must keep those values as `String` objects, then I'd recommend copying the Realm objects from that query over to an array and then manually sorting them yourself. That's not a great solution (Since you lose a lot of Realm's advantages doing that), but it will definitely work.

[We've discussed](https://github.com/realm/realm-cocoa/issues/1265) adding the ability to custom sort Realm `Results` objects before, but there's nothing solid on that at the moment.

I hope that helped!

**Comment by MonkeyRing** [comment]
##### Like ```nav_parent``` this field , like a lot of it will have a list of different values ​​, and I can save them as numerical data , but if it is empty , the background will return to this ```"--"``` string type data, so if I change nav_parent this field is numeric type , if the return string type```  "--" ``` when the data represents the contents of an empty , it will crash.


##### The value of this field will contain numeric data, and string data types , such as``` [ "10.5 ", " 15.0" , "50" , "--" ] ```, then the `" 10.5 ", " 15.0" , "50" `three one can be converted to numerical data , but " - " this is the type of string data

#####  So in storage , there will be different types of data . Is there any solutions or suggestions ? We can not change the server back-end side of the current structure , tight time they did not have time to help me change the structure , I can only think of a way

**Comment by TimOliver** [comment]
Hmm okay then!

It shouldn't matter if you can't change the backend since most of this is happening locally anyway. 

In any case, as long as you sanitise the data that comes down from the service before you insert it into Realm, you should be able to use a numerical value and avoid crashes. If `--` comes down, and you know this represents 'empty', then you can use Realm's [Optional Properties](https://realm.io/docs/swift/latest/#optional-properties) to mark that one as explicitly `nil`. In any case, you'd definitely need to try and convert every value to a number before passing it to Realm, as like you said, failing to do so will result in a crash.

But like I said before, the only other alternative is to perform the sort manually yourself by copying the results of the query to an array and perform a sort on that.

**Comment by MonkeyRing** [comment]
```
{
   srs: "0",
   pts: "0",
   trading_date: "",
   nav_parent: "0.9910",
   nav_fcst_parent: "0.9922",
   nav_fcst_parent_change: "0.13",
   nav_price_ratio_fcst_parent: "--",
   index_price_change: "--",
   price_change_a: "--",
   nav_fcst_a: "1.0031",
   nav_price_ratio_fcst_a: "--",
   nav_price_reduce_ratio: "--",
   price_change_b: "--",
   nav_fcst_b: "0.9669",
   leverage_ratio: "2.06",
}...
```
Like this , all values ​​are string type data , the corresponding variable declaration must declare a string type , if other types , you can not map out a valid value. However, the string data type sort guilty the hard ... I do not know how to solve. As you say , it does not guarantee the order .

**Comment by TimOliver** [comment]
That's just regular JSON right? It should be possible to transform the values to `Double` and changing `--` to `nil` before passing them to Realm. How are you passing the data to Realm right now? Are you using a third party JSON parsing library?

**Comment by MonkeyRing** [comment]
I'm using objectMapper

**Comment by TimOliver** [comment]
Ahh okay! Yep, ObjectMapper allows for transforms between types: https://github.com/Hearst-DD/ObjectMapper#custom-transforms

You should easily be able to get it to convert string numbers to `Double` values and discard `--` values. :)

**Comment by MonkeyRing** [comment]
hmm，ok  ,thank you very much Thank you for helping me

**Comment by TimOliver** [comment]
No problems! I hope that helped! 

Let me know if you have any more questions. :)
