### ISSUE TITLE
Error when build app with pod Realm

### ISSUE THREAD

**Issue by minhthuc251** [realm/realm-cocoa#3903]
> **Bugs**:

When i install Realm from Cocoa it build successful, but when i commit pod file into SVN other macbook build fail with this error.
![screen shot 2016-07-22 at 9 31 32 am](https://cloud.githubusercontent.com/assets/5000594/17045027/dc2b3208-4fef-11e6-9a1d-97872570168b.png)

## Goals

Other device build successful

## Expected Results

Other macbook can build project successful without remove pod Realm and install again.

## Actual Results
Build failed with error.

## Steps to Reproduce

1. Install Realm via Cocoapod in local device.
2. Commit to SVN via cornerstone.
3.Other device checkout but build failed.

Realm version: Newest Version

Xcode version: 7.2.1

iOS/OSX version: 10.10.5

Dependency manager + version: CornerStone v2.7.16

**Comment by mrackwitz** [comment]
Did you made sure to check in all files from the `Pods` directory into the repository?

Beside that you get some warnings because of missing directories in your `LIBRARY_SEARCH_PATHS`. If you don't need that, I'd recommend to remove those from your project configuration as such could lead to issues.

Please make sure as well that you build from the workspace and that `pod install` runs without warnings. You may not override `LIBRARY_SEARCH_PATHS` or `OTHER_LD_FLAGS` in your project settings without providing `$(inherited)` as well to inherit from the xcconfig where CocoaPods injects provided build settings.

Last but not least, could you try to nuke DerivedData on the device where it works currently, to exclude that it is just working because there are some build products still stuck and picked up by the linker?

**Comment by stel** [comment]
@minhthuc251 did you solve this problem? Can we close the issue?

**Comment by stel** [comment]
Will close this issue for now, @minhthuc251 feel free to reopen it or open a new issue.
