### ISSUE TITLE
Add primary key

### ISSUE THREAD

**Issue by skarctop** [realm/realm-cocoa#3926]
I have add new property

```
@property (nonatomic, assign) NSInteger id;
```
And
``` 
+ (NSString *)primaryKey {
    return @"id";
}
```
But show this 
```
Property 'id' has been made a primary key
```

**Comment by austinzheng** [comment]
Does this happen if you name your primary key anything besides "id"? `id` is a reserved word in Objective-C.

**Comment by jpsim** [comment]
This is expected behavior. `id` is a valid property name in Objective-C, despite Xcode's syntax highlighting hinting otherwise.

@skarctop when you make changes to your schema like adding a primary key, you need to increase the schema version number and perform a migration. That's what the exception message is telling you to do.

In the case of primary keys, you'll need to make sure that all objects of that model has a unique value for that property. Realm can't guess what values those should be, so you need to do this explicitly.

You can learn more about migrations in our docs: https://realm.io/docs/objc/latest/#migrations

**Comment by kishikawakatsumi** [comment]
I'll close this issue for now due to of inactivity. @skarctop if you can provide some more info please feel free to reopen this issue, thanks!
