### ISSUE TITLE
Inconsistency document about platform independent on supported type

### ISSUE THREAD

**Issue by sainttail** [realm/realm-cocoa#3928]
In the document [here](https://realm.io/docs/objc/latest/#supported-types) it said 

`CGFloat properties are discouraged, as the type is not platform independent.`

What about `NSInteger` though?

Is this type also discouraged? because if I remember correctly `NSInteger` is also platform dependent.

Thanks.

**Comment by jpsim** [comment]
Hi @sainttail, usage of `NSInteger` is be fine, since Realm only has a single representation for all integer widths, whereas it uses separate representations for different floating point widths.

**Comment by bdash** [comment]
In rarer cases using `NSInteger` may still be a problem. For instance, it can a problem if your Realm file is shared / can be moved between applications that run on different architectures, since an `NSInteger` on a 32-bit platform cannot represent all of the values of `NSInteger` on a 64-bit platform. If that's something your app may need to worry about then you'll want to use a fixed-size integer type rather than a type whose range may differ between architectures.

**Comment by JadenGeller** [comment]
If I understand correctly, using `NSInteger` will always produce the same schema on multiple platforms (since Realm only has a single integer type), but if the `Realm` file is shared between 32-bit and 64-bit platforms truncation may occur. However, using `CGFloat` might produce different schema on different platforms making the `Realm` file entirely incompatible between the same application on 32-bit and 64-bit platforms (crashes, not truncation).

**Comment by bdash** [comment]
That's correct.

**Comment by sainttail** [comment]
@bdash My usage is very simple. Not right that scenario but I just want to know the best practice that should I declare type explicitly like `int` and `long` or use `NSInteger`

**Comment by austinzheng** [comment]
Excellent! If the situation @bdash described above doesn't apply to your use case, feel free to choose whichever convention you prefer.
