### ISSUE TITLE
How can i encrypt a unencrypted realm?

### ISSUE THREAD

**Issue by FinderTiwk** [realm/realm-cocoa#3935]
Before one version of my app, i used realm but not encrypt it.   
But now ,i want to encrypt it .how can i write migration? or can u give me something code or demo

**Comment by jpsim** [comment]
You can use [`-[RLMRealm writeCopyToURL:encryptionKey:error:]`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)writeCopyToURL:encryptionKey:error:)/[`Realm.writeCopyToURL(_:encryptionKey:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm14writeCopyToURLFzTCSo5NSURL13encryptionKeyGSqCSo6NSData__T_) to write a copy of your Realm with whatever encryption key (or none) you specify.

There's no way to change/add/remove the encryption of a file in-place because other parts of your app could still be accessing that file.
