### ISSUE TITLE
Throw exception when setting both deleteRealmIfMigrationNeeded and readOnly

### ISSUE THREAD

**Issue by AlexLardschneider** [realm/realm-cocoa#3940]
Hello,
after I updated my project to Xcode 8 beta 4, my readOnly realm stopped working.
The cause of the crash is a 'Operation not permitted error' as soon as I try to open the realm.

## Goals

What do you want to achieve?

I want to use realm like I did before updating to Xcode 8 beta 4

## Expected Results

What did you expected to happen?

I can use realm like I could before the update, e.g. no crashes when trying to open it.

## Actual Results

What did happened instead?  

My app crashes as soon as I try to open the realm.

```
Could not open realm: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/containers/Bundle/Application/FC3109B8-F418-4886-98B1-E32EE4854212/test.app/db.realm.management': make_dir() failed: Operation not permitted." UserInfo={Error Code=2, NSFilePath=/var/containers/Bundle/Application/FC3109B8-F418-4886-98B1-E32EE4854212/test.app/db.realm.management, Underlying=make_dir() failed: Operation not permitted, NSLocalizedDescription=Unable to open a realm at path '/var/containers/Bundle/Application/FC3109B8-F418-4886-98B1-E32EE4854212/test.app/db.realm.management': make_dir() failed: Operation not permitted.}
```

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

Happened after I updated to Xcode 8 beta 4, no code changes made, except updating realm to the latest commit to get support for beta 4.

## Code Sample

```

static var CONFIG: Realm.Configuration!

func bundleURL(name: String) -> URL? {
    return Bundle.main.url(forResource: name, withExtension: "realm")
}
    
static func setup() {
    let url = bundleURL(name: "db")
        
    print(url)
        
    CONFIG = Realm.Configuration()
    CONFIG.fileURL = url
    CONFIG.readOnly = true
    CONFIG.deleteRealmIfMigrationNeeded = true
    CONFIG.schemaVersion = 1
        
    do {
       _ = try Realm(configuration: CONFIG)
    } catch let error {
        print("Could not open realm: \(error)")
    }
}

```

## Version of Realm and Tooling

Realm version: ?

Commit '05ca7aad2b74ab9a5e1de11e0f9cbd4598f05458'

Xcode version: ?

Xcode 8 beta 4

iOS/OSX version: ?

10.0

Dependency manager + version: ?

CocoaPods 1.0.1

**Comment by bdash** [comment]
Thanks for the bug report, @AlexLardschneider! I was able to reproduce this issue myself by modifying our PreloadedData example project to set up the configuration in the manner you described.

The issue is caused by specifying two mutually exclusive options in the configuration:

```swift
CONFIG.readOnly = true
CONFIG.deleteRealmIfMigrationNeeded = true
```

Prior to #3937, `deleteRealmIfMigrationNeeded` was ignored if `readOnly` was true. Now the properties change the same internal state, so the last set value takes precedence. This results in the request to open the Realm as read-only is being ignored. This change in behavior doesn't appear to have been intentional.

Since we cannot meaningfully honor `deleteRealmIfMigrationNeeded` if we've been asked to treat the Realm as read-only, you can avoid the exception you're seeing by not setting both options.

**Comment by AlexLardschneider** [comment]
Hello,
removing `deleteRealmIfMigrationNeeded ` did solve the issue, thanks for letting me know!

**Comment by JadenGeller** [comment]
@bdash Should the exception be thrown when setting the property or when the user tries to create a Realm from the configuration? I think the latter sounds more reasonable, but it requires changing how configuration works (ivar-backed properties like the Swift one rather than mutating a backing `realm::Realm::Config`.

**Comment by JadenGeller** [comment]
What should Swift do when its configuration is set to an invalid state? `fatalError`?
