### ISSUE TITLE
Realm Object Editor - does not display Inverse Relationships

### ISSUE THREAD

**Issue by peterlondon1** [realm/realm-cocoa#3957]
> We LOVE to help with any issues or bugs you have!
>
> **Questions**: If you have questions about how to use Realm, ask on 
> [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm).
> We monitor the `realm` tag.
>
> **Feature Request**: Just fill in the first two sections below.
>
> **Bugs**: To help you as fast as possible with an issue please describe your issue
> and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you! :-)
>
> Please remove this line and all above before submitting.

## Goals

What do you want to achieve?

## Expected Results

What did you expected to happen?

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by peterlondon1** [comment]
Is this known behaviour?

**Comment by peterlondon1** [comment]
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31

/Applications/Xcode.app/Contents/Developer
Xcode 7.3.1
Build version 7D1012

/Users/peterbaum/.rvm/gems/ruby-2.0.0-p353/bin/pod
1.0.1
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)

/usr/local/bin/carthage
0.17.1
(not in use here)

/usr/bin/git
git version 2.7.4 (Apple Git-66)

**Comment by jpsim** [comment]
Hi @peterlondon1, inverse relationships aren't actually stored in the Realm file anywhere. They're just established at runtime as a convenient way to represent already existing relationships from the other direction.

So the Realm Browser doesn't know anything about them. Since it could be possible to expose a user interface in the browser to allow setting up inverse relationships, I've created an issue for you tracking that: realm/realm-browser-osx#194. Let's continue the conversation about this there.

Note that I created that issue in the Realm Browser's issue tracker, which you should use in the future. This issue tracker is reserved for the Realm Objective-C and Realm Swift SDKs.

**Comment by peterlondon1** [comment]
thanks and apologies for using the wrong issue tracker

**Comment by jpsim** [comment]
no problem at all
