### ISSUE TITLE
Can not get value from optional property?

### ISSUE THREAD

**Issue by sonysum** [realm/realm-cocoa#4000]
i declare variable as optional
 Ex.  dynamic var name: String? = ""
and add some record to realm 
Ex. name = "jonh"
then i get that object from realm the name property alway default value
name = ""
i use swift 2.  Xcode 7.3 and Mac osx 10.11.6
why?
any solution?

**Comment by jpsim** [comment]
Hi @sonysum, you haven't provided sufficient information to explain what you're doing, what you expect to happen, what's actually happening, and how we can reproduce the behavior you're seeing. Please file a new issue taking care to fill out the issue template and we'll be happy to help.

**Comment by GevaZeichner** [comment]
I'm having this issue as well. I'm using a `dynamic var issueContainerId: String? = nil`. The property sometimes returns its set value with no problem, but after a while it suddenly becomes nil. It's not consistent. I haven't tried a different default yet.

## Goals

Persist an optional string in a reliable manner.

## Expected Results

Always get a value from this property once it has been set.

## Actual Results

After a while, could be after several debug sessions, the property has a nil instead of its modified value.
Sending call stack to help@realm.io

## Steps to Reproduce

Just use it for a while. Put a breakpoint testing when it becomes nil.

## Code Sample

Sending to help@realm.io

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555

/Applications/Xcode.app/Contents/Developer
Xcode 8.0
Build version 8A218a

/usr/local/bin/pod
1.1.0.beta.1
Realm (2.0.0)
RealmSwift (2.0.0)
Realm (from `https//github.com/realm/realm-cocoa.git`, tag `v2.0.0`)
RealmSwift (from `https//github.com/realm/realm-cocoa.git`, tag `v2.0.0`)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.17.2
(not in use here)

/usr/bin/git
git version 2.8.4 (Apple Git-73)
```

**Comment by jpsim** [comment]
Continuing over email.
