### ISSUE TITLE
Swift List

### ISSUE THREAD

**Issue by ilyakooo0** [realm/realm-cocoa#4050]
Is there a rational reason for why the List class is marked as `final`?
I ran into a situation where subclassing it is logical and makes sense. 
I need a collection type, that will be stored in realm, which should return data in an ordered fashion. I intend for the collection to be very large. I suspect, just inserting items into a `List` as they come along and querying it as ordered every time would not be very performant. 
What I am trying to do is have a subclass that inserts items in the correct order as they arrive. This way querying it would have the same performance as just getting a `List` in "as is" order and inserting would be log(numOfItems), which i consider to be quite performant. 

Really don't want to have to fork Realm...

Either remove the `final` or tell me that I'm done and propose a better way to do this.
Any help will be greatly appreciated.

**Comment by mrackwitz** [comment]
`List` is marked as `final` as it isn't built with external extensibility via inheritance in mind. You would need to be very careful when subclassing due to Realm's partial dynamic nature at runtime. For that reason, we limited subclassing to an absolute minimum.

Instead I would propose that you could either write a method on your `Object` subclass or as an extension on List:

```swift
extension List where Element: MySortableObject {
    func insertSorted(obj: Element) {
         // insert it at the correct position
    }
}
```

But as long as you don't have really big collections, which you need to query unfiltered and sorted all the time and already run in to troubles with performance, I'd recommend to use the built-in sorting.

**Comment by ilyakooo0** [comment]
I can't use extensions because adding such a method requires for `obj` to be `Comparable`, which it is not. I don't see a way to enforce this without subclassing. Please help.

**Comment by JadenGeller** [comment]
@ilyakooo0 `extension List where Element: Comparable { … }` should do the trick!
