### ISSUE TITLE
Sys realm

### ISSUE THREAD

**Issue by zbangsatz** [realm/realm-cocoa#4067]
Currently I can't find an official sys across platforms / devices.

So that this is my solution:
- save "default.realm" to iCloud using "Realm().writeCopyToPath(_:encryptionKey:)"
- delete all "auxiliary Realm files"
- save "default.realm" from iCloud to documents directory

But I'm not sure it's will work well in next versions. Just pray

**Comment by TimOliver** [comment]
Hi there! I'm guessing what you're referring to is the ability to sync Realm files. 

You certainly can transfer data between Realm files on separate devices using CloudKit. Actually moving the whole Realm file across devices probably isn't the best way to do it, since the possibility for merge conflicts is quite high, and it would be quite wasteful in terms of bandwidth (i.e., re-sending the whole file when changing a single item).

For CloudKit, I would recommend you don't try and sync the file, but more you just copy the data in your Realm database directly as `CKRecord` entries in your app's private CloudKit container. `CKRecord` objects are ostensibly just key-value stores, so it should be trivial to copy data out of your Realm `Object` subclass objects and into `CKRecord` objects and vice-versa. 

We're currently tracking what users might like in an officially supported sync solution [here](https://github.com/realm/realm-cocoa/issues/913). Please feel free to post in there and explain what your use case at the moment is!

**Comment by austinzheng** [comment]
Hello,

We've released an official sync solution, read about it here: https://realm.io/products/realm-mobile-platform/. We highly recommend you use this over uploading and downloading Realm files to iCloud.
