### ISSUE TITLE
Retrieving Realm objects from results is slower, after object update

### ISSUE THREAD

**Issue by f3n1kc** [realm/realm-cocoa#4089]
I have collection view with 70k+ items. Items are retrieved from Realm results with some sort descriptors and filters applied. If at some point I update item property (sorting and filter do not use that property), I get quite noticeable delay, while scrolling collection view.

## Goals

Quicker retrieve

## Expected Results

Realm object is retrieved with same speed despite updates

## Actual Results

Realm object is retrieved slower after it was updated

## Steps to Reproduce

1) Create TestItem with two String properties - index and status
2) Create TestItem results sorted by index
3) Retrieve first element for the first time - slow
4) Retrieve first element for the second time - fast
5) Update  first element status
6) Retrieve first element after update - slow

## Code Sample

I have 70 000 items in datatabase, index is from 0 - 70 000 and status is "pending"

```
class TestItem: Object {
  
  dynamic var index: String? = nil
  dynamic var status: String? = nil
}
```

```
func getItem() {
    let startDate = NSDate()
    print(self.results[0])
    print(NSDate().timeIntervalSinceDate(startDate))
  }
  
  func performTest() {
    
    let descriptors = [SortDescriptor(property: "index", ascending: false)]
    
    self.results = (try! Realm()).objects(TestItem).sorted(descriptors)
    
    // get item first time
    self.getItem()
    
    // get item second time
    self.getItem()

    let realm = try! Realm()
    try! realm.write({
      self.results.first!.status = "OK"
    })
    
    // get item after update
    self.getItem()
  }
```

I get next numbers:
-  get item first time: 0.217561006546021
-  get item second time: 0.00112396478652954
- get item after update: 0.21622097492218

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

/Applications/Xcode.app/Contents/Developer
Xcode 7.3.1
Build version 7D1014

/usr/local/bin/pod
1.0.1
RealmSwift (1.0.2)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)


(not in use here)

/usr/bin/git
git version 2.7.4 (Apple Git-66)
```

**Comment by tgoyne** [comment]
By default queries are run on-demand, so the first time you call `self.getItem()` the query is run, which takes a while due to the sort. The second time you call it the query results are already cached so very little work has to be done. The third time the query has to be re-run due to that you've made changes that may effect the result (the tracking of if queries depends on something that has changed is not done at a per-property level).

If you do not need the code to run synchronously you can use [addNotificationBlock()](https://realm.io/docs/swift/latest/#notifications) to get notified of the change to the query and do things there, which lets us rerun the query on a background thread rather than blocking when you try to access it.

**Comment by f3n1kc** [comment]
Thanks for your response. We use collection view and accessing query to setup cells, while user is scrolling, so this part should be synchronous. Is there any possible workaround? I was thinking about separating item properties to another object, eg removing status from TestItem under some TestItemStatus and have some link between them.

**Comment by jpsim** [comment]
Sorry for the delay in getting back to you @f3n1kc. Due to Realm's lazy loading semantics, removing properties from the model wouldn't affect the performance of synchronously querying for it.

Since you're using the results of the query to synchronously populate your UI, here are some of the things you can do to improve performance without having to rearchitect this part of your app:

1. Store your `TestItem`s in an already-sorted `List` property of another object. `List`s preserve their ordering, so the entire `Results` doesn't need to be sorted every time its contents change. Sorting 70k objects is likely the most expensive part of your benchmark. This would also mean you can drop the `index` property of your `TestItem` model, saving a small amount of space.
2. If you can't do no. 1, consider [indexing](https://realm.io/docs/swift/latest/#indexed-properties) the `index` property of your `TestItem` model. This will accelerate sorting based on this property.
3. Change the `TestItem.status` property from a `String` to an integer-backed enum. This likely won't have a significant impact on performance if sorting is the expensive operation, but will probably help a little.
4. Sort fewer objects. If you can "shard" the number of objects that need to be sorted by grouping them in "sort groups", you won't need to sort 70k objects. This should just be a last resort.

Really, you should just do option 1 in this list 😉. I added the other ones to be comprehensive and in the unlikely case that it's not possible for you to do.

**Comment by jpsim** [comment]
@f3n1kc I'm closing this issue because we haven't heard back from you in the last week, but please let us know if what we've posted here helped, and if you have any further questions or suggestions!
