### ISSUE TITLE
Can't use Realm.swift within CommandLine tool

### ISSUE THREAD

**Issue by Jauzee** [realm/realm-cocoa#4092]
## Goals

I want to use `Realm` framework in my app. I was added Command Line Tool target to iOS app and linked `Realm.framework` & `RealmSwift.framework` from Build/Mac directory of `Carthage` folder.

## Expected Results

Build Command Line tool with those libraries.

## Actual Results

Xcode output:
`dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: .../Xcode/DerivedData/.../Build/Products/Debug/RealmSwift.framework/Versions/A/RealmSwift
  Reason: Incompatible library version: RealmSwift requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0`

## Steps to Reproduce

Create empty Swift Command Line Tool and link Realm frameworks

## Code Sample

[CommandLineTest.zip](https://github.com/realm/realm-cocoa/files/472738/CommandLineTest.zip)

## Version of Realm and Tooling

Realm version: `github "realm/realm-cocoa" "master"`

Xcode version: 8 GM

Dependency manager + version: Carthage 0.18

**Comment by jpsim** [comment]
When linking dynamic frameworks with a command line target, you need to take special care to set the appropriate `@rpath`s. This is the case with any dynamic framework (and therefore any Swift framework) and is unrelated to Realm.

**Comment by Jauzee** [comment]
@jpsim that's why it compiles with Realm.framework and not with RealmSwift.

Can you please little bit explain on guide to some article on how can I set those `@rpath`s, because I'm in search about several hours on this issue.

**Comment by jpsim** [comment]
Maybe I'm misreading the error then, it could be that you're using a `RealmSwift.framework` binary that was compiled with a different version of the Swift compiler as your CommandLineTest binary. It's hard for me to tell because the zip you shared is missing the Realm frameworks.

**Comment by Jauzee** [comment]
@jpsim I was build them from `master` branch with latest (0.18) version of Carthage.

[Mac.zip](https://github.com/realm/realm-cocoa/files/472855/Mac.zip)

**Comment by Jauzee** [comment]
Just tested with `SwiftyJSON`. Issue is not caused by `Realm`. So I'll close it.

**Comment by jpsim** [comment]
You built `RealmSwift.framework` without embedding the Swift dynamic libraries, and they're not embedded by your CommandLineTest target either, so they can't be found at runtime. You'll need to include the Swift dynamic libraries for dynamic frameworks to find them.

**Comment by ralcr** [comment]
So did anybody found a solution for this? I moved from CoreData because the momd is not embeded in the cli, and now i see that neither realm is working in cli.

**Comment by jpsim** [comment]
@ralcr Realm's equivalent to `momd` bundles are your `RLMObject`/`RealmSwift.Object` subclasses, so that's unrelated to your issue.

What (I'm guessing) you're having trouble with is that Realm Swift is only available as a dynamic framework, and CLI binaries on macOS are generally single binaries (not bundles like AppKit or UIKit apps), which means you can't inline dynamic frameworks into them. This means you need to set your rpath and dynamic linker flags very carefully, plus ship dynamic frameworks alongside your main CLI binary. This is tricky to do, but many existing projects have done so, such as Carthage, SwiftLint, SwiftGen, etc.

You can skip this difficulty by using Realm Objective-C's static framework distribution, which you _can_ inline into your CLI. You can use Realm Objective-C from Swift too.

**Comment by ralcr** [comment]
Hi, thanks for your clarifications, this page https://realm.io/docs/objc/latest/ says that static libs are available only for iOS, but i downloaded it anyway and the osx sample has a cli app which gives the same error. I made a build phase to copy realm but is not copied into the executable, just along the bundle. If what we want was done before a guide is really helpful. In my case even the dynamic libs are an option because the cli will work along the cocoa app and i could link to the framework from the cocoa app bundle, but i don't know what the rpath is and if can be defined at runtime, and i don't know even if i can find the path to my cocoa app at runtime.
