### ISSUE TITLE
initializer from primary key for swift Object subclasses

### ISSUE THREAD

**Issue by tsheaff** [realm/realm-cocoa#4096]
I'm migrating my project to Swift, but I noticed that the Swift syntax for the objc method `-[RLMObject objectForPrimaryKey:]` is much more verbose and awkward.

I was expecting something like:

```swift
Dog(forPrimaryKey: "abc123")
```

but it ends up being

```swift
let realm = try? Realm()
realm?.object(ofType: Dog.self, forPrimaryKey: "abc123")
```

This feels pretty heavy for a simple lookup.  Am I missing something, or is this the only syntax for this primary-key lookup?

Cheers.

**Comment by tgoyne** [comment]
The Swift 3 API is in flux and will be changed to `realm.object(Dog.self, forPrimaryKey: "abc123")` soon.

For the Swift API in general we dropped the default realm convenience methods that the obj-c API has for two reason:

1. Most of them simply aren't possible in Swift's type system. Getting an object for a primary key is possible, but `Dog.filter("...")` isn't because we can't have a method of type `Results<Self>` on `Object`. We briefly toyed with the idea of an `objects()` free function which was equivalent to the `objects()` method on the default Realm, but that wouldn't be very discoverable and the call sites were unclear.
2. They mostly didn't actually make the code much more concise, since getting a default `Realm` is quite a bit less verbose than `[RLMRealm defaultRealm]`. This was made less true by Swift 2's error handling model forcing you to use `try`, but we would probably want to make all of the default realm convenience methods throw anyway and `try! Dog(forPrimaryKey: "...")` is pretty ugh.

**Comment by tsheaff** [comment]
Thanks for reply @tgoyne 

In terms of the error handling, perhaps swallowing any exceptions on `Realm()` inside the method and returning nil in this case.  Thus `Dog(forPrimaryKey: "x")` is equivalent to `(try? Realm())?. object(ofType: Dog.self, forPrimaryKey: "x")`

**Comment by jpsim** [comment]
Thanks for sharing your thoughts and opinions @tsheaff!

---

The concept of the default Realm has the unfortunate side effect of introducing global mutable state and duplicate APIs pretty much everywhere in Realm's Objective-C API, and so we took the opportunity to redesign this when initially building Realm Swift. Language constraints also guided these decisions.

The reason `try? Realm())?. object(ofType: Dog.self, forPrimaryKey: "x")` looks verbose, unclear and illegible is _exactly_ why it was designed that way.

The `Dog(forPrimaryKey: "x")` syntax (very similar to Realm Objective-C):

1. doesn't scale well to using multiple Realms since it increases the API surface area.
2. encourages bad practices such as ignoring errors.
3. hides too much of the internals that are actually useful to know for end users like yourself.

---

That being said, you're always free to make extensions to Realm if you'd like to use a different syntax. Though I think the specific syntax you proposed isn't possible if defined on `Object` due to Swift's lack of higher kinded types.
