### ISSUE TITLE
Invalid bundle in iTunes Connect

### ISSUE THREAD

**Issue by jdanthinne** [realm/realm-cocoa#4108]
## Goals

Submit a build to iTunes Connect with RealmSwift 1.1.0, compiled with Carthage and Swift 2.3.

## Expected Results

Test the new build.

## Actual Results

Build is rejected after submitting.
_"**Invalid Bundle** - One or more dynamic libraries that are referenced by your app are not present in the dylib search path."_

## Steps to Reproduce

1. Add Realm master branch to Cartfile: `github "realm/realm-cocoa" "master"`
2. Update dependencies: `carthage update --toolchain com.apple.dt.toolchain.Swift_2_3 --platform ios --no-use-binaries`
3. Drag Realm.framework and RealmSwift.framework to Xcode Project, in _Linked Frameworks and Libraries_
4. Use the copy-frameworks trick in the _Run Script_ phase, with _$(SRCROOT)/Carthage/Build/iOS/Realm.framework_ and _$(SRCROOT)/Carthage/Build/iOS/RealmSwift.framework_ as input files
5. Archive and submit the iTunes Connect

## Version of Realm and Tooling

Realm version: 1.1.0 (master branch / 5fbb4ce86b0679c2ced0babd2f1cfaf33f5dd68f)

Xcode version: 8 (8A218a)

iOS/OSX version: iOS10 / OSX 10.12GM (16A323)

Dependency manager + version: Carthage 0.17.2

**Comment by jpsim** [comment]
Hi @jdanthinne, sorry you're experiencing this issue. You seem to have followed the installation instructions correctly. Although `--no-use-binaries` shouldn't be necessary since you've specified building from the `"master"` branch in your Cartfile.

Are you sure the "Invalid Bundle" error you're getting is caused by Realm? If you replace Realm with a different framework, do you still get this error?

Are you also sure that `$(SRCROOT)/Carthage/Build/iOS/Realm.framework` resolves to the correct location of your built `Realm.framework` product?

If you try to archive using `xcodebuild -scheme <SchemeName> archive`, could you please share the log output with us?

Thanks!

**Comment by jdanthinne** [comment]
My, I was building with macOS Sierra beta, and now with the public release, everything seems ok.
