### ISSUE TITLE
Convert to Swift3 ?

### ISSUE THREAD

**Issue by kiokumicu** [realm/realm-cocoa#4131]

**Comment by bdash** [comment]
I'm not clear precisely what you're asking here. If you're wondering when Realm Swift will support Swift 3, then I have some good news for you: Realm Swift v1.1.0, released earlier in the month, supports Swift 3 out of the box.

**Comment by kiokumicu** [comment]
So why Xcode offers me convert some files  to Swift3 syntax ?

![2016-09-26 16 14 07](https://cloud.githubusercontent.com/assets/26886/18835525/285e825e-8404-11e6-83fd-aa108b59eb4e.png)

**Comment by bdash** [comment]
Realm Swift includes support for both Swift 2.3 and Swift 3.0. It looks like for whatever reason Xcode is attempting to migrate the Swift 2.3 portion of Realm Swift rather than using the Swift 3.0 portion. Given that you've not provided any of the information requested in the [issue template](https://github.com/realm/realm-cocoa/blob/master/.github/ISSUE_TEMPLATE.md) I can only guess as to why that would be. If you're using CocoaPods, please make sure you've followed the steps in the [CocoaPods section of the Installation guide](https://realm.io/docs/swift/latest/#cocoapods-install), including the step that explicitly sets `SWIFT_VERSION` for the pods you're building. If this doesn't help, please provide the information requested in the issue template and we will reopen this issue and help you further.

**Comment by martinnormark** [comment]
I had this issue too. The version installed by cocoapods was outdated, so running `pod update` fixed it for me.
