### ISSUE TITLE
Document converting a local Realm to a synced Realm

### ISSUE THREAD

**Issue by mbuchetics** [realm/realm-cocoa#4163]
## Goals

I would like to use the Realm Mobile Platform to provide syncing for my app, but not force the user to register or sign in. I.e., I would like to use a local Realm at first, then switch to a synced Realm if the user decides to use that feature.
## Expected Results

Support or documentation on how to transition from a local to a synced Realm.

**Comment by jpsim** [comment]
Hi @mbuchetics, you may convert a local Realm to a synced one by creating a new, empty synced Realm with the same schema as your local one and manually copy all the objects from one to the other.

We plan on simplifying that in the future to reduce the amount of boilerplate you need to write, but for now that's what we suggest.

I'll keep this ticket open since we should really mention this in our documentation. Thanks1

**Comment by jpsim** [comment]
We've updated the docs to clarify this: https://realm.io/docs/swift
