### ISSUE TITLE
No such module 'Realm' when importing Realm in a Watch extension target

### ISSUE THREAD

**Issue by cjcoax** [realm/realm-cocoa#4183]
I have an iOS app that uses Realm 2.0.

I'm now trying to  import Realm in my watch extension to be able to Read data stored in my main app.

I followed [instruction](https://realm.io/docs/objc/latest/#installation) to import Realm as a Dynamic Framework. And here is my setup 

![realmwatch](https://cloud.githubusercontent.com/assets/1046482/19095922/a38bf0ac-8a4d-11e6-928c-022272a84176.png)

But I'm keep on getting: `No such module 'Realm'` where ever I'm using Realm on the WatchExtension:

```
import WatchKit
import Foundation
import Realm


class InterfaceController: WKInterfaceController {
    override func awakeWithContext(context: AnyObject?) {
        super.awakeWithContext(context)
    }
    
    override func willActivate() {
        // This method is called when watch view controller is about to be visible to user
        super.willActivate()
    }
    
    override func didDeactivate() {
        // This method is called when watch view controller is no longer visible
        super.didDeactivate()
    }

}


```
Realm version: 2.0

Xcode version: 8.0

**Comment by jpsim** [comment]
Hi @cjcoax, sorry about the trouble. Turns out that Xcode doesn't like having an iOS and watchOS framework with the same name in the same project 😰. This isn't unique to Realm.

There's a StackOverflow post and answer covering this here: http://stackoverflow.com/q/35701858/373262

We're updating our [installation instructions](https://realm.io/docs/swift/latest/#installation) to reflect this issue:

```diff
Go to your Xcode project's "General" settings. Drag `RealmSwift.framework`
and `Realm.framework` from the appropriate Swift-versioned directory for your
project in `ios/`, `osx/`, `tvos/` or `watchos/` directory to the
-"Embedded Binaries" section. Make sure **Copy items if needed** is
-selected and click **Finish**.
+"Embedded Binaries" section. Make sure **Copy items if needed** is selected
+(except if using Realm on multiple platforms in your project) and click
+**Finish**.
```

It should be live on our site in the next few minutes.

I haven't filed a radar about this, but if you'd like Apple to fix this, please write one and I'll be happy to dupe it!
