### ISSUE TITLE
Building scheme "Realm" in Realm.xcworkspace takes too long

### ISSUE THREAD

**Issue by liuxuan30** [realm/realm-cocoa#4199]
Seeing below log in Travis CI for a couple of weeks, not sure if it's travis issue or Realm:
https://travis-ci.org/danielgindi/Charts/builds/165976532
Project:https://github.com/danielgindi/Charts
```
*** Building scheme "Realm" in Realm.xcworkspace

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```
Any idea?

**Comment by kishikawakatsumi** [comment]
@liuxuan30 We provide a pre-built binary for Carthage. No need to build from source. But

```
*** Skipped downloading realm-cocoa.framework binary due to the error:
	"Maximum number of login attempts exceeded. Please try again later."
```

above message shows downloading the pre-built binary fails due to API rate limit. Could you please try again later or set a `GITHUB_ACCESS_TOKEN` environment variable to avoid rate limit? https://github.com/travis-ci/travis-ci/issues/4195

**Comment by liuxuan30** [comment]
@kishikawakatsumi thanks, but where can I find the prebuilt binary for Carthage and how to use it?

**Comment by cliftonlabrum** [comment]
I can confirm it takes a really long time to build, but it eventually finishes.

@kishikawakatsumi Where can I get the pre-built Carthage binary? Are they on the latest (2.1) branch?

**Comment by stel** [comment]
@cliftonlabrum you can get it here: https://github.com/realm/realm-cocoa/releases/

**Comment by jpsim** [comment]
Building Realm with Carthage from source does indeed take a very long time, because of all the architectures that Realm supports and the fact that Carthage unnecessarily builds Realm many times from scratch. I'd suggest using Carthage with prebuilt binaries, or at least narrowing the number of platforms built by Carthage by specifying its `--platform` flag if you need to build from source.
