### ISSUE TITLE
Support non-updating change of primary key

### ISSUE THREAD

**Issue by michaelblight** [realm/realm-cocoa#4201]
I understand the restriction on not changing the value of the primary key. However, it is implemented such that it cannot be set at all, even if the value is not changing. The use case for this relates to how to update objects stored in Realm. Since I may want to cancel an update, I clone the Realm object to a stand-alone one. This clone needs to include the primary key because business rule validations often require it. Updates are done on the clone, and when the user saves, I check the business rules and then need to clone back in a write transaction. I should be able to clone the primary key because its value is not actually changing, but Realm raises an exception. The need to therefore clone the primary key one way but not the other is error prone (and am I right we can no longer see if an object is already in a Realm through isValid?). Realm should only raise the exception if the oldValue and newValue differ.

Or is there a better pattern for updating an object? I assume beginWrite followed maybe or maybe not sometime later by a commitWrite/cancelWrite is a very bad idea.

**Comment by jpsim** [comment]
Performing a check on every PK set has a non-negligible performance impact.

Since Realm doesn't override the setters for unmanaged (a.k.a. standalone) objects, it's not necessary to avoid setting their primary key property.

> am I right we can no longer see if an object is already in a Realm through isValid?

That's not how you can check if an object is managed by a Realm or not. You should check the object's [`realm`](https://realm.io/docs/swift/latest/api/Classes/Object.html#/s:vC10RealmSwift6Object5realmGSqCS_5Realm_) property, which is `nil` for unmanaged objects.

> Updates are done on the clone, and when the user saves, I check the business rules and then need to clone back in a write transaction. I should be able to clone the primary key because its value is not actually changing, but Realm raises an exception.

If you update the object using [`Realm.create(_:value:update: true)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm6createuRxCS_6ObjectrFTMx5valueP_6updateSb_x), the primary key property will just be skipped, which seems to be what you want. See [RLMAddObjectToRealm()](https://github.com/realm/realm-cocoa/blob/v2.0.2/Realm/RLMObjectStore.mm#L334-L336) for the logic that takes care of this.

**Comment by michaelblight** [comment]
Thanks for the info. I was assuming you were using KVO to update Realm, and could just check NSKeyValueChangeOldKey vs NSKeyValueChangeNewKey and not update the database if they were the same (as opposed to re-reading the database).

And thanks for the link into the (now open) source - it's a reminder I should pull my finger out and check what the Realm code is doing myself before asking.

I'm not sure sure your answer on updating objects suits my needs - I want one copy method to do managed -> unmanaged and unmanaged -> managed to support cancelable updates. Following the paragraph above will probably sort this out.

**Comment by jpsim** [comment]
> And thanks for the link into the (now open) source - it's a reminder I should pull my finger out and check what the Realm code is doing myself before asking.

Actually [realm/realm-cocoa](https://github.com/realm/realm-cocoa) and [realm/realm-object-store](https://github.com/realm/realm-object-store) have always been open source, it's [realm/realm-core](https://github.com/realm/realm-core) that was recently open sourced.
