### ISSUE TITLE
iOS example swift 3.0 error: no such module 'RealmSwift'

### ISSUE THREAD

**Issue by tumata** [realm/realm-cocoa#4225]
I am trying to launch the example iOS app with Swift 3.0 on xCode 8.0. I am seeing this error :
> Playground execution failed: error: GettingStarted.playground:2:8: error: no such module 'RealmSwift'

I have also tried creating a Swift 3.0 project from scratch and have followed all instructions to import the frameworks. Same error.

Realm version: 2.0.2

Xcode version: 9.0

iOS/OSX version: 10.0

Dependency manager + version: No dependency manager

**Comment by jpsim** [comment]
Thanks for bringing this to our attention @tumata! Turns out we hadn't entirely updated our packaging scripts, nor the source of the playground, to fully account for Swift 3. I've filed #4230 to address this.

In the meantime, you can make the following changes to the playground and it should run fine:

1. Add `import PlaygroundFrameworkWrapper` between the `Foundation` and `RealmSwift` imports.
2. Change `filter(using: ` to just `filter(`
3. Change `sorted(onProperty: "age")` to `sorted(byProperty: "age")`
4. Change `realm.deleteAllObjects()` to `realm.deleteAll()`
5. In the scheme selector choose PlaygroundFrameworkWrapper > iPhone 6s
6. Press Cmd + B
7. If the Playground didn't already run press the ▶︎ button at the bottom
