### ISSUE TITLE
Default NSFileProtection value / Exceptions when reading from realm while device is locked

### ISSUE THREAD

**Issue by settl** [realm/realm-cocoa#4237]
We have the problem that when reading a specific value from realm while the device is locked, sometimes (null) is returned instead. This happens only in production and at times when the value in the database shouldn't be empty. We had several users experiencing this, but weren't able to reproduce it yet. One guess is that the NSFileProtection settings of the database might be a problem. 

I'd like to ask two questions to get some insights that might help tracking down our problem:

(1) I played around with different NSFileProtection values on our realm: 
- Use the default value: I'm able to read values from the database when the device is locked (NSFileProtection is probably set to NSFileProtectionCompleteUntilFirstUserAuthentication or NSFileProtectionNone)
- Apply NSFileProtectionComplete to the parent folder or directly to the realm files: I get the `open() failed:` exception when trying to access the database while the device is locked

The Data Protection Capability was not enabled. 

From the realm documentation about [using-realm-with-background-app-refresh](https://realm.io/docs/swift/latest/#using-realm-with-background-app-refresh):

> On iOS 8 and above, files inside apps are automatically encrypted using NSFileProtection whenever the device is locked. If your app attempts to do any work involving Realm while the device is locked and the NSFileProtection attributes of your Realm files are set to encrypt them (which is the case by default), an open() failed: Operation not permitted exception will be thrown

This leads to my first question: Are you sure the default value for NSFileProtection is NSFileProtectionComplete?

I think that holds true only when Data Protection in the Capabilities Tab is enabled. When the Capability is enabled, the default protectionlevel of all files in the app will be set to NSFileProtectionComplete. When the Capability is not enabled, the default protection level is supposedly  [NSFileProtectionCompleteUntilFirstUserAuthentication](http://stackoverflow.com/questions/27961046/default-value-of-nsfileprotectionkey/28111608#28111608). 
I couldn't find any statement from Apple about the default value, so please let me know if you have any official sources.

(2) Does realm throw the exceptions in debug mode only or in release mode as well? It probably does from what I've seen so far. This would mean if the protection settings were our problem, we would experience exceptions/crashes instead of (null).
## Expected Results

Read a value from realm while the device is locked (value in the database is not empty)
## Actual Results

Get (null)
## Steps to Reproduce

Weren't able to reproduce it yet
## Version of Realm and Tooling

Realm version: 1.0.2 and 2.0.2

Xcode version: 7.3 and 8.0

iOS/OSX version: 9.3.4

**Comment by TimOliver** [comment]
Hi @settl! I'm the one who wrote that passage in the Realm documents about file protection.

We were prompted to write it after a user reported a bug to us that there were trying to use iOS multitasking to periodically trigger a network request while the app was backgrounded, and to save the results of that to disk. They reported to us that Realm would always fail with an exception stating that the file was inaccessible when the device was locked.

We haven't found any official documentation either on what the default file protection setting is, which is why we were careful about stating which protection mode is on by default. According to many Stack Overflow posts, the assumption is that it's `NSFileProtectionCompleteUntilFirstUserAuthentication`, but the fact we had a user bump into this issue before seems to imply that might not always be the case. (That being said, they never mentioned that they might have enabled the Data Protection capability, so that might have been it!)

In any case, that seems really odd. If the Realm file on disk is encrypted, you should be always experience that `open failed` exception instead of simply retrieving a `nil` value.

If you want to test out the file protection types, [there's a small demo app](https://github.com/erikr/DataProtectionDemo) you can run to test out the various levels of protection. Unfortunately, if your phone is plugged into a trusted computer, that apparently might disable complete file protection (This is how iTunes maintains a connection), so it may be tricky to test this in debug mode.

**Comment by jpsim** [comment]
@settl did @TimOliver's last comment help shed light on the situation? I'm closing this issue since we haven't heard back from you in a few weeks, but feel free to reopen if you have any further questions.
