### ISSUE TITLE
Improve handling incorrect encryption key for metadata realm

### ISSUE THREAD

**Issue by stel** [realm/realm-cocoa#4264]
`[RLMSyncManager sharedManager]` throws `Realm file decryption failed` exception if `sync_metadata.realm` was created with the encryption key which in some reason is not equal to the one stored in Keychain.
Related issue was reported for Browser: https://github.com/realm/realm-browser-osx/issues/228. The easiest way to reproduce this is just delete `io.realm.sync.keychain` item from the keychain.

Is it safe to just delete `sync_metadata.realm` in this case?

/c @austinzheng, @jpsim

**Comment by austinzheng** [comment]
Yeah. As things currently stand it's always easiest to just delete the metadata realm and allow it to be recreated.

We may want to do either or both of the following in the future:
* Expose to the bindings an API to reset the metadata Realm, or to auto-recreate it if it's bad
* Have an API to discover and mark any user directories that don't correspond to persisted users for deletion, to avoid "leaking" disk space. (This shouldn't be automatic, because it's possible that the user might want to keep the 'orphan' data and might log into the same user again in the future.)

**Comment by austinzheng** [comment]
@stel With your PR merged, can this ticket be closed?

**Comment by jpsim** [comment]
I'd say so. If @stel knows of an angle from which #213 doesn't fully solve this issue, he should explain and reopen.

**Comment by stel** [comment]
It's better to close this after #4355 is merged as changes implemented in https://github.com/realm/realm-object-store/pull/213 is not supported by bindings right now.
