### ISSUE TITLE
Command-line application using Realm framework crashes

### ISSUE THREAD

**Issue by Sil68** [realm/realm-cocoa#4283]
## Goals

Creating a command-line application facilitating the Realm framework as persistency engine.

## Expected Results

Successfully building & running the application.

## Actual Results

The build process completes successfully, but when launching the command-line application an error message pops up, reading

    dyld: Library not loaded: @rpath/RealmSwift.framework/Versions/A/RealmSwift
      Referenced from: /Users/usr/Library/Developer/Xcode/DerivedData/Persistency-gckyeswmmodbuvbqrkselxiuhwqr/Build/Products/Debug/Persistency
      Reason: image not found

Having Xcode copying the two Realm frameworks/libraries to the product directory results in another runtime error

    dyld: Library not loaded: @rpath/libswiftCore.dylib
      Referenced from: /Users/usr/Library/Developer/Xcode/DerivedData/Persistency-gckyeswmmodbuvbqrkselxiuhwqr/Build/Products/Debug/RealmSwift.framework/Versions/A/RealmSwift
      Reason: image not found

According to some sources on the internet, the corresponding Swift dylibs have to be manually added

* libswiftCore.dylib;
* libswiftCoreGraphics.dylib;
* libswiftDarwin.dylib;
* libswiftDispatch.dylib;
* libswiftFoundation.dylib;
* libswiftIOKit.dylib;
* libswiftObjectiveC.dylib.

But again to no avail, another runtime error message reading

    dyld: Symbol not found: __TMVs11AnyHashable
      Referenced from: /Users/usr/Library/Developer/Xcode/DerivedData/Persistency-gckyeswmmodbuvbqrkselxiuhwqr/Build/Products/Debug/RealmSwift.framework/Versions/A/RealmSwift
      Expected in: /Users/usr/Library/Developer/Xcode/DerivedData/Persistency-gckyeswmmodbuvbqrkselxiuhwqr/Build/Products/Debug/libswiftCore.dylib
     in /Users/usr/Library/Developer/Xcode/DerivedData/Persistency-gckyeswmmodbuvbqrkselxiuhwqr/Build/Products/Debug/RealmSwift.framework/Versions/A/RealmSwift
    (lldb) 

Using the "ready-made" (pre-compiled binary) frameworks from GitHub, or just  building my own version from the sources doesn't change anything at all; it's always one and the same outcome.

## Steps to Reproduce

1. Create a new command-line tool (Swift) project in Xcode;
2. Simply add the two Realm frameworks to the project (without importing any of these in any of the Swift files;
3. Build & run the project.

## Code Sample

    import Foundation
    print("Hello, World!")

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 2.0.3 (cloned 01/11/2016 from the GitHub master branch)

Xcode version: 8.1

iOS/OSX version: 10.12

Dependency manager + version: ?

**Comment by bdash** [comment]
There are two issues at play here:

1. When using a dynamic framework from a command-line app, your app needs to know where to find the dynamic framework at runtime in order to load it. Realm Swift's binaries are built with an `@rpath`-relative install name, which means that by default your app will look for the framework in the directories listed in the `LD_RUNPATH_SEARCH_PATHS` ("Runpath Search Paths") build setting. For command-line applications this build setting has no default value as there's no obvious default location to find frameworks for a command-line application.

2. When building a Swift command-line app, Xcode _statically_ links the Swift runtime into the application, rather than dynamically linking it like it does for normal GUI apps. This is fine if the application itself is the only thing that uses Swift, but it is problematic if frameworks you depend on do as well, as the frameworks have no way to resolve symbols against the application.

Note that neither of these issues is specific to Realm, and they'll be encountered when attempting to use any Swift framework from a command-line application.

Addressing both of these problems is a little involved, but thankfully [this blog post by Alsey Coleman Miller](https://colemancda.github.io/programming/2015/02/12/embedded-swift-frameworks-osx-command-line-tools/) outlines an approach that should do the trick.

**Comment by Sil68** [comment]
Thanks for shedding some light into this!

After some research on The Net, I stumbled across the "rpath" approach, but unfortunately it was to no avail.

Next thing on my plate is replicating what's been publish in Alsey's blog.

**Comment by bdash** [comment]
Good luck!
