### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by TheSwifter** [realm/realm-cocoa#4289]
We all know that Apple has the vocation to delete the prefix "NS" in Swift since its 3.x version.

What if they decide to delete the prefix "NS" from "NSObject", that would be a big collision with Realm object.

I think it will be wise to think of another nomenclature to realm objects from now.

Realm version: 2.x

Xcode version: 8+

iOS/OSX version: 10+

**Comment by jpsim** [comment]
Apple was actually quite clear in the Swift Evolution proposal in which they discussed dropping the `NS` prefix from certain classes that `NSObject` wouldn't be affected because it is "inherently tied to the Objective-C runtime and `NS` namespace". See [SE-0086](https://github.com/apple/swift-evolution/blob/master/proposals/0086-drop-foundation-ns.md).

So I thank you for the suggestion, but until Apple's direction on this changes, we'll be maintaining our current `RealmSwift.Object` class naming.
