### ISSUE TITLE
Realm file size went from tens of kilobytes to hundreds of megabytes after updating from v 1.1.0 to v2.1.0

### ISSUE THREAD

**Issue by RobinCaroff** [realm/realm-cocoa#4353]
Hey,

After updating from Realm v1.1.0 to v2.1.0 my database size (the realm file stored on the device) went from about 60KB to 500MB.

I haven't changed anything to the models or the number of elements stored.

Here is my model with pretty much all the elements of the db:

```swift
class MyModel: Object {
  
  dynamic var date : NSDate = NSDate()
  dynamic var someValue : Float = -1
  dynamic var propertyId : Int = 0
  
  override static func indexedProperties() -> [String] {
    return ["propertyId"]
  }
  
  convenience init(date: NSDate, someValue: Float, propertyId: Int) {
    self.init()
    self.date = date
    self.someValue = someValue
    self.propertyId = propertyId
  }
}
```

Nothing to complex here. Can it be the NSDate objects ?

For now, reverting to 1.1.0 fixes the issue.

Realm version: 2.1.0
Xcode version: 8.1
Swift version: 2.3
iOS/OSX version: 9.3
Dependency manager + version: Cocoapods

**Comment by jpsim** [comment]
@RobinCaroff we redesigned how Realm stores its transaction log for version 2.x, which for the most part has been a transparent migration for our users, however in your case it seems to have had a very large impact. Transaction logs are now stored inside the same Realm file as your data.

One scenario that could lead to a very large Realm file with Realm 2.x but not 1.x is if you have some very large transactions that don't actually commit much data. For example:

```swift
try realm.write {
  for _ in 0..<1_000_000 {
    let obj = MyModel()
    realm.add(obj)
    realm.delete(obj)
  }
}
```

This would make the file expand to a large size to store the entirety of the operations in that transaction, but wouldn't actually make the "data" part of the file grow. With Realm 1.x, since the transaction log was stored in its own file, that file could be periodically deleted when its results were incorporated into the main file. Now, that file will just stay large forever.

If this is what's causing your Realm file to grow so large (which I can't tell for sure is the case based on the information you've provided), perhaps you could consider not writing to the Realm until you know that a mutation should actually occur, rather than mutating unnecessarily.

You could also use [`Realm.writeCopy(toFile:encryptionKey:)`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm9writeCopyFzT6toFileV10Foundation3URL13encryptionKeyGSqVS1_4Data__T_) to write a compacted copy of your Realm file at app launch, when you're sure no part of your app has started accessing the file.

**Comment by jpsim** [comment]
I've commented on an old realm-core issue to see if there are any improvements we could make here: https://github.com/realm/realm-core/issues/984#issuecomment-262104324

Finally, there's also this ticket where we're tracking auto-compacting the Realm on app launch if its amount of recoverable space exceeds a certain threshold: #3289.

**Comment by finnschiermer** [comment]
This is interesting. @RobinCaroff Can you confirm @jpsims hypothesis about using large transactions with many changes to only few objects?

**Comment by RobinCaroff** [comment]
Thanks for your answer!

I don't get why transaction logs are stored in the Realm file. I don't think it is of any use in my case. Is there a way not to store them ?

To answer your question about large transactions, here is what happened in my case :

1. I setup about 10 tables pretty much as complex as the one described previously (from 3 to 8 columns).
2. On first run, about 3.000 transactions are made (mostly on the table previously described).
3. After first run, about 100 transactions are made per day.

Is there a way to check to logs size inside the Realm file ? It could confirm your hypothesis.

**Comment by finnschiermer** [comment]
There is at the moment no user visible way of getting the log size. The reason we store the logs, is that logs are used to drive updates and notifications. We cannot do without them.

We've always stored the logs. It is only the place which have changed. It may also be the case that you've always had large logs at some point, but never noticed, because earlier when the logs were in a separate file, we would shrink that file as soon as possible. We don't do that with the realm file.

A hypothesis: during the first run, when you generate the 3.000 transactions, you are also holding some early version open for reading. This causes all 3.000 transactions to stay in the transaction log at the same time, which grows the database. Next, you release the early version, and the transaction entries are reclaimed inside the Realm file. You cannot see that, because the Realm file is never shrunk. With the earlier version of Realm, the log file would grow in the same manner, but shrink to a modest size soon after. If this hypothesis is correct, you may be able to solve the problem by changing the App logic so that it doesn't hold on to an early version during the initial 3000 commits.

**Comment by RobinCaroff** [comment]
I noticed that the file storage grew up because the entire app's storage was way bigger than before.

In the case where the logs were already very big but not stored in the Realm file (but in the app's storage), the app storage would not have changed wouldn't it ?

I'm happy to change the way I am doing thing but I'm not sure about what you mean by 

> A hypothesis: during the first run, when you generate the 3.000 transactions, you are also holding some early version open for reading.

Here is how I perform my transactions:

```
class RealmModelARepository : RealmRepository, ModelARepositoryProtocol {
  
  func addModelToDatabase(model: ModelA) {
    if let _ = getFirstModelForDate(model.date, propertyId: measure. propertyId) {
      Logger.debugLog("Cannot reccord the same model twice!")
    } else if(model.date.compare(NSDate()) == NSComparisonResult.OrderedDescending) {
      Logger.debugLog("Cannot add a model after the current date!")
    } else {
      try! realm.write {
        self.realm.add(model)
      }
    }
  }

func getFirstModelForDate(date: NSDate, propertyId: Int) -> ModelA? {
    let predicate = NSPredicate(format: "date = %@ AND propertyId = %d", date, plugId)
    let models = realm.objects(ModelA).filter(predicate)
    return models.first
  }
}
```

Then every time I add a new model to the database:

```
let model = ModelA(date: date, someValue: value, propertyId: propertyId)
modelRepository.addModelToDatabase(model)
```

Do you have any suggestion about it ?
Thanks !

**Comment by finnschiermer** [comment]
I'm not sure how to translate "also holding some early version open for reading" into how it would look using Swift. Perhaps @jpsim can you help ^ ?

**Comment by jpsim** [comment]
> In the case where the logs were already very big but not stored in the Realm file (but in the app's storage), the app storage would not have changed wouldn't it ?

Yes, this would make a difference due to what @finnschiermer explained earlier: 

> when the logs were in a separate file, we would shrink that file as soon as possible. We don't do that with the realm file.

For more of a Swift API level description of what we mean by "holding some early version open for reading", see our docs on [File size & tracking of intermediate versions](https://realm.io/docs/swift/latest/#file-size--tracking-of-intermediate-versions).

**Comment by RobinCaroff** [comment]
Thank you both for the clarification!

 I will try to use the 'invalidate' method whenever it is possible then.
I will also give a go to the solution using `Realm.writeCopy(toFile:encryptionKey:)` on start.

I won't have time to try it anytime soon but I will update you as soon as possible.

**Comment by ShurupuS** [comment]
Hi, I faced with the same problem. As I using the db extremely frequently in my app - the db size is growing very fast - about 500mb per minute on 2.1.0. So, the app is crashing soon - and user can't restart it due to mmap() failed: Cannot allocate memory size: 3221225472 

So all the workarounds above are not suitable for me - unfortunately I have to switch to the 1.x version.

If somehow I can help you (with the db file or anything else) let me know

**Comment by jpsim** [comment]
You might be interested in the discussion in realm/realm-core#2343.

**Comment by jpsim** [comment]
Let's keep the conversation localized in realm/realm-core#2343, since this is a core issue.

It'd be very helpful if anyone affected could share clear Xcode projects that demonstrate larger than expected Realm file size growth (i.e. Realm file being an order of magnitude larger than any of its data stored at any given time).

**Comment by Zhuinden** [comment]
The problem here was that each object was saved in its own transaction; instead of many objects in one transaction.
