### ISSUE TITLE
Does Realm contact home?

### ISSUE THREAD

**Issue by nmdias** [realm/realm-cocoa#4367]
I'm getting this output in Xcode's console with every single build. 

`Version 2.1.0 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v2.1.0/CHANGELOG.md`

Does Realm contact home? And if so, how can I stop Realm from making network requests?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. We collect anonymous analytics, but only when the app is running in the Simulator or has a debugger attached. You can read more about this behavior, the rationale for it, and how to disable it [in our docs](https://realm.io/docs/objc/latest/#i-see-a-network-call-to-mixpanel-when-i-run-my-app-what-is-that).

**Comment by jpsim** [comment]
Although what @austinzheng wrote is correct, that's unrelated to the log you've shared, which is actually part of the update checker, which logs when a newer version of Realm than the one you're using has been released. You can disable that check by setting the `REALM_DISABLE_UPDATE_CHECKER` environment variable to any value. See [RLMUpdateChecker.mm](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMUpdateChecker.mm) for the source.

**Comment by nmdias** [comment]
@austinzheng The rationale doesn't really fully cover the need to log this to the console. You could still reach home and know which version are in use without advertising the new one in the console. Couldn't you?

I find the need to add an environment variable to remove this log very cumbersome, as it adds trash to a project with stuff that shouldn't be there or feels right.

It feels like an ad. An intrusive one...

**Comment by jpsim** [comment]
I understand your opinion @nmdias, which is why we've made it easy to disable.

Since Realm is actively maintained and new releases with features and bug fixes are made available regularly, many of our users benefit from being notified of new updates.

> I find the need to add an environment variable to remove this log very cumbersome, as it adds trash to a project with stuff that shouldn't be there or feels right.

Setting an environment variable in an Xcode project is actually very easy! You can set it in Xcode's schemes:

![image](https://cloud.githubusercontent.com/assets/474794/20908804/45e79a2e-bb0c-11e6-866c-af32d8a48477.png)

Or if you'd rather do it from your source code:

```objc
setenv("REALM_DISABLE_UPDATE_CHECKER", "", 1);
```

---

If neither of these approaches work for you, you can also fork this project and remove the call to [`RLMCheckForUpdates()`](https://github.com/realm/realm-cocoa/blob/v2.1.1/Realm/RLMRealm.mm#L135) entirely.
