### ISSUE TITLE
Automatic migration of the primary key from optional to required breaks primary key uniqueness

### ISSUE THREAD

**Issue by stel** [realm/realm-cocoa#4370]
This issue comes from https://github.com/realm/realm-cocoa/issues/4348.

When performing migration for primary key property from optional to required type the previous values for this property are discarded and some (type specific, not user defined) default value is used.

There are a couple of issues with this behavior if the migration block **is not specified**:

1. The previous values for this property are silently discarded for all objects.
2. The value of primary key is not unique (in case of `String?` -> `String` migration the value for this property is reset to an empty string for all objects) and no errors are generated.

See the example project: [pk_migration.zip](https://github.com/realm/realm-cocoa/files/613441/pk_migration.zip)

**Comment by beloso** [comment]
Additionally I feel that PK should be considered "mandatory" by default. `nil` should not be of type
`RLMPropertyTypeString` nor `RLMPropertyTypeInt`. And teh documentation states the following:

```
Only properties of types `RLMPropertyTypeString` and `RLMPropertyTypeInt` can be designated as the primary key.
```

**Comment by MattCarr147** [comment]
I believe I'm experiencing the same issue, or at least a similar one.

I've been migrating a codebase to Swift and today ported all my existing Realm model implementations (Obj-C) to Swift as a result. 

The previous implementation was lax when specifying required properties and I fixed this when porting the classes to Swift. The Swift classes are now much better defined in regards to optional and required properties. Unfortunately, it seems that any property that is now specified as 'required' in the Obj-C implementation is discarding previously stored values during migration in favor of the newly specified default value. 

This has raised two issues for me:

- Crashes occurring due to duplicate entries for primary keys following migration. 
- A lot of data being silently discarded in favor of the default values.

Do I have no choice at this point other than to manually migrate all affected values individually?

**Comment by tgoyne** [comment]
Yes, when changing the type of a property you have to explicitly copy the values from the old property to the new one (and handle any values that are no longer valid for the new property type).

**Comment by MattCarr147** [comment]
Thanks for the clarification, I look forward to writing those migrations! 

Just for the sake of discussion - and I appreciate this is an edge case - am I wrong to find this behaviour particularly unintuitive? I couldn't find any documentation for it when reading up on Swift Migrations and as it's a low priority bug it may be worth making this behaviour more clear until fixed. 

It's just that when I consider what it means to change the type of a property my mind jumps to the type of data being stored, rather than whether it is optional or not. I appreciate that in the underlying storage the distinction is probably more important, but from a migration perspective all we end up doing is manually copying the value (as is) from the old object to the new object using exactly the same key. It feels like unnecessary code to have to write and introduces quite a high potential for errors to creep in as any values not covered by migrations would be discarded silently.

**Comment by tgoyne** [comment]
The problematic case for converting an optional property to requires is what to do if the property being converted to required has some nil values. The idea behind requiring explicit copying was that it'd maximize the chance of a developer remembering to handle an unexpected nil, and failing to explicitly copy a property over would fail very visibly as long as the developer did any amount of testing. In practice I suspect that migrations being dynamically typed largely defeats this, since you can just write `newObject["foo"] = oldObject["foo"]` and move on.

In retrospect a better design would probably have been to make it preserve values and throw an exception at the end of the migration if any are still nil, but that would have been very difficult to implement with how migrations worked when we first added support for optional properties.

**Comment by MattCarr147** [comment]
Ahh I see, I can appreciate that reasoning and especially so in a more standard use case where perhaps only one or two properties in the schema are changed. I've definitely exacerbated the issue in my own case with having essentially required fields but that which weren't explicitly tagged as such in the previous schema, leaving me now with dozens of properties to migrate. 

Thanks for clarifying the behaviour and the reasoning behind it though, will be useful to know in future.
