### ISSUE TITLE
Xcode Playground support: Keychain returned unexpected status code: -34018

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-cocoa#4372]
## Goals

Use Realm Object Server from within Xcode playground.

## Expected Results

`SyncUser.all()` to return without failure.

## Actual Results

`libc++abi.dylib: terminating with uncaught exception of type realm::keychain::KeychainAccessException: Keychain returned unexpected status code: -34018`

## Steps to Reproduce

create workspace containing Realm and playground to load RealmSwift.

## Code Sample

`import RealmSwift`
`let users = SyncUser.all()`

## Version of Realm and Tooling

Realm version: "v2.0.3"

Xcode version: Version 8.1 (8B62)

iOS/OSX version: 10.1

Dependency manager + version: Carthage

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. The Realm Object Server-enabled version of Realm uses the device keychain for securing some metadata. Unfortunately, there's a known issue with keychain entitlements when running keychain-enabled apps (see [this Stack Overflow question](http://stackoverflow.com/questions/40014695/realm-in-swift3-0-unexpected-status-code-34018)). The normal solution would be to add an entitlement, but I don't think that applies to Playgrounds.

I think a better solution is probably disabling the keychain-related functionality altogether when running in a Playground. Would that solution work for you? In the meantime you can work around this error by creating a normal Xcode project instead of a Playground. Apologies for the inconvenience.

**Comment by DanielAsher** [comment]
@austinzheng thanks so much for your reply! 

Your colleague @jpsim has added a very useful suggestion about `RLMIsInPlayground()` in https://github.com/realm/realm-mobile-platform/issues/57. 

Allowing for this use-case would be awesome 😎

**Comment by austinzheng** [comment]
Thanks! I'll close this ticket and we'll track this on the other one. If you have any questions about Realm, Realm Object Server, or related topics, feel free to open another ticket.
