### ISSUE TITLE
Parse issue, Semantic Issue

### ISSUE THREAD

**Issue by skander300** [realm/realm-cocoa#4434]
Hi ,

I am building an iOS Library (Static Library) that depends on other pods like Realm (2.0.4).
Once I try to import it and use it in a new project, i have errors that i can't understand like : 

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:492:1: Expected unqualified-id 

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:8:1: Expected unqualified-id

Semantic Issue Group

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:494:9: Unknown type name 'NSString'

/Users/Conti/Desktop/staticLibrary/PassProj/Pods/Realm/Realm/ObjectStore/src/impl/apple/keychain_helper.cpp:23:10: In file included from /Users/Conti/Desktop/staticLibrary/PassProj/Pods/Realm/Realm/ObjectStore/src/impl/apple/keychain_helper.cpp:23:

**Comment by jpsim** [comment]
@skander300 can you share your project with us and the steps you're taking to integrate Realm into your static library so that we can retrace how you might be getting these errors? Looks like a misconfigured project to me.

Perhaps you could look at existing Realm-dependent CocoaPods libraries to see how they're configured and compare to yours to identify what you may be doing differently? Here are a few examples that come to mind:

* [Realm-JSON](https://github.com/matthewcheok/Realm-JSON/blob/master/Realm%2BJSON.podspec)
* [RBQFetchedResultsController](https://github.com/Roobiq/RBQFetchedResultsController/blob/master/RBQFetchedResultsController.podspec)
* [RealmConverter](https://github.com/realm/realm-cocoa-converter/blob/master/RealmConverter.podspec)

**Comment by skander300** [comment]
Thanks for your response , 
Here 's a link containing my project and the static library that i am using .
https://drive.google.com/open?id=0Bz3gTxavcPXycEJxUE1GV1F5NGs

Steps i followed  : 
- Building a library that depends on Realm and other libraries (like AFNetworking) successfully.
 (I integrated Realm through cocoapods).
- Creating a new app that depends on the newly created static library then i had those errors.

Thanks for the help ...

**Comment by kishikawakatsumi** [comment]
I'm closing this issue now as we've not heard back. Please feel free to reopen it or create a new issue if you have any other questions. @skander300
