### ISSUE TITLE
tvOS: Cannot allocate memory size (excessive memory usage?)

### ISSUE THREAD

**Issue by 4np** [realm/realm-cocoa#4461]
Hi,

I have [an open source Apple TV app](https://github.com/4np/UitzendingGemist) (in Dutch) that is using Realm to keep track of favourite Programs and watched Programs and Episodes. While I know this might lead to [unexpected behaviour](https://realm.io/news/is-tvos-the-future-of-apps/), it has proven to work fine for months at a time.

However, as of recently Realm seems to be having trouble allocating memory, causing the Realm part of the application to stop working. The app will work fine for a while (read: days of usage), but then crash at some point. When you re-launch the app it will immediately log memory allocation errors:

```
2016-12-19 10:41:06:128 UitzendingGemist[367:591750] Realm schema upgrade error (mmap() failed: Cannot allocate memory size: 2147483648 offset: 0)
2016-12-19 10:41:06:361 UitzendingGemist[367:591750] Could not fetch episode from realm (mmap() failed: Cannot allocate memory size: 2147483648 offset: 0)
... etcetera ...
```

_The logic to try to upgrade the schema can be found [here](https://github.com/4np/UitzendingGemist/blob/master/NPOKit/NPOKit/NPOManager.swift#L96), the logic to fetch the episode [here](https://github.com/4np/UitzendingGemist/blob/master/NPOKit/NPOKit/NPOEpisode.swift#L77) and for the program [here](https://github.com/4np/UitzendingGemist/blob/master/NPOKit/NPOKit/NPOProgram.swift#L86)._

I must say I find the amount of memory (2GB???) that is trying to be allocated rather large as the objects ([Program](https://github.com/4np/UitzendingGemist/blob/master/NPOKit/NPOKit/RealmProgram.swift) & [Episode](https://github.com/4np/UitzendingGemist/blob/master/NPOKit/NPOKit/RealmEpisode.swift)) itself are pretty thin.

I _think_ this started happening since November 2016 (possible candidate: [tvOS 10.0.1 build 14U100](https://en.wikipedia.org/wiki/TvOS#tvOS_10.x)?). I have updated to the latest Realm versions but no luck there.

```
pod 'RealmSwift', '~> 2.1'
```

Do you have any clue what might be causing this?

**Update**

My hunch is that this is related to #4353 and [realm core #2343](https://github.com/realm/realm-core/issues/2343) because there are many read-write operations... Every Program or Episode is basically written to Realm and when watching an episode the app is keeping track of how many seconds you have watched by writing it to the Episode. I suspect this is filling up the transaction log? Is there any way to see / debug the size of the transaction log?

**Comment by TimOliver** [comment]
Hi @4np! Sorry to hear you're having this sort of issue.

Yeah! 2GB is a bit unreasonable. Are you able to confirm the physical size of the Realm file on disk when this is happening?

Yeah my first guess would be this is related to the transaction log issue as well. I believe we're still discussing the best solution for mitigating that at the moment.

How often does your app make a write transaction to track the number of seconds the user has watched? Is it actually on every second?

**Comment by 4np** [comment]
Hi @TimOliver, currently it observes the video player and updates the Episode object (and hence the Realm object) [every second](https://github.com/4np/UitzendingGemist/blob/a1ac786ef3a58055626885017cd169184eec3737/UitzendingGemist/EpisodeViewController.swift#L487). A quick win would probably be to keep track of the playback duration separately and update the Realm object when the video player is dismissed, but this would just take the error a bit longer to start showing. What is the reasoning behind moving the transaction log into the realm objects itself?

**Comment by TimOliver** [comment]
Hi @4np.

Not necessarily. The transaction log will periodically clean itself of older entries, so slowing down the number of writes you make to the database will mean the file won't be prone to growing rapidly. It would certainly help a lot to scale back your writes to only when needed.

The PR and discussion behind moving the log file to the Realm file was done here: https://github.com/realm/realm-core/issues/1354

We're using transaction logs for a lot of things; most notably for helping consolidate changes done on separate devices during sync. There was talk of maybe trying to disable transaction logs for non-synchronized Realms, and also for being much smarter in the recycling of unused transaction log space. 

Suffice it to say, we're aware of the issue and are trying to come up with an effective way of avoiding it without sacrificing the other functionality we need. For the meantime, you'll definitely get much better performance/disk size if you save your `Episode` objects when leaving the view, instead of every second.

**Comment by 4np** [comment]
Hi @TimOliver ,

Thank you for getting back. I did already push code to [reduce the number of writes](https://github.com/4np/UitzendingGemist/commit/f1664f0065b3ab0b145bf7dcad907cd80d4dddbd) by only writing the number of seconds and episode played for when the video player is dismissed so I hope this in practice will make this issue les likely to surface. Unfortunately it seems like you cannot recover from the issue _if_ it occurs, so it is good to hear the house keeping will take care of some cleanup at certain intervals and that you are thinking of possible future improvements in this respect. 

What shall we do with this issue? Keep it open until this issue has been tackled, or close it?

Cheers, Jeroen

**Comment by TimOliver** [comment]
Hi @4np! No problems! Okay, cool! Good to hear you're reducing the number of writes for now.

If the issue has already occurred on a device, there's a way to mitigate it right now. There's a private method on `RLMRealm` called [`compact`](https://github.com/realm/realm-cocoa/blob/master/Realm/RLMRealm.mm#L541) that will let you perform a manual compaction on a Realm file in place. Calling it needs to be done as soon as the app is opened since it will fail if there are any other active connections to the file (even separate processes).

You'll need to expose the method using an extension or a category, but that should at least fix the problem in any devices still experiencing it.

Thanks again for reporting the issue! We've already got a lot of other issues tracking the same issue, so I think it'll be best to close this one off.

If you have any more problems, let me know! Thanks a lot!
