### ISSUE TITLE
Upgrading realm from 1.x to 2.x is unnecessary when deleteRealmIfMigrationNeeded is true

### ISSUE THREAD

**Issue by BObereder** [realm/realm-cocoa#4470]
## Goals

We delete the realm now every time a migration would be needed to assure perfect performance of our app.

## Expected Results

If I specify deleteRealmIfMigrationNeeded there is no need to upgrade the realm from old to new version because it is deleted any way.

## Actual Results

First it upgrades from old realm to new realm then deletes it.

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323

/Applications/Xcode.app/Contents/Developer
Xcode 8.2
Build version 8C38

/usr/local/bin/pod
1.2.0.beta.1

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.18
github "realm/realm-cocoa" "v2.1.1"

/usr/local/bin/git
git version 2.10.0

**Comment by jpsim** [comment]
The term "migration" tends to be a bit overloaded when it comes to Realm since we use that word to describe both _file format_ migrations and _schema_ migrations. So far, `deleteRealmIfMigrationNeeded` only worked with schema migrations, and we never really considered enabling it for file format migrations, because they involve no code or work on the user's part.

However, given that some file format migrations may be computationally or I/O expensive, it makes sense to extend it to apply `deleteRealmIfMigrationNeeded` to file format migrations as well.

I'm treating this as a bug fix, with changes in https://github.com/realm/realm-object-store/pull/302 and https://github.com/realm/realm-cocoa/pull/4471 pending review now.

Thanks for the suggestion!

**Comment by BObereder** [comment]
You are totally right, it can be mixed up.
However it does not make sense to update the file format if the file gets deleted anyway.
In our special case where updating the file format takes up to 30s this turns into a real issue and this could be easily solved by taking `deleteRealmIfMigrationNeeded` into account.
Thanks for your quick response and help.

**Comment by tgoyne** [comment]
The file format upgrade shouldn't be taking 30 seconds to begin with. Is this with 2.1.1? There were some significant improvement to the upgrade performance in that version.

**Comment by BObereder** [comment]
@tgoyne I totally agree it should not and we have huge problems with that.
I already filed a bug and it was even longer before, took up to 1 minute.
That is actually the reason we are deleting our realm now.
Here is the former bug [#4368](https://github.com/realm/realm-cocoa/issues/4368)

**Comment by BObereder** [comment]
@jpsim is this already released with v2.1.2?

**Comment by jpsim** [comment]
Not, this was merged to `master` in #4471, a few days after 2.1.2 was released. You'll need to build from `master` to get this now, or wait for a release, which could happen any time between tomorrow and end of next week.

We typically close issues when they're addressed on `master`, though, so I'll be closing this issue now.

**Comment by BObereder** [comment]
@jpsim ah ok. I was not sure because I read "reset file if a file format upgrade is required in ResetFile mode" in the release commits so I was not sure if it was the same you have been working on for this fix. Thanks for clearing that up and for helping me with this issue. Keep on rocking!
