### ISSUE TITLE
Feature request. File synchronization

### ISSUE THREAD

**Issue by gerchicov-bp** [realm/realm-cocoa#4475]
Could you at least give an idea how to implement this?

Currently realm supports database synchronization only

**Comment by jpsim** [comment]
We're really focusing on synchronizing Realm databases rather than arbitrary files.

There are certainly ways to build a more general purpose file synchronization algorithms on top of Realm's synchronization, but no out of the box solution.

One obvious way is to store data in a Realm rather than another file format. This is an option if you're trying to synchronize say a document format that's used with your app (like `.docx` or `.pages` bundles).

If you can't store the file data itself with Realm, you could also store the file metadata and actions. For example, every time a file operation is performed, record it in a side Realm, so you can track which files have been modified, in what way, in what order.

**Comment by gerchicov-bp** [comment]
Thanks for your response but there are some problems:
1)if I store files into Realm directly then the base may grow unpredictably. Additionally Realm has a limitation for file size size - they should be less than 15mb
2)if I store files outside Realm then I have troubles with file synchronization

But anyways thanks for your response.

**Comment by jpsim** [comment]
We're working to address some file growth issues in realm/realm-core#2343, this is something we very much want to fix, so I encourage you to share more details there.
