### ISSUE TITLE
Determine if Realm file is corrupted

### ISSUE THREAD

**Issue by rodriguez87** [realm/realm-cocoa#4500]
Hi :)

We've got some users with corrupted Realm. While we are investigating what's causing the issue (we believe we are moving the Realm file while it's being read) we need find a way to recover those users from the corrupted database.

For now, to determine if our Realm is corrupted we are basically matching NSError's userInfo's string. We check if errorCode is 2, domain is io.realm and userInfo's Underlying is "Bad header..." - which is pretty bad 😁.

Is there a better way to determine if Realm file is corrupted?

Thank you for all the hard work you put in to making databases easier for us :)

**Comment by bdash** [comment]
There's not a single error code that represents a corrupted Realm file as different errors may be generated depending on where the corruption occurs within a file.

**Comment by rodriguez87** [comment]
Hi, bdash, 

Thanks for answering :)

So, the way we are checking if the realm is corrupted (comparing errorCode, domain, userInfo strings) is not reliable at all?

If so, is there any other way to determine if realm is corrupted?

Thanks again :)

**Comment by rodriguez87** [comment]
Sorry to bump this but I think realm-ci put the wrong tag

**Comment by jpsim** [comment]
No, @realm-ci did its job by removing the "waiting for user" since you replied, so this ticket is no longer waiting for you...

To add more to what @bdash was saying, Realm doesn't expect the unexpected in all ways... in other words, often times when a Realm file has been corrupted (which by the way can happen by no fault of Realm itself), what identifies this corruption isn't a global check for corruption, but rather a failed assertion, leading to immediate process termination, which is unrecoverable.

Ideally, Realm would have no bugs whatsoever, files would never get corrupted and all potential failures would be gracefully recoverable. Unfortunately this isn't possible without incurring an impractical amount of overhead.

**Comment by rodriguez87** [comment]
Alright, thanks you very much!
