### ISSUE TITLE
Exception when trying to delete suffix of Results

### ISSUE THREAD

**Issue by alickbass** [realm/realm-cocoa#4591]
Hi! I experienced the following bug:

1. **Goals:** get first 100 objects from realm and then delete them
2. **Expected results**: objects deleted
3. **Actual results**: Received exception: `*** Terminating app due to uncaught exception 'RLMException', reason: 'Index 950 is out of bounds (must be less than 950)'`
4. **Steps to reproduce**: populate Realm with 1000 elements and then run the following code:

```swift
let realm = try! Realm()
let results = realm.objects(Model.self).suffix(100)

try! realm.write {
    realm.delete(results)
}
```
Realm version: v2.3.0
Xcode version: 8.2.1
iOS/OSX version: iOS 10
Dependency manager + version: Carthage

**Comment by istx25** [comment]
Hi @alickbass! Thanks for reaching out about this. We'll have someone review this and respond with a solution or follow-up questions soon. Cheers! :-)

**Comment by istx25** [comment]
Hey @alickbass! My apologies for the delay. We're working through a bit of backlog. I'm going to assign this issue to someone else who may be more available.

**Comment by austinzheng** [comment]
Hello! Thanks for getting in touch with us, and sorry that you're experiencing this issue.

The reason that this occurs is because `results` is an auto-updating collection. When you use `suffix()`, you create a slice, which is a view into the original results collection. When you call `delete(results)`, you are calling the version of the `delete()` method which takes in any generic Swift sequence, and deletes the elements one at a time. When you put all of this together, this means that elements from the `results` collection are being removed as it's being iterated through, causing the indices represented by the original slice to no longer be valid.

The easiest way to fix this is to use an `Array` instead:

```swift
let results = Array(realm.objects(Model.self).suffix(100))

    try! realm.write {
        realm.delete(results)
    }
```

This shouldn't incur any significant performance penalty (as the `Model` objects aren't being deep-copied, only references to them), and will avoid the mutating-white-iterating issue present in the original code.

Hope that helps, please let us know if we can be of further assistance!

**Comment by alickbass** [comment]
@austinzheng That is the exact workaround that I already use) Just thought that it maybe worth pointing out this issue, or at least to mention somewhere in the docs, which methods can be used and which should be avoided

**Comment by austinzheng** [comment]
I agree, we may want to revisit how our `delete()` method is implemented, and definitely make it clear in the documentation what is going on. Thank you for bringing this to our attention!
