### ISSUE TITLE
Run Realm Swift on Ubuntu

### ISSUE THREAD

**Issue by johnburkey** [realm/realm-cocoa#4610]
How hard would it be to get realm swift running on Ubuntu?

**Comment by TimOliver** [comment]
Hi @johnburkey! Thanks for the question!

We'd love to have Realm Swift running on Linux platforms in the future! But at the moment, it's sadly not possible. Realm Swift is built around Realm Objective-C which uses the reflection features of the Objective-C runtime to attach the Realm objects in code to the underlying Realm database.

Since the Objective-C runtime isn't available on any flavor of Linux, it would only be feasible if Realm Swift could bypass Objective-C in its entirety; something that's lot currently feasible at Swift's level of maturity (At the very least, Swift would need to support native C++ interoperability first).

Hopefully as Swift matures, we'll be able to look at this seriously in the future.

I hope this answered your question!

**Comment by jpsim** [comment]
We're already tracking Linux support in #3263, so I'll be closing this one as a duplicate.
