### ISSUE TITLE
Prevent throwing RLMException "Object has been deleted or invalidated". Return nil instead.

### ISSUE THREAD

**Issue by rokgregoric** [realm/realm-cocoa#4628]
## Goals

The problem I am facing happens when a deleted object is accessed by the UI (fetched form the DB and referenced before being deleted).
Realm throws an exception (RLMException - "Object has been deleted or invalidated").

Checking the object if `isInvalidated` or using unmanaged (detached) objects - `Object(value: ferchedObject)` is an option, but makes the code super ugly with tons of checks all over the place and very hard to manage.

When using unmanaged objects all references (links) to other objects have to be checked if `isInvalidated` otherwise the exception is thrown again.

So instead of throwing an exception I would like realm to just `return nil` as if the object or property was released.

## Expected Results

I would like realm to just `return nil` as if the object or property was released.

## Actual Results

Realm throws an exception (RLMException - "Object has been deleted or invalidated").

## Steps to Reproduce

That's very simple to reproduce:
* just create an object
* keep a reference to it
* delete the object
* try to access the deleted object

## Version of Realm and Tooling

Realm version: 2.4.2

Xcode version: 8.2.1

iOS/OSX version: iOS 10.2

Dependency manager + version: Cocoapods 1.2.0

**Comment by istx25** [comment]
Thanks for filing this, @rokgregoric. Someone will take a look at your PR soon. :)

**Comment by jpsim** [comment]
There's a significant difference between returning `nil` when accessing a valid object's property and accessing a deleted object. This type of ambiguous behavior, such as messaging `nil` in the Objective-C runtime, has [historically shown](http://blog.ioactive.com/2012/11/ios-security-objective-c-and-nil.html) to be [a source of bugs](http://vgable.com/blog/2008/05/31/messages-to-nowhere/).

That's why Realm distinguishes between both cases. For example:

```swift
class MyModel: Object {
    dynamic var property: String? = ""
}
let realm = try Realm()
realm.beginWrite()
let object = MyModel()
object.property = nil
_ = object.property // nil means one thing here

realm.cancelWrite()
```

We define any access to a deleted object as a usage error (by throwing that exception). Thankfully, Realm objects can only be invalidated at very specific points in time, so you shouldn't have to write as defensively as you would to avoid "faults" present in other frameworks. For example, when a Realm is refreshed, or when a deletion has happened earlier in that same thread.

If you'd like to avoid checking for `RLMObject.isInvalidated` directly, you could leverage [object notifications](https://realm.io/news/realm-objc-swift-2.4/) and handle the deletion of an object _reactively_.

**Comment by rokgregoric** [comment]
I agree returning `nil` is not the best option here .. but throwing an exception is even worse .. cause returning nil might crash you app in production .. but throwing an exception crashes it 100% if not caught. I am not suggesting to remove throwing exceptions all together .. but maybe have an option to disable exceptions when building in release mode .. to prevent unwanted crashes.

Imagine a scenario .. you have an app with 20 controllers and each has some realm objects referenced. On a background thread you delete some objects. Every controller needs some special handling to ensure that the objects (and their child objects) in use are not invalidated.
What's the best way to handle that?
If we are talking about Swift .. optionals and the compiler help you handle properties returning `nil` just fine.

**Comment by jpsim** [comment]
Realm only throws runtime exceptions for programmer misuse of the framework. Exceptions shouldn't be used as error-handling, we expose `NSError` pointers and Swift throwing functions/initializers for that.

_If_ a Realm user forgets to handle a case in which the object being manipulated has been invalidated, preventing the continuation of the app (e.g. crashing) is preferable to corrupting data due to misleading information being reported for property values. This is especially true for synchronized Realms, where changes are propagated to other clients and may cause irreversible damage.

> If we are talking about Swift .. optionals and the compiler help you handle properties returning `nil` just fine.

Actually that's not quite the case. For a non-optional property, you can't return `nil` under any circumstance. Doing so will crash the app, but without a helpful error message explaining why the value couldn't be fulfilled, which we gain by using exceptions.

Also, returning `nil` from an optional property should not conflate the meaning of "this valid object has a nil value for the queried property" with "this is an invalid object that may or may not have had a value for the queried property".

**Comment by bdash** [comment]
> Imagine a scenario .. you have an app with 20 controllers and each has some realm objects referenced. On a background thread you delete some objects. Every controller needs some special handling to ensure that the objects (and their child objects) in use are not invalidated.
> What's the best way to handle that?

It's important to be clear that when you delete objects on a background thread, your main thread will only see those objects as deleted after it has advanced to the new version of the Realm file (typically on a future runloop iteration). If you register for notifications on the objects your view controllers are working with, the notification handler will be called as part of the process of updating to a newer version within the Realm, giving you ample opportunity to see that the object has been removed and invalidate any references you may have to it.

**Comment by michaelpeternell** [comment]
It would be super-useful though if the error message could be improved, so that you know which object has been deleted or invalidated. Like "Object of type 'DnsServer' has been deleted or invalidated". Or even better "Object of type 'DnsServer' (id '2148729183') has been deleted or invalidated".
