### ISSUE TITLE
Bad changeset received: Assertion failed: left().nullable == right().nullable

### ISSUE THREAD

**Issue by gregiii** [realm/realm-cocoa#4650]
I'm getting this cryptic error message when I try to open a synced realm:

```swift
2017-02-09 21:28:01.753 Medisage[14791:592832] Sync: Connection[1]: Session[1]: Sending: IDENT(server_file_ident=8722228443253153481, client_file_ident=14, client_file_ident_secret=8271591352897651037, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)
2017-02-09 21:28:02.501 Medisage[14791:592832] Sync: Connection[1]: Session[1]: Bad changeset received: Assertion failed: left().nullable == right().nullable
```

It seems it's because of some property changed from being optional to non-optional. But it doesn't tell which property and which class is causing the error. 

Realm Object Server: 1.0.2

Realm version: 2.4.2 

Xcode version: 8.2.1 - Objective C

iOS/OSX version: MacOS Sierra

Dependency manager + version: CocoaPods 1.1.1

**Comment by istx25** [comment]
Hi @gregiii. Thank you for reaching out. We'll have one of the engineers look into this and follow-up soon. In the meantime, if you can provide us with a sample project that the problem exists in/reproducible - that'll speed up the process of resolving the issue.

**Comment by gregiii** [comment]
I have the sample project which reproduces this issue. However, I cannot post it here and would like to send the download link directly to you.

**Comment by austinzheng** [comment]
You can send the download link to help@realm.io.

**Comment by gregiii** [comment]
I have sent the link to the sample project.

Thank you.

**Comment by istx25** [comment]
Awesome, thanks @gregiii. We'll review that and follow-up soon.

**Comment by jpsim** [comment]
@gregiii you're definitely right that this is due to a schema mismatch between the server and the client. We're tracking ways to improve the error messages internally, but in the mean time, you could print the schema information from both the client (using the [`RLMRealm.schema`](https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(py)schema) property) and from the server (using the Node.js SDK) and compare them to see how they differ.

I'm sorry I don't have a more convenient way for you to do this right now.

**Comment by gregiii** [comment]
@jpsim Thanks for the assistance.
