### ISSUE TITLE
LinkingObjects issue

### ISSUE THREAD

**Issue by atom2ueki** [realm/realm-cocoa#4658]
I have a Group object
```
dynamic var id = 0
let users = LinkingObjects(fromType: MyUser.self, property: "groups")
dynamic var name = ""
dynamic var created_at : NSDate?
dynamic var updated_at : NSDate?
```
and User Object
```
...
var groups = List<MyGroup>()
...
```

when I update users with newUser.groups.append(xxx), user table updated, but Group table users attribute not updated, I thought LinkingObjects will run automatically

May I know how to use it?

**Comment by bdash** [comment]
`LinkingObjects` only reflect managed objects (i.e., objects that have been added to the Realm). It's not clear from your example whether the objects involved are managed or not. If not, this is expected behavior. If they are managed, it sounds like a bug and we'd need more information about how to reproduce it.

**Comment by istx25** [comment]
Hi @atom2ueki. Would you be able to read @bdash's response and provide more information? Thanks.

**Comment by istx25** [comment]
Do you still require assistance, @atom2ueki?

**Comment by jpsim** [comment]
Closing as we haven't heard back from @atom2ueki in a while.
