### ISSUE TITLE
Updating realm requires Updating realm mobile platform?

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-cocoa#4683]
When I updated from Realm 2.3.0 to Realm 2.4.0 I also had to update from Realm Mobile Platform 1.0.0-beta to Realm Mobile Platform 1.0.0-Release. It was not mentioned in the changelog or the documentation. 

I now updated from 2.4.0 to 2.4.3. Realm Mobile Platform seems to work but the changelog is telling me that there are several synchronization bugs fixed. 

Would it be possible to make it clear after each new version of Realm if there also is an update required for Realm Mobile Platform to make use of all new features and bug fixes?

**Comment by istx25** [comment]
Hi @Montrazul. Thanks for bringing up this concern. I'll bring this up to the team and follow-up with you soon. 😸

**Comment by austinzheng** [comment]
I'll bring this up with @jpsim when he becomes available again.

**Comment by jpsim** [comment]
Hi @Montrazul, sorry for the delay in getting back to you. Did you end up resolving this since your last comment?

As far as compatibility goes, any version of Realm Cocoa 2.4 or later should be compatible with any version of the Realm Object Server 1.0 or later, other than certain features as explicitly noted in their changelog entries.

For example, the [`SyncPermission` changelog entry](https://github.com/realm/realm-cocoa/blame/25cdc6b9b4fcef8f322e4a463c8bd50a0c98a416/CHANGELOG.md#L10-L11) states that ROS 1.1.0 or later is required.

**Comment by TimOliver** [comment]
@Montrazul It's been two weeks so I'm going to close this issue now. If you haven't managed to resolve it yet, please re-open it. :)
