### ISSUE TITLE
Error: Not working in different network

### ISSUE THREAD

**Issue by nikunjazilen** [realm/realm-cocoa#4691]
Hi Realm Team,

Can you please answer the below question? So that would be great help for me.

## Goals
To achieve the drawing demo in different devices in different network.

## Expected Results
I expected the above result while I integrate the drawing demo which connected to the realm object server.

## Actual Results
I run the draw demo in different network but its not drawing reflected into other devices.

## Code Sample
[https://github.com/realm/realm-cocoa/tree/master/examples/ios/objc/Draw](url)
[https://github.com/realm-demos/realm-draw](url)

## Version of Realm and Tooling
pod 'Realm', '~> 2.4'

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: ? 2.4

Xcode version: ? 8.2

iOS/OSX version: ? 9.3.5

1) Can you please explain me authURL:::::::::::http://192.168.X.XX:9080 and Login syncURL:::::::::::realm://192.168.X.XX:9080/~/Draw?

2) There is a static NSString *const kIPAddress = @"192.168.X.XX" in Constant.h file. Is it the server IP Address which is the central of my network?

3) Is not supported different network? For example: I run the draw demo with step 2 IP Address in different device and one my device connected to hotspot wifi network and other 2 devices are own connected wifi network. But when I drawing from hotspot wifi network its not reflect to other devices. Can you tell me the issue what is the problem there? I have logged in all devices with same credentials.

4) How can I realm set up with my own sever to implement the drawing demo? Is it free or paid service?

5) Why Login failed: the request time out occurred even realm object server connected?

6) If run this start-object-server.command from my mac and there is IP Address: 192.168.X.XX and run this demo into hotspot wifi network that time its give me error like "Could not connect to server". Can you tell me why this is happen?

Best Regards,
Nikunj

**Comment by istx25** [comment]
Hi @nikunjazilen. Thanks for reaching out. We'll have someone review what you've shared and your questions and respond to you soon.

**Comment by teotwaki** [comment]
Hi @nikunjazilen,

For the record: You can disclose 192.168.x.x addresses, as there is (usually) no security risk involved. It will make it easier to reason about if we have real IPs.

To answer your questions:

1. The `authURL` is the URL used to authentication a user, and to "log on" to the Realm Object Server (ie: create a session, get the authorisation tokens to access Realm files). The `syncURL` is the WebSocket URL used to access a specific Realm file. These would typically have the same hostname/IP address.
2. This is auto-generated, and based off the values provided in `authURL` and `syncURL`.
3. Different networks are supported. The Realm Object Server and the client SDKs are completely agnostic to this: if you can ping/SSH to a box, you should be able to use the sync system (assuming there are no firewall rules blocking port `tcp/9080`). I suspect the issue comes from something else than the networks. You would have to provide us with client and server logs to be able to help you further.
4. The Realm Mobile Platform is a self-hosted product. There is a free version, the Developer Edition, and then there are two paid-for versions, which provide more features: the Professional Edition, and the Enterprise Edition.
5. I suspect there is something wrong in your networking stack. Are you able to ping/ssh into the machine?
6. I don't know your networking environment, so no, I can not tell you why it doesn't work. You would have to give more information regarding the kind of networks that you're trying to communicate between, and how routing/firewalling is setup.

**Comment by stel** [comment]
As for question number 2: there is "Get Device IP Address" build phase that generates that file and uses the IP address of the current machine automatically. So if you want to use another address you can specify it manually in `authURL` and `syncURL`.

**Comment by nikunjazilen** [comment]
Hi Teotwaki and Stel,

Thanks for the answers of all questions. I have tested drawing demo with different network and its working fine but some time not working even connected. Don't know the exact issue but when I run again its working. So do you any idea why this is happen?

Is there anyway to implement video chat/calling with Realm?

Thanks.

**Comment by stel** [comment]
@nikunjazilen try to investigate this issue by looking at the error messages in a console output (or just post it here) and please keep in mind that the server address is hardcoded in demo apps for simplicity, so if you change the sync server you won't be able to connect to it.

As for video streaming it's always up to you what technologies to use, personally I'd suggest you to look at some streaming protocols and libraries instead.

**Comment by nikunjazilen** [comment]
Hi,

Thanks, I have tested in different network while run the app in device but its not working while switching the network while app working in foreground. 

For example: Run the demo in 2 different devices with different network its working fine but when I switch into other network in one device its not working.

```
 Sync: Connection[1]: Session[1]: Starting session for '/var/mobile/Containers/Data/Application/0C1F9587-9E8E-424B-9F6D-9D3B55B20EFB/Documents/realm-object-server/842243bbb74f8d593740d1ffd690d8c0/realm%3A%2F%2F27.109.15.3%3A9080%2F%7E%2FDraw'
 Sync: Connection[1]: Session[1]: Sending: BIND(server_path='/842243bbb74f8d593740d1ffd690d8c0/Draw', signed_user_token_size=601, need_file_ident_pair=0)
 Sync: Connection[1]: Session[1]: Sending: IDENT(server_file_ident=4419331368953599864, client_file_ident=33, client_file_ident_secret=7540001611921371947, scan_server_version=18608, scan_client_version=870, latest_server_version=18608, latest_server_session_ident=5232872301700732439)
```

Can I integrate QuickBlox sdk to implement video chat/calling feature in app with Realm drawing feature?

Thanks

**Comment by teotwaki** [comment]
Please provide IP addresses of the different machines involved, and double check that you can access the dashboard from all the different clients.

Also, please post connection logs from both client and server.

**Comment by jpsim** [comment]
Hi @nikunjazilen, I'm just following up on @teotwaki's last request. Thanks!

**Comment by TimOliver** [comment]
It's been two weeks, so I think we can safely close this. @nikunjazilen If you have any further follow-up for this issue, please feel free to re-open it. :)
