### ISSUE TITLE
Merge two .realm files into one with complete data

### ISSUE THREAD

**Issue by pavlem** [realm/realm-cocoa#4718]
## Goals
Upload .realm to some cloud storage, delete the app, populate the new .realm with some data and merge it with the old one from cloud storage (just an addition of data from 2 .realm files).

## Expected Results
One, final, universal .realm file merged from two .realm files with the same schema (model classes) but with different data inside (just the union of both). 
 
Please point me to a flow on how to do this (is there some API function meant for this, should I export to, for example, CSV combine them and then import them back or should I load them both inside of the project, read all models from one and add them, one by one to another (the one .realm file meant to display complete, merged info). 

Found no useful info on stack-overflow.

**Comment by jpsim** [comment]
I don't see what you're having difficulty with. Just add the missing objects from the old Realm to the new Realm?

**Comment by pavlem** [comment]
I merged them programmatically, First I downloaded the old, backed up Realm from cloud storage and then I copied all of the objects, one by one to the current Realm i had in my App. Also, for the cases where I had objects with other linked objects, I had to add restored linked objects to the current one as well. For all of this I had to make copies of all objects from the current Realm and their linked object as well because I would get an exception that I cannot use Realm objects from one Realm in another Realm. This made me some problems, but I did it in the end. 

I found no solutions on the net for this problem I had (backup Realm, delete app, install app, download backed Realm and merge with existing one) and I had to think how to do this out of the box. It would come in handy for you to implements some documentation regarding this (how to merge files if we are not using your realm-mobile-platform).

Thanks,

**Comment by jpsim** [comment]
Realm is a general purpose mobile database, which is why we provide APIs that are composable and flexible to handle a variety of situations, including the merging of two Realms like the mechanism you've built.

Since the way in which a user would want to merge two Realm files very much matters on what semantics they want for the merge, this is something that would be difficult (or at least verbose) to document. By semantics, I mean how do you reconcile ordering, does anything override anything else, should objects with primary keys have one version discarded, or should both be kept, mutating the primary key of the second object, if properties are present in one Realm but not the other, which "wins", etc?

Rather than add this to our documentation, I think this would make a great blog post. If you were to write a quality article describing what you did, let me know, I'm sure we'd be able to promote it and link to it from our documentation as additional resources like we do other articles.

Thanks.
