### ISSUE TITLE
Feasibility: PPT Play

### ISSUE THREAD

**Issue by Nik20112** [realm/realm-cocoa#4751]
Hi Realm Team,

I have successfully testing the drawing demo in multiple devices and its working fine vice versa case. I want to know that when I play the PPT file in one device and its reflect/play into other device or multiple device.

Please suggest me this feature. Is it feasible with realm mobile platform or not?

Best Regards,
Nikunj

**Comment by TimOliver** [comment]
Hi there @Nik20112! Thanks for the issue!

What do you mean by a 'PPT file' exactly? Are you referring to a Microsoft PowerPoint file?

Thanks a lot!

**Comment by Nik20112** [comment]
Thanks.
I want to play Microsoft power presentation file in one device and its play or reflect into other device.

Hope you got my point.

**Comment by TimOliver** [comment]
Ahh okay. I see.

It definitely depends on your implementation, but yes, you could use the Realm Mobile Platform to synchronize the progression of a PowerPoint presentation across multiple devices.

You could use the Developer Edition to write a small app that keeps track of a single object that tracks the slide number and slide animation count. Other copies of that same app can be running on your client devices, and when they detect those values have updated, they can forward those changes along to PowerPoint.

I wrote a similar integration a while ago into a book reader app I was writing. As the user was reading the book on one device, the other devices would update to show the same page automatically. :)

The hardest challenge here would be interoperating Realm with PowerPoint. As far as I can gather, it's probably not possible on iOS unless you rolled a completely custom app that could also open and display the contents of PPT files itself. You could possibly do it on macOS if your app could remotely control a copy of PowerPoint running on it.

I hope that helped!

**Comment by Nik20112** [comment]
Thanks for the help.
How can I start to implement this feature? If you have any demo link, plz give me so I can move ahead on it.

**Comment by TimOliver** [comment]
Not at all!

I recommend you read [the Realm documentation](https://realm.io/docs/realm-object-server/) to get an idea on how to set up the Realm Object Server.

As for demos, we're maintaining [a separate repo full of demo apps](https://github.com/realm-demos) in order to demonstrate how to write apps using the Realm Mobile Platform. 

If you get stuck on any of the code, I'd recommend asking it as a new question over on [Stack Overflow](https://stackoverflow.com). We monitor that one just as closely as GitHub issues and it's more conducive for community support. :)

Happy hunting!
