### ISSUE TITLE
Index out of bound error when scrolling in collectionView. Notification block aren't called

### ISSUE THREAD

**Issue by jovanpreet** [realm/realm-cocoa#4754]
Lets say i have 5 objects in realm and at a time 3 cell is visible. Now i have UIRefreshControl  and i pull the collectionView and didn't release it so now only 2 cells are visible. Now as UIRefreshControl valueChange event gets fired. I call web api and from api bottom 3 object's id didn't come so i delete them from realm. But i am still holding the collectionView. Now realm doesn't call notificationBlock until and unless i release the collectionView. But as soon as i release the collectionView cell 3 get visible so cellForItemAt indexPath gets called which require realm to have object at index 2 but in actual realm has only 2 objects which throws index out of bound error.

Why notifications aren't fired when collectionView(UIScrollView) is scrolling.

I need urgent workaround for this situation. Please help

**Comment by istx25** [comment]
Hi @jovanpreet. Thanks for reaching out. Would you be able to share a code sample demonstrating your issue? From there, the engineers will be able to better assist you.

**Comment by jpsim** [comment]
I don't think there's a need for a repro case for this. This is part of Realm's designed operation. Notifications aren't delivered if the "event tracking" runloop mode (`NSEventTrackingRunLoopMode `). One thing you could do is to disable `autorefresh` on the Realm when scrolling the view.

**Comment by jovanpreet** [comment]
But don't you think notification should be delivered or app will crash every time user will pull refresh a little bit forcefully.

**Comment by jovanpreet** [comment]
disabling autoRefresh fixes the issue thanks. But there are many situation where realm gets updated later and data gets updated earlier and may lead to NSInternalInconsistencyException. Like we have two notifications for two sections of tableView will result in error. I think notification and realm should be synced at same time.

**Comment by TimOliver** [comment]
@jovanpreet Good to hear that disabling `autorefresh` fixed the issue for you!

Unfortunately, since the notification mechanism works by refreshing at the start of a new runloop iteration, making it so Realm and the notification blocks are triggered synchronously isn't very feasible.

If you have logic in your code where you explicitly need to update the collection view right after you've written new data to Realm, you can use [`Realm.commitWrite(withoutNotifying:)`](https://realm.io/docs/swift/2.4.4/api/Classes/Realm.html#/s:FC10RealmSwift5Realm11commitWriteFzT16withoutNotifyingGSaCSo20RLMNotificationToken__T_) to perform the write without triggering the notification block, and then manually performing the UI update code yourself.

I hope that helps!

**Comment by TimOliver** [comment]
I think this issue is resolved at this point. Feel free to re-open it if you have any additional follow-up questions!
