### ISSUE TITLE
How can i handle Realm incorrect thread exception gracefully without app crash.

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#4762]
_An empty new issue template was posted. Removed by @istx25._

**Comment by Zhuinden** [comment]
The "graceful" way is to access Realm instances, RealmResults, and RealmObjects only on the thread where the Realm instance was created.

Each thread requires their own Realm instance to "communicate with" the Realm.

**Comment by santhoshs5** [comment]
this crash is not happening always but it is happening some times i don't know the reason .
I am using a separated realm each save,fetch requests of realm. if any body can tell me how can i gracefully handle this so that i can put that code in my common methods whose task is to perform fetch and save of realm objects.

**Comment by austinzheng** [comment]
I'm really sorry, but there's really nothing else you can do but figure out _how_ your code works and _what_ parts of it are running on what threads. This is a really fundamental part of building iOS or macOS applications. Incorrect thread exceptions are explicitly _not_ intended to be handled, because they represent a serious error on the programmer's part.

**Comment by tigerraj32** [comment]
We need to understand the fact  **Realm Objects cannot be accessed from different threads.** What does this means and how to workout this issue.

First, realm objects cannot be access from different thread means, one instance of thread defined in one thread cannot be access from different thread.  What we should do actually is we need to have different instance of realm instance for each thread.
    
For eg. let's look at following e.g. where we insert 50 records in database asynchronously in background thread upon button click and we add notification block in main thread to update the no of people in count label. Each thread (main and background ) have its own instance of realm object to access Realm Database. Because Realm Database is thread safe.


```
class Person: Object {
    dynamic var name = ""
    convenience init(_ name: String) {
        self.init()
        self.name = name
    }
}


override func viewDidAppear(_ animated: Bool) {
    let realmMain = try!  Realm ()
    self.people = realmMain.objects(Person.self)
    self.notification = self.people?.addNotificationBlock{ [weak self] changes in
        print("UI update needed")
        guard let countLabel = self?.countLabel else {
            return
        }
        countLabel.text = "Total People: \(String(describing: self?.people?.count))"
    }
}

@IBAction func addHandler(_ sender: Any) {
    print(#function)
    let backgroundQueue = DispatchQueue(label: "com.app.queue",
                                        qos: .background,
                                        target: nil)
    
    
    
    backgroundQueue.async {
        print("Dispatched to background queue")
        let realm = try! Realm()
        try! realm.write {
            for i in 1..<50 {
                let name = String(format: "rajan-%d", i)
                //print(#function, name)
                realm.add(Person(name))
            }
        }
        
    }
}

```
