### ISSUE TITLE
try! Realm() crash

### ISSUE THREAD

**Issue by danlniel** [realm/realm-cocoa#4845]
Hello,
I try to add with cocoapods, and doing simple things.
add "let realm = try! Realm()" in viewDidLoad
add to appDelegate "Realm.Configuration.defaultConfiguration.deleteRealmIfMigrationNeeded = true"
But then crash happened, i have no clue. Desperate here

## Actual Results
"libc++abi.dylib: terminating with uncaught exception of type NSException"

## Code Sample

Realm framework version: 2.5.1

Xcode version: 8.2

iOS/OSX version: 10.2

**Comment by evliu** [comment]
it might be useful to see what the error is by doing a `do-try-catch` instead of forcing a `try!`, then print out the error

**Comment by timtraversy** [comment]
If anyone else encounters this- I placed `try Realm()` in a `do-try-catch` and printed the `NSError`, and I realized it was failing because I had added new properties to one of my Realm objects, so I needed to migrate. So I just deleted my realm file (in Finder, outside of code), since I didn't need to preserve any data. This error was crashing Xcode entirely, which is kind of weird behavior.

**Comment by mendes-develop** [comment]
I was having the same problem and later on I realized I had a mistake when I was setting new properties to one of my Realm objects.
