### ISSUE TITLE
Updates to ignoredProperties in memory getting lost

### ISSUE THREAD

**Issue by michaelspecht** [realm/realm-cocoa#4877]
This could very well just be me doing something stupid. Basically, I have an Object that has a list of child objects, and when I try to modify an ignoredProperty on a child object and then access it, it still has the default value. I've put together a little sample project that demonstrates this.

```
class SomeObject: Object {
    dynamic var name = ""
    var children = List<ChildObject>()
}

class ChildObject: Object {
    var enteredValue = ""
    dynamic var name = ""
    
    override static func ignoredProperties() -> [String] {
        return ["enteredValue"]
    }
}

let realm = try! Realm()

let newObj = SomeObject()
newObj.name = "Parent object name"
let child = ChildObject()
child.name = "Child name"
newObj.children.append(child)

try! realm.write {
    realm.add(newObj)
}

array = Array(realm.objects(SomeObject.self))

let newString = "Some new string"
array.first!.children.first!.enteredValue = newString
assert(newString == array.first!.children.first!.enteredValue)
```
That assert fails for some reason.

Here is the full project.
[RealmTest.zip](https://github.com/realm/realm-cocoa/files/935462/RealmTest.zip)

**Comment by austinzheng** [comment]
Thanks for getting in touch with us.

Unfortunately, the behavior you're seeing is expected. Ignored properties are only guaranteed to be consistent across individual Swift instances, but retrieving an object from a collection creates a new Swift instance each time, thus the behavior that you see.

Normally this isn't problematic, since the Swift instance serves as a lightweight view to the underlying object in the database (and thus all instances of an `Object` pointing to the same underlying object should behave consistently), but ignored properties don't care about this relationship.

Hope that helps.

**Comment by michaelspecht** [comment]
Thanks for the prompt response, that does help.
