### ISSUE TITLE
A question about query after background thread write

### ISSUE THREAD

**Issue by hiXgb** [realm/realm-cocoa#4880]
I try to query results after background write, but the results is always empty. If change to sleep(5) the results is OK, please see the code below. 

```objective-c
dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
    // Import many items in a background thread
    dispatch_async(queue, ^{
        
        NSMutableArray *arr = [NSMutableArray new];
        for (int i = 0; i < 500; i ++) {
            // Create a standalone object
            Dog *mydog = [[Dog alloc] init];
            
            // Set & read properties
            mydog.name = [NSString stringWithFormat:@"Rex%d",i];
            mydog.age = i;
            NSLog(@"Name of dog: %@", mydog.name);
            [arr addObject:mydog];
        }
        
        // Realms are used to group data together
        RLMRealm *realm = [RLMRealm defaultRealm]; // Create realm pointing to default file
        
        // Save your object
        [realm beginWriteTransaction];
        [realm addObjects:arr];
        [realm commitWriteTransaction];
    });
    
    
    sleep(1);
    
    RLMRealm *realm = [RLMRealm defaultRealm]; // Create realm pointing to default file
    // Query
    RLMResults *results = [Dog objectsInRealm:realm where:@"name contains 'x'"];
    
    // Queries are chainable!
    RLMResults *results2 = [results objectsWhere:@"age > 8"];
    NSLog(@"Number of dogs: %li", (unsigned long)results2.count);
    
    while (results2.count == 0) {
        
        realm = [RLMRealm defaultRealm];
        results = [Dog objectsInRealm:realm where:@"name contains 'x'"];
        results2 = [results objectsWhere:@"age > 8"];
        
    }
```

**Comment by istx25** [comment]
Hi @hiXgb. Thanks for reaching out for support.

For now and in the future, I would like to request that you always fill out our issue template (found [here](https://github.com/realm/realm-cocoa/issues/new) which is designed to collect and prepare the information that we need to help you the best. For this question, I would appreciate it if you could let us know which versions of Realm and Xcode you're using as well as if you're using a dependency manager and if so, which one and what version. 

In the meantime though, I think I know why this is happening. 

I believe this is happening because the dispatch async block is, as you already know, executing the code inside the block on a background thread whereas the rest of the code (outside the dispatch async block) is being executed on the main thread.

In this situation, this is problematic because the code in the dispatch async block isn't necessarily executed right away or before the code after the block. It is instead queued and the task is executed when something internally decides it's its turn. 

So the reason you're not seeing your desired results with `sleep(1);` is because the dispatch async block isn't being executed within one second whereas it is executed within five seconds allowing you to see your desired results with `sleep(1);`.

One recommendation I would have is that you do some tests to see if you can drop `sleep(5);` down to 3 or 2 but I will say the speeds may be different for actual users in comparison to locally on your machines. Someone else may have a better suggestion but one better solution that I can recommend is that you do something like this:

```objective-c
dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
// Import many items in a background thread
dispatch_async(queue, ^{
    NSMutableArray *arr = [NSMutableArray new];
        
    for (int i = 0; i < 500; i ++) {
        // Create a standalone object
        Dog *mydog = [[Dog alloc] init];
            
        // Set & read properties
        mydog.name = [NSString stringWithFormat:@"Rex%d",i];
        mydog.age = i;
        NSLog(@"Name of dog: %@", mydog.name);
        [arr addObject:mydog];
    }
        
    // Realms are used to group data together
    RLMRealm *realm = [RLMRealm defaultRealm]; // Create realm pointing to default file
        
    // Save your object
    [realm beginWriteTransaction];
    [realm addObjects:arr];
    [realm commitWriteTransaction];

    // Create a blo
    dispatch_async(dispatch_get_main_queue(), ^{
        RLMRealm *realm = [RLMRealm defaultRealm]; // Create realm pointing to default file
        // Query
        RLMResults *results = [Dog objectsInRealm:realm where:@"name contains 'x'"];
    
        // Queries are chainable!
        RLMResults *results2 = [results objectsWhere:@"age > 8"];
        NSLog(@"Number of dogs: %li", (unsigned long)results2.count);
    
        while (results2.count == 0) {
            realm = [RLMRealm defaultRealm];
            results = [Dog objectsInRealm:realm where:@"name contains 'x'"];
            results2 = [results objectsWhere:@"age > 8"];
        }
    });
});
```

I've moved the code that was previously outside the (background) dispatch async block inside and wrapped it inside another dispatch async block that is on the main queue/thread. Please let me know if you have any other questions (or if I made any mistakes). Cheers!

**Comment by istx25** [comment]
One of my colleagues just suggested another solution (which is a lot better). Instead of wrapping the main thread code in a dispatch async block, it's better to use a notification block such as:

```objective-c
[[NSNotificationCenter defaultCenter] addObserverForName: kObserverName
                                                  object: nil
                                                   queue: [NSOperationQueue mainQueue]
                                              usingBlock:^(NSNotification *notification) {

    RLMRealm *realm = [RLMRealm defaultRealm];
    RLMResults *results = [Dog objectsInRealm:realm where:@"name contains 'x'"];
    
    RLMResults *results2 = [results objectsWhere:@"age > 8"];
    NSLog(@"Number of dogs: %li", (unsigned long)results2.count);
    
    while (results2.count == 0) {
        realm = [RLMRealm defaultRealm];
        results = [Dog objectsInRealm:realm where:@"name contains 'x'"];
        results2 = [results objectsWhere:@"age > 8"];
    }
}

dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
dispatch_async(queue, ^{
    NSMutableArray *arr = [NSMutableArray new];
        
    for (int i = 0; i < 500; i ++) {
        Dog *mydog = [[Dog alloc] init];
        mydog.name = [NSString stringWithFormat:@"Rex%d",i];
        mydog.age = i;

        NSLog(@"Name of dog: %@", mydog.name);
        [arr addObject:mydog];
    }

    RLMRealm *realm = [RLMRealm defaultRealm];

    [realm beginWriteTransaction];
    [realm addObjects:arr];
    [realm commitWriteTransaction];

    [[NSNotificationCenter defaultCenter] postNotificationName: kObserverName 
                                                        object: nil];
});
```

And again, don't hesitate to follow-up if you have additional questions. :-)

**Comment by jpsim** [comment]
Please don't use `NSNotificationCenter` to notify threads that transactions have been committed and data is available. That's inherently prone to race conditions. In other words, there are times where that will work, and others when it won't.

I strongly recommend using one of Realm's several existing [Notifications](https://realm.io/docs/swift/latest/#notifications) mechanisms to be notified when changes to objects you care about have been applied and are available to the Realm on your thread. Please see our documentation on notifications for details.

**Comment by istx25** [comment]
Ah, my bad. Still learning about those. Thanks JP! I'll let you continue on here.

**Comment by TimOliver** [comment]
I hope that answered your question, @hiXgb! Feel free to re-open this issue if you have any follow-up questions. Thanks! :)
