### ISSUE TITLE
dyld: Library not loaded realm

### ISSUE THREAD

**Issue by sassiwalid** [realm/realm-cocoa#4892]
## Bugs

i added a framework that i developed in ios to the new project. I tried to make the app universal (one framework work both in device and simulator) according to this tutorial create an ios universal framework . When i run my demo project using this universal framework i get this errors

```
dyld: Library not loaded: @rpath/Realm.framework/Realm
**Referenced from: /private/var/mobile/Containers/Bundle/Application/DDF71B22-F535-43E5-B770-D3425419B108/DemoSDk2.app/Frameworks/#######.framework/######### Reason: no suitable image found. Did find: /private/var/mobile/Containers/Bundle/Application/DDF71B22-F535-43E5-B770-D3425419B108/DemoSDk2.app/Frameworks/########.framework/Frameworks/Realm.framework/Realm: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/DDF71B22-F535-43E5-B770-D3425419B108/DemoSDk2.app/Frameworks/##########.framework/Frameworks/Realm.framework/Realm'**
```

## Version of Realm and Tooling

Realm framework version: 2.0

Realm Object Server version: ?

Xcode version: 7.3

iOS/OSX version: 10.12

Dependency manager + version: ?

**Comment by kishikawakatsumi** [comment]
@sassiwalid Maybe you forgot to add the parent path of RealmSwift.framework to the “Framework Search Paths” in build settings. Because RealmSwift.framework uses Realm.framework internally, so RealmSwift.framework should be able to find Realm.framework and linked to.

FYI: Unfortunately AppStore rejects if your app includes such nested frameworks. In other words, even if your attempt succeeds, no one can distribute apps that use the framework to AppStore. That is why RealmSwift.framework does not include Realm.framework.

**Comment by sassiwalid** [comment]
thank you, sure when i send my framework to the appstore, it's was rejected. so i decided to make realm outside of my framework. Best regards

**Comment by edward-gray** [comment]
I had the same issue in Xcode 11.4 and I fixed it by editing my pod file to:

platform :ios, '13.0'

target 'YourTarget' do
  #use_frameworks! -> !!! very important

  pod 'Realm', :modular_headers => true
  pod 'RealmSwift', :modular_headers => true

end
