### ISSUE TITLE
For in at RLMResults, speed

### ISSUE THREAD

**Issue by skarctop** [realm/realm-cocoa#4898]
```objc
RLMRealm *realm = [RLMRealm defaultRealm];
    RLMResults *results = [realm allObjects:@"xx"];

      NSTimeInterval start = CFAbsoluteTimeGetCurrent();
    for (RLMObject * object in results) {
    }    
    NSLog(@"count = %ld, spend time  %lf",results.count, CFAbsoluteTimeGetCurrent() - start);
```

   when count larger than 2W, spend about 1 sec,
  why is so slow , Can be quick?

**Comment by istx25** [comment]
Hi @skarctop. Please fill out [this issue template](https://github.com/realm/realm-cocoa/issues/new] and provide us with as much information as possible as well as which versions of Realm and tooling that you're using. Thanks.

**Comment by skarctop** [comment]
Realm version is 1.1.0
xcode version 8.3.2
iOS     version latest new

nsarray will be very quick, why RLMResults is so slow

**Comment by kishikawakatsumi** [comment]
@skarctop Because Realm defers memory allocation and copying memory as much as possible for performance. At the time you call the `allObjects` method, Realm doesn't allocate any elements of the `RLMResults`. It just returns a proxy object. The actual elements of `RLMResults` are created when you really access to each element (= in the loop). That's why iterating `RLMResults` takes longer time than `NSArray`. Instead, `NSArray` needs to create all objects before iteration, so it takes the same time or more at that time (also it consume more memory).

```objc
NSMutableArray *array = [NSMutableArray array];
for (int i = 0; i < 2500000; i++) {
    [array addObject:[TestObject new]];
}
// ^ this takes more 1 sec

RLMResults *results = [TestObject allObjects];
// ^ this takes less than 0.001 secs
```

Realm's architecture is more appropriate for actual use cases in mobile applications. Since it is a quite rare case to iterate all a large number of results. For example, when displaying data in `UITableView`, only a small amount of data is needed around same as the screen size.

**Comment by TimOliver** [comment]
I hope that answered your question @skarctop! Please let us know if you have any follow-up queries! :)
