### ISSUE TITLE
Hook reachability into token refresh subsystem

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#4905]
Right now the system that refreshes tokens just attempts to retry failed network requests nonstop (with some backoff delay), depending on the specific error.

~If reachability notes that there is no network connectivity, that subsystem should stop refreshing tokens.~ (see below) When connectivity is restored, that subsystem should refresh any outstanding tokens.

**Comment by bdash** [comment]
I'm not sure it's wise to halt attempts to refresh just because reachability says there may not be connectivity (we'd need to be certain that we're using reachability data for the specific host / port we need to talk to). It's definitely worth using the transition back to having connectivity as a trigger for refreshes, though.
