### ISSUE TITLE
Is casting from Realm Results<Object> to Swift array lead to blocking UI and slow performance?

### ISSUE THREAD

**Issue by peihsendoyle** [realm/realm-cocoa#4906]
I'm in stuck with this case, hope that someone will help me point this out.

My app calls API and save it to Realm database before showing to view (because we want the live update on all views). Everything works but it's somehow slow and block the UI every time we call load more (call API --> save to realm in spite of the numbers of items is just 10 per page).

I'm considering between 2 reasons:

1. I saved items to realm on main thread, so it leads to UI blocking. Someone told me add items to realm on background thread, but if I do that I have to access them after that immediately so I have to pass the data from background to main thread via "resolve" function (in Realm docs). Is it better?

2. I don't use Realm results from queries to show on tableView, so I have to cast it to swift array Array<>. Is it leads to UI blocking and slow performance?

Hope that someone was in this case like me, thanks everyone for attention.

**Comment by kishikawakatsumi** [comment]
@peihsendoyle 
> I saved items to realm on main thread, so it leads to UI blocking. Someone told me add items to realm on background thread

Yes, it depends on the amount of data you are adding though, parsing JSON and allocating model classes takes time, so doing them on a background thread is generally a good practice.

> if I do that I have to access them after that immediately so I have to pass the data from background to main thread via "resolve" function (in Realm docs). Is it better?

No, Realm `Results` and other Realm objects are auto-updated. You do not need to re-fetch or passing Results or objects beyond threads after you added/updated/deleted objects. Just reload table view after you committed a transaction.  See the auto-updating section of the document https://realm.io/docs/swift/latest/#auto-updating-objects and table view example code https://github.com/realm/realm-cocoa/blob/master/examples/ios/swift-3.0/TableView/TableViewController.swift

> I don't use Realm results from queries to show on tableView, so I have to cast it to swift array Array<>. Is it leads to UI blocking and slow performance?

Probably yes. Because Realm Results' Lazy loading and zero copy mechanism contribute greatly to performance. Copying Results to an Array means losing its advantage (the automatic update mentioned above also is lost). We strongly recommend you to use `Results` objects as data source directly instead of copying to an array.

For example, A `Results` object returned by Realm is just a proxy object, it does not allocate any objects at that time. It allocates memory only when accessing the properties of each element. On the other hand, copying `Results` to `Array` requires allocation of all objects at that time. It will cause slow performance.

**Comment by austinzheng** [comment]
I hope Katsumi's response answered your question, Hieu. If you have any further questions on this topic, feel free to re-open the issue. If you have additional questions, feel free to open new issues. And, as always, thank you for using Realm!
