### ISSUE TITLE
Realm crashes the app instead of raising errors

### ISSUE THREAD

**Issue by gsabran** [realm/realm-cocoa#4931]
I'm using RealmSwift pod.

It seems that Realm has chosen to crash the app when something is not done right instead of raising a Swift exception that can be caught, and defining function signatures as throwing. This is very hard to work with and makes it almost impossible to be totally sure that all errors are handled well.

**Comment by stel** [comment]
Could you provide more info about the issue you're getting: error messages, console logs etc? Realm logs information when throwing exceptions and it can help debug when things go wrong.

**Comment by austinzheng** [comment]
Realm Swift throws Swift exceptions when it encounters recoverable errors, and uses `fatalError()` to deal with logic errors (programmer violates an API precondition). For example, accessing a Realm collection at an out of bounds index is a programmer error, and will cause the application to trap. This is by design.

If you are encountering C++ exceptions please feel free to file a new ticket, filling out the issue template.

**Comment by gsabran** [comment]
Thanks. @austinzheng it's be nice to give developers who'd rather caught errors than crash the app the option to do so by not using `fatal_error` but throwing swift errors. I'm part of those who don't want such thing in production. Is there a place for features requests?

**Comment by jpsim** [comment]
Realm exposes _recoverable_ errors via `NSError` pointers in our Objective-C APIs and by annotating initializers/methods as `throws` in Swift. Those you should definitely handle in your usage of Realm.

However, for _unrecoverable_ errors, we'll use `fatalError()` or unhandled Objective-C runtime exceptions, as is idiomatic in Objective-C and Swift, such as assertions in the Swift standard library or exceptions in Foundation.

All these unrecoverable errors should be avoided by reading our documentation and ensuring proper use of our public APIs rather than attempted to be recovered at runtime.
