### ISSUE TITLE
[realmModel class] function return "RLM:Managed 4 realmModelClass"

### ISSUE THREAD

**Issue by fuboyou** [realm/realm-cocoa#4949]
## Goals

I want to get realmModel Property List

## Steps to Reproduce

create a model based on Realm, call function class_copyPropertyList([model class], &propertyCount), now return NULL, [Model class] return "RLM:Managed 4 Model"

## Code Sample

create a realm object;
unsigned int propertyCount, i;
objc_property_t *properties = class_copyPropertyList([realmObject class], &propertyCount);

## Version of Realm and Tooling

Realm framework version:  
CocoaPods Realm 2.7.0

Xcode version:
 8.3 (8E162)

iOS/OSX version:
 ios 10.3.1(14E304)

**Comment by bdash** [comment]
Instances of your model class will really end up being one of two subclasses that Realm generates at runtime: one for unmanaged instances, and one for managed instances. These subclasses provide implementations of property getters and setters that provide Realm's semantics (for instance, the managed subclass properties read / write from the underlying Realm file rather than from the corresponding instance variable).

Depending on what you're trying to do you can either:
1) Walk up the class hierarchy until you get to a non `RLM:` prefixed class. This will be the real model class that contains the Objective-C properties.
2) Use Realm's `RLMObjectSchema` to learn about the managed properties of the model class. This can be accessed via the `objectSchema` property on an instance of an `RLMObject` subclass.

**Comment by fuboyou** [comment]
Thank you very much，I try override `- (Class)class` to My RealmModel, like this：
```
@implementation myModel
- (Class)class
{
    return NSClassFromString(@"myModel");
}
@end
```
it's work to me , but can be affect Realm？

**Comment by bdash** [comment]
Why do you want to do that? There's an expectation that `-class` returns the actual class of the object.

**Comment by fuboyou** [comment]
Sorry for my English is not very good, may describe a bit of a problem, I want to get the object of the real class because it is dependent on a tripartite library XXX, the library passed into an array, the array element is realmObject, XXX internal use `class_copyPropertyList ([realmObject Class], & propertyCount)` to get the member variable information, so you want to return the real class information，
Although RLMObjectSchema can get member information, but I can not change the implementation of the three-party library XXX, can only get real class information，Thanks again

**Comment by fuboyou** [comment]
if I try override `- (Class)class` to My RealmModel, Will the Realm be affected?

**Comment by austinzheng** [comment]
We can't guarantee that Realm will continue to work if you try to override `-class`. If you can, pass a new, unmanaged, empty instance of your class into the `XXX` library API instead of your Realm object.

If all else fails, you can try using the Objective-C runtime API `object_setClass()` to force the object's class back to the model class right before calling the `XXX` library API, and force it back to the original internal subclass after the `XXX` library API returns. But we can't guarantee anything using this approach, especially if the `XXX` API does anything besides getting a list of properties for the class.

**Comment by fuboyou** [comment]
Create a new object to convert,  it work for me. Thanks for the realm team.
