### ISSUE TITLE
Not possible to encrypt and then sync? 

### ISSUE THREAD

**Issue by sree127** [realm/realm-cocoa#4971]
## Goals

Encrypt and then sync the database 

## Expected Results

Encrypted data in the Object Server Database

## Actual Results

Data not getting encrypted

## Steps to Reproduce

nil

## Code Sample

```
let config = Realm.Configuration(syncConfiguration: SyncConfiguration(user: user, realmURL: syncServerURL), encryptionKey: Utility().getKey() as Data)
self.realm = try! Realm(configuration:  config)
```
Screenshot of database below:
![screen shot 2017-05-23 at 10 56 03 am](https://cloud.githubusercontent.com/assets/3157263/26339604/adea37c0-3fa6-11e7-9cc8-492d08a844c6.png)

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323

Xcode 8.3.2
Build version 8E2002

1.1.0.rc.2
Realm (2.7.0)
RealmSwift (2.7.0)

**Comment by austinzheng** [comment]
Thanks for getting in touch, and sorry that you're experiencing this issue. How do you know the data is not being encrypted -- is it because you can open your encrypted Realm using the Realm browser?

**Comment by sree127** [comment]
@austinzheng Hey, thanks for replying. Yes, exactly. Because when viewed through Realm Browser its not encrypted. The data we're trying to store is little confidential and don't think its really good idea to see those data :) 

Currently we'd to encrypt each and every field before saving to Realm :(

**Comment by jpsim** [comment]
@sree127 is it possible that you also asked this question on Stack Overflow? https://stackoverflow.com/q/44324038/373262

If that's the case, I think it's likely that you're dealing with two separate Realms, and that you're loading the unencrypted local Realm in the browser, not the encrypted synchronized Realm.

**Comment by sree127** [comment]
@jpsim Hey, that was not me :)  [https://stackoverflow.com/q/44324038/373262](url)

I created a new project just to try if it works. I used only one Realm configuration and it still didn't encrypt the data. 

Attaching the complete code here: 
[https://pastebin.com/zeNybpGA](url)

**Comment by bdash** [comment]
@sree127, I apologize for the delay in getting back to you.

To make sure I understand you correctly, your concern is that the data stored by the Realm Object Server is not encrypted, and that if you open the Realm from the Object Server using Realm Browser, you are not prompted for the encryption key?

I believe this is currently the expected behavior. The encryption key you specify indicates that the _local_ copy of the Realm is encrypted. This ensures that the data stored on the user's device is encrypted. It does not control how the data is stored on the server. If server-side encryption is something that's of interest to you, I'd suggest [filing an enhancement request in the realm-mobile-platform repository](https://github.com/realm/realm-mobile-platform/issues/new).

If I've misunderstood what you're asking, please let me know.

**Comment by stel** [comment]
@sree127 do you need any further help here or can we close this issue?

**Comment by sree127** [comment]
@stel  We encrypted each field before storing. Little hectic, but it works.
