### ISSUE TITLE
Background thread notification token issue

### ISSUE THREAD

**Issue by pauluhn** [realm/realm-cocoa#4984]
## Goals

1. Listen for realm changes (on main or bg threads) without significant realm file size increase
2. Listen for realm changes on background thread reliably

## Expected Results

1. Use notification tokens with small overhead
2. Notification block on background thread called on all realm updates

## Actual Results

1. Realms with listeners grow in file size; more listeners, more growth; use background thread, even more growth
![simulator screen shot may 30 2017 2 59 23 pm](https://cloud.githubusercontent.com/assets/6515165/26603110/4cbf4148-454b-11e7-87f1-d8c9fea11e1b.png)
2. Notification block is not called on all realm updates
```
517865579.834305: DEBUG: thread is about to start; stop scheduled after: 8.7
517865588.549028: DEBUG: thread is about to stop; start scheduled after: 0.9
517865588.552048: DEBUG: total received = 1003
517865589.456269: DEBUG: thread is about to start; stop scheduled after: 8.6
517865598.089873: DEBUG: thread is about to stop; start scheduled after: 0.8
517865598.090624: DEBUG: total received = 1007
517865598.901256: DEBUG: thread is about to start; stop scheduled after: 9.3
517865608.210002: DEBUG: total received = 0
517865608.210002: DEBUG: thread is about to stop; start scheduled after: 0.3
517865608.511731: DEBUG: thread is about to start; stop scheduled after: 14.7
517865623.232688: DEBUG: total received = 0
517865623.232688: DEBUG: thread is about to stop; start scheduled after: 0.6
517865623.843544: DEBUG: thread is about to start; stop scheduled after: 9.9
517865633.747636: DEBUG: total received = 0
517865633.747639: DEBUG: thread is about to stop; start scheduled after: 1.0
517865634.748254: DEBUG: thread is about to start; stop scheduled after: 12.3
517865647.049919: DEBUG: thread is about to stop; start scheduled after: 0.2
517865647.049979: DEBUG: total received = 0
517865647.25054: DEBUG: thread is about to start; stop scheduled after: 7.2
517865654.453644: DEBUG: thread is about to stop; start scheduled after: 0.7
517865654.453788: DEBUG: total received = 0
517865655.160422: DEBUG: thread is about to start; stop scheduled after: 11.1
517865666.26647: DEBUG: total received = 0
517865666.26647: DEBUG: thread is about to stop; start scheduled after: 0.4
517865666.697211: DEBUG: thread is about to start; stop scheduled after: 5.9
517865672.598778: DEBUG: total received = 0
517865672.598778: DEBUG: thread is about to stop; start scheduled after: 0.3
517865672.899108: DEBUG: thread is about to start; stop scheduled after: 12.9
517865685.804484: DEBUG: thread is about to stop; start scheduled after: 0.3
517865685.834585: DEBUG: total received = 368
```
## Steps to Reproduce

1. Run sample app and watch UI and file system
2. Run sample app and watch console

## Code Sample

https://github.com/pauluhn/RealmReadWriteTestApp.git

## Version of Realm and Tooling

```
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73

/Applications/Xcode.app/Contents/Developer
Xcode 8.3.2
Build version 8E2002

/Users/pauluhn/.rbenv/shims/pod
1.2.1
Realm (2.7.0)
RealmSwift (2.7.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)


(not in use here)

/usr/bin/git
git version 2.11.0 (Apple Git-81)
```

**Comment by pauluhn** [comment]
I made some updates today to the sample app. Running the app using older commit `fd9a40206a` for 50k count (and 15k) resulted in the following:
```
write only:       13 mb   (5 mb)
read:             14 mb (4.5 mb)
listener:         36 mb  (12 mb)
two listeners:    56 mb  (22 mb)
thread listener: 576 mb (240 mb)
```
Running the app for a few seconds with latest commit `e83e30a581` which reuses above created realms:
```
write only:       11 mb (6.5 mb) // not sure why the first two increased
read:             11 mb (6.5 mb)
listener:         12 mb   (7 mb)
two listeners:    12 mb  (11 mb)
thread listener:  13 mb (6.5 mb)
```
The final test was to remove realms and rerun the app on latest commit (took a long time, so I stopped at 15k):
```
write only:       4.5 mb
read:              10 mb
listener:         7.5 mb
two listeners:     11 mb
thread listener:   33 mb
```
So maybe the issue on file size can be solved but am still getting zero change notifications on background thread.

**Comment by austinzheng** [comment]
Thanks for the update. I plan on looking at your app today and seeing what I can figure out from it.

**Comment by bdash** [comment]
Hi @pauluhn, thanks so much for providing a sample app that demonstrates the problem you are encountering. I'm sorry it's taken so long for us to follow up with you. This got a little lost in the shuffle of WWDC.

When running your sample app, I can reproduce the problem you describe (the background thread often reports 0 notifications received). In attempting to understand what your sample app is doing, I noticed a couple of odd things:
1. You immediately asynchronously schedule 100 write transactions to each of 5 Realm files. Given that Realm only supports a single active write transaction per Realm file, you immediately end up with a huge number of threads parked waiting to acquire the write lock. After the threads acquire the write lock and perform their write transaction, they immediately schedule another write. This means there are constantly hundreds of concurrent attempts to acquire a write transaction on each Realm. 
2. Each of the write transaction uses `Realm.asyncOpen` to open the Realm. This is relatively expensive compared to opening the Realm directly, and appears to be unnecessary in this context (you're already on a background queue, so why bother having Realm jump to another background queue to open the Realm file?).
3. The `shouldCompactOnLaunch` block you provide can result in repeatedly attempting to compact a Realm file if compacting is unable to reduce the Realm file below the criteria you specify (10MB, < 10% slack space). These repeated compacts end up significantly impeding writes of whichever Realm hits them.

I've locally addressed these points by making the following changes:
1. Create a serial queue per Realm file, and schedule the write operations on the appropriate queue.
2. Open the Realm file directly rather than using `asyncOpen`.
3. Disable the compact on launch blocks.

After doing this I still sometimes see 0 notifications being delivered on the listener thread, but it's much less frequent than before. There's also no longer hundreds of dispatch worker threads sitting blocked waiting to acquire Realm write transactions (in real applications, tying up huge number of dispatch worker threads like this can result in deadlocks, so I'd certainly avoid this pattern in any production code you're writing).

I'll take another look at this next week to try and understand why there are sometimes no notifications delivered.

**Comment by jpsim** [comment]
This needs further investigation to identify why notifications are sometimes still not delivered, even after the changes reported by @bdash above.
