### ISSUE TITLE
List cant append Lazy collections

### ISSUE THREAD

**Issue by Genhain** [realm/realm-cocoa#5055]
## Goals
To append to the contents of a Realm list that was produced using the non string version of `filter` and `map` to another Realm list using `list.append(objectsIn: otherList)`

## Expected Results
The contents of the `otherList` to now exist as elements in `list`

## Actual Results
the contents are not appended

## Steps to Reproduce
Create a `List` of an `Object` type then attempt to use one of the described functions and then attempt to append that list to another.

## Code Sample
I produced the following snippet in a swift `.playground`

	import RealmSwift

	class Thing: Object {
		dynamic var name: String = ""
		
		convenience init(name: String) {
			self.init()
			self.name = name
		}
	}

	var things: List<Thing> = List<Thing>()
	things.append(Thing(name:"a"))
	things.append(Thing(name:"b"))
	things.append(Thing(name:"c"))

	let filteredThings = things.filter { $0.name == "a" }

	for thing in filteredThings {
		print("first loop: \(thing)")
	}

	things.removeAll()
	things.append(objectsIn: filteredThings)

	for thing in things {
		print("second loop: \(thing)")
	}

## Version of Realm and Tooling

Realm framework version: 2.8.3

Realm Object Server version: ?

Xcode version: 8.3.3

iOS/OSX version: ?

Dependency manager + version: cocoapods 1.2.1

**Comment by Genhain** [comment]
# Followup information

`list.filter { /*code*/ }` returns a lazy collection of some type in the case of the code sample a `LazyFilterBidirectionalCollection` rather than `[Things]`

This issue can be solved by doing the following on the list
`let filteredThings = Array(things).filter { $0.name == "a" }`

Although a solution for the current problem it's a tad cumbersome. Should it no be able to append without this step or is there more to it?

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. The behavior you're seeing is expected.

`LazyFilterBidirectionalCollection` in this case wraps a reference to the original `List<T>`. Since Realm's `List<T>` is a reference type, not a copy on write collection like the Swift collections, when you remove all objects from `things` you also remove all objects from the collection backing `filteredThings`, since they are one and the same.

Your "workaround" works because you are copying the items to a new collection (presumably a Swift array), rather than creating a `LazyFilterBidirectionalCollection` backed by a reference to the original collection.

**Comment by austinzheng** [comment]
It's been a few days so I'm going to close this ticket. If you have further questions or issues please feel free to open a new one.

**Comment by Genhain** [comment]
Thanks for replying, apologies i've been terribly busy. But to clarify essentially because it's all references and filter does not produce copies, when i remove them from the original List it removes them from the filtered List. Thus it ends up me trying to append an empty array to an array.
