### ISSUE TITLE
Errors when archiving with Xcode 8.3.3

### ISSUE THREAD

**Issue by tirrorex** [realm/realm-cocoa#5125]
It seems archiving an app containing realmSwift makes a bunch of logic errors appearing with xcode 8.3.3, is the team aware of it?
If needed i will provide a screen or something containing said errors.

## Expected Results
No errors

## Actual Results
A lot of log errors appearing at buildtime

## Steps to Reproduce
Archiving an app for production containing realmSwift

## Version of Realm and Tooling

  - RealmSwift (2.8.3):
    - Realm (= 2.8.3)

Xcode version: 8.3.3

Dependency manager + version: cocoapods 1.2.1

**Comment by jpsim** [comment]
Creating a fresh project in Xcode 8.3.3, using CocoaPods 1.2.1, I am able to successfully archive an app using Realm Swift 2.8.3.

Here's the project: https://static.realm.io/debug/GH5125.tgz

Here's the command I ran:

```bash
$ xcodebuild -workspace GH5125.xcworkspace -scheme GH5125 -configuration Release archive -archivePath GH5125.xcarchive
[lots of output...]
Validate /Users/jp/Library/Developer/Xcode/DerivedData/GH5125-adryxrsxuxgewddnrwxcgmwjtayf/Build/Intermediates/ArchiveIntermediates/GH5125/InstallationBuildProductsLocation/Applications/GH5125.app
    cd /Users/jp/Downloads/GH5125
    export PATH="/Applications/Xcode-8.3.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-8.3.3.app/Contents/Developer/usr/bin:/usr/local/opt/rbenv/shims:/Users/jp/.rbenv/shims:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:/usr/local/opt/rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/jp/Library/Developer/Xcode/DerivedData/GH5125-adryxrsxuxgewddnrwxcgmwjtayf/Build/Intermediates/ArchiveIntermediates/GH5125/InstallationBuildProductsLocation/Applications/GH5125.app -validate-for-store

Touch /Users/jp/Library/Developer/Xcode/DerivedData/GH5125-adryxrsxuxgewddnrwxcgmwjtayf/Build/Intermediates/ArchiveIntermediates/GH5125/BuildProductsPath/Release-iphoneos/GH5125.app.dSYM
    cd /Users/jp/Downloads/GH5125
    export PATH="/Applications/Xcode-8.3.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-8.3.3.app/Contents/Developer/usr/bin:/usr/local/opt/rbenv/shims:/Users/jp/.rbenv/shims:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:/usr/local/opt/rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin"
    /usr/bin/touch -c /Users/jp/Library/Developer/Xcode/DerivedData/GH5125-adryxrsxuxgewddnrwxcgmwjtayf/Build/Intermediates/ArchiveIntermediates/GH5125/BuildProductsPath/Release-iphoneos/GH5125.app.dSYM

** ARCHIVE SUCCEEDED **
```

---

In the future, I'd appreciate if you could be more thorough in your "steps to reproduce". Please be specific in exactly what we can do to trigger a problem you're seeing. This will save you (and us) quite a bit of time.

**Comment by tirrorex** [comment]
I never said the archive build didn’t succeeded.
Archive the build with xcode and not the command line and you will see what i am talking about.

**Comment by jpsim** [comment]
> I never said the archive build didn’t succeeded.

You said "It seems archiving an app containing realmSwift makes a bunch of logic errors appearing with xcode 8.3.3" and didn't share further steps to reproduce, so I came up with the best way I could to fill in the blanks.

I tried again just now with the Xcode GUI, per your last comment, with no issues again. I've attached the logs Xcode produced during the archive here so that you can see how they differ from yours: 
[Archive GH5125_2017-07-16T12-35-27.rtf.zip](https://github.com/realm/realm-cocoa/files/1151301/Archive.GH5125_2017-07-16T12-35-27.rtf.zip)

So once more, I ask for detailed steps that I could follow in order to reproduce the issue you're seeing. Without you telling me how to recreate the problem, I'm afraid I won't be able to help you.

You also haven't shared _what_ errors you're seeing, only "A lot of log errors appearing at buildtime". If you were more specific, I might be able to research the errors you're seeing even if I can't trigger them myself.

**Comment by tirrorex** [comment]
> So once more, I ask for detailed steps that I could follow in order to reproduce the issue you're seeing. 
If I had additionnal steps besides archiving the build with xcode don't you think that i would've share them? I just don't have any, the only thing i did is archiving the build and i cannot even reproduce this behaviour since the build changed meanwhile.
And like i said 
> If needed i will provide a screen or something containing said errors.
If you don't ask for it don't blame me for not sharing them... i am just sharing information, i don't need a fix.
Anyway, closing this
