### ISSUE TITLE
`List` should conform to `MutableCollection` rather than `RangeReplaceableCollection`?

### ISSUE THREAD

**Issue by austinzheng** [realm/realm-cocoa#5150]
`List` doesn't conform exactly to `RangeReplaceableCollection`'s semantics, and `MutableCollection` didn't exist when we first decided `List`'s conformance. Revisit this for 3.0.

**Comment by jpsim** [comment]
I misremembered when I spoke earlier, `MutableCollection` _did_ actually exist when we considered `List` conformance to Swift collection protocols, it was called `MutableCollectionType` in Swift 1.x: http://swiftdoc.org/v1.2/protocol/MutableCollectionType/

I don't recall why we went with conformance to `RangeReplaceable` though, and due to the leaky abstraction, it's worth revisiting the decision.

**Comment by austinzheng** [comment]
My guess would be trying to replicate `Swift.Array`'s semantics as closely as possible?

**Comment by austinzheng** [comment]
Fixed in #5276.
