### ISSUE TITLE
Crash during Realm.init when wrapping app with XenMobile

### ISSUE THREAD

**Issue by ADShawnHampton** [realm/realm-cocoa#5151]
## Goals

Allow mobile app to be wrapped with XenMobile.

## Expected Results

No crashes.

## Actual Results

Crash in Realm.init.
![screen shot 2017-07-20 at 3 14 28 pm](https://user-images.githubusercontent.com/8866667/28441618-9211dc8c-6d60-11e7-84b4-69e18dc26aee.png)

## Steps to Reproduce

Wrap app with XenMobile and use Realm.init

## Code Sample

let realm = try Realm()

## Version of Realm and Tooling

Realm framework version: ?
RealmSwift : 2.2.0

Realm Object Server version: ?

Xcode version: ?
8.2.1

iOS/OSX version: ?
iPhone OS 10.3.2

Dependency manager + version: ?
Cocoapods 1.2.1

**Comment by bdash** [comment]
This crash is in code called by CitrixDylib.dylib, which appears to be intercepting system calls that Realm is making. We can't guarantee that Realm will work correctly if the basic system calls that we rely on are being intercepted by third-party code. In this case, the problem seems likely to originate within CitrixDylib.dylib rather than Realm itself.

**Comment by ADShawnHampton** [comment]
Okay thank you bdash!
