### ISSUE TITLE
To-Many Relationships issue

### ISSUE THREAD

**Issue by baiwhte** [realm/realm-cocoa#5153]
I having some problem about to-many relationships

Here is my models:
```objc
@interface YSDailyNews : RLMObject
@property NSString *dailyNewsId;
.....
@property RLMArray<YSColumns> *columns;
@end

@implementation YSDailyNews
+ (NSString *)primaryKey {
    return @"dailyNewsId";
}
@end

@interface YSColumns : RLMObject

//@property (nonatomic, copy) NSString *iD;
@property NSString *dailyNewsId;
@property NSString *columnsId;
....
@property (readonly) RLMLinkingObjects *owners;

@end

@implementation YSColumns
+ (NSString *)primaryKey {
    return @"columnsId";
}
@end

+ (NSDictionary *)linkingObjectsProperties {
    return @{
             @"owners": [RLMPropertyDescriptor descriptorWithClass:YSDailyNews.class
                                                      propertyName:@"columns"],
             };
}
```

 I got some datas from server about YSDailyNews and YSColumns, and I save them every times. then I user Realm Browser Open the realm database, It shows that In YSDailyNews table:
![a](https://user-images.githubusercontent.com/20255561/28457624-6a634020-6e39-11e7-9210-cc119da734a2.png) It has 10 records but in YSColumns table only 5 records.
![b](https://user-images.githubusercontent.com/20255561/28457831-2851edac-6e3a-11e7-94d8-f9fbc7324b56.png)

Why it is and How to solve it?

I having an other problem yet, I use cocoapods in static framework , then my project cannot print log in console use NSLog or using po ...

Version of Realm and Tooling

Realm framework version: 2.8.1
Xcode version: 8.3.2
iOS/OSX version: iPhone6s, iOS 10.3.2

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. We will need more information to solve this problem.

Can you change your project to use the Realm binaries available from our web site ([this link](https://static.realm.io/downloads/objc/realm-objc-2.8.3.zip)), and then use `NSLog` to print out the count and contents of `columns`? It's not possible just from the screenshots and code you've provided to understand what is going on.

**Comment by baiwhte** [comment]
Thank you for providing the link, and I downloaded the realm.framework from the link, then write a ios project use static framework.

run this project , and click 'AddColumns' button, will print out the count and contents of columns,
and print out the count of YSColumns table's records. 

i don't understand why i call 'createOrUpdateInRealm: withValue:' method, the count will add.
I thought it only update data , if the primaryKey don't changed.

note: because cannot upload large files , so i delete the framework from my project.

[RealmToManyRelationshipsDemo.zip](https://github.com/realm/realm-cocoa/files/1167321/RealmToManyRelationshipsDemo.zip)

**Comment by kishikawakatsumi** [comment]
Thank you for the reproducible project. I can reproduce the issue. It is expected behavior. `RLMArray` allows holding duplicates. 5 `YSColumns` objects are created and they are added to `YSDailyNews`'s `columns` array, then they are saved to Realm when I click "AddColumns" button. If click "AddColumns" button again, 5 `YSColumns` objects are created again and they are also added to `YSDailyNews`'s `columns` array. So `columns` has 10 `YSColumns` objects. But since the objects have the same primary key (1 to 5), they will overwrite duplicate objects when saved in Realm. Therefore, the number of objects stored in Realm will remain five. Though I'm not sure what you want to do, 
if you want to store ten objects in Realm, change the primary key for each object or remove the primary key definition.
If you do not want to save duplicate objects in RLMArray, you need to remove duplicates yourself.

**Comment by baiwhte** [comment]
Thanks your answer!  I solved the probrem according to your method.
