### ISSUE TITLE
Problem trying to get a value by date without time

### ISSUE THREAD

**Issue by jlubeck** [realm/realm-cocoa#5156]
## Goals

Search for an object by day without time. 

## Expected Results

Get an object from the DB

## Actual Results

I get no objects

## Code Sample

This is the JSON of my objects before going into the DB:
```
{
currency_id : 32,
date : "2017-07-22",
id : 115266,
value : 183.45
}
```

This is how they look on Realm Browser:
![Alt text](https://monosnap.com/file/zNDYrWyEnwujS3ZOv7a87YYiQcqpfu.png)

And this is my method to search for the object:
```
+ (ChartPoint*)getChartPointWithCurrencyID:(NSString*)identifier andDate:(NSDate*)date{
	NSDateFormatter *formatter = [NSDateFormatter new];
	formatter.dateFormat = @"yyyy-MM-dd";
	NSString *dateString = [formatter stringFromDate:date];
	date = [formatter dateFromString:dateString];
	return [[ChartPoint objectsWhere:@"currencyID =[c] %d AND date = %@", identifier.intValue, date] firstObject];
}
```

I initially tried without the formatter, but without any luck either. I tried with the formatter so that I would get the same input as the JSON. (day only without time). But didn't work either.

## Version of Realm and Tooling

Realm framework version: 2.8.0

Realm Object Server version: n/a

Xcode version: 8.3.3

iOS/OSX version: 10.3

Dependency manager + version: Cocoapods 1.2.0

**Comment by bdash** [comment]
`NSDate` objects represent a moment in time. If you’d like to query for objects whose date property falls on a specific day, you’ll want to use `NSCalendar` to find the `NSDate`s that represent the start and end of that day, and perform a query for dates that fall between those two points.

You’ll also want to be sure that you’re storing dates in a consistent time zone, since otherwise you may run into issues if you store it using the current local time zone and are later in a different time zone when you perform your query.

**Comment by jlubeck** [comment]
Hi @bdash. I thought that NSDates by default use UTC. And I thought I reassured that when I saw that all of the objects on my Realm DB are being stored by default with the time 00:00:00. 

I'm going to try to set everything in UTC to see if it works that way and get back.

**Comment by bdash** [comment]
`NSDate` represents a point in time, independent of any time zone. It's when you create or examine a `NSDate` that you need to be wary of time zones, since questions like "on which day does this point in time fall" inherently require considering a time zone in order to define the duration of that day.

**Comment by jlubeck** [comment]
Just by forcing the timezone to use in the delegate everything is  working now
```
[NSTimeZone setDefaultTimeZone:[NSTimeZone timeZoneWithAbbreviation:@"GMT"]];
```
thanks!
