### ISSUE TITLE
realm file is broken for some reason

### ISSUE THREAD

**Issue by boboboa32** [realm/realm-cocoa#5161]
The realm file should be deleted when user logout and create new one when login.
I found this case the realm file is not deleted and the file can't opened by realm browser, alert like below.
![898559dd-0a2a-4582-a111-5c5d3b389dfe](https://user-images.githubusercontent.com/278816/28554561-b8856940-712c-11e7-824a-192bf5e4d633.png)
So what can cause this problem? maybe crash while committing transaction?
thanks~

realm version: objc 2.8.2

**Comment by jpsim** [comment]
If you're deleting a Realm file and you're ending up with a corrupt file, it's probably because the deletion didn't complete successfully, or that Realm APIs were still accessing the file while it was being deleted. We can't guarantee the consistency of Realm files if you're changing them via external APIs, such as file system operations.

**Comment by boboboa32** [comment]
I add this check to see if it works
```objc
if ([[RLMRealm defaultRealm] inWriteTransaction]) {
      [[RLMRealm defaultRealm] cancelWriteTransaction];
}
```

**Comment by austinzheng** [comment]
The requirement is stricter than simply not being in a write transaction.

To safely delete a Realm file after the Realm has been opened, the Realm needs to be closed. This only happens when:
- There are no more valid references to the Realm, or any managed objects from the Realm.
- All autorelease pools that previously contained valid references to the Realm (or managed objects) are drained.

It's safer and easier to delete Realm files upon app launch, or at least before you open any Realms.
