### ISSUE TITLE
Realm swift: App group in realm browser

### ISSUE THREAD

**Issue by pak-amsiq** [realm/realm-cocoa#5163]
Hello everyone. 

I'm having a problem with accessing my database through Realm Browser, when my Realm database uses app groups. 

I'm downloading my app container through xCode devices, and read it with realm browser. 
When using app group the browser shows me an empty file, but the database exist in runtime.

It works just fine, when I'm saving to default location.

Does anyone know how to download/read the database saved in app group?

Thank you!

**Comment by austinzheng** [comment]
Thanks for getting in touch with us! When you say you are having a problem, is it because you get the file out of the app group's shared directory and the file is empty when opened in the Realm browser, because you can't find the file at all, or some other reason? Can you send us the Realm file in question so we can take a look at help@realm.io, and provide us a more detailed description of the problem?

**Comment by pak-amsiq** [comment]
Thank you. I just sent an email to help@realm.io.

**Comment by kishikawakatsumi** [comment]
Continue in mail support https://secure.helpscout.net/conversation/403408909/10738/?folderId=366141

**Comment by kishikawakatsumi** [comment]
IIRC, there is no way to export an app group container from devices using Xcode.
https://openradar.appspot.com/radar?id=5021353337946112
