### ISSUE TITLE
asyncOpen doesn't handle authentication errors

### ISSUE THREAD

**Issue by stel** [realm/realm-cocoa#5188]
When open realm user doesn't have permission for with `asyncOpen` its callback is never called.

```Swift
let configuration = Realm.Configuration(
    syncConfiguration: .init(user: nonAdminUser,
                             realmURL: URL(string: "realm://localhost:9080/__admin")!)
)

Realm.asyncOpen(configuration: configuration) { realm, error in
    // never called
}
```

`SyncManager.shared.errorHandler` reports auth error.

Realm framework version: 2.9
Realm Object Server version: 1.8.2

**Comment by jpsim** [comment]
I'd say the underlying issue is actually in sync, since `wait_for_download_completion` never invokes its callback if the user does not have permission to access the Realm, and the binding can't monitor the shared error handler to cancel that request since it can't associate the error with _which_ `asyncOpen` call triggered it.

**Comment by bdash** [comment]
Blocked by realm/realm-sync#1501.

**Comment by Damnum** [comment]
@bdash what issue do you mean? That link is dead.

**Comment by austinzheng** [comment]
It's a link to a private repository, hence it shows up as a 404 to anyone without access. We'll post to this ticket if there is anything to report.
