### ISSUE TITLE
RLMRealmConfiguration.syncConfiguration is missing from the API documentation

### ISSUE THREAD

**Issue by bdash** [realm/realm-cocoa#5240]
The [API documentation for `RLMRealmConfiguration`](https://realm.io/docs/objc/latest/api/Classes/RLMRealmConfiguration.html) does not mention the `syncConfiguration` property. This property is declared in a category on `RLMRealmConfiguration` that is for some reason annotated with the `:nodoc:` attribute.

@austinzheng, do you recall why the `:nodoc:` attribute was added back in https://github.com/realm/realm-cocoa/commit/b768f0b08ade30e2e30e594f02f71ada719776c4#diff-6cb54647727d874ca9774095f53bf554?

**Comment by austinzheng** [comment]
The intention behind adding `:nodoc:` to the extension declaration would have been to suppress a Jazzy warning without suppressing documentation generation for the method inside the extension. If that `:nodoc:` can be removed without causing a warning, it should definitely be removed; otherwise it can probably be replaced by a basic docstring.

**Comment by bdash** [comment]
Removing the `:nodoc:` results in a warning about the extension being undocumented. Replacing it with a documentation comment avoids that warning, and the comment doesn't appear to be shown anywhere in the generated documentation (?!). I'll fix this, along with another issue I noticed.
