### ISSUE TITLE
Crashing on compactRealm, out of memory

### ISSUE THREAD

**Issue by misterlib** [realm/realm-cocoa#5245]
We just released an app to production that is migrating data out of Core Data into Realm. It works on many devices, but we are getting a lot of "Cannot allocate memory" errors.

## Goals
Move through a migration without crashing.

## Expected Results
Data is migrated out of core data and into realm without crashing due to being out of memory.

## Actual Results
Most migrations are working. For others, even with a lot of free space available on their devices, the app crashes with this error coming though BugSnag. Here is an example: 

> 
RCTFatalException: Exception 'mmap() failed: Cannot allocate memory size: 1476395008 offset: 0' was thrown while invoking compactRealm on target CoreDataToRealmMigrator with params ( 1511 ) in mh_execute_header

## Steps to Reproduce
We know that the realm is considerably bloated by the end of migration and we compact it at the end before it goes into use, which is working for those that make it that far.  So we tried to add compacting at multiple places within migration as a test, but that seems to cause more problems instead of fixing it.

We are migrating first from core data to realm with realm cocoa, and this is where the unexplained crashes are happening. The app then goes on to migrate again from realm cocoa to realm js, but it seems to be crashing in the realm cocoa part.

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: 1.8.3

Xcode version: 

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by bdash** [comment]
Which version of Realm Cocoa are you using?

Am I correct in understanding that you're attempting to use both Realm Cocoa and Realm JS within the same application? Can you share a little information about how you're going about that? Are you interacting with the same Realm files with both Realm Cocoa and Realm JS at the same time? Is the Realm file you're migrating data into using Realm Cocoa open via Realm JS at the same time that you're performing the migration?

**Comment by jasonmerino** [comment]
@bdash 

We are using Realm Cocoa `2.8.3`. Yes, we are using both Realm Cocoa and Realm JS within the same app. 

What we are doing is migrating a bunch of data over from Core Data to Realm. We start migrating on the Objective C side where we have duplicated the schema definitions what we use in the new app and map the data from Core Data into the Realm schema. We had class naming conflicts between the Core Data classes and Realm schema classes, and so we postfixed all of our Realm schema classes with "Realm" to get around that. After copying all of the Core Data into Realm on the native side we go about moving the data from those schemas that are postfixed with "Realm" into the standard schema names that the app uses (ex. StudentRealm -> Student, EventRealm -> Event, etc). We do the migration of that data in two steps. Step 1 is to copy the primitive data, second step is to migrate the lists, etc. 

We are indeed interacting with the same realm from both the native and JS side, but we are not reading from it or writing to it at the same time from both native and JS.

To your last question, yes both sides use the same realm so it is open on both the native and JS sides simultaneously. 

There is an update that I should share.

We've been able to get past the migration code and get all the realm data into the right spot on a local realm. Now we are having problems getting the conversion of a local realm to a synced realm going because of the same "cannot allocate memory" error. We are storing images in realm itself. We were able to get around the migration itself crashing by not moving the images around to the Picture schema (we left it in the PictureRealm schema). When we had tried to copy those over we duplicated all of them before deleting them which was causing issues. But now that we are converting from a local realm to a synced realm we are back in the same boat with it duplicating the data.

Hope that information helps.

**Comment by kishikawakatsumi** [comment]
How much data is actually stored? Due to the limitation of iOS, it is impossible to map files over a certain size. Depending on the device though, there is a limit around 3-4 GB. If the original file is several gigabytes, it probably can not be migrated to Realm.

**Comment by jasonmerino** [comment]
@kishikawakatsumi I can't say exactly how much data is actually stored, but it would make sense that we are going over realms abilities here because some of the people that are experiencing this issue have hundreds of images in their existing core data databases.

**Comment by austinzheng** [comment]
Apologies for the delayed response. Unfortunately, like most technologies, Realm makes certain trade-offs in order to achieve certain goals, and one of these trade-offs is that it's ill-suited for storing very large amounts of binary data like images.

I can't speak for your specific use case, of course, but we've generally found our users who want to store binary data are better served storing the files in the filesystem and using Realm as a metadata database (storing file paths instead of the entire image). For many applications the features Realm provides (querying, sane modification of data from multiple threads, etc) aren't applicable to large binary files, so it turns out to be an acceptable tradeoff.

**Comment by austinzheng** [comment]
Glad you found a solution! Please feel free to file more issues if you run into any more problems.
