### ISSUE TITLE
RealmSwift Change Values without affecting stored objects

### ISSUE THREAD

**Issue by yuanjilee** [realm/realm-cocoa#5275]
## Goals

I have a needs in my Project which I change the realm Object without update its stored value. Maybe i would discard the change, so I don't want to update cache. But Realm require me to modify a Realm Object in transaction.

## Expected Results

Is there any method to change Realm Object only mirror and temporary outside a transaction.

## Actual Results

I attempt long time but not reslove it. and search in Google with "Change Values without affecting stored objects Realm" not find a solution.

## Version of Realm and Tooling

Realm framework version:  The latest version (2.10)

Xcode version:  Xcode 8

iOS/OSX version:  iOS 8+

**Comment by kishikawakatsumi** [comment]
@yuanjilee There is no way to modify the stored object without a transaction. 

Another solution is to create a temporary copy of the object.

```
let tempCopy = SomeRealmObject(value: storedObject)
...
```

Since the object that copied from in that way is detached from Realm, a transaction is not needed for change.

If you show us the use case why you want to do that, we may be able to make another suggestion.

**Comment by bdash** [comment]
Closing as it looks like @kishikawakatsumi has answered your question.

**Comment by sunflowerseat** [comment]
@kishikawakatsumi It can't solve the problem, tempCopy still attached realm.
