### ISSUE TITLE
Database file size growing significantly and the app crashes 

### ISSUE THREAD

**Issue by binoklev** [realm/realm-cocoa#5278]
I use Realm cocoa in Objective-C written application as cache database. DB saves list of Salons with staff as RLMArray property.
It was all OK in testing, but in production the list of salons grew up to 14000 records and the app crashing with error "mmap() failed: Cannot allocate memory size:..."
I tried to reproduce this issue on simulator and found that DB size growing up to 12 GB.
I read all issues here and added @autoreleasepool and decrease count of beginWriteTransaction/commitWriteTransaction calls, but anyway - database growing up to 3GB
After compacting it takes 1,3 MB only.

**Questions**:
1. Is there a way to perform compacting by demand, for example during server response parsing after each 1000 records?
2. Is there a way to create compacted records in database without reload of database file?

## Expected Results
The app downloading 2.3 MB XML data from server and saving it to database. Expected behaviour - to get comparable size of database without reloading any files and the app.  

## Actual Results
Database size growing up to 3GB and decrease to 1,3 MB after Compacting. The app crashing due of out of memory.  

## Steps to Reproduce
I’ve created test project with only 2 RLMObject-based model classes and create 14000 objects in for circle, but it doesn’t growing like in real project. Real model a bit complicated, is it important?

## Version of Realm and Tooling

Realm framework version: Realm Objective‑C 2.10.0

Xcode version: 8.3.3 (8E3004b)

iOS/OSX version: 10.12.6 (16G29)

**Comment by skrew** [comment]
This kind of issue come again and again... and for big projects with massive multithreading, it's really a headache and time consuming while tracking that.

And it's not only an simple issue, if it's happening in production and the DB gets max memory allocation, the application would never opening again... The user have to uninstall / reinstall, with the disagreement you can imagine for the support team and the user.
And don't tell us "it's not a problem anymore, you can now compacting the DB at launch", as it's only works if the user re-open app (and not restoring from background) BEFORE the max allocation are coming. (and all users don't have 1 gb of free space to lost until a fresh restart of the app) 

Some suggestions here:

- It would be fine to have a notification, or even (yes it's dirty..) a crash when the realm file approach from the max memory allocation. It's better to have a crash than a dead application. (yes we can track the file size ourself, but many devs don't know (yet) about this issue)

- It's could be possible to have an option like `disableVersioning` or `disablePinning`), so we can make massive read/write for some seconds without risks ?

- It could be fine to have a "safe" queue from Realm, like "ok this would be more slow but 100% secure". Why not a separate lib if you don't want to embedding that in Realm ?

- A tool (or api) in Realm who display pinned transactions. So you add a "label" property, and anytime we can get a list of pinned transactions, easily identifiable by the label. Because for now, we have to track ALL access and it's really not easy and really time consuming (or i have missed something).

For me (and i think i'm not the only one), it's the last **big** problem in Realm.

Ah, and for @binoklev, just look all issues like your, read the doc, and make a lot of coffee, you can resolve your issue, but it would be a very long task. I think nobody can help you without having the full project, as the issue can be anywhere, even the little and (as you think) insignifiant query.
**And don't publish your app with this issue, for your support team, and your users).** ;)

**Comment by binoklev** [comment]
I've found the issue - the main reason was in calling beginWriteTransaction/commitWriteTransaction 14K times. I put it all in one transaction and DB file now has only 18.8 MB size.
