### ISSUE TITLE
 "Unable to open a realm at path XXXXXX"  for Jailbreak mobile iPhone 6 iOS 8.1.2   

### ISSUE THREAD

**Issue by MarvinShawn** [realm/realm-cocoa#5281]
1.Crash description

/var/mobile/Containers/Data/Application/9C785D2A-53BA-4C86-B5B6-4FE235AA1BB0/Documents/CustomName.realm.management/access_control.write.mx: Unable to open a realm at path '/var/mobile/Containers/Data/Application/9C785D2A-53BA-4C86-B5B6-4FE235AA1BB0/Documents/CustomName.realm.management/access_control.write.mx'. Please use a path where your app has read-write permissions.

2.Stack information

0 CoreFoundation | ___exceptionPreprocess + 132
-- | --
1 libobjc.A.dylib | objc_exception_throw + 60
2 CustomName | RLMSetErrorOrThrow(NSError*, NSError* __autoreleasing*) (RLMUtil.mm:300)
3 CustomName | RLMRealmTranslateException(NSError* __autoreleasing*) (RLMRealm.mm:276)
4 CustomName | +[RLMRealm realmWithConfiguration:error:] (RLMRealm.mm:375)

3.My suppose

The realm version is 2.7.0. And just this user(Jailbreak mobile iPhone 6 iOS 8.1.2) encountered this problem.   I don't know whether it is the cause of  "Jailbreak mobile && iOS 8.1.2".

Maybe this issue is the a little same as issue [https://github.com/realm/realm-cocoa/issues/3426](3246)

Now I am upgrade the Realm to 2.10.0. And Waiting for observation

Thanks.

**Comment by austinzheng** [comment]
Thanks for getting in touch with us.

If a phone is jailbroken it's not possible for us to anticipate modifications to the way the operating system or system libraries work as part of whatever software the user installs. It's possible that the user may have modified file permissions in such a way that the application is no longer able to write to files in its user directory.

If you have access to the phone you can try something: make your app try to write a file to the parent directory (`/var/mobile/Containers/Data/Application/9C785D2A-53BA-4C86-B5B6-4FE235AA1BB0/Documents`) and see if you get the same error. Otherwise there's unfortunately little we can do to help.

**Comment by MarvinShawn** [comment]
Ok  I got it .Thank you so much  :)
