### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by MihaelIsaev** [realm/realm-cocoa#5305]
Xcode 9 GM was released. Could you please provide with Swift4 release ASAP???

**Comment by walsht** [comment]
+1

**Comment by austinzheng** [comment]
We are aware that Xcode 9 is in GM and will release an updated version of Realm as soon as we are able to. Thank you for your enthusiasm.

**Comment by MihaelIsaev** [comment]
And when??? Why I should wait till release? I'm not a customer, I'm developer and I should develop my apps before release! Don't you think???!

**Comment by austinzheng** [comment]
Please review our [code of conduct](https://realm.io/conduct/) and the guidelines on proper interpersonal communication if you wish to further participate in our community. Thank you, and have a nice day!

**Comment by bdash** [comment]
We have [supported using Realm with Xcode 9 and Swift 4 for many months now by building Realm from source](https://stackoverflow.com/a/44641478/1991710), so not having a release of Realm that supports Swift 4 should not have been a hindrance to your development. We don’t make binary releases using beta versions of Xcode, so we have to wait for Xcode to hit GM like everyone else before before we can make a release that includes Swift 4 binaries. Since Xcode 9 GM was released yesterday we’ve been working through the necessary steps to prepare for a release that includes it. That work takes a non-zero amount of time. We hope it will be completed and a release including Swift 4 binaries published in the next day or two. Until then, you’re welcome to continue building Realm from source for use with Swift 4.
