### ISSUE TITLE
Unable to run tests: RLMObject subclasses with the same name cannot be included twice in the same target

### ISSUE THREAD

**Issue by plm75** [realm/realm-cocoa#5308]
## Goals
I want to be able to run unit tests in a project with a RealmSwift dependency

## Expected Results
Being able to run unit tests

## Actual Results
Depending on target memberships of model files, either the app crashes or Xcode is unable to build the test target

## Steps to Reproduce
I've attached a sample app to demonstrate the issue

## Code Sample
See attached sample app

## Version of Realm and Tooling
See attached sample app

Xcode version: 8.3.3

iOS/OSX version: iOS 10 - osx: 10.12.6

Dependency manager + version: ?
Cocoapods
[RealmTest.zip](https://github.com/realm/realm-cocoa/files/1302017/RealmTest.zip)

**Comment by austinzheng** [comment]
Thanks for getting in touch with us, and for providing a sample project.

To get things to work, I went to the project in the Project Navigator, clicked the RealmTestTests target, went to Build Phases, went to Compile Sources, and removed all the files from the list that were not part of the test target. See the screenshot:

![screen shot 2017-09-15 at 10 59 27 am](https://user-images.githubusercontent.com/3687054/30496719-284e9214-9a05-11e7-9bd3-fe1746999ca0.png)

More generally, since you are linking the application against your test target as if it were a framework (e.g. `@testable import RealmTest`), you don't need to ask the test target to compile the application source files. I suspect that you didn't run into any non-Realm related projects because your test application doesn't expose anything as `public` or `open`, but Realm (even Realm Swift) works at the Objective-C level and does not benefit from the same visibility restrictions.

**Comment by plm75** [comment]
👍 Thank you for your help Austin.
