### ISSUE TITLE
Uncaught exception: RLMException: Missing value for property 

### ISSUE THREAD

**Issue by sumeet85** [realm/realm-cocoa#5321]
Uncaught exception: RLMException: Missing value for property 
Realm framework version: ? Realm Objective‑C 2.10.1
Xcode version:  9
iOS/OSX version: ios 11
 Uncaught exception: RLMException: Missing value for property

**Comment by kishikawakatsumi** [comment]
@sumeet85 Please provide the necessary information requested in the issue template to investigate the cause. The `Missing value for property` exception is typically raised when a value is not given for the primary key property when creating an Realm object. Providing sample code that reproduces the problem is best, but the model definitions, code snippet where the exception occurred are also help us.

**Comment by kishikawakatsumi** [comment]
Closing due to no response
