### ISSUE TITLE
Realm file size became 3 GB

### ISSUE THREAD

**Issue by santhoshs5** [realm/realm-cocoa#5330]
I have four tables with 6 columns each and each table is having 5k entries each table.(all are strings)

what could be the issue it reaches 3GB?

**Comment by kishikawakatsumi** [comment]
It is hard to think that it will be 3GB unless there are very long strings. The Realm file may be larger than the actual data due to version pinning of the transaction.

For details, please see our documentation as follows.
https://realm.io/docs/swift/latest/#limitations-file-size

In that case, you can reduce the Realm file size to the same size as the data by copying Realm file (`Realm().writeCopyToPath(_:encryptionKey:)`) or executing compaction (`shouldCompactOnLaunch`).

For details on compaction, please see the link below.
https://realm.io/docs/swift/latest/#compacting-realms

**Comment by kishikawakatsumi** [comment]
​First of all, please make sure that the data is actually 3 Gbytes or not. If it contains a lot of transaction version data, the file size will increase from the actual size. To do this, execute compaction or copy the Realm file.

Please see more details:
https://realm.io/docs/swift/latest/#limitations-file-size 
​
At that time, if the file size does not change, 3 Gbytes of data is actually stored, so it can not be made smaller.
If the file size decreases, the file size is larger than the actual due to the transaction version pinning.

When I look at your code, you are using Realm in multithread, so there is a possibility to occur unintentional version pinning. Try to use autorelease pool to minimize the lifetime of Realm instance. Also, setting `shouldComplatOnLaunch` to periodically compact at startup can also help solve the problem.

**Comment by Zhuinden** [comment]
You might be missing the `autoreleasepool` in the dispatch async queue

**Comment by bruce-lumo** [comment]
Question on this `autoreleasepool`: I swear last time I reviewed my codebase in light of `https://realm.io/docs/swift/latest/` the `autorelease` wrapping example wasn't there. Am I nuts and should have been doing this all along or is this doc been updated? Whats the best way to stay on top of this kind of thing?

**Comment by austinzheng** [comment]
It's very possible the examples were updated. We had a number of users run into this issue over the summer and spent some time trying to make our documentation clearer in order to head off this problem.

Unfortunately we don't currently have public diffs of our documentation or anything like a RSS feed, but one thing you can do from our docs page is click on "Latest" (where it says "Realm Swift X.X.X", below the navigation bar but above the beginning of the content), and choose an older version of the docs to compare. I will bring this issue up with our web team to see if they have any ideas.

**Comment by Zhuinden** [comment]
@bruce-lumo it was there but you had to look for it. I'm pretty sure it was *added* to the top example later. In fact, it was added with the docs update to [2.5.1](https://realm.io/docs/swift/2.5.1/).

**Comment by Zhuinden** [comment]
Btw another thing I've heard can increase your size so much is if you add the items in a new transaction each time, because it increases the transaction log a lot.

And another thing is that there can be reclaimable space created by super-large transactions (10000+ objects at a time for example)
