### ISSUE TITLE
App is crashing when Swift 3 @obj inference in build setting is set to default.

### ISSUE THREAD

**Issue by ayushsharma0809** [realm/realm-cocoa#5439]
## Goals
When upgraded to swift 4 there were warning of of swift 3 @obj inference and so the solution to remove the warning was to set the swift 3 @obj inference in build setting to default. 

## Expected Results
Expected result is to work as it was working in swift 3.

## Actual Results
if I set the swift 3 @obj inference to default then it crashing with the error "Primary key property 'id' does not exist on object" and when i see the realm browser then there is no model. The realm browser is blank. But when I set the Swift 3 @obj inference to On then the App is not crashing and i can see all the models in Realm Browser but the App is very slow and calling too much threads in the background.
I have attached the screenshot of the Realm Browser when the Swift 3 @obj inference is set to default.

![screen shot 2017-10-30 at 12 09 38 pm](https://user-images.githubusercontent.com/22798350/32159403-604db28a-bd73-11e7-9685-6fff29d450c6.png)

## Steps to Reproduce
Just set the Swift 3 @obj inference to default in build setting for targets

## Version of Realm and Tooling

Realm framework version: 3.0.1

Xcode version: 9.0

iOS/OSX version: 11

**Comment by austinzheng** [comment]
Because Swift 4 changed what the `dynamic` keyword means, you indeed either need to mark all your model properties with `@objc dynamic` instead of `dynamic`, or to set `@objc` inference to true.

It's very implausible that the existence of `@objc` inference has changed the number of threads Realm uses or the performance of Realm. If you can demonstrate this by creating two sample apps, one using Realm 3 and one using Realm 4, that are identical but demonstrate non-trivial performance differences, we'd be happy to investigate further.

**Comment by ayushsharma0809** [comment]
are you able to reproduce the bug that i am telling about?

**Comment by austinzheng** [comment]
The onus is on you to either give us a reproduction case, or enough information to reproduce the bug ourselves, so no. Please read my previous comment again.

**Comment by ayushsharma0809** [comment]
i have marked all my properties with "@objc dynamic" and now everything is working perfectly in my case. Thanks for your response.
