### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2:

### ISSUE THREAD

**Issue by ZengR** [realm/realm-cocoa#5459]
Realm framework version: 3.0.1

Xcode version: 9.1

iOS/OSX version:  macOS 10.12.6

**Comment by qiyazong** [comment]
Hey body! I am the same question of you.Did you have solved it ?

**Comment by bdash** [comment]
How are you integrating Realm into your project? Are you using a dependency manager such as CocoaPods or Carthage, are you building Realm from source, or are you integrating a prebuilt Realm framework binary?

**Comment by qiyazong** [comment]
I download in realm official website. I didn't use cocoapod or carthage

**Comment by bdash** [comment]
Since Swift does not yet have a stable ABI, a framework binary built with one version of Swift cannot be used by another version of Swift. This means that if you're using prebuilt binaries of a given Swift framework, you should cannot update to a newer version of Xcode until prebuilt binaries are available that were built with that version of Xcode. Our most recent release predates the release of Xcode 9.1 so we currently do not have prebuilt binaries of Realm Swift that are built with Xcode 9.1. We hope to make a new release including binaries built with Xcode 9.1 later this week.

Until then, please see [my post on Stack Overflow](https://stackoverflow.com/a/44641478/1991710) for instructions on building Realm Swift from source for Xcode versions that we do not yet have binaries built for. You'll need to change a) the Swift version number, and b) the Realm version number to be the latest release. As I mention in that post, using CocoaPods or Carthage sidesteps this issue by building dependencies from source.

**Comment by amirpervaiz086** [comment]
@qiyazong https://github.com/amirpervaiz086/Realm-swift-4.0.2 download it from here :)

**Comment by amirpervaiz086** [comment]
its compiled binaries file with Xcode 9.1 swift 4.0.2. Hope it helps

**Comment by bdash** [comment]
@amirpervaiz086, take a look at [v3.0.2](https://github.com/realm/realm-cocoa/releases/tag/v3.0.2) instead.

**Comment by amirpervaiz086** [comment]
oh ok thanks. I compiled it couple of days ago as there was no version at that time :) thanks for uploading it.

**Comment by qiyazong** [comment]
@amirpervaiz086 ok thank you !
