### ISSUE TITLE
improve realm time transactions

### ISSUE THREAD

**Issue by raphaels17** [realm/realm-cocoa#5474]
**Questions**: I have some code takes forever (3sec) to execute and I m fairly sure this is because I don't use realm transaction properly

## Code Sample

```
let aRealmObject = MassiveFunction() // last 3 sec See below
.....
MassiveFunction(firstObject,secondObject)-> aRealmObject {
let  theFutureaRealmObject = aRealmObject()
theFutureaRealmObject.propertyOne = secondObject.property
....
 firstFunc(theFutureaRealmObject) //  add  the object to realm, which takes a sec
 secondFunc(firstObject,theFutureaRealmObject) //     append the object to another realm object, which takes a sec
 thirdFunc(theFutureaRealmObject) //append the object to another realm object, we retrieve through a realm query, , which takes a sec

return theFutureaRealmObject
} 
```
 in firstFunc, secondFun and, thirdFunc, I proceed to a try.write  in each of them. with this snippet each time
`//Prevent realm multiple transaction 
        while realm.isInWriteTransaction {
            continue
        }
`
What should I do ? can I have only one transaction?  Should I resort to background threads?

## Version of Realm and Tooling

Realm framework version: 'RealmSwift','~> 2.10.1'

Realm Object Server version: ?

Xcode version: 9.1

iOS/OSX version: 11

Dependency manager + version: ?

**Comment by austinzheng** [comment]
Please provide an actual code sample. The pseudocode you provided doesn't give us enough information to help you out.

Generally speaking, loops should be contained within write transactions (rather than the other way around), so that all changes take place in one write transaction rather than incurring the overhead of beginning and committing many write transactions in a row. Write transactions should also not contain code that takes a long while to run, as keeping a write transaction open blocks other queues or threads trying to make write transactions.

**Comment by raphaels17** [comment]
That actually was the info I needed, know back to less than 0.3 sec
