### ISSUE TITLE
realm.deleteAll() removes all the data but the file size remains the same.

### ISSUE THREAD

**Issue by kansaraprateek** [realm/realm-cocoa#5549]
App Realm database handles all the data for a logged in user. 

When I login using "user 1", which has a whole bunch of data, the realm file size goes to 600MB.
When I logout and login using "user 2" which has no data, I call realm.deleteAll() . Which removes all the previous user data from default.realm. 
But the file size remains the same i.e 600MB.

Here's the link to the realm file, Which has no data - 
https://www.dropbox.com/s/cz8m0e5p1xabdjs/default.realm.zip?dl=0

Is there something I am missing while clearing data from realm. 

Realm framework version: 2.10.2
Xcode version: 9.2
iOS/OSX version: 11.2.1

**Comment by ansarimawais** [comment]
The same issue is happening to me. After realm.deleteAll() file size remains the same.

**Comment by cmelchior** [comment]
That is currently by design. See https://realm.io/docs/java/latest/#faq-large-realm-file-size

**Comment by sandeepbol** [comment]
The most interesting part is if I do 

`$ cat realm | grep "some_keyword"`

 it shows in both of the files. Also

`$ diff old.realm new.realm `

Binary files old.realm and new.realm differ!

@cmelchior if this is by design, why not clear the old data from the app? This can be a potential security flaw as the data is still accessible after a user logs out (deleteAll()).

**Comment by bmunkholm** [comment]
It's by design, because clearing data takes a lot of time. Compacting a file likewise. If you have a special need to clear all data, you should de so yourself, or use encryption.
