### ISSUE TITLE
is there a way to know: - How many object are waiting to be sync

### ISSUE THREAD

**Issue by ankursharma234** [realm/realm-cocoa#5551]
While syncing to realm object server, can we get a success response for each object that is successfully synced and failure for those are pending?

**Comment by michael-mckenna** [comment]
Have you already looked into Sync Sessions?

**Comment by bdash** [comment]
This information isn't available at an object level granularity due to the way that synchronization works. Synchronization processes transactions at a time. You can use [`SyncSession.addProgressNotification(for:mode:block:)`](https://realm.io/docs/swift/latest/api/Extensions/SyncSession.html#/s:FE10RealmSwiftCSo14RLMSyncSession23addProgressNotificationFT3forOES_S0_17ProgressDirection4modeOES_S0_12ProgressMode5blockFVES_S0_8ProgressT__GSqCSo28RLMProgressNotificationToken_) with the `forCurrentlyOutstandingWork` progress mode to be notified when the changes made in a given write transaction have been uploaded.
