### ISSUE TITLE
Realm Notifications on Grouped UITableView

### ISSUE THREAD

**Issue by joninsky** [realm/realm-cocoa#5553]
## Goals
I want to be able to have sections of a `UITableView` represent queries of different object types and update using Realm's notification system

## Expected Results
`UITableView` updates and reloads sections and rows in sections with no crashes

## Actual Results
I frequently get crashes with something similar to this stack trace:

``` Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 1.  The number of rows contained in an existing section after the update (4) must be equal to the number of rows contained in that section before the update (0), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).```

## Steps to Reproduce
Set up a Realm with at least two distinct object's and make a query for each object. Then display the results of each query in a different section of a `UITableView`. Finally, add a Realm notification block for each query and update the appropriate `UITableView` section. 

## Code Sample
I have an [open stack overflow question with a complete code sample](https://stackoverflow.com/questions/47521455/grouped-uitableview-and-realm-notifications).

## Version of Realm and Tooling

Realm framework version: 3.0.2

Realm Object Server version: None

Xcode version: Version 9.2 (9C40b)

iOS/OSX version: 11

Dependency manager + version: Cocoapods 1.4.0.beta.2

**Comment by StefanDesu** [comment]
Seconded. I have two sections in my table view for two different Realm Lists. There are also two notifications, one for each list. If (for example through changes on the server which are then synced back) the number of items in both sections changed at the same time, the notifications would go off in sequence and the table view would crash after the first notification because the database had already updated for the other section as well.

My current workaround is to manually keep track of the number of rows in each section and only update the number for the respective section if a notification occurs. This works perfectly, but it's still a workaround.

To implement this in Realm, I have two different suggestions:
1. Make sure only the respective list is updated when a notification is fired.
or 
2. Add a new kind of batch notification for pairs of sections and Realm collections where the insertions/deletions/modifications are provided as index paths instead of just rows. This would be the more elegant way in my opinion.

**Comment by gcox** [comment]
If it ever becomes a priority, this would be solved by #3384.

**Comment by bmunkholm** [comment]
I'll close this as it's now referenced by #3384
