### ISSUE TITLE
xcode crashed and shut down when i try to read or write to realm !!

### ISSUE THREAD

**Issue by HassanDuhair11** [realm/realm-cocoa#5572]
## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: ?

**Comment by Zhuinden** [comment]
Please fill out the issue template so that the issue can be reproduced.

**Comment by fpiruzi** [comment]
Same issue for me, sometimes trying to get the Realm default instance too :S

**Comment by bdash** [comment]
If Xcode crashed, you really need to file a bug report against Xcode with Apple, providing specific steps to reproduce so that they can investigate and fix it. There's nothing _we_ can do to fix an Xcode crash. At most we could work around it, but I suspect even that would be incredibly difficult for us to do.

**Comment by fpiruzi** [comment]
I think that you need fix the issue, I can't debug anything and provide any useful information If Realm crash when I do this complex line of code: let realm = try! Realm(), and trust me that also is very difficult for us continuing using a tool that explodes Xcode. For now the solution for us is uninstall the app install it again.... Have a good day.

**Comment by bdash** [comment]
Have you reported the Xcode crash to Apple? If so, what is Apple's bug report ID for the issue that you filed? If not, why not?

**Comment by fpiruzi** [comment]
Not yet Because I'm trying to continue and finish my deadlines, it seems that is going to be impossible if this issue still there. I spent 5 hr today trying to see why such thing happen but its mystic, just try to get the default instance and Xcode dies, i really don't know why. Environment : macOS 10.13.2, MacBookPro  13' : i5, 8gb ram, ssd.  Xcode 9.2. Realm last version installed with cocoapods. Swift 4. I think the problem is realm not Xcode, I just comment the line when this happens and everything is ok.

**Comment by bdash** [comment]
I'm sorry that you're hitting this problem, but I really don't see what we can do about a bug in Xcode. If Xcode is crashing, _by definition_ the problem is in Xcode.

**Comment by bdash** [comment]
My suggestion would be to downgrade back to Xcode 9.1 and see if you continue to experience the problem. If not, there's your workaround.

**Comment by SheikhZayed** [comment]
is there any fix for this? its crashing for me too :(..uninstalling and reinstalling the app works .. for xcode 9.2

**Comment by kedavidsa** [comment]
@bdash Same issue for me, I think it happens when I do some modifications to the model and run again the app. 
In my case I had  a class like this:
```
public class Field:Object, Decodable {    
    @objc dynamic var id: String = ""
    @objc dynamic var mandatory: Bool = ""
...
}
```
When I change it with:
```
public class Field:Object, Decodable {    
    @objc dynamic var id: String = ""
    @objc dynamic var mandatory: String = ""
...
}
```
It start to crash. Do we have to do some migration? How can we fix this?

**Comment by bmunkholm** [comment]
@kedavidsa This is a closed issue. Please open a new issue with all details filled into the template. Thanks!
