### ISSUE TITLE
Realm Object fields are nil  while unwrapping an Optional value

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [realm/realm-cocoa#5597]
I'm having a strange issue with objects in Realm. When i fetch an object from Realm database at first time & deleted object from database. unwrapping an optional value 'nill'.
Model:
`  class Outlet: Object {

    @objc dynamic var id:string = ""
    @objc dynamic var name:string = ""
    @objc dynamic var name1:Double = 0.0
    @objc dynamic var name2:Double = 0.0
    @objc dynamic var name3:Double = 0.0
    @objc dynamic var name4:Double = 0.0
    @objc dynamic var name5:Int = 0

    let  OutletListS = List<OutletList>()
    override class func primaryKey() -> String? {
    return "id"
    }
    } `

My Code: 
    `   class DBManager {

    private var database:Realm
    static let sharedInstance = DBManager()
    private init() {
        database = try! Realm()
    }
    func getDataFromDB() -> Outlet {
         let result = database.objects(Outlet.self)
        return result.first!
    } 
    }`
and calling method:

` let selectedOutlet =  DBManager.sharedInstance.getDataFromDB()`

**Error:** .  `Printing description of result:
Results<Outlet> <0x7fb64f02c230> (

)`
I know this issue here, but i could't solve it myself. help me please.

**Comment by bdash** [comment]
From the information you've shared, it looks like there are no `Outlet` objects in the Realm file, so when you unwrap `result.first` you're attempting to unwrap an optional that is nil.

**Comment by IOSDeveloperProgrammer** [comment]
Yes, There are no Outlet. How Can I write & check ? I'm fetching data from database on "ViewDidAppear" method at first time. It's necessary to check database in my class every time user entered Screen. . I'm declared:
`var selectedOutlet = Outlet() selectedOutlet = DBManager.sharedInstance.getDataFromDB()`

I had  tried with it. I had stuck here. please Thanks!

**Comment by bdash** [comment]
An optional may not contain a value. For instance, if you have no `Outlet` instances in your database, `database.objects(Outlet.self).first` cannot return an `Outlet` instance and must return nil. It's not sensible to force-unwrap the result of `Results.first` unless you _know_ that more than one object exists. Given that you cannot guarantee that you have an `Outlet` in the database, you likely want to propagate the optional rather than force-unwrapping.

I'd suggest doing some reading about optionals in Swift since this appears to be a misunderstanding about a language feature rather than anything specific to Realm.
