### ISSUE TITLE
Incorrect object schema during migration

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-cocoa#5624]
## Goals

Inspecting the new schema during a migration and checking if a newly added primary key is marked as primary key.

## Expected Results

Inspecting the realm object which has a newly added primary key to return correct data - e.g. "isPrimary" to be `YES` like below:

```
Subject {
		name {
			type = string;
			objectClassName = (null);
			linkOriginPropertyName = (null);
			indexed = YES;
			isPrimary = YES;
			array = NO;
			optional = NO;
		}
	}
```

## Actual Results

`isPrimary` is incorrectly set to `NO`. Once the migration is over, inspecting the schema correctly recognizes the new primary key.

## Steps to Reproduce
Add a new primary key and inspect `migration.newSchema` during a migration.

## Version of Realm and Tooling

Realm framework version:  RealmSwift 3.1.1 

Xcode version: 9.2

iOS/OSX version: 11.0

Dependency manager + version: CP 1.3.1

**Comment by tgoyne** [comment]
Primary keys are disabled during migrations because they can have some very surprising effects (e.g. you can accidentally merge all of your objects into a single object when adding a new PK column if you do anything at all before initializing the values of that column), and this is reflected in the schema reported during the migration as the schema object is the actual thing that we work off of internally and not a separate view.

**Comment by icanzilb** [comment]
Thanks, this explains the behavior, though it'd be helpful if that was stated in the migration docs.
