### ISSUE TITLE
How to take backup and restore in realm Swift ios 

### ISSUE THREAD

**Issue by Rushang007** [realm/realm-cocoa#5660]
i want to know How to take backup and restore in realm  in Swift ios ?

**Comment by duncangroenewald** [comment]
This seems to work fine.. Still trying to figure out how to restore from a backup - might need to somehow restart the app or make sure there are hooks in all viewControllers to close any open realms and reload them.
I would be keen to know of any solutions - I am thinking maybe some sort of Realm() subclass that can handle notifications or some sort of RealmFactory that keep track of any open references.

```
// Create a backup of the database to the backupURL
    func backupLocalStore(storeBackupDirectoryURL: URL) -> Bool {
        
        let backupURL = storeBackupDirectoryURL.appendingPathComponent(backupStoreFilename)
        // To be implemented
        let realm = try! Realm()
        // Optionally wrap in a write transaction to
        // prevent other changes happening
        realm.beginWrite()
        do {
            try realm.writeCopy(toFile: backupURL)
        } catch {
            DebugLog("Error backing up data")
            return false
        }
        realm.cancelWrite()
        return true
    }
```

**Comment by duncangroenewald** [comment]
I managed to get the restore to work now as well.  Its a bit tricky because you have to make sure the Realm database is closed - and given I have many viewControllers displaying data this proved to be a bit more complicated than I thought it would be.

I had to refactor my app to have a start ViewController which does nothing other than check if a restore is required and has no references to any of the main app objects.  If no restore is required it immediately segue's to the main app.

In the main app I have replaced any singletons to be properties on a real singleton and these are only accessed via the Global singleton object.  This object has a reset() method to set the references to these pseudo singletons to nil if a restore is required - in order to release any retained references to Realm objects.

Now in the main app I have a backup manager and if the user selects to restore a database file I store the restore filename in UserDefaults and set the main app window's rootViewController to the startup ViewController and I call dismiss() on the previous rootViewController - this releases any of the main apps ViewControllers and any references they have to Realm objects.

Now in theory the Realm database should be closed - just use Xcode to check what objects still existing in memory after the rootViewController has been reset.  

In the start ViewController's viewDidLoad() method I check for the existence of a database restore filename in user defaults and then simply use NSFileCoordinator to replace the current default.ream database file.  Prior to resetting the app I get the current Realm database filename by calling realm.configuration.fileURL and store this with the restore filename.  

So far this seems to work very well.  Just be wary of trying to restore directly from an iCloud backup because iCloud files may need to be downloaded first before they can be accessed.

Let me know if you need any more detail and I can write things up in a bit more detail.

**Comment by bmunkholm** [comment]
Thanks for the help @duncangroenewald

**Comment by InfiniteDreamz** [comment]
@duncangroenewald  What if some kind of DB migration was done. So my current app is running with the latest DB schema but the realm.default file is quite old.

**Comment by duncangroenewald** [comment]
@InfiniteDreamz - well clearly if you restore from an old backup you are going to get an old schema.  To handle this you would need to include some migration logic to migrate to the new schema.  

```
var realmConfig: Realm.Configuration {
        var config = Realm.Configuration.defaultConfiguration
        
        let realmFile = realmDir.appendingPathComponent("default.realm")
        
        config.fileURL = URL(fileURLWithPath: realmFile.path)
        
        config.schemaVersion = 3
        
        // Code to perform any required migration
        config.migrationBlock = { migration, oldSchemaVersion in
            
            Notifications.databaseMigrationNotification.post(object: "Data migration starting...")
            
            if oldSchemaVersion < 1 {
                // Apply the necessary migration logic
                Notifications.databaseMigrationNotification.post(object: "Version 1 migration starting.")
            }
            if oldSchemaVersion < 2 {
                // Apply the necessary migration logic
                Notifications.databaseMigrationNotification.post(object: "Version 2 migration starting.")
            }
            if oldSchemaVersion < 3 {
                // Apply the necessary migration logic
                Notifications.databaseMigrationNotification.post(object: "Version 3 migration starting.")
            }
            Notifications.databaseMigrationNotification.post(object: "Data migration completed.")
        }
        return config
    }
```
