### ISSUE TITLE
Realm mutex stuck while init (deadlock?)

### ISSUE THREAD

**Issue by own2pwn** [realm/realm-cocoa#5730]
## Auto-incrementer

I wanted to create some sort of auto-incrementer for model. 
I have a helper table(`Schema` which tracks next id by a class name(model) ). 
[There's](https://gist.github.com/own2pwn/385367816219f53e1991f18aded55b09) my `RealmService`
[Base](https://gist.github.com/own2pwn/ebefbb83b0231d5ea79158ef0a929398) `RealmModel`
[Custom](https://gist.github.com/own2pwn/2a9a3e4b385a2a9ad5a82ae28aa6c1f9) `SpendModel`

And basically I'm trying the following: 
```swift
let m1 = SpenModel(with: "str")
let m2 = SpenModel(with: "str2")
realmService.save([m1, m2])
```
But the whole app get stuck due to realm instantiating. Basically in computed property `realm` in `RealmService`.

I think it's worth noting that if I dont provide default implementation for RealmModel's id (just set it to -1 for ex.) and do actually id fetch in derived class it works fine. 

Am I doing something wrong?

[Screenshots (imgur)](https://imgur.com/a/aJwHw)

<details>
  <summary>There are some screenshots of call stack. </summary>

![image](https://user-images.githubusercontent.com/7850039/38783780-e35d6efc-410f-11e8-9b08-05fbfaae264f.png)

![image](https://user-images.githubusercontent.com/7850039/38783773-ae75354e-410f-11e8-98ab-05a1976293b6.png)

</details>

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1114

/Applications/Xcode.app/Contents/Developer
Xcode 9.2
Build version 9C40b

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

/usr/local/bin/carthage
0.29.0
github "realm/realm-cocoa" "v3.3.2"

/usr/local/bin/git
git version 2.15.1

iOS/OSX version: Simulator

```

**Comment by tgoyne** [comment]
If this didn't deadlock it would instead be an infinite loop. Creating an object calls `nextID()`, which will create another object, which calls `nextID()` again, etc. The deadlock is because Realm itself also creates an instance of each class during schema init so that we can use reflection to discover what properties are present, and that leads to trying to access the Realm while our global state is still being initialized if any of the initializers for those objects try to access Realm.
