### ISSUE TITLE
Realm stop processing my code without crashes my app

### ISSUE THREAD

**Issue by adelbios** [realm/realm-cocoa#5757]
For some reason when I call let realm = Realm() it stops processing (doesn't crash) my code.or when i try perform other query ( add , delete , get and other ) My app is still running, but the screen keep frozen.

**Comment by bmunkholm** [comment]
@adelbios Please fill out the template we provide for new issues instead of deleting it. Support here on github is only for bugs. You need to provide a reduced testcase or sample app that clearly demonstrates the bug in Realm. Otherwise post to StackOverflow for general help. There it is also required that you are very specific so that you enable people to actually help you.
Thanks!

**Comment by adelbios** [comment]
thanx  @bmunkholm  ... but u don't need any sample app 
open Xcode -> setup pod file 'RealmSwift' -> build my App -> import RealmSwift in (AppDelegate) file 
then put this code   `let realm = try! Realm()`
that's all ..... my app freezing do not any think just white blank page  ... otherwise  
ViewController -> implement `Results<ModelName>` 
also freezing my app

**Comment by bmunkholm** [comment]
@adelbios Have you tried one of our demo apps? Does those work for you? Please check the differences from those to your app.

**Comment by adelbios** [comment]
@bmunkholm  yeh I tried `realm-tasks-master` and I get same problem please I wanna help

**Comment by bmunkholm** [comment]
@adelbios I doubt it's a bug in Realm. Since we only handle bugs or feature requests in github, please follow our guidance and open an issue in StackOverflow. There you will find guidance on how to get help. One tip for that: You have to be very specific on what you are doing and what's not working and how others would replicate your issue so they can help you. Providing a sample app and noting exactly which tool version you use will make it easy for others to either replicate the issue or help you point out what you have overlooked.

P.S.: I would suggest you try out the "simple" example in the examples folder of this repo.

**Comment by adelbios** [comment]
@bmunkholm 
`  override class func primaryKey() -> String? {
        return "id"
        
    }`

this code is  the reason of my problem when I deleted  it's work

**Comment by bmunkholm** [comment]
Happy you found it!

**Comment by adelbios** [comment]
Yup  i catch damn error  and I undrestand why it’s happening
