### ISSUE TITLE
How to keep the sort of data

### ISSUE THREAD

**Issue by CHENDONGY** [realm/realm-cocoa#5796]
If I have model1, model2, model3, model4. Now I delete model3, how to keep the order of model1, model2, model4

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Swift Forum](https://forums.realm.io/c/swift) or [Obj-C Forum](https://forums.realm.io/c/objc).

Thanks for your help!

**Comment by CHENDONGY** [comment]
@bmunkholm Excuse me, I want to delete one of the data in the database, but the sort of the entire data is not in accordance with the original sort. I did not find the results I need in StackOverflow. Thank you.

**Comment by bmunkholm** [comment]
@CHENDONGY We require that you fill out the template we provide. The template is made so that we can best help you by having all the needed information. If you have posted the question on StackOverflow, then please refer with a link to that post and we will be happy to answer there.
In order to get help, please help us as much as possible by providing code examples (preferably a standalone project that demonstrates your problem).
Thanks!
