### ISSUE TITLE
Realm database file size

### ISSUE THREAD

**Issue by sochalewski** [realm/realm-cocoa#5799]
## Goals
My app uses previously generated .realm database with read-only permission. I see that my .realm file size is more than doubled when switched from Realm ~~3.0.2~~ 3.5.0 to 3.6.0. Previously it was under 100 MB, but now it is over 260 MB!

The database stores just one simple object type (each one has one string property).

## Expected Results
Is it still possible to get reduced .realm file size using the current Realm Database?

## Steps to Reproduce
* Create a big database using Realm ~~3.0.2~~ 3.5.0
* Create a big database using Realm 3.6.0
* Compare file sizes

You can use [my repository](https://github.com/netguru/swift-collections-performance) for this. The correct target is RealmDatabaseWizard, which exports two databases to `~/Library/Containers/co.netguru.RealmDatabaseWizard/Data/`. Then unlock version in `Podfile`, run `pod update` and run the target one more time.

## Version of Realm and Tooling
Realm framework version: ~~3.0.2~~ 3.5.0 / 3.6.0

Realm Object Server version: n/a

Xcode version: 9.4

iOS/OSX version: macOS 10.13.5

Dependency manager + version: CocoaPods 1.5.2

**Comment by tgoyne** [comment]
There's no changes between 3.0.2 and 3.6.0 that should have had any impact, and the only vaguely related change I can find is a change to the allocator that shouldn't effect `writeCopy()`. Looks like this may be exposing a bug...

For things you can do: the index and primary key on `StringObject` don't appear to actually be used anywhere (filtering a List of objects won't use an index on those objects' properties) and add quite a bit of space overhead. Using a `List<String>` rather than `List<StringObject>` should cut the size a bit as there's a bit less overhead involved. Sorting the strings by their length prior to inserting them into the Realm might cut down on the total size a bit due to a quirk of how the string storage works, but that probably won't be significant.

**Comment by sochalewski** [comment]
Even when I get rid of the index and primary key the difference between file sizes is ridiculous: 57,5 MB vs 211,4 MB.

Now I can see that up to 3.5.0 it's small, but 3.6.0 makes it huge.

PS Unfortunately I can't replace `StringObject` with just `String`, because querying is currently only implemented for arrays of Realm Objects.

**Comment by tgoyne** [comment]
This appears to be due to https://github.com/realm/realm-core/pull/3039, which seems to have incorrectly made it also save the transaction logs for non-syncronized Realms. As a temporary workaround, inserting an empty write transaction after the one which inserts the data gets the file back under 100 MB for me.

**Comment by sochalewski** [comment]
Thank you, this really helps. Nevertheless I hope it will be fixed soon 👌

**Comment by L4grange** [comment]
Hello guys, I've opened issue #5810 since I am facing a similar problem.

However, adding an empty write transaction after inserting the data, my file size stays the same. Do you think the two issues are connected?

**Comment by sochalewski** [comment]
Closing as it's fixed in 3.7.2. Thank you for help, Thomas!
