### ISSUE TITLE
data sync error in muti-thread

### ISSUE THREAD

**Issue by wf08314110101** [realm/realm-cocoa#5835]
## Goals

I want commit data in global queue,and query data success in main queue

## Expected Results

I want commit data in global queue,and query data false in main queue
TestModifyRule.excute-solution1 it's ok,  TestModifyRule.printData print"printData count:1" 

## Actual Results

 I use solution2, it's bad,  TestModifyRule.printData print"printData count:0" 

## Steps to Reproduce

1、create and commit data A in main queue
2、assgin a member property
3、delete A in global queue
4、create and commit data A in global queue
5、qurey it in main queue

## Code Sample

```
@interface Cat : RLMObject
@property NSString* name;
@end
RLM_ARRAY_TYPE(Cat)

@interface Man : RLMObject
/// primary key
@property NSString* cardId;
@property RLMArray<Cat*><Cat> *cats;
@end

@interface TestModifyRule()
@property (nonatomic, assign) BOOL needDelete;
@property (nonatomic, strong) Man* mm;
@end
@implementation TestModifyRule
- (Man*)_createData
{
    NSLog(@"create data begin");
    __block Man* m = nil;
    RLMRealm* realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        m = [Man createOrUpdateInRealm:realm withValue:@{@"cardId":@"card1"}];
        Cat* c = [Cat createInRealm:realm withValue:@{@"name":@"c"}];
        [m.cats addObject:c];
    }];
    RLMResults* rlst = [Man allObjects];
    NSLog(@"create data end:%ld, id:%@", rlst.count, [rlst.firstObject cardId]); 
    return m;
}
- (void)_deleteData
{
    NSLog(@"delete data begin");
    Man* m = [Man objectForPrimaryKey:@"card1"];
    NSLog(@"delete data id:%@", m.cardId);
    RLMRealm* realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm deleteObjects:m.cats];
        [realm deleteObject:m];
    }];
    NSLog(@"delete data end:%ld", [Man allObjects].count);
}
- (void)printData
{
    /// expect: printData count:1
    /// solution1: printData count:1
    /// solution2: printData count:0
    NSLog(@"printData count:%ld", [Man objectForPrimaryKey:@"card1"].cats.count);
}
- (void)excute2
{
    __weak TestModifyRule* this = self;
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        if (this.needDelete) {
            this.needDelete = NO;
            [this _deleteData];
        }
        else {
            this.needDelete = YES;
            [this _createData];
            dispatch_async(dispatch_get_main_queue(), ^{
                [this printData];
            });
        }
        dispatch_async(dispatch_get_main_queue(), ^{
            [this performSelector:@selector(excute2) withObject:nil afterDelay:3];
        });
    });
}
- (void)excute
{
    _needDelete = YES;

// ------solution1 begin------
//    [self _createData];
// ------solution1 end------
    
// ------solution2 begin------
    _mm = [self _createData];
    NSLog(@"_init data:%@", _mm);
// ------solution2 end------

    [self performSelector:@selector(excute2) withObject:nil afterDelay:3];
}
@end

@interface ViewController ()
@property (nonatomic, strong) TestModifyRule* test;
@end
@implementation ViewController
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    RLMRealmConfiguration* config = [RLMRealmConfiguration defaultConfiguration];
    config.schemaVersion = 0;
    [RLMRealmConfiguration setDefaultConfiguration:config];
    RLMRealm* realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm deleteAllObjects];
    }];
    _test = [TestModifyRule new];
    [_test excute];
}
@end
```
## Version of Realm and Tooling

Realm framework version: 3.7.1

Realm Object Server version: ?

Xcode version: 9.4.1

iOS/OSX version: 11.4

Dependency manager + version: ?

**Comment by wf08314110101** [comment]
solution1:![solution1](https://user-images.githubusercontent.com/5351703/42263386-79929f86-7fa0-11e8-9247-086a02520341.png)
solution2:
![solution2](https://user-images.githubusercontent.com/5351703/42263685-510f1084-7fa1-11e8-9456-7e25b5a77fc6.png)

**Comment by tgoyne** [comment]
Realm instances on threads with runloops, such as the main thread, [update to the latest version of the data in the Realm file](https://realm.io/docs/swift/latest/#seeing-changes-from-other-threads) as a result of a notification being posted to their thread's runloop. A time window exists between committing a write transaction on a background thread and when that notification is received by the other thread's runloop, and due to the order that `CFRunLoop` processes its dispatch queue relative to its notification sources, it's not uncommon for a `dispatch_async` to the main queue performed immediately after a write transaction is committed to be serviced before the notification can be delivered.

There are a couple of ways to address this issue:

* Use one of Realm's notification mechanisms, such as collection notifications, to react to the changes you made on the background thread rather than explicitly using `dispatch_async`.
* Explicitly call [`Realm.refresh()`](https://realm.io/docs/swift/latest/api/Classes/Realm.html#/s:FC10RealmSwift5Realm7refreshFT_Sb) at the top of the block you dispatch to the main queue to have it bring itself to the latest version, whether or not the thread has had a chance to process the notification that triggers the automatic refresh.

**Comment by Double-Dude** [comment]
Hello @tgoyne, I think it's a quite common case that you dispatch to Main queue immediately which is the same issue I've experienced. 

Example:
1. You network request a chunk of data, results of creating 1000 objects.
2. It will block the UI thread if you write it on that, so you will have to do a background writing.
3. After persisting the objects, then you immediately want to refresh UI, so that you dispatch to main queue and query the objects. 
4.But there will be no data as Main Thread Realm hasn't got updated at the time you dispatch to Main Queue

The reason I query the objects instead of observing the collection change is that there will be a time difference between observer block gets called and the completion block of the network request gets called(which gets called earlier than observer ). If you start a spinner when you start requesting the data and stops it when completion block gets called, then there will be a delay between you dismissing your spinner and data gets showed as again the observer block may gets called after a second of completion block gets called as it's waiting for the next event of runloop which you described.
