### ISSUE TITLE
data race

### ISSUE THREAD

**Issue by sroik** [realm/realm-cocoa#5849]
<img width="1680" alt="screen shot 2018-07-07 at 9 45 09 am" src="https://user-images.githubusercontent.com/7701363/42407823-da24887e-81ca-11e8-9dfc-1e7befc6cbcd.png">

**Comment by sroik** [comment]
in `realm_notifier.cpp`

**Comment by tgoyne** [comment]
This is probably a false-positive. Using thread sanitizer on Realm.framework unfortunately doesn't really work because it requires that all libraries involved be instrumented by tsan, and we include a prebuilt c++ library that we don't ship a a tsan-instrumented variant for. We do test the libraries themselves with asan and tsan, though.
