### ISSUE TITLE
Better error message when creating query in write transaction

### ISSUE THREAD

**Issue by mrh-is** [realm/realm-cocoa#5898]
## Goals
Debug crash from creating async query in write transaction (`Cannot create asynchronous query while in a write transaction`)

## Expected Results
Error message is full of useful debug info.

## Actual Results
Error message merely says that such a thing is not possible. The stack trace points to the write transaction, but there is no information about the query. This means I would potentially have to investigate every query I have in my entire app 😵 (or hopefully that's not true already and there are better debugging techniques here).

## Steps to Reproduce
1. Create an async query while in a write transaction.
2. Examine crash report.

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65

/Applications/Xcode.app/Contents/Developer
Xcode 9.4.1
Build version 9F2000

/usr/local/bin/pod
1.5.0
Realm (2.10.0)
RealmSwift (2.10.0)
RealmSwift (~> 2.0)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)


(not in use here)

/usr/bin/git
git version 2.15.2 (Apple Git-101.1)
```

**Comment by tgoyne** [comment]
If you can trigger the error at least somewhat reliably, you can set a breakpoint on exception throws and try to trigger it. If it's a really rare error, you're probably trying to add a notification block from within another notification and running into the fact that notifications are sometimes delivered within a write transaction.

Some upcoming core changes will make it so that it's possible to add notifications from within a write transaction and make the whole problem go away, but that's a few months out still.

**Comment by mrh-is** [comment]
Ooh nice, those are great tips. I actually just found one thanks to the exception breakpoint (and finding a way to reliably trigger them). 👏

**Comment by mrh-is** [comment]
What's the recommendation for not adding notifications within notifications, especially where the outer notification's change may be propagating a few layers deep?

**Comment by ericjordanmossman** [comment]
@mrh-is 
Are the layered notification blocks still an issue?

One thing you could check if you're unexpectedly in a write transaction while handling notifications is `isInWriteTransaction`.

**Comment by ericjordanmossman** [comment]
Closing on inactivity. If this is a problem for anyone else, please comment and we can revisit.
