### ISSUE TITLE
Need better Building Realm instructions

### ISSUE THREAD

**Issue by smartcat32** [realm/realm-cocoa#5924]
Please provide better build instructions in the "Building Realm" section of the readme file.  Here's what's missing:   
   1) Name the branch to build for an Xcode that's in beta.  E.g. when building against Xcode 10 betas, it's not at all obvious what branch I should be using, if any.
   2) Provide a few typical examples of the exact build command(s) for, say, building for swift 4.2 on iOS.  (i.e. what would produce the same results as what you provide in the pre-built Realms we download? 

I currently find myself blocked from shipping because I don't trust the Realm that I built due to above concerns.  So now I wait an unknown # of days for the official pre-built Realm.   Also, each summer I have to puzzle out some sort of Realm build that works in latest betas for both simulator and devices.  If the build steps were clear, I wouldn't at all mind making such builds and would in fact prefer to automatically build my own Realm year-round.

**Comment by tgoyne** [comment]
`master` supports building for Xcode 10 for all platforms other than watchOS. We generally merge support for new Xcode betas to `master` as soon as it appears to work, rather than having a separate branch of it.

`./build.sh ios-swift` builds `Realm.framework` and `RealmSwift.framework` using the currently active version of Xcode (selected with `xcode-select` or by setting `DEVELOPER_DIR`). The only additional build machinery we have around this is assembling builds made with a bunch of versions of Xcode into a single release package and tests for the end result.

**Comment by smartcat32** [comment]
Thank you!
