### ISSUE TITLE
RealmCollectionChange.Initial notification is not always received when observing List

### ISSUE THREAD

**Issue by dmitry-maksimenko** [realm/realm-cocoa#5942]
Almost duplicate of https://github.com/realm/realm-cocoa/issues/3501.

RLMResults.mm
```
- (RLMNotificationToken *)addNotificationBlock:(void (^)(RLMResults *, RLMCollectionChange *, NSError *))block {
    [_realm verifyNotificationsAreSupported:true];
    return RLMAddNotificationBlock(self, _results, block, true);
}
```

RLMManagedArray.mm
```
- (RLMNotificationToken *)addNotificationBlock:(void (^)(RLMArray *, RLMCollectionChange *, NSError *))block {
    [_realm verifyNotificationsAreSupported:true];
    return RLMAddNotificationBlock(self, _backingList, block);
}
```

As you see, RLMResults sets 'suppressInitialChange'. Why is it not implemented for RLMArray?

## Expected Results

Always receive a .initial notification after .observe()

## Actual Results

We don't receive the .initial notification while doing some complex logic in our app. Instead of .initial, we receive .update which has only 'modifications'.

## Steps to Reproduce
At the moment I'm not sure how to reproduce it. The issue happens in a live project that performs dozens of write transactions at once, and objects have complex many-to-many relationships between each other.

## Version of Realm and Tooling

Realm framework version: 3.9.0

Xcode version: 10.0

iOS/OSX version: 12.0

Dependency manager + version: Cocoapods 1.5.3

**Comment by tgoyne** [comment]
The difference in behavior is because accessing an RLMResults can involve running a query, while an RLMArray does not. When a notification block is added to an RLMResults, the query is run on a background thread, and the result of that is sent as the `.initial` notification. This allows you to avoid ever blocking the main thread with a slow-running query.

With RLMArray there's nothing to run on the background thread, and whatever things you would do when receiving a `.initial` notification can instead just be done immediately.
