### ISSUE TITLE
Invalid streaming format cookie (0)

### ISSUE THREAD

**Issue by hschaaps** [realm/realm-cocoa#5974]
Hi,

in one of our iPad projects we have been using the realm database for some time now without any issues. Starting yesterday we are seeing reports from our users were the app can't open the database, the error we see is:

`Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=2 "Unable to open a realm at path '/var/mobile/Containers/Data/Application/2C9AD842-2D0D-45AE-9A6A-534B21063E11/Documents/default.realm': Invalid streaming format cookie (0)." UserInfo={Error Code=2, NSFilePath=/var/mobile/Containers/Data/Application/2C9AD842-2D0D-45AE-9A6A-534B21063E11/Documents/default.realm, Underlying=Invalid streaming format cookie (0), NSLocalizedDescription=Unable to open a realm at path '/var/mobile/Containers/Data/Application/2C9AD842-2D0D-45AE-9A6A-534B21063E11/Documents/default.realm': Invalid streaming format cookie (0).}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.37.1/src/swift/stdlib/public/core/ErrorType.swift, line 184`

After investigating the users getting this error upgraded their iPads to iOS 12.1 which was just released. We tried this scenario ourselves but cannot reproduce the issue. 

We traced the error (Invalid streaming format cookie (0).) to the realm core:
https://github.com/realm/realm-core/blob/master/src/realm/alloc_slab.cpp

However we're not really sure what is the actual cause of this issue.
We're using an encryption key to secure the realm database which is stored in keychain and it's only accessible when the app is in the foreground (kSecAttrAccessibleWhenUnlockedThisDeviceOnly)

We're using basic logic to access the database:

`try Realm(configuration: encryptionKey: getKey() as Data)`

Our project is using realm 3.11.1, xcode 10 and swift 4.2 and targets iOS 11+

Any help would be appreciated

Hans

**Comment by tgoyne** [comment]
When writing a compacted Realm file with `writeCopy(toFile:)` or from a compaction done due to the `shouldCompactOnLaunch` function returning true, we write the Realm in a "streaming form" which places some of the data normally found in the file header at the end of the file instead. This error indicates that decryption succeeded and the file header was valid, but the footer was not found at the expected location at the end of the file.

This means that either something went very wrong while writing the file, or the file was truncated or lengthened after it was written. If you're manually calling `writeCopy(toFile:)` it's possible that a write was interrupted and then you tried to open an incomplete file. Automatic compaction on launch shouldn't be able to cause such issues as we write to a temporary file and then do an atomic rename over the source file if it succeeds. If you're using neither of those features, something very strange has happened.

If you're able to share one of the files that's having issues we could try to investigate it to see what's wrong, but if it's only happening on user devices I'm guessing you can't.

**Comment by tgoyne** [comment]
That code will fail catastrophically if the device is low on disk space: `writeCopy()` will create the file, write to it until the disk is full, then throw an error. We don't delete the incomplete file when writing fails, so the original file will then be replaced with the incomplete one and produce the error you're seeing. If this is the problem, then the link to iOS 12.1 would be that iOS updates take up a whole lot of disk space and errors related to running out of storage temporarily become a lot more common whenever one comes out.

The fix for this would be to either handle the error thrown by `writeCopy()` and delete the temporary file, or use compact on launch which should handle all of the error cases safely.

**Comment by hschaaps** [comment]
Hi @tgoyne,

it's been a couple of days and users have been testing a version of our app without any form of database compacting. We now have another user that was logged into the app, and the app was in the background. The user then installed the iOS 12.1 update (12.0 -> 12.1) on his device and then the app could no longer open the database with the same error as before. We know the device had more then 10 gig of free space available so that shouldn't have caused the issues.

Do you have any ideas or other scenario's that could cause this behavior?

**Comment by hschaaps** [comment]
No updates I'm affraid. Since our app is used by a controlled Group werven instructed them to not Install iOS updates before syncing their data.

**Comment by stan-ko** [comment]
We provide preshipped realm DB in our android app and it is located in assets folder as default.realm file. Before placing it to assets we compact it using RealmBrowser desktop application so app is shipped with compacted realm DB. 
I assume that on initialization of Realm it makes kinda uncompacted copy of this DB and this process requires free space. If it so we can't know how much free space is required by Realm to warn user before this process starts. But since process starts app crashes due to low space.
```
Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/ourapppackage/files/default.realm': Invalid streaming format cookie (288230376154869818) Path:. (Invalid streaming format cookie (288230376154869818) Path: /data/data/ourapppackage/files/default.realm) (/data/data/ourapppackage/files/default.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init> + 171(OsSharedRealm.java:171)
       at io.realm.internal.OsSharedRealm.getInstance + 241(OsSharedRealm.java:241)
       at io.realm.internal.OsSharedRealm.getInstance + 231(OsSharedRealm.java:231)
       at io.realm.RealmCache.doCreateRealmOrGetFromCache + 318(RealmCache.java:318)
       at io.realm.RealmCache.createRealmOrGetFromCache + 284(RealmCache.java:284)
       at io.realm.Realm.getInstance + 428(Realm.java:428)
```
this happens at line `Realm.getInstance(realmConfiguration)` in
```
Realm.init(context); // app context here
realmConfiguration = new RealmConfiguration.Builder()
					.schemaVersion(46)
					.migration(new Migration())
					.build();
mRealmInstance = Realm.getInstance(realmConfiguration)
```
And this happens on user devices. So the question is - how to prevent this issue? How to know how much space is needed by Realm before executing `getInstance()`?

**Comment by cliftonlabrum** [comment]
I'm seeing this same error. Here's what I'm doing:

**= 1 = Compact the Realm**
```
func compactRealm(filename: String) -> URL{
  //Get the default realm file
  let defaultURL = Realm.Configuration.defaultConfiguration.fileURL!
  //Get a new file path for the realm file we'll upload
  let defaultParentURL = defaultURL.deletingLastPathComponent()
  let compactedURL = defaultParentURL.appendingPathComponent(filename)
  
  //Delete existing file
  if FileManager.default.fileExists(atPath: compactedURL.path){
    try! FileManager.default.removeItem(at: compactedURL)
  }
  
  autoreleasepool { 
    let realm = try! Realm()
    //Write the file
    try! realm.writeCopy(toFile: compactedURL)
  }
  
  return compactedURL
}
```
**= 2 = Upload the Realm**
I upload the compacted Realm to a server.

**= 3 = Download the Realm**
I pull down the compacted Realm with Realm JS and see this error. 
> Unable to open a realm at path '/Users/clifton/JS/api.entries.cloud/data/_41b3b965c62592fbbcc500e38dc87217.realm': Invalid streaming format cookie

Here's the full stack track: https://d.pr/n/i5D8kK

I know this error is in the JS SDK, but since it's coming from a Realm compacted on iOS, I thought it might be useful.

Interestingly, if I wait a few seconds, I can open the realm in my JS app successfully. It's just not available in quick succession after saving it:
```
let response = await axios.get(record.fields.file.value.downloadURL, { responseType: 'stream' })
let file = fs.createWriteStream(res.locals.path)
response.data.pipe(file)
//Crash occurs on first attempt to open realm
```
I hope that helps. 🙂

**Comment by tgoyne** [comment]
I don't have a lot of experience with node's APIs, but it looks like you aren't waiting for the download to complete? That code snippet appears to set up a pipe to stream the data from the network to the file asynchronously, and trying to open the file while it's downloading would give exactly the behavior you're describing.

**Comment by cliftonlabrum** [comment]
@tgoyne Ah, you're right! Good catch. Thank you!

**Comment by ericjordanmossman** [comment]
I'll Close this issue because of tgoyne's answers [here](https://github.com/realm/realm-cocoa/issues/5974#issuecomment-435974187) and [here](https://github.com/realm/realm-cocoa/issues/5974#issuecomment-614178092).

Feel free to comment if these don't completely address the issue!

**Comment by tfe** [comment]
In case anyone comes across this in the future, I found another potential cause for this obscure error.

I was using `writeCopy(toFile:)` on first launch to copy a starter realm in my app bundle to the writeable Documents folder for use within the app. I do this operation on every access of the realm if needed (usually only the first time).

The problem was that I added code that caused the realm to be opened on app launch from multiple threads (main, and also a background operation). The first access would trigger the starter data `writeCopy` operation, but before it could finish the other thread would try to open the partially-written realm file. That's why I got the "Invalid streaming format cookie" error, I assume, because the file was still being written at the time the second thread tried to open it.

What's worse is that this crashed the app, leaving a partially written but unopenable copy of the Realm file.

To resolve this I think I'm going to implement a lock for my `writeCopy` operation, to ensure that all other threads trying to open the realm are held until the copy is finished.
