### ISSUE TITLE
Support objects with same name on different schemas

### ISSUE THREAD

**Issue by matibzurovski** [realm/realm-cocoa#6049]
## Goals
I am developing a framework that uses Realm. I want to make sure the client apps won't crash when using Realm as well, regardless of the name they decide to provide to their own objects.

## Expected Results
Client apps can use Realm without any trouble.

## Actual Results
Client apps crash if they try to create an `Object` with a name already used in the Framework schema.
>  *** Terminating app due to uncaught exception 'RLMException', reason: 'RLMObject subclasses with the same name cannot be included twice in the same target. Please make sure 'UserObject' is only linked once to your current target.'

As you may see below, I am overriding the `func shouldIncludeInDefaultSchema()` so that the framework objects aren't included in the app schema, but it still crashes.

## Steps to Reproduce
Run the client app with the code below.

## Code Sample
```Swift
// In the Framework:

class UserObject: Object {
    @objc dynamic var lastName = ""
    
    override class func shouldIncludeInDefaultSchema() -> Bool {
        return false
    }
}

class PersistenceController {
   
   // Method used to access the Realm instance, properly set with its object types
   func createRealm() throws -> Realm {
        let objectTypes: [Object.Type] = [UserObject.self]
        let configuration = Realm.Configuration(schemaVersion: 1, objectTypes: objectTypes)
        return try Realm(configuration: configuration)
    }
}

----------------------------------------------------------

// In the client app:

class UserObject: Object {
    @objc dynamic var firstName = ""
    @objc dynamic var lastName = ""
    @objc dynamic var age = 18

}

```
## Version of Realm and Tooling
**Realm framework version:** 3.11.2

**Xcode version:** 10.1

**iOS/OSX version:** iOS 12.1

**Comment by tgoyne** [comment]
This check exists because when you have a property like `@objc dynamic var obj: UserObject?`, the obj-c runtime just tells us that the type is `UserObject`, and not what the namespace of that type is. As a result, if a `UserObject` type is defined in two namespaces, we don't know which one it is.

A workaround for this is to override the obj-c names of the classes defined in a framework to give them a unique prefix, as you would when defining obj-c classes directly. The syntax for this is `@objc(FrameworkUserObject) class UserObject: Object { ... }`.
