### ISSUE TITLE
How to Get all Regular Users by login via Admin User ?

### ISSUE THREAD

**Issue by sagarshirbhate** [realm/realm-cocoa#6087]
## Question
I have created a list of 10 Regular users on realm object server and each regular user have assigned 3 realms. I tried to get all users via login admin user but no luck.
What I need exactly ?
1. All Regular users available in my realm server.
2. Get Realms files of all regular users.

## Goals
Want all regular users as List in Realm Server (Using Swift 4.2 , RealmSwift 3.10)

## Actual Results
Get Only current user details Not a whole users list

## Version of Realm and Tooling

Realm framework version: 3.16
Realm Object Server version: 3.16
Xcode version: 10.1
iOS/OSX version: Swift 4.2 , iOS 12.1
Dependency manager + version: Swift 4.2

**Comment by ericjordanmossman** [comment]
To keep track of users in ROS you would have to create a realm file to track this information. You could include columns like "username", "email", "userID", etc. The syncUser objects are available in __admin/User, but is **not recommended** to edit or use __admin classes directly because this is system data used for server processes.

I'll close this ticket since it's more related to ROS behavior and not strictly realm-cocoa.
