### ISSUE TITLE
How to use Realm with Xcode 11 Betas?

### ISSUE THREAD

**Issue by cnstoll** [realm/realm-cocoa#6216]
Is anyone successfully using Realm with Xcode Beta 11? If so, I'd like to request some official documentation on how to do this. I've been using Realm for several years now and the summer beta season has always been a little rough. But this summer especially it seems like Realm is just not usable in Xcode 11 at all. 

With my project on Xcode 11 I've tried using Swift Package Manager, and tried manually building Realm and RealmSwift manually and linking them into the project. Both of those worked successfully in Xcode 11 Beta 1, but neither seems to work in Xcode 11 Betas 4 and 5.

I realize that supporting beta release is kind of an unofficial thing, and that we deal with moving targets while things are changing during the summer. But we all also have customers who are expecting iOS 13 support from our apps - and being unable to build and work on our apps with the beta versions of Xcode makes that proposition a lot harder.

Maybe I'm doing something wrong, but that's why I'd like to request some real documentation for "during beta season if you're using Xcode betas...here's how you can continue to use Realm".

As an engineer, when I see a critical dependency like Realm failing to build, it's pretty scary. I'd like to know that the Xcode betas are actually being looked at and that support is planned as soon as the required work can be completed.

**Comment by tgoyne** [comment]
There are instructions for using Realm with Xcode 11 at https://github.com/realm/realm-cocoa/issues/6163. If those do not work for you, you'll need to post the actual errors you're getting to get help with it.

**Comment by virtuosovidit** [comment]
Built the xcframeworks using the instructions provided in #6163 ; They work in  Xcode beta 1, 2 and 3 but are totally broken in Xcode beta 4 and 5. 

Attaching screenshots of the slew of errors that gets thrown out. As far as I can tell there's something wrong with the way the RealmSwift modules are being generated. 

<img width="798" alt="Screenshot 2019-08-02 at 4 28 57 AM" src="https://user-images.githubusercontent.com/20414466/62332755-7cbcd400-b4de-11e9-872c-c81b2a6500c5.png">
<img width="464" alt="Screenshot 2019-08-02 at 4 28 49 AM" src="https://user-images.githubusercontent.com/20414466/62332764-85150f00-b4de-11e9-9cb0-c1222471943f.png">

Using SPM, I get the "Failed to load RealmSwift module" error.

**Comment by tgoyne** [comment]
A few people have said that they had to restart their computer after installing beta 5 for it to work, so give that a try if you haven't. Deleting DerivedData to ensure it's actually rebuilding everything after updating Xcode is a good idea as well.

If i create a brand new iOS project in Xcode 11 beta 5, add the Realm swift package to it (via File -> Swift Packages -> Add Package Depdendency..., entering `https://github.com/realm/realm-cocoa`, and then checking both the Realm and Realm Swift targets), add `import RealmSwift` and a call to `try! Realm()` to AppDelegate.swift, and then hit run, everything builds without errors. Does this work for you as well? If it doesn't, then perhaps it's something related to the macOS version? I'm currently running 10.14.5 rather than a Catalina beta.

If a fresh project does work, then it's probably something related to your application's project. If you can share the project file (the actual source code is probably unnecessary) I'd be happy to try to figure out what's wrong. There isn't much I can do with just some screenshots of errors, though.

**Comment by virtuosovidit** [comment]
It Finally worked. Turns out, the error stems from a Swift Header file that's generated when trying to use a swift class in Objective C. For some reason, SPM dependencies are not recognised in that. 

It also helps to remove and reinstall the SPM dependency after fixing issues with the header file. 

Sigh, It's been a rough beta season.

**Comment by cnstoll** [comment]
I think I've narrowed it down a bit: my project links Realm to an iOS target and an Apple Watch target, via Swift Package Manager. 

If I remove Realm from my Apple Watch target then the iOS target will build! But it won't build if Realm is linked to both iOS and Watch targets. This did work in Beta 1, but seems to be broken in Beta 4.

**Comment by virtuosovidit** [comment]
Yes, Having the same issue ever since I added Realm on the watchOS target.

**Comment by smartcat32** [comment]
With Xcode beta 5, I'm able to finally build RealmSwift.xcframework without error (using DEVELOPER_DIR=/Applications/Xcode-beta.app/Contents/Developer ./build.sh ios-swift ) but the resulting directory ( build/ios/swift-11.0/RealmSwift.xcframework ) only has an Info.plist in it.

- Deleted the realm-cocoa/build directory first, which includes DerivedData.
- Made sure my Xcode 11 beta 5's Command Line Tools point to "11.0 (11M382q)"

Also, with the switch to .xcframeworks, is it still the expectation that I need to embed & link against both Realm.xcframework and RealmSwift.xcframework for an iOS Swift 5.1 app built with Xcode 11?

Now that Mongo owns Realm, any chance we can simply get some pre-built binaries soon after each Xcode beta, or at least some status and exact instructions for how we're to create and use them with each particular beta?

**Comment by jsflax** [comment]
Hi @smartcat32 ,

The idea of prebuilt binaries has recently been floated around, but nothing official has been decided yet. It's safe to assume that there will be a more official support policy for the Xcode betas going forward.

As far as switching to .xcframeworks, yes, you would need to link through the dependency graph. However, we recommend you use Swift PM for now, and potentially going forward (if it suits your use case).

**Comment by virtuosovidit** [comment]
Hi @jsflax 
Currently using Swift Package Manager for an Xcode Project that contains an iOS, Catalyst (UIKitForMac) and an Independent watchOS app. SPM works for iOS and Catalyst, however, when Realm & RealmSwift are added to the watchOS target using SPM, the app only builds with the watchOS target and not the default iOS target.

**Comment by jsflax** [comment]
Hi @virtuosovidit ,

Please try this: https://github.com/realm/realm-cocoa/issues/6213#issuecomment-518771871

If that does not work, I will take a further look.

**Comment by virtuosovidit** [comment]
Hi @jsflax 
It still doesn't work. Gives an error when building the app through the iOS target. I'm using Realm and RealmSwift for both iOS and watchOS apps.

![Screenshot 2019-08-07 at 9 22 46 PM](https://user-images.githubusercontent.com/20414466/62637804-dba8a000-b959-11e9-9fad-d23843b03275.png)
This is the error I keep getting when building with the iOS target.

**Comment by virtuosovidit** [comment]
Hi @jsflax 
Following up on the Realm issue with watchOS targets. Is there a workaround that'll get this working? Willing to share a dummy project that shows the setup if that helps.

**Comment by ChristianSteffens** [comment]
I don't want to be rude, but quite frankly the current situation is making things really difficult for us. I'm working in a big project where Realm is one of our key dependencies. We're really happy with it and are immensely grateful to use it, but with each new major Xcode release it's the same: Realm is by far (!) the last framework that is compatible to a new Xcode / Swift version.

I understand that Realm is a huge project with many - at least to me - unknown dependencies on it's own. But with the huge popularity comes IMHO also some major responsibility to your customers / users. I do know most of them are not paying anything, but I would really appreciate it, if you would spent more time or at least prfioritize the Xcode migration paths.

I know some might think "You're not required to use Realm (at all)", "If is taking you to long, open a PR on your own" - but in the end and at least from my developers colleagues I know this by fact: We all got our own deadlines / projects. We simply don't have the resources to spent some meaningful time to help migrate to the latest Xcode version.

It's certainly not the first time either. For the past years we **always** have to wait for Realm to  be compatible with the latest Xcode (beta).

Don't get me wrong here, we're appreciate the effort put into Realm and it safes us so much time (outside the Xcode-Beta-Interval), but even for a free product at some point you should be aware of the impact towards your users.

I always get the feeling that nobody really cares about the fact that Realm is always behind to support beta Xcode releases. But maybe the others simply moved on and migrated to another framework. The last comment on this issue is now 12 days ago, I can't really believe we're the only ones waiting for a version compatible to Xcode 11 beta ... but maybe we are?

**Comment by tgoyne** [comment]
I'm honestly pretty confused by the claim that Realm is always behind on supporting beta Xcode releases. We've always dropped everything to support new versions of Xcode ASAP, and it's rarely taken more than a few days to support each new beta. In the case of Xcode 11, it took four days. As far as I know, there's only a single outstanding issue with Xcode 11 support (it doesn't build correctly for watchOS when including the new SPM package via an Xcode project and building via the Xcode UI). If you're having trouble with something else, please create an issue with detailed information about what you're trying to do and what isn't working so that we can help figure out how to solve it.

**Comment by tgoyne** [comment]
https://github.com/realm/realm-cocoa/pull/6233 disables building xcframeworks as it turns out that being able to do that without building in ABI-stable mode was just a bug in the earlier Xcode 11 betas.

**Comment by ChristianSteffens** [comment]
> If you're having trouble with something else, please create an issue with detailed information about what you're trying to do and what isn't working so that we can help figure out how to solve it.

Okay this is embarrassing - I just tried to build it on my home machine (from source / latest master) and it was successful. The `xcframeworks` have been created. I'm not sure why I didn't works this morning (and the whole last week for that matter) on my office machine. I'm running Xcode 11 Beta 6 on my home machine and I'm pretty sure it's Beta 5 on the office machine. Either way that's clearly my fault.

**Comment by tgoyne** [comment]
I think there actually is something wrong with xcframework generation for RealmSwift specifically. It seem to have worked for me on one machine but not another with both running Xcode 11 beta 6.  This is the main frustrating thing about Xcode betas.

**Comment by bmunkholm** [comment]
@tgoyne Was the last issue resolved so this can be closed?
