### ISSUE TITLE
Unit testing: XCTAssertEqual returns always false

### ISSUE THREAD

**Issue by maroony** [realm/realm-cocoa#6229]
## Goals
I want to use realm object in unit tests. 

## Expected Results
I want to implement my own equals method. Realm should use my equals method.

## Actual Results
I can not implement a equals method or Realm does not use this.

## Steps to Reproduce
Do something like this

```
let results = realm.objects(MyClass.self)
XCTAssertEqual(results.first, results.first)
```

This returns false!

## Version of Realm and Tooling

Realm framework version: 3.17.3

**Comment by tgoyne** [comment]
Realm overrides equality to compare primary keys for types with primary keys, but for types without primary keys we fall back to the default pointer equality because we're otherwise unable to guarantee that objects which compare equal will have the same hash. If you define your own conformance to Equatable you can do whatever you want.
