### ISSUE TITLE
Primary Key change exception

### ISSUE THREAD

**Issue by levelchanger** [realm/realm-cocoa#6339]
I upgraded to Realm 4.0 and now I'm getting the following exception:
Primary key can't be changed after an object is inserted.

The line of code that kicks off the exception is...
competitionGroup = [TDCompetitionGroup allObjectsInRealm:self.realm].firstObject;

Trying to get the first object causes the problem. Here's the stack trace
<img width="749" alt="Stack Trace" src="https://user-images.githubusercontent.com/43216100/68536972-fc91e000-0310-11ea-9492-1b7ee90ec94c.png">

Here's the initializer for TDCompetitionGroup:

+ (NSString *)primaryKey {
    return @"key";
}

- (instancetype)init {
    if (self = [super init]) {
        self.key = NSUUID.UUID.UUIDString;
        self.rules = RulesUnknown;
    }
    return self;
}

Class definition:
@interface TDCompetitionGroup : RLMObject
@property NSString *key;
@property NSInteger rules;

@property TDTeam *myTeam;
@property (readonly) BOOL isCollegiate;

Why is Realm trying to create one of my objects when all I want is the first object from an RLMResults? How can a primary key be considered changed within its initializer?

## Goals
Not have it blow an exception. It worked fine in 3.21.

## Expected Results
Have it work like it did in 3.21.

## Actual Results
See stack trace above

## Code Sample
See above

## Version of Realm and Tooling
Realm framework version: 4.0

Realm Object Server version: ?

Xcode version: 11.1

iOS/OSX version: 10.15.1

Dependency manager + version: Cocoapods 1.8.4

**Comment by tgoyne** [comment]
Overriding `defaultPropertyValues` rather than `init` to populate the properties for newly created objects is the recommended approach and will fix this problem.

One of the 4.0 changes is to switch from 3 designated initializers (which caused problems in Swift) to using a single designated initializer, so now the no-arg init method is called even when creating accessor objects when reading from the Realm. I think there's some room for making it better behaved, though; currently you can't actually safely do much of anything in the initializer.

**Comment by levelchanger** [comment]
Yep, that fixed it. Thanks for the help.
