### ISSUE TITLE
Failed to resolve 'myapp.us1.cloud.realm.io:443': Host not found (authoritative)

### ISSUE THREAD

**Issue by veluloganathan** [realm/realm-cocoa#6377]
I have a watchOS app running with realm. Everything works fine in simulator. But fails in the real device.

**Comment by bmunkholm** [comment]
@veluloganathan Please fill out the issue template.

**Comment by veluloganathan** [comment]
@bmunkholm updated

**Comment by bmunkholm** [comment]
Thanks @veluloganathan. I was hoping for more information actually :-) Consider what info you would like if you were to help resolve such an issue? 
i.e.:
Where does this message come from (share full error message, logs)?
What has changed since it worked?
Can you reliably replicate this now?
How can others replicate this? (can you share a minimal project)
What have you done to debug this?

Helping you debug this remotely requires you provide us with as much info as possible.
If you can make it very easy for others to help you troubleshoot I'm sure someone will try (despite this repo is only for bugs)

**Comment by veluloganathan** [comment]
as same as https://github.com/realm/realm-cocoa/issues/5513 
so realm doesn't support watchOS apps?

**Comment by leemaguire** [comment]
With WatchOS 6 supporting web sockets, this has been added to a list of feature requests.
