### ISSUE TITLE
Realm=4.3.1 install error with CocoaPods

### ISSUE THREAD

**Issue by Lax** [realm/realm-cocoa#6407]
!!! MANDATORY TO FILL OUT !!!

## Goals

Integrate Realm with existing iOS project with cocoapods.

## Expected Results

with no errors

## Actual Results

```
Errno::ENOENT - No such file or directory @ rb_check_realpath_internal - /Users/lax/Perspire/demoapp/ios/Pods/Realm/include/Realm/RLMAccessor.h
```

This path is a soft link to ../../Realm/RLMAccessor.h, which does not exist.

this issue happens to Realm=4.3.1, while for Realm<=4.3.0 there's no such issue.

## Steps to Reproduce

add `pod "Realm"` to Podfile, then run `pod install`

## Version of Realm and Tooling

Realm framework version: 4.3.1

Realm Object Server version: ?

Xcode version: ?

iOS/OSX version: ?

Dependency manager + version: cocoapods 1.8.0

**Comment by Eyesony** [comment]
I got the same error today. 
After several hours of investigation, I managed to fix it.

Remove Realm, RealmSwift under 
~/Library/Caches/CocoaPods/Pods/Release
~/Library/Caches/CocoaPods/Pods/Specs
Then `pod install`

I guess this is caused by a failed 'pod install' previously.
I did fail about 2~3 times due to a poor network connection.

**Comment by leemaguire** [comment]
@Lax, Did @Eyesony's comment help you fix you issue?

**Comment by Lax** [comment]
Yes, it works perfectly.

```
rm -rf ~/Library/Caches/CocoaPods/Pods/Release/Realm ~/Library/Caches/CocoaPods/Pods/Specs/Release/Realm
```

**Comment by KingCloser957** [comment]
You sava my day @Lax
