### ISSUE TITLE
error "Error Domain = io.realm Code = 1" Provided schema version 33 is less than last set version 40. "UserInfo = {NSLocalizedDescription = Provided schema version 33 is less than last set version 40., Error Code = 1}" that persists even removing the appl

### ISSUE THREAD

**Issue by adrianorezena** [realm/realm-cocoa#6417]
I am trying to install my app on the device to an earlier version (the old version was deleted from the device), but it appears that the base is not being deleted when removing the app.
We have the app and an extension using the same database.
The problem does not occur in the simulator, only in the device. It appears that the shared folder is not being removed when deleting the app. And I made sure I deleted it and didn't use the "Offload App" option.

I had done it countless times and it always worked, but I noticed this problem in the last few days.
Tested on devices with iOS 13.3, 13.3.1 and 12.4

Has anyone had something like that?

## Version of Realm and Tooling
RealmSwift (3.18.0)

**Comment by leemaguire** [comment]
Hi,

This sounds like an issue with App Groups. To summarise, in order to remove the old files you must remove all apps (or extensions) related to that App Group on your device.

Here is a link with a similar issue to yours https://stackoverflow.com/questions/35365682/removing-app-doesnt-remove-app-group-data

Thanks,
Lee
