### ISSUE TITLE
Realm collection notification takes 7 seconds to arrive

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#6514]
BUG

For some reason it is taking around 7 seconds for an update to a collection to arrive.  Any suggestions as to where to look as this seems pretty strange.

The update is creating a new item in the primary collections objects List properties.

Store {
 var id: String
...

let fixtures = List<Fixture>()
}

The primary collection is Results<Store> 

and a new fixture gets created - the realm commit is almost instantaneous

Could this have anything to do with number of data records - and there are < 200 Stores, each with maybe 100 fixtures.

Any pointers will be welcome.  Happy to dig into things in more detail if required.

OK I just noticed it seems to be very slow the first time a new fixture is created but its fast for subsequent creations.  Perhaps something to do with a lazy fetch the first time ?

**Comment by leemaguire** [comment]
Hi @duncangroenewald 

This may answer why your operation is showing a delay the first time round:

`Since notifications are delivered using a run loop, the delivery of notifications might be delayed by other activity on the run loop. When notifications can’t be delivered immediately, changes from multiple write transactions may be coalesced into a single notification.`

Here is the link: https://realm.io/docs/swift/latest/#notifications

Thanks,
Lee
