### ISSUE TITLE
Help: Attempt to improve perf by replacing Array(results) with results.freeze()

### ISSUE THREAD

**Issue by Kdoherty11** [realm/realm-cocoa#6545]
## Goals
Improve performance by replacing `Array(realmResults)` with `realmResults.freeze()`

## Expected Results
I would expect iterating over a frozen `Results<T>` directly to be faster than copying the results into an Array and iterating

## Actual Results
Iterating over the frozen `Results<T>` is 2x slower

<img width="879" alt="Screen Shot 2020-05-31 at 10 54 11 AM" src="https://user-images.githubusercontent.com/1815585/83355465-9e206380-a32d-11ea-8190-fd8121071d0f.png">

I know there are reasons iterating over contiguous memory is faster, but it seems like avoiding the copies should offset them since these objects are not small. Most of the overhead comes from RLMAccessorContext. Can the accessor constraints be relaxed for frozen Results?

## Code Sample
```swift
func run1(results: [T]) {
  for t in results { ... }
}
func run2(results: Results<T>) {
  for t in results { ... }
}
// Faster
let results = realm.objects(T.self)
run1(results: Array(result))
// Slower
let results2 = realm.objects(T.self).freeze()
run2(results: results2)
```

Note: I'm running this in a private repository which would take some work to get into a state where others could use it to reproduce. If the above code samples are not enough, please let me know any I can try to work something out.

## Version of Realm and Tooling
Realm framework version: 5.0.0

Xcode version: 11.4.1

iOS/OSX version: 10.15.4

Dependency manager + version: Pod 1.8.4

**Comment by tgoyne** [comment]
Eliminating the Array doesn't speed things up much because very little of the time is spent in constructing the Array. In both `for object in realm.objects(...) { ... }` and `for object in Array(realm.objects(...)) { ... }` we need to allocate an accessor for each object in the Results, and putting those accessors into an array is relatively cheap compared to creating them in the first place. Freezing the Results doesn't do anything that'd let us skip allocating the accessor objects.

Where you would see a speedup is if freezing replaced a copy of the objects. For example, something like replacing `results.map { T(value: $0) }` with `results.freeze()` would generally give a substantial speedup.

**Comment by leemaguire** [comment]
Closing this issue, if you come across anything else please feel free to reach out.

Thanks,
Lee
