### ISSUE TITLE
Compact realm file manually

### ISSUE THREAD

**Issue by jr9098** [realm/realm-cocoa#6580]
Is there a way to compact a large realm file (1.67GB) I have tried to use the compact on launch feature but I get an exception with reason "failed to allocate memory". The crash is 100% reproducible with my large realm file on an iPhone 7. If I take another realm file that is normal size < 500MB I don't get this issue. I'm using Realm 5.0.2.  I noticed that Realm-java has a function to compact a realm file static boolean compactRealm(RealmConfiguration configuration) but Realm cocoa has no equivalent. Also I succeeded to compact the file to 15.4MB with Realm Studio just by creating a fresh copy of the realm file. Any help would be greatly appreciated!

**Comment by ericjordanmossman** [comment]
The compaction process [is a memory intensive operation](https://realm.io/docs/swift/latest/#compacting-realms) because it requires copying the realm file, so this may explain the exception you see immediately.

But it's also important to consider the underlying problem of why the realm file grows that large. [Here](https://github.com/realm/realm-cocoa/issues/5931) and [here](https://github.com/realm/realm-cocoa/issues/5482) are two threads that go into detail on some behavior.

**Comment by jr9098** [comment]
The problem is that we have some user in production client that are stuck with this large file and we cannot do anything for them to make the app work unless we delete the realm file and this would result in loss of data. We did address those issues to make sure the realm file doesn't grow anymore but I would like to fix those client where the damage is already done...

**Comment by bmunkholm** [comment]
Did you try with the newest version as well? I know things have been updated in this area, so it might actually help to use the latest version.

**Comment by ianpward** [comment]
If your hardware cannot compact the realm then you will need to move it to a hardware platform that can. Or manually copy the realm out to somewhere else (like a laptop) and move the data to prevent data loss
