### ISSUE TITLE
Remove very high number of active versions

### ISSUE THREAD

**Issue by qazwini** [realm/realm-cocoa#6783]
!!! MANDATORY TO FILL OUT !!!

## Goals

Make a write transaction without issues.

## Expected Results

Setting `config.maximumNumberOfActiveVersions = 5` should remove my 5000 active versions.

## Actual Results

Getting this error:
```
Terminating app due to uncaught exception 'RLMException', reason: 'Number of active versions (5837) in the Realm exceeded the limit of 5'
```

## Steps for others to Reproduce

I basically messed up with my write transaction. I was doing something like:
```
for myClass in myClasses {
    try! realm.write {
        let newMyClass = realm.create(MyClass.self, value: [
            "id": myClass.id,
            "entitle": myClass.entitle,
            "location": myClass.location,
            "trans": myClass.trans
        ], update: .modified)
    }
}
```
On every update released, which was destroying the world and bloating the realm database file size and giving me this error:
```
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=9 "mmap() failed: Cannot allocate memory size: 63963136 offset: 469762048" UserInfo={NSLocalizedDescription=mmap() failed: Cannot allocate memory size: 63963136 offset: 469762048, Error Code=9}
```
So I realized that this causes too many write transactions, so I inverted the loop and the write transaction:
```
try! realm.write {
    for myClass in myClasses {
        let newMyClass = realm.create(MyClass.self, value: [
            "id": myClass.id,
            "entitle": myClass.entitle,
            "location": myClass.location,
            "trans": myClass.trans
        ], update: .modified)
    }
}
```
But now, there are always ~5700 active versions. I tried setting `config.maximumNumberOfActiveVersions = 5` but this only gives me the error:
```
Terminating app due to uncaught exception 'RLMException', reason: 'Number of active versions (5837) in the Realm exceeded the limit of 5'
```

## Code Sample

This is my setup function:
```
static func setup() {
    let migrationBlock: MigrationBlock = { migration, oldSchemaVersion in
        if oldSchemaVersion < 2 {
            migration.enumerateObjects(ofType: MyClass.className()) { oldObject, newObject in
                let favorited = oldObject!["favorited"] as! Bool
                newObject!["favorite"] = NafFav(favorited: favorited, dateFavorited: getNormalDate(withYear: true, numberFormat: true))
            }
        }
    }
    var config = Realm.Configuration(schemaVersion: version, migrationBlock: migrationBlock)
    config.fileURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: appGroupID)!.appendingPathComponent("db.realm", isDirectory: true)
    //config.maximumNumberOfActiveVersions = 5//64
    Realm.Configuration.defaultConfiguration = config
}
```

## Version of Realm and Tooling

Realm framework version: 5.3.5

Realm Object Server version: 6.0.19

Xcode version: 12 GM

iOS/OSX version: 14.0

Dependency manager + version: SPM 5.2

**Comment by bguidolim** [comment]
I think this configuration is not intended to remove active versions, but only to give you a tool to understand what is happening and you fix by yourself.

You're probably opening instances of your database in different places at the same time, and somehow it's not being deallocated, generating multiple versions. This usually happens when you create new instances in a background thread.

You must confine background instances in a serial queue or use `autoreleasepool` blocks if you're not confining in a `DispatchQueue`. (Am I right @tgoyne?)

**Comment by ericjordanmossman** [comment]
> Setting config.maximumNumberOfActiveVersions = 5 should remove my 5000 active versions.

@bguidolim is correct -- `maximumNumberOfActiveVersions` will not remove active versions, it [sets a cap on active versions ](https://github.com/realm/realm-cocoa/issues/6572#issuecomment-658274745)in order to prevent a situation where the number of active versions gets out of control. `maximumNumberOfActiveVersions` gives the developer more feedback on whether that's happening.

If you find yourself with more active versions of a particular realm open then you expect, you'll need to ensure that you're not [holding onto references](https://github.com/realm/realm-cocoa/issues/6572#issuecomment-662770639) to that realm on a different thread.

As I mentioned [yesterday,](https://github.com/realm/realm-cocoa/issues/6773#issuecomment-694371720) if you've already controlled for that, upgraded to 5.4.x, and still see mmap failures, please let us know in #6572 .

**Comment by qazwini** [comment]
Oh, I see. This is what I was doing:
```
let group = DispatchGroup()
group.enter()
DispatchQueue.global().async {
    let serializer = JSONSerializer()
    serializer.percentCompleted = { percent in
        DispatchQueue.main.async {
            circularProgress.progress = percent
        }
    }
    serializer.serialize(input: "MyFile")
    group.leave()
}
```

Looks like using the `global()` queue was causing it. But not my progress bar doesn't work anymore. Is there a way to make it work?

**Comment by ericjordanmossman** [comment]
@qazwini 
I couldn't comment on your progress bar for sure. For any general questions/help about how to use Realm [please try our developer forums](https://developer.mongodb.com/community/forums/) or stack overflow.
