### ISSUE TITLE
Using RealmSwift.NotificationToken type when RealmSwift acts as a dependency fails CocoaPods lib lint validation

### ISSUE THREAD

**Issue by DenTelezhkin** [realm/realm-cocoa#6800]
## Goals

Use RealmSwift as a dependency for CocoaPod in Xcode 12. Not sure when this started happening, as this integration was working for couple of years without any issues.

## Expected Results

When using RealmSwift as a dependency, pod lib validation should succeed.

## Actual Results

Pod lib lint returns undefined symbols error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RLMNotificationToken"
```

## Steps for others to Reproduce

1. Clone https://github.com/DenTelezhkin/DTModelStorage, branch [cocoapods-enable-realm](https://github.com/DenTelezhkin/DTModelStorage/tree/cocoapods-enable-realm)
2. Run `bundle exec pod lib lint --allow-warnings --no-clean --verbose`
3. Observe build failures.

## Code Sample

Attaching CocoaPods-generated project that failed pod lib lint validation for easier debugging:

[CocoaPods-Lint-20200923-61087-vg31ow-DTModelStorage.zip](https://github.com/realm/realm-cocoa/files/5268025/CocoaPods-Lint-20200923-61087-vg31ow-DTModelStorage.zip)

Also build failure can be observed on CI: 

https://github.com/DenTelezhkin/DTModelStorage/runs/1154609764?check_suite_focus=true

It seems, that the only issue is with RLMNotificationToken type, because if the code referencing this type is commented out, build succeeds.

## Version of Realm and Tooling

Xcode 12
CocoaPods 1.10.0.beta.2
Realm 5.3.5
RealmCore 6.0.19

**Comment by mentrena** [comment]
Having the same issue here.

<img width="1066" alt="Screenshot 2020-09-25 at 09 26 55" src="https://user-images.githubusercontent.com/1587536/94249101-51354e00-ff17-11ea-8bca-f4e5c827ea98.png">

Xcode 12
Cocoapods 1.9.3
Realm 5.4.3

**Comment by mattjankowiak-sy** [comment]
Seeing the exact same issue here as @mentrena, exact same specs he listed.

**Comment by manish-Wibmo** [comment]
facing exact issue here as well... any fixes? 

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RLMNotificationToken", referenced from:
      objc-class-ref in RxRealm.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rubenbacanu** [comment]
+1

**Comment by x-NR-x** [comment]
Hi,

We are facing the same issue as well.
Xcode 12
Cocoapods 1.9.3
Realm 5.5.0

Is there any kind of update?

Thanks,
Nilit

**Comment by mentrena** [comment]
And still facing this issue on:
Xcode 12.0.1
Cocoapods 1.9.3
Realm 10.0.0

**Comment by andreadelfante** [comment]
Hi,
I'm facing this issue as well. My environment is:
Xcode 12.1
Cocoapods 1.10.0
Realm 5.5.0

**Comment by leemaguire** [comment]
@andreadelfante `pod lib lint --allow-warnings` passes for me using Realm Cocoa 10.1.1 & Cocoapods 1.10

**Comment by mentrena** [comment]
Xcode 12.1
Cocoapods 1.10.0
RealmSwift 10.1.2

Cocoapods fails to validate for watchOS target.

Steps:
- Clone pod repository: https://github.com/mentrena/SyncKit
- Run  `pod lib lint SyncKit.podspec --subspec=RealmSwift --no-clean`
- Validation fails. The Cocoapods generated project can be inspected and these are the build errors:

```
Undefined symbols for architecture x86_64:
  "_RLMRealmPathForFile"
"_OBJC_CLASS_$_RLMNotificationToken"
"_OBJC_CLASS_$_RealmSwiftObject"
"_OBJC_METACLASS_$_RealmSwiftObject"
```

**Comment by JonnyBeeGod** [comment]
Same issue with Xcode 12.2 cocoa pods 1.10

What I discovered is that when building with the no-clean option and opening the generated App.xcworkspace First compilation will fail as well, it will however succeed when tried another time, this time with cleared derived data. Does not help because pod lib lint will still always fail but maybe it helps with debugging

**Comment by JonnyBeeGod** [comment]
I am also getting the same error for RealmSwiftObject


```

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RealmSwiftObject"

```

**Comment by petropavel13** [comment]
Looks like we need to add `Realm` to `podspec` file:
```ruby
s.dependency "Realm"
```
Otherwise your target will not depend on `Realm` despite [`RealmSwift` has dependency on `Realm`](https://github.com/realm/realm-cocoa/blob/master/RealmSwift.podspec#L21):

Looks like coocapods bug.

### For example:

#### Target dependencies in Pods project with implicit `Realm` dependency:

<img width="635" alt="Screenshot 2020-11-25 at 14 30 47" src="https://user-images.githubusercontent.com/6436245/100223048-08f0d700-2f2c-11eb-99e5-bf57917121a4.png">
<img width="705" alt="Screenshot 2020-11-25 at 14 30 57" src="https://user-images.githubusercontent.com/6436245/100223054-0aba9a80-2f2c-11eb-8c17-6eb60c9d50ac.png">

#### Target dependencies in Pods project with explicit `Realm` dependency:

<img width="647" alt="Screenshot 2020-11-25 at 14 38 54" src="https://user-images.githubusercontent.com/6436245/100223151-29b92c80-2f2c-11eb-954b-98d9ea9e0478.png">
<img width="700" alt="Screenshot 2020-11-25 at 14 39 19" src="https://user-images.githubusercontent.com/6436245/100223154-2a51c300-2f2c-11eb-93f3-5fa3ccc29d6b.png">

**Comment by DenTelezhkin** [comment]
This totally fixed this issue for me, thanks @petropavel13! Closing.

**Comment by bolambaoZebo** [comment]
@petropavel13 thanks a lot this solve also same issue that I have.

Xcode Version 12.4 (12D4e)
cocoa pods 1.10.1
