### ISSUE TITLE
Have RLMResults report query changesets when realm is updated / NSFetchedResultsController alternative

### ISSUE THREAD

**Issue by matthewcheok** [realm/realm-cocoa#687]
This would be great for animations similar to `NSFetchedResultsController`.

**Comment by voidref** [comment]
I am looking forward to this now too, have to do some unsettling state management for making table views not just completely reload themselves when something changes.

**Comment by bigfish24** [comment]
If interested in a NSFetchedResultsController replacement until Realm implements it internally, check out: https://github.com/Roobiq/RBQFetchedResultsController

It was built to be a drop-in replacement, with the only hitch that you have to log your changes through a RBQRealmChangeLogger to broadcast them since Realm isn't reporting changes yet. Feel free to reach out at adam@roobiq.com if you have any questions.

**Comment by hwaxxer** [comment]
I'd love to use Realm for a new project but this is unfortunately a deal breaker. Hope you get there soon! :+1:

**Comment by leosobral** [comment]
+1

**Comment by jamesbrooks** [comment]
+1

**Comment by kylebshr** [comment]
+1

**Comment by cooler333** [comment]
+1

**Comment by 1amageek** [comment]
I also made a FetchedResultsController in Swift
https://github.com/1amageek/RLMFetchedResultsController

**Comment by mommyme** [comment]
+1
