### ISSUE TITLE
Retrieve, Update, Delete data the same time and app crash

### ISSUE THREAD

**Issue by phuocmobytelab** [realm/realm-cocoa#6930]
Hi all, I made IOS app search place with local database. And every day I will update local database from server. When I update i will do: 
1/ delete all objects in Database
2/ update new value to Database
-> sometime app will crash with message: Object invalid or deleted. It happen only app ready get old data from database and show in app. Can you give me any advise for this situation? Thank you very much

**Comment by pavel-ship-it** [comment]
Hi @phuocmobytelab 
Could you please fill the issue template?
We need the information on what version of Realm you are using? 
Do you use Sync?
Any crashlogs?
Steps to reproduce and/or code snippet?

From what you write it's not easy to say what goes wrong.

**Comment by ericjordanmossman** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
