### ISSUE TITLE
Crash with 'Object has been deleted or invalidated.' like issue stated in #4856

### ISSUE THREAD

**Issue by kaungkhantsoe** [realm/realm-cocoa#7081]
Steps to reproduce.
1. Implement TabBarController with two view controllers
2. Store some data or a list and display it in first view controller
3. Go to second view controller and call realm.deleteAll() 
4. Return to the first view controller(*** previously displayed data from realm is still there ***) and store data again
5. App will crash with following exception

*** Terminating app due to uncaught exception 'RLMException', reason: 'Object has been deleted or invalidated.'
terminating with uncaught exception of type NSException

**Comment by jsflax** [comment]
@kaungkhantsoe could you send us an example of this? If you're trying to re-add invalidated Objects, that's not supported behaviour.

**Comment by ericjordanmossman** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
