### ISSUE TITLE
Slow notification when adding object to synced Realm (MongoDB Realm SDK V10.x)

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7357]
## Goals
App has a list of realm objects and observes the Results<ObjectType> in order to update the list if items are added or removed

## Expected Results
When the user add a new item to the realm we expect to get an immediate notification in order to update the user interface and show the new item in the list

## Actual Results
When using a synced realm the notifications are taking a long time to be delivered 2 - 5 seconds which does not appear to be the same behaviour we have been seeing with the RealmSwift 5.x SDK and Realm Cloud.

## Steps for others to Reproduce
Open a synced realm and query an object collection and create an observer to get notified of any changes to the list

## Code Sample

let objects = realm.objects(Item.self)

self.notificationToken = objects?.observe { [weak self] (changes: RealmCollectionChange) in

    // Update the UI list if things change

}

## Version of Realm and Tooling

Realm framework version: RealmSwift v10.9.0

Xcode version: 12.5.1

iOS/OSX version: maxOS 11.5

Dependency manager + version: N/A

EDIT:

THIS MAY HAVE NOTHING TO DO WITH SYNCED REALM - sorry that could be misleading as I see there seems to be some regression with realm-core with the 'DeepChangeChecker'. https://github.com/realm/realm-core/pull/4816

**Comment by leemaguire** [comment]
Hi @duncangroenewald 

I'm not sure that the regression with the DeepChangeChecker is related to what you're seeing. Would you be able to update to the latest version and let us know if the issue persists?

Also how big is the `Results` that you are observing?

Thanks

**Comment by duncangroenewald** [comment]
The results is tiny - 8 objects.   CPU does spike to 100% for the duration until the notification arrives.

I will test with 10.10 and let you know.

Cheers.

**Comment by duncangroenewald** [comment]
@leemaguire - same result with 10.10.  Tomorrow I will test with local version (non-synced) and maybe try an earlier version - I think I saw someone mention 10.7 never had this issue - assuming it is the same issue - unless you have some other suggestions.  

Weird thing is I am getting about 5 other notifications with modifications when all I have done is add one object.

I would only expect to see one notification with one insertion - but then I haven't really studied notifications and how they work much.

**Comment by duncangroenewald** [comment]
@leemaguire - I just tested with local only version and get the same issue so not sync related.  I will try earlier versions.

**Comment by duncangroenewald** [comment]
Issue is the same with 10.7.6 and 10.7.1

**Comment by tgoyne** [comment]
If 10.10.1 doesn't help with your specific case, then some sort of sample app which hits problems would be very useful. There's a lot of room for further optimizations in the notifier code, but where the hot spots are varies quite a bit depending on what your schema and object graph look like so it's easy to speed a bunch of artificial benchmarks up without actually fixing the problem that a specific app is running in to.

**Comment by duncangroenewald** [comment]
@tgoyne - I will see if it is feasible to create a test app.

In the meantime can you confirm the following:

1.  In general notifications for adding an object to a collection should be sent nearly instantly and should not be taking 2 - 5 seconds.  
2. Is there any difference in behaviour for synced or non-synced realms ?
3. What is going on in the background prior to sending the notification that could take so much time ?
4. What if any steps can be taken to avoid such slowdowns ?

**Comment by duncangroenewald** [comment]
@tgoyne - sorry I didn't see the 10.10.1. - will give that a go - I have only tried 10.10.0

**Comment by tgoyne** [comment]
The release is currently building and will be out today. Turns out it'll actually be 10.11.0 though as another PR landed that added features.

> In general notifications for adding an object to a collection should be sent nearly instantly and should not be taking 2 - 5 seconds.

For the simplest case where you're observing a single List and nothing else, your schema is acyclic, and you perform a write which does nothing but create a new object and add it to the List, it is reasonable to expect a change notification from that in the ballpark of 10ms on a relatively recent iPhone. If your collection is a sorted Results with a hundred thousand  objects, then we have to recalculate the sort after modifications, and that obviously takes longer. If you modify any of the objects of the type which a List contains then we check if any of the objects in the List were modified, and this can sometimes take an unreasonably long amount of time (and it is this checking which 10.11.0 will have some improvements for).

Multiple second delays is not the expected behavior and probably means that either you're (possibly unintentionally) observing a very large number of collections or are hitting some code which needs to be better optimized.

(Or it means that you're using a debug build while installing via SPM, which builds the whole library without compiler optimizations and so can be dramatically slower than release builds).

> Is there any difference in behaviour for synced or non-synced realms ?

There should not be. Write transactions on synchronized Realms are sometimes slower than on non-synchronized Realms, but nothing that happens between `commitWrite()` returning and a notification being delivered differs in any way between them.

**Comment by duncangroenewald** [comment]
OK - yes that pretty much what I was expecting - haven't seen any issues with the same collections and Results sets on 5.x previously so this is a bit of a surprise.

It is a new software release and never noticed this delay previously.  

With a simple creation of a new object would it be normal to get only a single notification with the inserted object ?

The scenario we have is there are 5 shelves each with a number of items on the shelf and when we add a new item to one of the shelves we are getting what appears to be 5 notifications - only one of which has an 'inserted' - the rest have 'modifications'.

class Shelf: Object {
    _id: String
   ...
   let items = List<Item>()
}
class Item: Object {
   _id: String
   shelf: Shelf
   ...
}
extension Shelf {
  var filteredItems: Results<Item> {
      return self.items.filtered(...).sorted(...)
  }
}

The same code is creating the 5 shelves and setting up observers for the list of filtered items for each shelf.  

The Shelf.items property contains the list of Items but the displayed list is a filtered sorted list from the Shelf.items property.

Will dig a bit deeper into this but I wouldn't expect that the shelves that do not have items added should be receiving notifications (well the observers of the filtered sorted Results for that shelves items property) when a new item is added to another shelf.

**Comment by duncangroenewald** [comment]
@tgoyne - thanks 10.11.0 fixes the issue - great work.

**Comment by duncangroenewald** [comment]
@tgoyne - I have just run into another crash when deleting objects from the same collection as well as others.  The crash log said to log the issue with realm-code which I have done. See realm-code issues for more details.
