### ISSUE TITLE
Type 'Int' does not conform to protocol 'RealmPropertyType'

### ISSUE THREAD

**Issue by caglayansever** [realm/realm-cocoa#7369]
We upgraded realm version to 10.10. After upgrade `RealmOptional` has warning that _'RealmOptional' is deprecated: RealmOptional<T> has been deprecated, use RealmProperty<T?> instead._
But we can't use RealmOptional for Integers.

How can we use optional int with new version.

```dynamic var xxx = RealmProperty<Int>() ``` _Type 'Int' does not conform to protocol 'RealmPropertyType'_

```dynamic var yyy = RealmOptional<Int>()``` _'RealmOptional' is deprecated: RealmOptional<T> has been deprecated, use RealmProperty<T?> instead._

**Comment by dianaafanador3** [comment]
Hi @caglayansever, 
You have to declare your `Int` as optional in order to use it with RealmProperty 
`var otherInt = RealmProperty<Int?>()`

As another option, have you considered use our new model syntax declaration `@Persisted`, so instead of using `RealmOptional` or `RealmProperty` you can declare your int as optional and use our new property wrapper. For example
```
final class ModernSyntaxObject: Object {
   @Persisted var intOpt: Int?
}
```

**Comment by raphaels17** [comment]
If one keeps the same name for the var intOpt  then intOpt but just change the encapsulation method, does this calls for a migration in some scenario ?  or can I change  all my 
let exampleVariable = RealmOptional<Int>() to
@Persisted var exampleVariable: Int?
without any concern? 

Kind regards
