### ISSUE TITLE
"Realm accessed from incorrect thread." from inside Task

### ISSUE THREAD

**Issue by adamek314** [realm/realm-cocoa#7431]
I'm working with iOS 15.0 (19A5340a) on my iPhone, developing in Xcode 13 beta and using Realm 10.14.0.

As I understand it, when I create a task, operations inside it are one one thread (not counting child tasks). I created a realm inside a task. I thought I could use that realm to retrieve items inside that task. However, I'm getting a "Realm accessed from incorrect thread." fatal crash. 

Are realm operations inside a Task not possible in the iOS15 beta?

It crashed at `guard let asyncItem = asyncRealm.object(ofType: ShoppingItems.self, forPrimaryKey: itemKey)` in the code below.

Task(priority: .userInitiated) {
            do {
                let asyncConfig = await foodyState.thisConfig
                let asyncRealm = try Realm(configuration: asyncConfig)
                let currentReceiptKey = await foodyState.currentReceiptKey
                let userKey = await foodyState.uuidUser
                let familyKey = await foodyState.uuidFamily
                guard let asyncItem = asyncRealm.object(ofType: ShoppingItems.self, forPrimaryKey: itemKey) else {
                    NSLog("WARNING: Could not get ShoppingItem for \(itemKey).")
                    return
                }

**Comment by tgoyne** [comment]
We do not currently support task-confined Realms. Each Realm instance can only be used on a single thread at a time, and Tasks do not provide that guarantee.

**Comment by lsmilek1** [comment]
Is there any workaround for this? Do you plan any build in feature to overcome this? 

Due to swift "async infection" through the code there is currently not much space for having async/await in the code together with Realm.

**Comment by sethsamuel** [comment]
Is there any update on this? Currently can't use Realm with async/await because initing a realm with async always does so on the main thread, which immediately causes a crash if the async code has been moved to a background thread.

**Comment by theoks** [comment]
Any updates on supporting Realm usage with Swift's new concurrency system? Everything is gradually pivoting there and there is no viable way to use async/await in a clean way within codebases where async network calls are tightly coupled with realm operations.

**Comment by jsflax** [comment]
@theoks what issues are you seeing with Realm and async/await? We have added limited async/await support so we should be able to guide you in the right direction.

**Comment by theoks** [comment]
The most frequent issue I face is something along these lines:

```
Task {

  let networkResponse = await myNetworkCall()
  
  let realm = Realm() // Simplified it here, we use a computed property on a manager

  try! realm.write {
    // It usually fails here, with a "Cannot register notification blocks from within write transactions."
    // Once I got a crash from accessing the realm from an incorrect thread.
  }
}
```
I guess that this is probably an issue created due to the notification blocks that the Combine publisher extensions create under the hood (?). Before Task and async/await I would usually do the write in another background thread, and that would fix the issue, but in this case there is actually no guarantee or control over the thread the transaction will happen.

One solution I thought of but haven't tested so far is to move the write transaction to another DispatchQueue within the task (albeit it's ugly and defeats the purpose of using async/await).

I am also worried for random crashes due to the thread confinement restriction. I took a look at issue https://github.com/realm/realm-swift/pull/7576 however it's not clear that this feature will remedy the issues I mentioned above.
