### ISSUE TITLE
'Unsupported predicate value type', reason: 'Object type any not supported'

### ISSUE THREAD

**Issue by JAManfredi** [realm/realm-cocoa#817]
**\* Terminating app due to uncaught exception 'Unsupported predicate value type', reason: 'Object type any not supported'

I cant quite figure out why this exception is happening, it doesnt make much sense to me, but here is what I can find. The first query is the one that is breaking, the second one works fine, the only difference is that one property is set up as a String in the database, the other an Int.

```
        let predicate: NSPredicate = NSPredicate(format: "item_id = %@", "1234")
        let returnedArray: RLMArray = Obj.objectsWithPredicate(predicate)

        let predicate: NSPredicate = NSPredicate(format: "sort_id = %i", 1234)
        let returnedArray: RLMArray = Obj.objectsWithPredicate(predicate)
```

Im running Xcode 6 beta 6.

**Comment by jayesh15111988** [comment]
Did anyone find a fix for it? I am getting exception raised when trying to query Realm using predicate.
Here's my code : 

        let val: String = "883"
        let predicate = NSPredicate(format: "tagIdentifier BEGINSWITH \(val)")
        var objectsMAtchingGivenPredicate = Tag.objectsWithPredicate(predicate) --> Crashes with exception on this line
(*** Terminating app due to uncaught exception 'Unsupported predicate value type', reason: 'Object type any not supported')

Any help or pointer towards solving this issue is much appreciated!

**Comment by jpsim** [comment]
@jayesh15111988 NSPredicate syntax requires strings to be quoted, or passed in as format arguments:

```swift
NSPredicate(format: "tagIdentifier BEGINSWITH '\(val)'")
// or
NSPredicate(format: "tagIdentifier BEGINSWITH %@", val)
```

So this is more of a problem with your NSPredicate rather than Realm.

**Comment by jayesh15111988** [comment]
@jpsim  Thanks for responding back. You are right that it was a problem with single quote for the given statement. However, this was one the many ways I tried to fix the problem. 

But it seems problem was in the model representation where I overlooked that property should be explicitly initialized with empty string. So,

dynamic var tag: String = "" //will work
dynamic var tag: String! //Won't work, crash with *** Terminating app due to uncaught exception 'Unsupported predicate value type', reason: 'Object type any not supported'

Though we declare the property as String, we still need to assign initial value. Is that a bug or a specific feature that I am not aware of?

**Comment by jpsim** [comment]
> Though we declare the property as String, we still need to assign initial value. Is that a bug or a specific feature that I am not aware of?

Neither. Swift's limited reflection capabilities means that properties need a default value to be introspected in a way that Realm can build up a full, type-safe model definition. Since Realm doesn't support null property values and that none of this prevents the use of custom initializers, it shouldn't make a difference in terms of practical usage.

**Comment by jayesh15111988** [comment]
@jpsim Thanks a ton! That was very informative comment

**Comment by krzyzanowskim** [comment]
It is not working for Optional types as well.

**Comment by jpsim** [comment]
@krzyzanowskim there are many different scenarios referred to in this thread. Could you be more specific about what you're trying to do with optionals and how it's not working?

If you're referring to not being able to specify optionals in your model in Realm Swift, please note that Realm requires models to be initializable by calling `init()` on it, which means setting a default value for every property. However, those types can be explicitly specific as optional for to-one relationships like so:

```swift
final class Company: Object {
  dynamic var name = "" // => Type can't be `String?`, because strings aren't nullable in Realm.
}
final class Employee: Object {
  dynamic var company: Company? = Company() // => Type can be optional Company, because links in Realm are nullable.
}
```

**Comment by krzyzanowskim** [comment]
@jpsim I was trying to have optional String
```swift
dynamic var String?
```

**Comment by jpsim** [comment]
Understood. We're working on supporting nullable `String` and `NSData` properties (among others), which we're tracking as #628.
