### ISSUE TITLE
Passing RLMObjects Between Threads

### ISSUE THREAD

**Issue by jamescmartinez** [realm/realm-cocoa#946]
Am I missing something, or is it not possible to pass RLMObjects between threads?

For example, when importing, I import in a background thread and pass the imported objects back to the caller in a completion block. These passed-back imported objects are not valid in the completion block since this is in a different thread.

**Comment by LouisCo** [comment]
@Altimor I coppletely agree with you! Realm seems very cool, but when it comes to REST or any other background task, it's a pain. As you, I spent a lot of time mastering Realm, and now, I find that I can't use it because of this bad thread policy. Unfortunately, this adds to my obstacles list using Realm, and for this huge issue, the workaround is too complex, so I'm going to move to [Paper][1].
[1]: https://github.com/pilgr/Paper

**Comment by jpsim** [comment]
@stuartro in https://github.com/realm/realm-cocoa/issues/3925#issuecomment-237955141, I explain why thread confinement isn't a limitation or artificial constraint, but rather sits at the core of Realm's safety.

Whereas immutability provides thread safety by preventing you from ever changing anything, thread-confinement achieves it by combining mutations via ACID database transactions. Obviously never changing your database's values isn't really an option, so Realm uses option 2.

We have a PR that's currently in its final review phase (#4114) which allows creating thread-safe references to thread-confined Realm objects, which can be passed between threads, all while maintaining Realm's isolation guarantees.
